import test from 'node:test';
import assert from 'node:assert/strict';
import {createGroupService,GROUP_KEYS} from '../lib/group-service.js';
import {createPointService} from '../lib/participation-admin.js';
import {createCommunityService} from '../lib/community-service.js';
import {groupRequest} from '../lib/group-http.js';
import {activityStorage} from './helpers/activity-storage.js';
const owner={id:'owner',role:'member'},member={id:'member',role:'member'},admin={id:'admin',role:'admin'};
const body='지역 교통 정책에 대하여 시민들이 다양한 관점을 나누고 충분한 근거 자료를 함께 검토하여 실행 가능한 개선 방안을 찾아보면 좋겠습니다.';
async function fixture(){const db=activityStorage();let time=Date.parse('2026-09-16T03:00:00Z'),i=0;const service=createGroupService({command:db.command,now:()=>time,idFor:()=>String(++i),examples:false}),points=createPointService({command:db.command,clock:()=>time});let {item}=await service.save(owner,{operation:'create',input:{name:'정책 토론',category:'politics',description:'마을 이야기',region:'서울',rules:'존중',visibility:'members',privacyAccepted:true}});const change=async(user,operation,input={})=>{const r=await service.save(user,{id:item.id,version:item.version,operation,input});item=r.item;return r;};await change(admin,'review',{decision:'approve'});await change(member,'join',{privacyAccepted:true});await change(owner,'member',{userId:member.id,decision:'approve'});return {db,service,points,change,advance:n=>time+=n,get item(){return item;},now:()=>time};}
// Missing group+wallet CAS causes missing award, stale retry duplicates, or orphan wallet changes.
test('group post reward commits with indices and retry survives stale version without leaking member metadata',async()=>{const f=await fixture(),payload={id:f.item.id,version:f.item.version,operation:'post',input:{kind:'post',title:'논의',body,requestId:'group-request-0001'}};const p=await f.service.save(owner,payload);assert.equal(p.activityReward?.credited,100);const again=await f.service.save(owner,payload);assert.equal(again.item.posts.length,1);assert.equal((await f.points.wallet(owner)).wallet.balance,100);assert.ok(f.db.sets.get(GROUP_KEYS.user(owner.id)).has(f.item.id));assert.doesNotMatch(JSON.stringify((await f.service.get(f.item.id,member)).item),/activityReward|earnedToday|activityDebt/);assert.doesNotMatch(f.db.values.get(GROUP_KEYS.item(f.item.id)),/activityReward|earnedToday|activityDebt/);});
test('group and community share cooldown and hashes and HTTP reports retry seconds',async()=>{const f=await fixture();await f.change(owner,'post',{title:'논의',kind:'post',body});const request=await groupRequest({method:'POST',body:{id:f.item.id,version:f.item.version,operation:'comment',input:{postId:f.item.posts[0].id,body:'이 의견에 대한 구체적인 자료를 공유해 주세요.'}}},{service:f.service,user:owner,url:new URL('https://example.org/api/v3/groups')});assert.equal(request.status,429);assert.equal(request.data.retryAfterSeconds,30);f.advance(30000);const c=createCommunityService({command:f.db.command,now:()=>new Date(f.now()).toISOString()});assert.equal((await c.createPost('itsme',{title:'복사',body:body+'!!!'},owner)).activityReward?.reason,'duplicate');});
test('group failed commit leaves both content and wallet unchanged',async()=>{const f=await fixture();f.db.rejectWrites=true;await assert.rejects(f.change(owner,'post',{title:'논의',kind:'post',body}),/GROUP_CONFLICT/);assert.equal((await f.points.wallet(owner)).wallet.balance||0,0);assert.equal((await f.service.get(f.item.id,owner)).item.posts.length,0);});
test('group moderation and parent removal preserve innocent commenters; self deletion recovers award',async()=>{const f=await fixture();await f.change(owner,'post',{title:'논의',kind:'post',body});const postId=f.item.posts[0].id;await f.change(member,'comment',{postId,body:'마을의 지속 가능한 교통 계획을 함께 논의하고 싶습니다.'});await f.change(owner,'post-hide',{postId,hidden:true,reason:'검토 중'});assert.equal((await f.points.wallet(member)).wallet.balance,50);await f.change(owner,'post-delete',{postId});assert.equal((await f.points.wallet(owner)).wallet.balance,0);assert.equal((await f.points.wallet(member)).wallet.balance,50);});
test('group parent cascade sums own comment reversals while preserving another author and already-revoked events',async()=>{const f=await fixture();await f.points.activityPolicy(admin,{policy:{cooldownSeconds:0},reason:'모임 삭제 검증'});await f.change(owner,'post',{title:'논의',kind:'post',body});const postId=f.item.posts[0].id;await f.change(owner,'comment',{postId,body:'지속 가능한 마을 교통 계획의 상세한 예산을 공개하면 좋겠습니다.'});await f.change(owner,'comment',{postId,body:'주민들이 함께 의견을 나눌 수 있는 공청회가 필요합니다.'});const prior=f.item.posts[0].comments.at(-1),eventId=(await f.points.wallet(owner)).wallet.ledger.find(x=>x.contentId===prior.id).eventId;await f.points.activityRevoke(admin,{userId:owner.id,eventId,reason:'기존 회수',requestId:'group-cascade-revoke-0001'});await f.change(member,'comment',{postId,body:'실제 주민들의 다양한 교통 수요도 반영해야 합니다.'});const deleted=await f.change(owner,'post-delete',{postId});assert.equal(deleted.activityReversal.recovered,150);assert.equal(deleted.activityReversal.debtAdded,0);const status=await f.points.wallet(owner);assert.equal(status.wallet.balance,0);assert.equal(status.activityRewards.earnedToday,200);assert.equal(status.wallet.ledger.filter(x=>x.type==='activity-revoke'&&x.eventId===eventId).length,1);assert.equal((await f.points.wallet(member)).wallet.balance,50);await f.change(owner,'post',{title:'재등록',kind:'post',body});assert.equal((await f.points.wallet(owner)).wallet.balance,0);});
test('group moderator removing another author reverses only the moderators own removed comments',async()=>{const f=await fixture();await f.change(member,'post',{title:'회원의 의견',kind:'post',body});const postId=f.item.posts[0].id;await f.change(owner,'comment',{postId,body:'공청회 일정과 참여 방식을 자세히 알려 주시면 좋겠습니다.'});const deleted=await f.change(owner,'post-delete',{postId,reason:'운영 정리'});assert.equal(deleted.activityReversal?.recovered,50);assert.equal((await f.points.wallet(owner)).wallet.balance,0);assert.equal((await f.points.wallet(member)).wallet.balance,100);});
