import test from 'node:test';
import assert from 'node:assert/strict';
import {createCommunityService} from '../lib/community-service.js';
import {createPointService} from '../lib/participation-admin.js';
import {TARGET_KEYS} from '../lib/migration-service.js';
import {storage} from './helpers/person-refresh-fixture.js';
const user={id:'activity-member',role:'member',nickname:'회원'},admin={id:'admin',role:'admin'};
const body='지역의 교통과 교육 정책에 관하여 시민들이 충분한 자료를 검토하고 서로 다른 의견을 존중하며 구체적인 개선 방안을 함께 논의해야 한다고 생각합니다.';
const comment='제안한 정책의 구체적인 시행 일정과 예산도 함께 공개하면 좋겠습니다.';
const wk='jcs:points:v1:wallet:'+user.id;
function fixture(){const db=storage();let time=Date.parse('2026-09-16T14:50:00Z'),serial=0;const service=createCommunityService({command:db.command,now:()=>new Date(time).toISOString(),makeId:()=>String(++serial)}),points=createPointService({command:db.command,clock:()=>time});return {db,service,points,advance:n=>time+=n,post:(input={})=>service.createPost('community',{title:'정책 토론',body,...input},user)};}
// Missing atomic reward mutation would leave balance unchanged and fail these literal assertions.
test('new post and comment earn atomically while unrelated wallet fields survive',async()=>{const f=fixture();f.db.values.set(wk,JSON.stringify({balance:12000,firstPaid:true,analysisAccess:{person:{expiresAt:12345}},refreshRequests:{pending:{fee:100}}}));const p=await f.post();assert.equal(p.activityReward?.credited,100);f.advance(30000);const c=await f.service.addComment('community',p.id,{text:comment},user);assert.equal(c.activityReward?.credited,50);const state=await f.points.wallet(user);assert.equal(state.wallet.balance,12150);assert.equal(state.activityRewards.credit,150);assert.deepEqual(state.wallet.analysisAccess,{person:{expiresAt:12345}});assert.deepEqual(state.wallet.refreshRequests,{pending:{fee:100}});assert.doesNotMatch(f.db.values.get(TARGET_KEYS.content('community')),/activityReward/);});
test('common rate limit rejects storage but an idempotent retry returns the original item',async()=>{const f=fixture(),p=await f.post({requestId:'activity-request-0001'});const again=await f.post({requestId:'activity-request-0001'});assert.equal(again.id,p.id);await assert.rejects(f.service.addComment('community',p.id,{text:comment},user),e=>e.message==='ACTIVITY_RATE_LIMIT'&&e.retryAfterSeconds===30);assert.equal((await f.points.wallet(user)).wallet.balance,100);assert.equal(JSON.parse(f.db.values.get(TARGET_KEYS.content('community'))).items.length,1);});
test('meaningful normalization excludes markup, URLs, jamo, symbols and repetition without rejecting content',async()=>{for(const [value,reason] of [['<b>짧은 의견</b> https://example.org/'+ 'a'.repeat(80),'minimum-length'],['😀 ! ㄱ ㅋ '.repeat(100),'minimum-length'],['정책개선'.repeat(30),'repetitive']]){const f=fixture(),p=await f.post({body:value});assert.equal(p.activityReward?.reason,reason);assert.equal((await f.points.wallet(user)).wallet.balance||0,0);}});
test('duplicate text persists across deletion and boards; deletion recovers only unused activity credit',async()=>{const f=fixture(),p=await f.post();let wallet=(await f.points.wallet(user)).wallet;wallet.balance=12000;wallet.activityCredit=0;f.db.values.set(wk,JSON.stringify(wallet));await f.service.deletePost('community',p.id,user);assert.equal((await f.points.wallet(user)).wallet.balance,12000);assert.equal((await f.points.wallet(user)).activityRewards.debt,100);f.advance(30000);const duplicate=await f.service.createPost('itsme',{title:'다른 게시판',body},user);assert.equal(duplicate.activityReward?.reason,'duplicate');f.advance(30000);const p2=await f.post({body:body+'추가로 주민 설명회와 공청회를 개최할 필요가 있습니다.'});assert.equal(p2.activityReward?.offset,100);assert.equal(p2.activityReward?.credited,0);assert.equal((await f.points.wallet(user)).wallet.balance,12000);assert.equal((await f.points.wallet(user)).activityRewards.earnedToday,200);});
test('daily partial cap and KST midnight reset are shared by posts and comments',async()=>{const f=fixture();await f.points.activityPolicy(admin,{policy:{dailyLimit:125},reason:'시범 운영'});const p=await f.post();f.advance(30000);const c=await f.service.addComment('community',p.id,{text:comment},user);assert.equal(c.activityReward?.earned,25);assert.equal((await f.points.wallet(user)).activityRewards.remainingToday,0);f.advance(570000);const next=await f.post({body:body+'다음날 논의를 계속합니다.'});assert.equal(next.activityReward?.earned,100);assert.equal((await f.points.wallet(user)).activityRewards.day,'2026-09-17');});
test('admin policy, restriction and revocation require authority and reasons and preserve recharge funds',async()=>{const f=fixture();await assert.rejects(f.points.activityPolicy(user,{policy:{dailyLimit:10},reason:'x'}),/ADMIN_REQUIRED/);await assert.rejects(f.points.activityPolicy(admin,{policy:{postPoints:-1},reason:'x'}),/INVALID_ACTIVITY_POLICY/);await assert.rejects(f.points.activityRestrict(admin,{userId:user.id,hours:1,requestId:'restriction-0001'}),/REASON_REQUIRED/);await f.points.activityRestrict(admin,{userId:user.id,hours:1,reason:'반복 도배 확인',requestId:'restriction-0001'});const p=await f.post();assert.equal(p.activityReward?.reason,'restricted');await f.points.activityRestrict(admin,{userId:user.id,hours:0,reason:'확인 후 해제',requestId:'restriction-0002'});f.advance(30000);const rewarded=await f.post({body:body+'새로운 논의입니다.'});const ledger=(await f.points.wallet(user)).wallet.ledger;const event=ledger.find(x=>x.type==='activity');assert.ok(event);await f.points.activityRevoke(admin,{userId:user.id,eventId:event.eventId,reason:'부정 적립 확정',requestId:'revoke-request-0001'});await f.points.activityRevoke(admin,{userId:user.id,eventId:event.eventId,reason:'부정 적립 확정',requestId:'revoke-request-0001'});assert.equal((await f.points.wallet(user)).wallet.balance,0);assert.ok((await f.points.status(admin)).activityAdmin.audit.length>=3);assert.equal((await f.points.status(user)).activityAdmin,undefined);});
test('failed content CAS never credits and concurrent duplicate creates have at most one reward',async()=>{const f=fixture(),command=async a=>a[0]==='EVAL'?0:f.db.command(a),bad=createCommunityService({command});await assert.rejects(bad.createPost('community',{title:'토론',body},user),/CONTENT_CHANGED_RETRY/);assert.equal((await f.points.wallet(user)).wallet.balance||0,0);const results=await Promise.allSettled([f.post(),f.post()]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await f.points.wallet(user)).wallet.balance,100);});
test('normalization catches HTML entities and punctuation padding across posts and comments',async()=>{const f=fixture(),p=await f.post();f.advance(30000);const encoded=[...body].map(c=>'&#'+c.codePointAt(0)+';').join(' . ');const c=await f.service.addComment('community',p.id,{text:encoded},user);assert.equal(c.activityReward?.reason,'duplicate');});
test('admin and disabled rewards never grant; edits never award; own deletion returns a reversal receipt',async()=>{const f=fixture();const p=await f.post();await f.service.editPost('community',p.id,{body:body+'수정한 추가 의견입니다.'},user);assert.equal((await f.points.wallet(user)).wallet.balance,100);const deleted=await f.service.deletePost('community',p.id,user);assert.equal(deleted.activityReversal?.recovered,100);const a=await f.service.createPost('community',{title:'관리자',body},admin);assert.equal(a.activityReward.reason,'ineligible');await f.points.activityPolicy(admin,{policy:{enabled:false},reason:'일시 중지'});f.advance(30000);assert.equal((await f.post()).activityReward.reason,'disabled');});
test('administrative history identifies reward targets and shows successful events for revocation',async()=>{const f=fixture();f.db.values.set(TARGET_KEYS.users,JSON.stringify({[user.id]:user}));await f.post();const status=await f.points.member(admin,user.id);assert.equal(status.activityEvents[0].domain,'community');assert.equal(status.activityEvents[0].kind,'post');f.advance(30000);await f.post();const suspect=(await f.points.status(admin)).activityAdmin.suspects[0];assert.equal(suspect.nickname,'회원');assert.equal(suspect.domain,'community');});
test('parallel distinct rewards share a partial daily cap with cooldown disabled',async()=>{const f=fixture();await f.points.activityPolicy(admin,{policy:{dailyLimit:125,cooldownSeconds:0},reason:'한도 검증'});const r=await Promise.all([f.post(),f.post({body:body+'추가로 주민들의 참여도 필요합니다.'})]);assert.deepEqual(r.map(x=>x.activityReward.earned).sort((a,b)=>a-b),[25,100]);assert.equal((await f.points.wallet(user)).wallet.balance,125);});
test('request replay uses original submitted body even when storage trims whitespace',async()=>{const f=fixture(),input={body:'  '+body+'  ',requestId:'trim-request-0001'},p=await f.post(input);assert.equal((await f.post(input)).id,p.id);});
test('short-pattern spam with a different leading word does not earn',async()=>{const f=fixture();assert.equal((await f.post({body:'시민참여 '+ '좋은정책입니다 '.repeat(30)})).activityReward.reason,'repetitive');});
test('comments on stored example content earn no points',async()=>{const f=fixture();f.db.values.set(TARGET_KEYS.content('community'),JSON.stringify({items:[{id:'example',title:'예시',published:true,isExample:true}]}));const c=await f.service.addComment('community','example',{text:comment},user);assert.equal(c.activityReward.reason,'ineligible');});
// Entity decoding must precede canonicalization: otherwise compatibility characters get a second hash.
test('ordinary fullwidth and entity-fullwidth bodies share one hash across boards and comments',async()=>{const f=fixture(),plain='Citizens should examine transport policies carefully and discuss practical improvements with their neighbors.',wide=plain.replace(/[A-Za-z]/g,c=>String.fromCodePoint(c.codePointAt(0)+0xfee0)),encoded=wide.replace(/[Ａ-Ｚａ-ｚ]/g,c=>'&#'+c.codePointAt(0)+';'),p=await f.post({body:plain});f.advance(30000);assert.equal((await f.service.createPost('itsme',{title:'대화',body:wide},user)).activityReward.reason,'duplicate');f.advance(30000);assert.equal((await f.service.addComment('community',p.id,{text:encoded},user)).activityReward.reason,'duplicate');assert.equal((await f.points.wallet(user)).wallet.balance,100);});
test('entity-encoded decomposed accents normalize like composed text while isolated jamo remain excluded',async()=>{const f=fixture(),plain='Citizens discuss café transport and résumé policies together with practical neighborhood improvements.',encoded=[...plain.normalize('NFD')].map(c=>'&#'+c.codePointAt(0)+';').join(''),p=await f.post({body:plain});f.advance(30000);assert.equal((await f.service.addComment('community',p.id,{text:encoded},user)).activityReward.reason,'duplicate');f.advance(30000);assert.equal((await f.post({body:'&#12593; '.repeat(60)})).activityReward.reason,'minimum-length');});
// Missing descendant reversals lets an author remove rewarded content while retaining its points.
test('community parent deletion recovers own removed comments and preserves independent and other-author awards',async()=>{const f=fixture(),other={id:'other',role:'member'};await f.points.activityPolicy(admin,{policy:{cooldownSeconds:0},reason:'삭제 검증'});const parent=await f.post();await f.post({body:body+'독립적인 주민 참여 방안도 논의합니다.'});await f.service.addComment('community',parent.id,{text:comment},user);await f.service.addComment('community',parent.id,{text:'주민 설명회에서 상세한 정책 자료를 제공하면 좋겠습니다.'},other);const deleted=await f.service.deletePost('community',parent.id,user);assert.equal(deleted.activityReversal.recovered,150);assert.equal(deleted.activityReversal.debtAdded,0);assert.equal((await f.points.wallet(user)).wallet.balance,100);assert.equal((await f.points.wallet(user)).activityRewards.earnedToday,250);assert.equal((await f.points.wallet(other)).wallet.balance,50);const remaining=JSON.parse(f.db.values.get(TARGET_KEYS.content('community'))).items.find(p=>p.body.startsWith(body));assert.equal((await f.service.addComment('community',remaining.id,{text:comment},user)).activityReward.reason,'duplicate');});
test('cage cascade reverses all actor-owned removed posts and comments atomically, skips prior reversals and protects spent recharge',async()=>{const f=fixture(),other={id:'other',role:'member'};await f.points.activityPolicy(admin,{policy:{cooldownSeconds:0},reason:'케이지 삭제 검증'});f.db.values.set(wk,JSON.stringify({balance:100000,firstPaid:true}));const cage=await f.points.cage(user,{fee:50000,title:'토론장',body:'지역 정책 토론',requestId:'cascade-cage-0001'}),own=await f.post({cageParentId:cage.id,camp:'progressive'}),their=await f.service.createPost('community',{title:'다른 의견',body:body+'다른 관점입니다.',cageParentId:cage.id,camp:'conservative'},other);await f.service.addComment('community',cage.id,{text:comment,camp:'progressive'},user);await f.service.addComment('community',their.id,{text:'다른 관점을 반영한 구체적인 실행 계획도 필요합니다.',camp:'progressive'},user);const prior=await f.service.addComment('community',own.id,{text:'주민들의 의견을 반영할 수 있는 공청회도 제안합니다.',camp:'progressive'},user);await f.service.addComment('community',own.id,{text:'서로 다른 지역의 주민 의견도 충분히 청취해야 합니다.',camp:'conservative'},other);const eventId=(await f.points.wallet(user)).wallet.ledger.find(x=>x.contentId===prior.id).eventId;await f.points.activityRevoke(admin,{userId:user.id,eventId,reason:'기존 회수 확인',requestId:'cascade-revoke-0001'});await f.points.cage(user,{fee:50000,title:'별도 토론장',body:'독립적인 토론',requestId:'cascade-cage-0002'});const beforeWallet=f.db.values.get(wk),beforeContent=f.db.values.get(TARGET_KEYS.content('community'));const refusing=createCommunityService({command:a=>a[0]==='EVAL'?Promise.resolve(0):f.db.command(a)});await assert.rejects(refusing.deletePost('community',cage.id,user),/CONTENT_CHANGED_RETRY/);assert.equal(f.db.values.get(wk),beforeWallet);assert.equal(f.db.values.get(TARGET_KEYS.content('community')),beforeContent);const deleted=await f.service.deletePost('community',cage.id,user),status=await f.points.wallet(user);assert.equal(deleted.activityReversal.recovered,0);assert.equal(deleted.activityReversal.debtAdded,200);assert.equal(status.wallet.balance,200);assert.equal(status.activityRewards.debt,200);assert.equal(status.activityRewards.earnedToday,250);assert.equal(status.wallet.ledger.filter(x=>x.type==='activity-revoke'&&x.eventId===eventId).length,1);assert.equal((await f.points.wallet(other)).wallet.balance,150);assert.equal((await f.post()).activityReward.reason,'duplicate');});
