import test from 'node:test';import assert from 'node:assert/strict';
import {boardTile,remapPoint,projectItem,unprojectDelta,triangleMatrix} from '../src/core/polimable-board-geometry.js';
import {defaults,validate} from '../src/core/polimable-tile-design.js';
import {mountTileFaces} from '../src/ui/polimable-tile-faces.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('32 independent rectangles fit the viewport with balanced margins and no planar overlap',()=>{const tiles=Array.from({length:32},(_,i)=>boardTile(i));for(const t of tiles){assert.equal(t.corner,t.index%8===0);if(!t.corner)near(Math.max(t.w,t.h)/Math.min(t.w,t.h),120/76);for(const[x,y]of t.points){assert.ok(x>=0&&x<=1672&&y>=0&&y+35<=941);}}
 for(let i=0;i<32;i++)for(let j=i+1;j<32;j++){const a=tiles[i],b=tiles[j],overlap=Math.min(a.u+a.w,b.u+b.w)-Math.max(a.u,b.u)>0&&Math.min(a.v+a.h,b.v+b.h)-Math.max(a.v,b.v)>0;assert.equal(overlap,false,`${i}/${j}`);}near(453-772*.515,941-(453+772*.515+35));});
test('saved coordinates map reversibly and remain unchanged on disk',()=>{const d=defaults(),copy=JSON.stringify(d);for(const [key,v]of Object.entries(d.items)){const p=projectItem(key,v);if(key.startsWith('tile.')){const i=Number(key.split('.')[1]),back=remapPoint(i,p,true);near(back.x,v.x);near(back.y,v.y);const delta=unprojectDelta(key,13,-9),moved=projectItem(key,{...v,x:v.x+delta.x,y:v.y+delta.y});near(moved.x-p.x,13);near(moved.y-p.y,-9);}else assert.deepEqual(p,v);}assert.equal(JSON.stringify(d),copy);assert.deepEqual(validate(d),d);});
test('triangle texture mapping hits every destination vertex',()=>{for(const i of [0,4,8,12,16,20,24,28]){const p=boardTile(i).points;for(const ids of [[0,1,2],[0,2,3]]){const all=[[0,0],[1,0],[1,1],[0,1]],src=ids.map(n=>all[n]),dst=ids.map(n=>p[n]),m=triangleMatrix(src,dst);src.forEach(([x,y],n)=>{near(m[0]*x+m[2]*y+m[4],dst[n][0]);near(m[1]*x+m[3]*y+m[5],dst[n][1]);});}}});
class E{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.style={};this.dataset={};this.classList={add(){}};}setAttribute(k,v){this.attrs[k]=String(v);if(k==='id')this.id=v;}append(...x){this.children.push(...x);}}
const all=n=>[n,...n.children.flatMap(all)];
test('all 32 blocks stay rendered before and after contact; silver and corner art are separate',()=>{const previous=globalThis.document;globalThis.document={createElementNS:(_,tag)=>new E(tag)};try{const c=new E('div'),f=mountTileFaces(c);f.paint(defaults());const surfaces=all(c).filter(n=>'data-pm-tile-surface'in n.attrs);assert.equal(surfaces.length,32);for(const s of surfaces){const i=Number(s.attrs['data-pm-tile-surface']);f.contact(i,7);assert.equal(s.children.at(-1).attrs.transform,'translate(0 7)');assert.match(s.children[1].attrs.transform,/matrix/);f.contact(i,0);assert.equal(s.children.at(-1).attrs.transform,'translate(0 0)');assert.notEqual(s.style.display,'none');const images=all(s).filter(n=>n.tag==='image');assert.equal(images.length,2);} }finally{globalThis.document=previous;}});
