import test from 'node:test';
import assert from 'node:assert/strict';
const mod=await import('../lib/group-service.js').catch(()=>({}));
const {createGroupService,GROUP_KEYS}=mod;
const owner={id:'owner',nickname:'운영자',role:'member'},admin={id:'admin',role:'admin'},member={id:'reader',nickname:'회원',role:'member'};
const input={name:'정책 모임',category:'politics',description:'동네 이야기',region:'가상 지역',rules:'서로 존중',visibility:'members',privacyAccepted:true};
function database(){const strings=new Map(),hashes=new Map(),sets=new Map();const calls=[];return {strings,calls,command:async a=>{calls.push(a);const [op,key,...rest]=a;if(op==='GET')return strings.get(key)||null;if(op==='MGET')return [key,...rest].map(k=>strings.get(k)||null);if(op==='HVALS')return [...(hashes.get(key)||new Map()).values()];if(op==='SMEMBERS')return [...(sets.get(key)||[])];if(op==='EVAL'){const count=Number(a[2]),keys=a.slice(3,3+count),v=a.slice(3+count);if((strings.get(keys[0])||'')!==v[0])return 0;strings.set(keys[0],v[1]);const h=hashes.get(keys[1])||new Map();h.set(v[3],v[2]);hashes.set(keys[1],h);for(let i=2;i<keys.length;i++){const s=sets.get(keys[i])||new Set();if(v[i+2]==='1')s.add(v[3]);else s.delete(v[3]);sets.set(keys[i],s);}return 1;}throw Error('Unhandled '+op);}};}
async function fixture(options={}){const db=database(),service=createGroupService({command:db.command,now:()=>Date.parse('2026-09-15T08:00:00Z'),...options});let {item}=await service.save(owner,{operation:'create',input});const change=async(user,operation,value={})=>{const r=await service.save(user,{id:item.id,version:item.version,operation,input:value});item=r.item;return item;};return {db,service,change,get item(){return item;}};}
test('approval and membership indices exclude examples and never write global users',async()=>{const f=await fixture();assert.equal((await f.service.list(null)).total,0);assert.equal((await f.service.list(null)).examples.length,3);assert.equal((await f.service.list(owner,{view:'mine'})).items[0].status,'pending');await f.change(admin,'review',{decision:'approve'});assert.equal((await f.service.list(null)).total,1);await f.change(member,'join',{privacyAccepted:true});await f.change(owner,'member',{userId:member.id,decision:'approve'});assert.equal((await f.service.list(member,{view:'mine'})).items.length,1);await f.change(member,'leave');assert.equal((await f.service.list(member,{view:'mine'})).total,0);assert.ok(f.db.calls.filter(c=>c[0]!=='EVAL').every(c=>c.slice(1).every(k=>k.startsWith('jcsr2:groups:'))));});
test('parallel updates have one winner and preserve the committed post',async()=>{const f=await fixture();await f.change(admin,'review',{decision:'approve'});const payload={id:f.item.id,version:f.item.version,operation:'post',input:{title:'제목',body:'본문',kind:'post'}};const results=await Promise.allSettled([f.service.save(owner,payload),f.service.save(owner,payload)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(results.find(r=>r.status==='rejected').reason.message,/GROUP_CONFLICT/);assert.equal((await f.service.get(f.item.id,owner)).item.posts.length,1);});
test('private projection and invitation discovery do not expose member content',async()=>{const f=await fixture();await f.change(admin,'review',{decision:'approve'});await f.change(owner,'post',{title:'PRIVATE_TITLE',body:'PRIVATE_BODY',kind:'post'});const guest=(await f.service.get(f.item.id,null)).item;assert.doesNotMatch(JSON.stringify(guest),/PRIVATE_TITLE|PRIVATE_BODY|inviteToken|pathname|requestedAt/);await f.change(owner,'settings',{visibility:'invite'});assert.equal((await f.service.list(null)).total,0);await assert.rejects(f.service.get(f.item.id,null),/GROUP_NOT_FOUND/);await assert.rejects(f.service.list(member,{view:'manage'}),/GROUP_FORBIDDEN/);});
test('example records stay complete and immutable with no Redis mutations',async()=>{const f=await fixture();for(const row of (await f.service.list(null)).examples){const detail=(await f.service.get(row.id,admin)).item;assert.equal(detail.posts.length,8);assert.equal(detail.events.length,2);assert.equal(detail.viewer.canWrite,false);assert.equal(detail.viewer.canManage,false);await assert.rejects(f.service.save(admin,{id:row.id,version:1,operation:'close',input:{reason:'x'}}),/GROUP_EXAMPLE_READ_ONLY/);}assert.equal((await f.service.list(admin,{view:'manage'})).examples.length,0);});
const png=Buffer.from([137,80,78,71,13,10,26,10,...Array(16).fill(0)]).toString('base64');
test('private image ACL is checked again after membership removal',async()=>{const puts=[],gets=[];const f=await fixture({env:{JCS_GROUPS_BLOB_READ_WRITE_TOKEN:'private-test'},putImpl:async(path,bytes,opts)=>{puts.push(opts);return {pathname:path};},getImpl:async(path)=>{gets.push(path);return {statusCode:200,stream:new ReadableStream({start(c){c.enqueue(new Uint8Array([1]));c.close();}})};}});await f.change(admin,'review',{decision:'approve'});await f.change(member,'join',{privacyAccepted:true});await f.change(owner,'member',{userId:member.id,decision:'approve'});const upload=await f.service.upload(owner,{id:f.item.id,purpose:'gallery',contentType:'image/png',base64:png});assert.equal(upload.version,f.item.version+1);await f.service.save(owner,{id:f.item.id,version:upload.version,operation:'post',input:{kind:'gallery',title:'비공개 사진',body:'',imageIds:[upload.image.id]}});await f.service.image(f.item.id,upload.image.id,member);assert.equal(puts[0].access,'private');let latest=(await f.service.get(f.item.id,owner)).item;await f.service.save(owner,{id:latest.id,version:latest.version,operation:'member',input:{userId:member.id,decision:'remove',reason:'규칙 위반'}});await assert.rejects(f.service.image(f.item.id,upload.image.id,member),/GROUP_NOT_FOUND/);assert.equal(gets.length,1);assert.doesNotMatch(JSON.stringify(upload),/private-test|pathname/);});
test('image errors deny upload before storage and clean up only uncommitted new blobs',async()=>{let puts=0;const removed=[];const f=await fixture({env:{JCS_GROUPS_BLOB_READ_WRITE_TOKEN:'test'},putImpl:async(path)=>{puts++;const raw=JSON.parse(f.db.strings.get(GROUP_KEYS.item(f.item.id)));raw.version++;f.db.strings.set(GROUP_KEYS.item(f.item.id),JSON.stringify(raw));return {pathname:path};},delImpl:async path=>removed.push(path)});await assert.rejects(f.service.upload(member,{id:f.item.id,purpose:'cover',contentType:'image/png',base64:png}),/GROUP_FORBIDDEN/);await assert.rejects(f.service.upload(owner,{id:f.item.id,purpose:'cover',contentType:'image/svg\+xml',base64:png}),/GROUP_IMAGE_INVALID/);assert.equal(puts,0);await assert.rejects(f.service.upload(owner,{id:f.item.id,purpose:'cover',contentType:'image/png',base64:png}),/GROUP_CONFLICT/);assert.equal(puts,1);assert.equal(removed.length,1);assert.match(removed[0],/^groups\//);});
test('invalid envelopes and reserved IDs cannot smuggle group roles or example flags',async()=>{const f=await fixture();await assert.rejects(f.service.save(null,{operation:'create',input}),/LOGIN_REQUIRED/);await assert.rejects(f.service.save(owner,{operation:'create',input:null}),/GROUP_INPUT_INVALID/);const {item}=await f.service.save(owner,{operation:'create',input:{...input,status:'approved',isExample:true,members:[admin],ownerId:'admin'}});assert.equal(item.status,'pending');assert.equal(item.isExample,false);assert.equal(item.viewer.role,'applicant');});
test('members can cancel participation from MyGroups while reapproval blocks detail',async()=>{const f=await fixture();await f.change(admin,'review',{decision:'approve'});await f.change(member,'join',{privacyAccepted:true});await f.change(owner,'member',{userId:member.id,decision:'approve'});await f.change(owner,'settings',{name:'새 모임명'});await assert.rejects(f.service.get(f.item.id,member),/GROUP_NOT_FOUND/);const summary=(await f.service.list(member,{view:'mine'})).items[0];assert.equal(summary.canLeave,true);await f.service.save(member,{id:summary.id,version:summary.version,operation:'leave',input:{}});assert.equal((await f.service.list(member,{view:'mine'})).total,0);});
test('closed groups do not retain an unread notification that members cannot dismiss',async()=>{let instant=Date.parse('2026-09-15T08:00:00Z');const f=await fixture({now:()=>instant});await f.change(admin,'review',{decision:'approve'});await f.change(member,'join',{privacyAccepted:true});await f.change(owner,'member',{userId:member.id,decision:'approve'});instant+=10000;await f.change(owner,'post',{kind:'post',title:'공지',body:'새 이야기'});assert.equal((await f.service.list(member,{view:'mine'})).notifications.length,1);await f.change(owner,'close',{reason:'활동 종료'});const mine=await f.service.list(member,{view:'mine'});assert.equal(mine.notifications.length,0);assert.equal(mine.items[0].unread,false);assert.equal(mine.items[0].canLeave,true);});
test('leave cannot reveal existence or version of a hidden group to an outsider',async()=>{const f=await fixture();await assert.rejects(f.service.save(member,{id:f.item.id,version:0,operation:'leave',input:{}}),/GROUP_NOT_FOUND/);await f.change(admin,'review',{decision:'approve'});await f.change(owner,'settings',{visibility:'invite'});await assert.rejects(f.service.save(member,{id:f.item.id,version:0,operation:'leave',input:{}}),/GROUP_NOT_FOUND/);});
