import test from 'node:test';
import assert from 'node:assert/strict';
import {createPartyPollService,publicPartyPoll,PARTY_POLL_KEYS} from '../lib/party-poll-service.js';
const poll={id:'gallup-2026-10-01',institution:'한국갤럽',topic:'party-support',sourceUrl:'https://www.gallup.co.kr/gallupdb/reportContent.asp?seqNo=1',publishedDate:'2026-10-01',startDate:'2026-09-28',endDate:'2026-09-30',sampleSize:1000,results:{parties:[{id:'democratic',name:'더불어민주당',value:40},{id:'ppp',name:'국민의힘',value:30},{id:'none',name:'무당층',value:30}]},provenance:{provider:'gallup'}};
function storage(){const values=new Map();return {values,command:async([op,key,...args])=>{if(op==='GET')return values.get(key)||null;if(op==='SET'){if(args.includes('NX')&&values.has(key))return null;values.set(key,args[0]);return 'OK';}if(op==='EVAL'){if(key.includes('PARTY_RELEASE')){const [,lock,token]=args;if(values.get(lock)!==token)return 0;values.delete(lock);return 1;}const [,lock,snapshot,token,old,next]=args;if(values.get(lock)!==token||(values.get(snapshot)||'')!==old)return 0;values.set(snapshot,next);return 1;}throw Error(op);}};}
test('rejects malformed shares and untrusted source without leaking raw fields',()=>{assert.equal(publicPartyPoll({...poll,secret:'private'}).secret,undefined);assert.equal(publicPartyPoll({...poll,sourceUrl:'https://evil.test'}),null);assert.equal(publicPartyPoll({...poll,results:{parties:[{id:'none',name:'none',value:130}]}}),null);});
test('keeps latest valid result on failure, deduplicates unchanged notifications',async()=>{const db=storage();let data={items:[poll],providers:[{id:'gallup',state:'success'}]};const service=createPartyPollService({command:db.command,seed:[],now:()=>Date.parse('2026-10-02'),collect:async()=>data,generate:async()=>({state:'configuration_needed'})});await service.collectScheduled();await service.collectScheduled();let raw=JSON.parse(db.values.get(PARTY_POLL_KEYS.snapshot));assert.equal(raw.notifications.filter(e=>e.kind==='party-poll').length,1);data={items:[],providers:[]};await service.collectScheduled();assert.equal((await service.list()).items[0].id,poll.id);assert.equal((await service.list()).providers[0].state,'error');});
test('old data cannot replace current result; public reads do not collect',async()=>{const db=storage();let count=0;const service=createPartyPollService({command:db.command,seed:[poll],collect:async()=>{count++;return {items:[{...poll,id:'old',publishedDate:'2026-09-01',startDate:'2026-08-28',endDate:'2026-08-30'}],providers:[{id:'gallup',state:'success'}]};},generate:async()=>({state:'pending'}),now:()=>Date.parse('2026-10-02')});assert.equal((await service.list()).items[0].id,poll.id);assert.equal(count,0);await service.collectScheduled();assert.equal((await service.list()).items[0].id,poll.id);});

test('party alerts identify subject and watchdog catches missing party runs',async()=>{const {pushCopy,watchdogProblems}=await import('../lib/update-notifications.js');assert.match(pushCopy({kind:'party-poll',target:'party-poll',providers:['gallup']}).title,/한국갤럽 정당 지지도/);const now=Date.parse('2026-10-02T10:00:00Z');assert.ok(watchdogProblems({now,partyPolls:null}).some(p=>p.target==='party-poll'&&p.reason==='missing'));});
