import test from 'node:test';import assert from 'node:assert/strict';
import {beginInlineFields,inlineField,finishInlineFields} from '../src/ui/inline-field-markup.js';
import {fieldsForClick} from '../src/ui/person-page-editor.js';
import {renderPoliticianDetail} from '../src/views/politicians.js';
const item={id:'p',type:'assembly',name:'정치인',party:'정당',office:'국회의원'},report={accessTier:'admin',diagnoses:[{id:'01',title:'브랜드',display:{kind:'brand',search:{pc:1000,mobile:1000},indicators:[{value:0},{value:12}],nowSignal:'기사 제목',evidenceTitle:'기사 제목',evidenceUrl:'https://example.com/news'}}],news:[{title:'뉴스 제목',url:'https://example.com/second'}]};
test('equal numbers retain independent source paths and no edit metadata reaches ordinary users',()=>{const search=report.diagnoses[0].display.search;beginInlineFields(item,report,true);const html=finishInlineFields('<b>'+inlineField(search,'pc','1K')+'</b><b>'+inlineField(search,'mobile','1K')+'</b>');assert.match(html,/display.search.pc/);assert.match(html,/display.search.mobile/);beginInlineFields(item,report,false);assert.equal(finishInlineFields(inlineField(search,'pc','1K')),'1K');});
test('attribute tokens are removed and article anchors retain exact URL field',()=>{const d=report.diagnoses[0].display;beginInlineFields(item,report,true);const html=finishInlineFields('<a href="'+inlineField(d,'evidenceUrl',d.evidenceUrl)+'">'+inlineField(d,'nowSignal',d.nowSignal)+'</a>');assert.match(html,/href="https:\/\/example.com\/news"/);assert.match(html,/data-inline-article="true"/);assert.ok(!/[\uE000-\uE002]/.test(html));});
test('article editor offers only title and URL from the clicked article',()=>{const fields=[{path:'news.0.title'},{path:'news.0.url'},{path:'news.1.title'},{path:'news.1.url'}];assert.deepEqual(fieldsForClick({fields},'news.1.title'),fields.slice(2));});
test('real detail render binds search values and news without marker leakage',async()=>{const html=await renderPoliticianDetail('p',null,{user:{id:'admin',role:'admin'}},{},{ok:true,item,intelligence:report});assert.match(html,/data-inline-path="display.search.pc"/);assert.match(html,/data-inline-path="news.0.title"/);assert.ok(!/[\uE000-\uE002]/.test(html));const plain=await renderPoliticianDetail('p',null,{user:{id:'staff',role:'admin'}},{},{ok:true,item,intelligence:report});assert.doesNotMatch(plain,/data-inline-path/);});
