import fs from 'node:fs';
import assert from 'node:assert/strict';
const base=new URL('../',import.meta.url);
const page=fs.readFileSync(new URL('src/views/polimable-page.js',base),'utf8');
const js=fs.readFileSync(new URL('src/ui/polimable-interactions.js',base),'utf8');
const css=fs.readFileSync(new URL('css/polimable-201.css',base),'utf8');
assert.match(page,/data-pm-dice-roll/);
assert.match(page,/data-pm-die-dock="1"/);
assert.match(page,/data-pm-die-dock="2"/);
assert.match(page,/data-pm-die-flight="1"/);
assert.match(page,/data-pm-die-flight="2"/);
assert.match(js,/function fairDie/);
assert.match(js,/getRandomValues/);
assert.match(js,/polimable:dice-result/);
assert.match(js,/lastDiceTotal/);
assert.doesNotMatch(js,/pm-character-token.*style\.left/);
assert.match(css,/pmDiceThrowA/);
assert.match(css,/pmDiceThrowB/);
console.log('31.230 dice action stage OK');
