import test from 'node:test';
import assert from 'node:assert/strict';
import {createGameState,rollTurn,resolveChoice,useCard,cashOut,getRecordableScore,stageForScore} from '../lib/polimable-engine.js';
import {createPoliMarbleService} from '../lib/polimable-service.js';

const fixed=(ints=[1],floats=[.1])=>{let i=0,f=0;return {int:(min,max)=>Math.max(min,Math.min(max,ints[i++%ints.length])),float:()=>floats[f++%floats.length]};};

test('stage thresholds',()=>{assert.equal(stageForScore(2999),1);assert.equal(stageForScore(3000),2);assert.equal(stageForScore(8000),3);assert.equal(stageForScore(15000),4);});
test('game starts at 1000',()=>{const s=createGameState({sessionId:'s',userId:'u',initials:'ABC'});assert.equal(s.score,1000);assert.equal(s.position,0);assert.equal(s.status,'playing');});
test('roll is server deterministic with injected rng',()=>{const s=createGameState({sessionId:'s',userId:'u',initials:'ABC'}),n=rollTurn(s,fixed([1]));assert.equal(n.position,1);assert.equal(n.score,1140);assert.deepEqual(n.lastDice,[1]);});
test('choice resolves safely',()=>{let s=createGameState({sessionId:'s',userId:'u',initials:'ABC'});s.pendingChoice={id:'x',safeGain:220,riskWin:850,riskLose:-650,riskWinChance:.5};s=resolveChoice(s,'safe',fixed([1]));assert.equal(s.score,1220);assert.equal(s.pendingChoice,null);});
test('shield blocks next loss',()=>{let s=createGameState({sessionId:'s',userId:'u',initials:'ABC'});s.cards=['SHIELD'];s=useCard(s,'SHIELD');s.position=22;const n=rollTurn(s,fixed([1]));assert.equal(n.position,23);assert.equal(n.score,1000);assert.equal(n.effects.shieldCharges,0);});
test('cashout makes score recordable',()=>{let s=createGameState({sessionId:'s',userId:'u',initials:'ABC'});s.score=4321;s=cashOut(s);assert.equal(getRecordableScore(s),4321);assert.equal(s.status,'cashed_out');});

function fakeRedis(){const strings=new Map(),zsets=new Map();return async args=>{const [opRaw,...rest]=args,op=String(opRaw).toUpperCase();if(op==='SET'){strings.set(rest[0],rest[1]);return 'OK';}if(op==='GET')return strings.has(rest[0])?strings.get(rest[0]):null;if(op==='DEL')return strings.delete(rest[0])?1:0;if(op==='EXPIRE')return 1;if(op==='ZSCORE'){const z=zsets.get(rest[0]);return z?.has(String(rest[1]))?String(z.get(String(rest[1]))):null;}if(op==='ZADD'){const [key,score,member]=rest;if(!zsets.has(key))zsets.set(key,new Map());zsets.get(key).set(String(member),Number(score));return 1;}if(op==='ZREVRANGE'){const [key,start,end]=rest,rows=[...(zsets.get(key)||new Map()).entries()].sort((a,b)=>b[1]-a[1]).slice(Number(start),Number(end)+1),out=[];for(const [m,s] of rows){out.push(m,String(s));}return out;}if(op==='ZCOUNT'){const [key,min,max]=rest,minExclusive=String(min).startsWith('('),minValue=Number(String(min).replace(/^\(/,'')),maxValue=max==='+inf'?Infinity:Number(max);return [...(zsets.get(key)||new Map()).values()].filter(v=>(minExclusive?v>minValue:v>=minValue)&&v<=maxValue).length;}throw new Error('UNSUPPORTED '+op);};}

test('service is idempotent for duplicate roll request id',async()=>{const command=fakeRedis(),service=createPoliMarbleService({command,uuid:()=> 'session-1',now:()=>new Date('2026-09-20T00:00:00+09:00'),rngFactory:()=>fixed([1])}),user={id:'u1',nickname:'KKS'};const {state:start}=await service.start(user,{requestId:'start-1'});const first=(await service.roll(user,{sessionId:start.sessionId,requestId:'roll-1'})).state;const second=(await service.roll(user,{sessionId:start.sessionId,requestId:'roll-1'})).state;assert.equal(first.turn,1);assert.equal(second.turn,1);assert.equal(second.score,first.score);});
test('cashout records best score in TODAY leaderboard',async()=>{const command=fakeRedis(),service=createPoliMarbleService({command,uuid:()=> 'session-2',now:()=>new Date('2026-09-20T00:00:00+09:00'),rngFactory:()=>fixed([1])}),user={id:'u2',nickname:'하늘바람'};const {state:start}=await service.start(user,{});await service.roll(user,{sessionId:start.sessionId,requestId:'r1'});const out=await service.cashout(user,{sessionId:start.sessionId,initials:'하늘',requestId:'c1'});assert.ok(out.recordedScore>1000);const board=await service.leaderboard('today','u2');assert.equal(board.entries[0].userId,'u2');assert.equal(board.me.rank,1);});
