import fs from 'fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const page=read('src/views/polimable-page.js');
const css=read('css/polimable-201.css');
const ui=read('src/ui/polimable-interactions.js');
if(!page.includes('data-pm-logical-canvas')) throw new Error('logical canvas missing');
if(!css.includes('width:1672px;height:941px')) throw new Error('logical canvas size missing');
if(!css.includes('.pm-strategy-slots{display:none!important}')) throw new Error('strategy slots should be hidden in step 1');
if(!css.includes('.pm-ranking-overlay{display:none!important}')) throw new Error('ranking should be hidden in step 1');
if(!ui.includes('rect.width/1672')) throw new Error('logical canvas scale sync missing');
console.log('polimable logical canvas base test: OK');
