import fs from 'node:fs';
const base=new URL('../', import.meta.url);
const read=p=>fs.readFileSync(new URL(p,base),'utf8');
const inter=read('src/ui/polimable-interactions.js');
const page=read('src/views/polimable-page.js');
const css=read('css/polimable-201.css');
const must=(cond,msg)=>{if(!cond)throw new Error(msg)};
must(inter.includes('START_CASH=10000'),'start cash missing');
must(inter.includes('salaryForLap'),'START pass salary missing');
must(inter.includes("state.turn=playerIndex===0?1:0"),'turn alternation missing');
must(inter.includes("setTimeout(()=>runTurn(1),900)"),'AI auto turn missing');
must(inter.includes('buyProperty'),'property buying missing');
must(inter.includes('sellProperty'),'property selling missing');
must(inter.includes('upgradeProperty'),'property upgrade missing');
must(inter.includes('transferOwnership'),'buyout missing');
must(inter.includes("type:'card'"),'strategy card tiles missing');
must(page.includes('AI 시민'),'AI HUD missing');
must(page.includes('data-pm-action-modal'),'action modal missing');
must(css.includes('.pm-action-modal'),'modal styling missing');
console.log('polimable 31.234 gameplay test: OK');
