import test from 'node:test';
import assert from 'node:assert/strict';
import {createTaxiPartyService,PARTY_RECORD_LUA} from '../lib/taxi-party-service.js';
const parties=['a','b','c','d'].map(id=>({id,name:'Party '+id}));
const questions=Array.from({length:18},(_,i)=>({id:'q'+i,version:'test-v1',domain:'domain'+Math.floor(i/3),title:'Question '+i,options:parties.map(p=>({partyId:p.id,text:'Policy '+i+' '+p.id,speech:'Anonymous story '+i+' '+p.id,sources:[{title:'Official '+p.id,url:'https://example.com/'+p.id,date:'2026-01-01'}]}))}));
function setup(){const db=new Map(),hashes=new Map();let at=100000,seq=0;
 const command=async a=>{if(a[0]==='GET')return db.get(a[1])??null;if(a[0]==='HGETALL')return hashes.get(a[1])||{};
 assert.equal(a[0],'EVAL');assert.equal(a[1],PARTY_RECORD_LUA);const [key,stats,personal,old,next,ttl,record]=a.slice(3);if((db.get(key)??'')!==old)return 0;
 const r=record?JSON.parse(record):null;if(r){const h=hashes.get(stats)||{},m=hashes.get(personal)||{},marker=r.question+':'+r.kind;const first=!m[marker];m[marker]=1;
 for(const [field,value]of Object.entries(r.counts)){h[field]=(h[field]||0)+value;if(first)h['first:'+field]=(h['first:'+field]||0)+value;}hashes.set(stats,h);hashes.set(personal,m);}db.set(key,next);return 1;};
 const service=createTaxiPartyService({command,now:()=>at,random:()=>.42,parties,questions});const user={id:'test-user',status:'active'};
 const body=(action,v,choice)=>({action,expectedVersion:v,requestId:'party_request_'+(++seq),...(choice!==undefined?{choice}:{})});
 return {db,hashes,service,user,body,tick:n=>at+=n};}
async function begin(f){let s=await f.service.get(f.user);s=await f.service.mutate(f.user,f.body('start',s.version));assert.equal(s.ride.phase,'intro');assert.equal(s.ride.passengerKind,'party');assert.equal(s.ride.options,undefined);return f.service.mutate(f.user,f.body('begin',s.version));}
test('party identity and sources stay hidden until dropoff; five distinct domains',async()=>{const f=setup();let s=await begin(f);assert.equal(s.ride.totalBeats,5);assert.equal(s.ride.passenger,undefined);assert.equal(s.ride.beat.sources,undefined);s=await f.service.mutate(f.user,f.body('compare',s.version));assert.equal(s.ride.options.length,4);for(const o of s.ride.options){assert.match(o.id,/^[a-f0-9-]{36}$/);assert.equal(o.partyId,undefined);assert.equal(o.sources,undefined);}s=await f.service.mutate(f.user,f.body('dropoff',s.version));assert.ok(s.ride.passenger.name);assert.equal(new Set(s.ride.beats.map(b=>b.domain)).size,5);assert.ok(s.ride.beats[0].options[0].sources.length);});
test('comparison exposure and actual choice are atomic and idempotent',async()=>{const f=setup();let s=await begin(f);const compare=f.body('compare',s.version);await Promise.all([f.service.mutate(f.user,compare),f.service.mutate(f.user,compare)]);s=await f.service.get(f.user);let stats=await f.service.stats();assert.equal(stats.parties.every(p=>p.shown===1),true);assert.equal(stats.responses,0);
 const chosen=s.ride.options[2].id,body=f.body('choose',s.version,chosen);const results=await Promise.all([f.service.mutate(f.user,body),f.service.mutate(f.user,body)]);assert.equal(results.filter(x=>x.result.replayed).length,1);s=await f.service.get(f.user);stats=await f.service.stats();assert.equal(stats.responses,1);assert.equal(stats.firstResponses,1);assert.equal(stats.parties.reduce((n,p)=>n+p.selected,0),1);
 await assert.rejects(f.service.mutate(f.user,{...body,choice:'none'}),/REQUEST_ID_REUSED/);await assert.rejects(f.service.mutate(f.user,f.body('choose',s.version,'none')),/ALREADY_SELECTED/);
 s=await f.service.mutate(f.user,f.body('dropoff',s.version));const selected=s.ride.beats[0].selection.partyId;assert.equal(stats.parties.find(p=>p.id===selected).selected,1);assert.notEqual(selected,s.ride.passenger.id);});
test('invalid selections, premature advance and stale versions cannot count',async()=>{const f=setup();let s=await begin(f);await assert.rejects(f.service.mutate(f.user,f.body('listen',s.version)),/CHOICE_REQUIRED/);await assert.rejects(f.service.mutate(f.user,f.body('choose',s.version,'none')),/OPTIONS_REQUIRED/);s=await f.service.mutate(f.user,f.body('compare',s.version));await assert.rejects(f.service.mutate(f.user,f.body('choose',s.version,'a')),/CHOICE_INVALID/);await assert.rejects(f.service.mutate(f.user,f.body('choose',s.version-1,'none')),/VERSION_CHANGED/);assert.equal((await f.service.stats()).responses,0);});
test('none is an explicit answer; reset preserves cumulative and first-question markers',async()=>{const f=setup();for(let ride=0;ride<2;ride++){let s=await begin(f);s=await f.service.mutate(f.user,f.body('compare',s.version));s=await f.service.mutate(f.user,f.body('choose',s.version,'none'));s=await f.service.mutate(f.user,f.body('reset',s.version));assert.equal(s.ride,null);}const stats=await f.service.stats();assert.equal(stats.responses,2);assert.equal(stats.none,2);assert.equal(stats.firstResponses,1);assert.equal(stats.firstNone,1);assert.equal(stats.parties.every(p=>p.selected===0&&p.shown===2&&p.firstShown===1),true);});
test('five answers complete a ride and preserve sources; next guest starts with consent',async()=>{const f=setup();let s=await begin(f);for(let i=0;i<5;i++){s=await f.service.mutate(f.user,f.body('compare',s.version));s=await f.service.mutate(f.user,f.body('choose',s.version,s.ride.options[0].id));s=await f.service.mutate(f.user,f.body(i===4?'finish':'listen',s.version));}assert.equal(s.ride.status,'completed');assert.equal(s.history.length,1);assert.equal(s.ride.beats.filter(b=>b.selection).length,5);s=await f.service.mutate(f.user,f.body('start',s.version));assert.equal(s.ride.phase,'intro');assert.equal(s.ride.heardCount,0);assert.equal(s.ride.options,undefined);});
test('guest and account isolation, pause and intro distance, input allowlist',async()=>{const f=setup();const a=await f.service.get(),b=await f.service.get();assert.notEqual(a.sessionToken,b.sessionToken);let s=await f.service.mutate(null,f.body('start',0),a.sessionToken);f.tick(20000);s=await f.service.mutate(null,f.body('heartbeat',s.version),a.sessionToken);assert.equal(s.ride.distanceMeters,0);assert.equal((await f.service.get(null,b.sessionToken)).ride,null);s=await f.service.mutate(null,f.body('begin',s.version),a.sessionToken);f.tick(1000);s=await f.service.mutate(null,f.body('pause',s.version),a.sessionToken);assert.equal(s.ride.distanceMeters,8);f.tick(60000);s=await f.service.mutate(null,f.body('resume',s.version),a.sessionToken);assert.equal(s.ride.distanceMeters,8);await assert.rejects(f.service.mutate(null,{...f.body('heartbeat',s.version),partyId:'a'},a.sessionToken),/INVALID_INPUT/);await assert.rejects(f.service.get({id:'inactive',status:'suspended'}),/ACCOUNT_INACTIVE/);});
test('previous-question choice tokens cannot vote on another question; last guidance closes the ride',async()=>{
 const f=setup();let s=await begin(f),previous;
 for(let i=0;i<4;i++){s=await f.service.mutate(f.user,f.body('compare',s.version));if(previous)await assert.rejects(f.service.mutate(f.user,f.body('choose',s.version,previous)),/CHOICE_INVALID/);previous=s.ride.options[0].id;s=await f.service.mutate(f.user,f.body('choose',s.version,previous));s=await f.service.mutate(f.user,f.body('listen',s.version));}
 assert.equal(s.ride.beat.comfort.kind,'closing');assert.doesNotMatch(s.ride.beat.comfort.text,/다음 이야기/);assert.match(s.ride.beat.comfort.text,/내려도/);assert.equal((await f.service.stats()).responses,4);
});
