import {MOCK_BILL,ballots,tally} from '../data/mock-bill.js?v=0.0.31.419';
const colors={yes:'#67dbbd',no:'#ff898b',abstain:'#b8c2d6'};
const hash=s=>[...s].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,2166136261);
export function chamberSeats(bill=MOCK_BILL){
 const votes=ballots(bill),order=['democratic',...bill.parties.map(p=>p.id).filter(id=>!['democratic','ppp'].includes(id)),'ppp'];
 const ordered=order.flatMap(id=>votes.filter(v=>v.party===id).sort((a,b)=>hash(a.id+'seat')-hash(b.id+'seat')));
 return ordered.map((v,i)=>{const column=Math.floor(i/6),row=i%6,a=Math.PI+(column+.5)/50*Math.PI,r=365-row*35;return {...v,x:420+Math.cos(a)*r,y:320+Math.sin(a)*r*.73,color:bill.parties.find(p=>p.id===v.party).color};});
}
export function renderChamber(bill=MOCK_BILL){const all=chamberSeats(bill),visible=all.filter((_,i)=>i%4===0);return `<svg class="bill-chamber" viewBox="0 0 840 440" role="img" aria-label="가상 인물이 착석한 본회의장과 책상 위 태블릿"><defs><linearGradient id="desk-wood" x2="0" y2="1"><stop stop-color="#aa8157"/><stop offset="1" stop-color="#513827"/></linearGradient><linearGradient id="chair-leather" x2="0" y2="1"><stop stop-color="#48504b"/><stop offset="1" stop-color="#161d20"/></linearGradient></defs><path d="M35 65Q420 5 805 65L815 415H25Z" fill="#161a20bb" stroke="#b3926155"/><path d="M300 45L330 15H510L540 45Z" fill="url(#desk-wood)"/><text x="420" y="36" text-anchor="middle" fill="#f4e8d0" font-size="17">JCS</text>${visible.map((v,i)=>{const col=Math.floor(i/5),row=i%5,x=83+col*48,y=102+row*59+Math.abs(col-7)*3,skin=['#c49b7c','#d5b298','#b88d6c'][i%3],hair=['#292320','#433b34','#97928b','#1b1c22'][i%4],suit=['#283845','#333943','#444045','#38453f'][i%4];return `<g class="bill-delegate" transform="translate(${x} ${y})"><ellipse cy="24" rx="19" ry="7" fill="#0005"/><rect x="-12" y="5" width="24" height="24" rx="6" fill="url(#chair-leather)" stroke="#958268" stroke-width=".6"/><path d="M-11 18L-10 1Q0-7 10 1L11 18Z" fill="${suit}"/><path d="M-10 3L-17 -7M10 3L17 -7" stroke="${suit}" stroke-width="6" stroke-linecap="round"/><path d="M0 1V17" stroke="#ffffff10"/><rect x="-3" y="-8" width="6" height="7" fill="${skin}"/><ellipse cy="-12" rx="6.2" ry="7.5" fill="${skin}"/><path d="M-6 -10Q-8 -22 0 -21Q8 -22 6 -9Q0 -14 -6 -10" fill="${hair}"/>${i%5===0?'<path d="M-6 -13Q-10 -7 -6 -2H6Q10 -7 6 -13" fill="'+hair+'"/>':''}<path d="M-20 -10L-20 -26Q0 -31 20 -26L20 -10Z" fill="url(#desk-wood)" stroke="#c2a578" stroke-width=".7"/><rect x="-8" y="-25" width="16" height="11" rx="1.5" fill="#070c12" stroke="#929da7" stroke-width=".8"/><rect data-seat-vote="${v.vote}" data-seat-id="${v.id}" x="-6.5" y="-23.5" width="13" height="8" rx=".7" fill="${colors[v.vote]}" style="opacity:0"/><path d="M-15 -10L-12 -9M15 -10L12 -9" stroke="${skin}" stroke-width="3" stroke-linecap="round"/></g>`;}).join('')}<text x="190" y="430" text-anchor="middle" fill="#94beef" font-size="16">더불어민주당</text><text x="444" y="430" text-anchor="middle" fill="#d9ccaf" font-size="15">기타 정당 · 무소속</text><text x="668" y="430" text-anchor="middle" fill="#e7a0a1" font-size="16">국민의힘</text></svg><div class="bill-chamber-controls"><span>가상 인물·의석은 연출용 · 전체 300명 집계</span><button type="button" data-bill-action>결과 보기</button></div><p class="bill-live-result" role="status" aria-live="polite">결과 보기를 누르면 표결이 시작됩니다.</p><script type="application/json" data-bill-votes>${JSON.stringify(all.map(v=>({id:v.id,vote:v.vote})))}</script>`;}
const runs=new WeakMap();
export function playBillVote(hall,{instant=false}={}){
 if(!hall)return;const old=runs.get(hall);if(old)cancelAnimationFrame(old);
 const lamps=new Map([...hall.querySelectorAll('[data-seat-vote]')].map(el=>[el.dataset.seatId,el]));const seats=JSON.parse(hall.querySelector('[data-bill-votes]').textContent).sort((a,b)=>hash(a.id+'reveal')-hash(b.id+'reveal'));
 const t=tally({parties:[{yes:Number(hall.dataset.voteYes),no:Number(hall.dataset.voteNo),abstain:Number(hall.dataset.voteAbstain)}]}),verdict=hall.querySelector('.bill-verdict'),quorum=hall.querySelector('.bill-quorum b'),live=hall.querySelector('.bill-live-result');
 if(!seats.length)return;const reduced=instant||matchMedia('(prefers-reduced-motion: reduce)').matches;
 const totals={yes:0,no:0,abstain:0};let shown=0,start;
 lamps.forEach(el=>el.style.opacity='0');hall.dataset.voteState='playing';hall.querySelector('[data-bill-action]').textContent='빠르게 결과만 보기';hall.closest('.bill-page').querySelector('[data-bill-jump="bill-results"]').disabled=true;hall.classList.add('is-voting');verdict.innerHTML='<img src="/assets/bills/plates/voting-414.svg" alt="표결 진행 중">';quorum.textContent='집계 중';live.textContent='';
 for(const v of Object.keys(totals))hall.querySelector('.bill-'+v+' strong').textContent='0';
 function frame(now){if(!hall.isConnected)return;start??=now;const count=reduced?300:Math.min(300,Math.floor((now-start)/8000*300));while(shown<count){const vote=seats[shown++],seat=lamps.get(vote.id);if(seat){seat.style.opacity='1';if(!reduced)seat.animate([{filter:'brightness(2)'},{filter:'brightness(1)'}],{duration:450});}totals[vote.vote]++;}for(const v of Object.keys(totals))hall.querySelector('.bill-'+v+' strong').textContent=totals[v];if(shown<300){runs.set(hall,requestAnimationFrame(frame));return;}hall.classList.remove('is-voting');hall.dataset.voteState='complete';hall.querySelector('[data-bill-action]').textContent='표결 다시 보기';hall.closest('.bill-page').querySelector('[data-bill-jump="bill-results"]').disabled=false;verdict.innerHTML=`<img src="/assets/bills/plates/${t.passed?'passed':'rejected'}-414.svg" alt="모의 ${t.passed?'가결':'부결'}">`;quorum.textContent=t.passed?'가결 기준 충족':`가결까지 ${t.needed}표`;live.textContent=`표결 완료. 찬성 ${t.yes}, 반대 ${t.no}, 기권 ${t.abstain}.`;runs.delete(hall);}
 runs.set(hall,requestAnimationFrame(frame));
}
export function mountBillVote(root){const hall=root.querySelector('.bill-hall');if(!hall||hall.dataset.voteMounted)return;hall.dataset.voteMounted='1';hall.dataset.voteState='idle';hall.querySelector('[data-bill-action]').addEventListener('click',()=>playBillVote(hall,{instant:hall.dataset.voteState==='playing'}));const page=hall.closest('.bill-page');page.querySelector('[data-bill-fullscreen]')?.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await page.requestFullscreen();}catch{}});}
