import {diceOrientation,pips,pressFrames,stepTiming,ownerColor} from '../core/polimable-motion.js';
export function mountGameMotion(root){
 const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches,animations=new Set(),owners=new Map();let dead=false;
 const play=(el,frames,options)=>{if(!el||dead||!root.isConnected)return null;const a=el.animate(frames,options);animations.add(a);a.finished.catch(()=>{}).finally(()=>{animations.delete(a);a.cancel();});return a;};
 for(const die of root.querySelectorAll('[data-pm-die-flight]')){die.classList.add('pm-die-3d');const cube=document.createElement('div');cube.className='pm-dice-cube';for(let n=1;n<=6;n++){const face=document.createElement('div');face.className=`pm-cube-face pm-cube-face-${n}`;face.setAttribute('aria-hidden','true');for(const p of pips(n)){const dot=document.createElement('i');dot.className=`pm-cube-dot p${p}`;face.append(dot);}cube.append(face);}die.replaceChildren(cube);}
 const card=document.createElement('div');card.className='pm-card-reveal';card.setAttribute('aria-hidden','true');card.innerHTML='<div class="pm-card-flipper"><div class="pm-card-back"><span>J</span><small>STRATEGY</small></div><div class="pm-card-front"><span data-card-art></span><strong></strong><p></p></div></div>';root.append(card);
 const ensureShadow=token=>{if(!token.querySelector('.pm-token-shadow')){const s=document.createElement('span');s.className='pm-token-shadow';s.setAttribute('aria-hidden','true');token.prepend(s);}};
 root.querySelectorAll('[data-pm-character-token]').forEach(ensureShadow);
 function pulse(index,color,last=false){const ring=root.querySelector(`[data-pm-tile-ring="${index}"]`);if(!ring)return;ring.style.stroke=color;play(ring,[{opacity:0,strokeWidth:1},{opacity:1,strokeWidth:last?5:3,offset:.3},{opacity:0,strokeWidth:1}],{duration:reduced()?180:last?640:260,easing:'ease-out'});}
 function press(index,pi,last=false){const els=[root.querySelector(`[data-pm-tile-surface="${index}"]`),root.querySelector(`[data-pmle-key="tile.${index}.label"]`),root.querySelector(`[data-pm-property-object="${index}"]`),...root.querySelectorAll(`[data-pm-character-token][data-pm-tile="${index}"]`)];for(const e of els)play(e,pressFrames(last,reduced()),{duration:last?stepTiming.landing:stepTiming.contact+130,easing:'cubic-bezier(.2,.7,.3,1)'});pulse(index,ownerColor(pi),last);}
 function hop(pi){const token=root.querySelector(`[data-pm-character-token="${pi}"]`);if(!token||reduced())return;play(token.querySelector('img'),[{transform:'translateY(0)'},{transform:'translateY(-12px) rotate(-3deg)',offset:.46},{transform:'translateY(0)'}],{duration:stepTiming.travel+20,easing:'ease-in-out'});play(token.querySelector('.pm-token-shadow'),[{scale:'1',opacity:.35},{scale:'.7',opacity:.18,offset:.5},{scale:'1',opacity:.35}],{duration:stepTiming.travel+20});}
 function ownership(props){root._pmTileFaces?.setOwners(props);const next=new Map();for(const [i,p]of Object.entries(props)){const signature=`${p.owner}:${p.level}`;next.set(i,signature);if(owners.has(i)&&owners.get(i)!==signature||!owners.has(i)){const el=root.querySelector(`[data-pm-property-object="${i}"] img`);play(el,reduced()?[{opacity:.6},{opacity:1}]:[{opacity:0,transform:'translateY(-18px) scale(.65)'},{opacity:1,transform:'translateY(2px) scale(1.08)',offset:.65},{opacity:1,transform:'none'}],{duration:460,easing:'ease-out'});pulse(i,ownerColor(p.owner),true);}}owners.clear();for(const [i,s]of next)owners.set(i,s);}
 function turn(pi){root.querySelectorAll('[data-pm-character-token]').forEach((e,i)=>e.classList.toggle('pm-active-player',i===pi));}
 async function reveal(data,icon){if(dead||!root.isConnected)return;card.querySelector('[data-card-art]').textContent=icon;card.querySelector('strong').textContent=data.name;card.querySelector('p').textContent=data.desc;card.setAttribute('aria-hidden','false');const a=play(card.querySelector('.pm-card-flipper'),reduced()?[{opacity:0},{opacity:1}]:[{transform:'rotateY(180deg) scale(.6)'},{transform:'rotateY(180deg) scale(1.03)',offset:.2},{transform:'rotateY(0deg) scale(1)',offset:.45},{transform:'rotateY(0deg) scale(1)'}],{duration:reduced()?700:1800,easing:'ease-out',fill:'both'});if(a)await a.finished.catch(()=>{});card.setAttribute('aria-hidden','true');}
 function react(pi,type){const img=root.querySelector(`[data-pm-character-token="${pi}"] img`);if(reduced())return;play(img,type==='fail'||type==='sad'||type==='angry'?[{rotate:'0deg'},{rotate:'-6deg',offset:.25},{rotate:'6deg',offset:.7},{rotate:'0deg'}]:[{scale:'1'},{scale:'1.09',offset:.4},{scale:'1'}],{duration:430,easing:'ease-out'});}
 const observer=new MutationObserver(()=>{if(!root.isConnected){dead=true;for(const a of animations)a.cancel();animations.clear();observer.disconnect();}});observer.observe(document.body,{childList:true,subtree:true});
 return {press,hop,ownership,turn,reveal,react,reduced,stop(){for(const a of animations)a.cancel();animations.clear();}};
}
export function setCubeFace(el,value){const cube=el.querySelector('.pm-dice-cube');if(cube)cube.style.transform=diceOrientation(value);}
