import {politicalMapSummary,normalizeRegion,normalizeParty,POLITICAL_MAP_REGIONS} from '../core/political-map-model.js?v=0.0.31.391';
import {MAP_REGIONS,MAP_DISTRICTS,MAP_VIEWBOX} from '../data/political-map-geometry.js?v=0.0.31.391';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={all:'전체',assembly:'국회의원',metropolitan:'광역단체장',basic:'기초단체장'};
const colors={'더불어민주당':'#245cce','국민의힘':'#d83c4b','조국혁신당':'#164a86','개혁신당':'#e8791c','진보당':'#ac2259','기본소득당':'#137f79','사회민주당':'#b46427','무소속':'#64748b','미분류':'#9798a5','공석':'#c8cbd3'};
const color=p=>colors[p]||'#8064a2',partyOf=p=>p?.isVacant?'공석':normalizeParty(p?.party);
const mounted=new WeakSet();
const anchors={서울:[175,135],인천:[140,200],경기:[280,192],세종:[210,250],대전:[290,335],충남:[173,305],충북:[300,267],대구:[372,350],경북:[423,283],울산:[478,395],부산:[430,466],경남:[320,425]};
let snapshot;const load=()=>{if(!snapshot){snapshot=fetch('/api/v3/politicians?map=1',{credentials:'same-origin'}).then(async r=>{const d=await r.json();if(!r.ok||!d.ok)throw Error();return d;}).catch(e=>{snapshot=null;throw e;});setTimeout(()=>{snapshot=null;},300000).unref?.();}return snapshot;};
const key=s=>String(s||'').replace(/\s+/g,'');
// District geometries include administrative wards; a city mayor covers all of that city's wards.
export function matchDistrict(d,items){const candidates=items.filter(p=>p.type==='basic'&&normalizeRegion(p)===d.region);return candidates.filter(p=>{const j=key(p.jurisdiction),n=key(d.name);const local=key(j.replace(/^(서울특별시|부산광역시|대구광역시|인천광역시|대전광역시|울산광역시|경기도|강원특별자치도|강원도|충청북도|충청남도|전북특별자치도|전라북도|전남광주통합특별시|전라남도|광주광역시|경상북도|경상남도)\s*/,''));return !!local&&(n===local||(local.endsWith('시')&&n.startsWith(local)));}).sort((a,b)=>b.jurisdiction.length-a.jurisdiction.length)[0];}
export function mapSvg(items,state,compact){
 const summary=politicalMapSummary(items,{type:state.type}),regions=new Map(summary.regions.map(r=>[r.id,r]));
 const regionShape=MAP_REGIONS.find(r=>r.name===state.region),bounds=regionShape?.bounds;
 const box=!compact&&bounds&&state.zoom?`${bounds[0]-18} ${bounds[1]-18} ${bounds[2]+36} ${bounds[3]+36}`:MAP_VIEWBOX;
 const fill=(party,region)=>state.party!=='all'&&party!==state.party?'#e6e8ed':color(party);
 let defs='',paths='';
 if(state.type==='basic')paths=MAP_DISTRICTS.map(d=>{const p=matchDistrict(d,items),party=p?partyOf(p):'미분류';return `<path d="${d.d}" fill="${p?fill(party,d.region):'#e7e8ed'}" data-map-region="${esc(d.region)}" data-map-district="${esc(d.name)}" tabindex="0" role="button" aria-label="${esc(d.region+' '+d.name+' · '+(p?p.name+' '+party:'등록 인물 없음'))}"><title>${esc(d.name+' · '+(p?p.name+' / '+party:'등록 인물 없음'))}</title></path>`;}).join('');
 else paths=MAP_REGIONS.map((r,i)=>{const data=regions.get(r.name),p=data?.parties||[];let paint='#e6e2ee';if(state.type==='metropolitan')paint=p.length?fill(p[0].party,r.name):'#e7e8ed';if(state.type==='assembly'&&p.length){let at=0;defs+=`<linearGradient id="pm-${compact?'h':'d'}-${i}">`+p.map(s=>{const start=at;at+=s.share*100;return `<stop offset="${start}%" stop-color="${fill(s.party,r.name)}"/><stop offset="${at}%" stop-color="${fill(s.party,r.name)}"/>`;}).join('')+'</linearGradient>';paint=`url(#pm-${compact?'h':'d'}-${i})`;}return `<path d="${r.d}" fill="${paint}" data-map-region="${esc(r.name)}" tabindex="0" role="button" aria-label="${esc(r.name+' · '+(data?.total||0)+'명')}"><title>${esc(r.name)}</title></path>`;}).join('');
 const flags=state.type==='all'?MAP_REGIONS.map(r=>{const data=regions.get(r.name);if(!data?.total)return '';const [x,y]=anchors[r.name]||r.center;let offset=0;const bands=data.parties.map(p=>{const a=offset;offset+=p.share*56;return `<rect x="${a}" y="0" width="${p.share*56+.2}" height="17" fill="${fill(p.party,r.name)}"/>`;}).join('');return `<path d="M${r.center[0]} ${r.center[1]}L${x} ${y}" stroke="#81788f" stroke-width="1.3" fill="none" pointer-events="none"/><g transform="translate(${x-28} ${y-12})" data-map-region="${esc(r.name)}" tabindex="0" role="button" aria-label="${esc(r.name+' '+data.total+'명')}" class="pmap-flag"><title>${esc(r.name+': '+data.parties.map(p=>p.party+' '+p.count).join(', '))}</title><path d="M0 -3V30" stroke="#4b3b65" stroke-width="2"/><rect x="0" y="-1" width="57" height="20" rx="2" fill="#fff"/>${bands}${compact?'':`<text x="28" y="33" text-anchor="middle">${esc(r.name==='전남광주'?'전남·광주':r.name)}</text>`}</g>`;}).join(''):!compact?MAP_REGIONS.map(r=>`<text class="pmap-label" x="${(anchors[r.name]||r.center)[0]}" y="${(anchors[r.name]||r.center)[1]}" text-anchor="middle" pointer-events="none">${esc(r.name==='전남광주'?'전남·광주':r.name)}</text>`).join(''):'';
 return `<svg viewBox="${box}" aria-label="대한민국 ${labels[state.type]} 정당 분포 지도" class="pmap-svg"><defs>${defs}</defs><g class="pmap-boundaries">${paths}</g>${flags}</svg>`;
}
function partyRows(summary,state,compact){const rows=compact?summary.parties.slice(0,3):summary.parties;return rows.map(p=>`<button type="button" data-map-party="${esc(p.party)}" aria-pressed="${state.party===p.party}" class="pmap-party"><i style="--party:${color(p.party)}"></i><span>${esc(p.party)}</span><b>${p.count}<small>${state.type==='assembly'?'석':'명'}</small></b>${compact?'':`<em>${(p.share*100).toFixed(1)}%</em><span class="pmap-party-track"><span style="width:${p.share*100}%;background:${color(p.party)}"></span></span>`}</button>`).join('')||'<p>등록된 정보가 없습니다.</p>';}
export function renderPoliticalMapContent(data,state,compact){const all=politicalMapSummary(data.items,{type:state.type}),summary=politicalMapSummary(data.items,{type:state.type,region:state.region}),filtered=politicalMapSummary(data.items,{type:state.type,region:state.region,party:state.party}),people=filtered.items.filter(p=>(!state.district||p.id===state.district)&&(p.name+' '+p.jurisdiction).includes(state.q));
 const tabs=`<nav class="pmap-tabs" aria-label="정치지도 분류">${Object.entries(labels).map(([k,v])=>`<button data-map-type="${k}" aria-pressed="${state.type===k}">${v}</button>`).join('')}</nav>`;
 if(compact)return tabs+`<div class="pmap-preview"><a class="pmap-mini-map" href="/political-map?type=${state.type}" data-layout-route="/political-map?type=${state.type}" aria-label="${labels[state.type]} 지도 확대">${mapSvg(data.items,state,true)}</a><div class="pmap-mini-stats"><div class="pmap-total"><span>${labels[state.type]} 등록 현황</span><strong>${all.total}<small>${state.type==='assembly'?'석':'명'}</small></strong></div>${partyRows(all,state,true)}</div></div><p class="pmap-mini-note">${state.type==='all'?'깃발 색은 지역별 정당 구성 비율':'지역을 눌러 인물과 정당 구성을 확인하세요'}</p>`;
 const regionOptions=POLITICAL_MAP_REGIONS.filter(r=>r.id!=='미분류'||all.regions.find(x=>x.id===r.id)?.total);
 return tabs+`<div class="pmap-toolbar"><label>지역<select data-map-region-select><option value="all">전국</option>${regionOptions.map(r=>`<option value="${r.id}" ${state.region===r.id?'selected':''}>${r.label}</option>`).join('')}</select></label><button data-map-reset>전국으로</button><button data-map-zoom ${state.region==='all'?'disabled':''} aria-pressed="${state.zoom}">${state.zoom?'전체 지도':'선택 지역 확대'}</button></div><div class="pmap-layout"><div class="pmap-map-panel">${mapSvg(data.items,state,false)}<p class="pmap-map-note">${state.type==='all'?'깃발의 색 비율 = 지역별 등록 인원의 정당 구성':state.type==='assembly'?'시·도별 정당 구성 비율 · 국회의원 선거구 경계와는 다릅니다':state.type==='basic'?'시·군·구 경계별 단체장 소속 정당 · 회색은 미등록 또는 미분류':'시·도별 광역단체장 소속 정당'}</p></div><aside class="pmap-summary"><div class="pmap-total"><span>${esc(state.region==='all'?'전국':state.region)} · ${labels[state.type]}</span><strong>${summary.total}<small>${state.type==='assembly'?'석':'명'}</small></strong></div><p class="pmap-counts">현원 ${summary.occupied} · 공석 ${summary.vacant}</p>${state.type==='all'?`<div class="pmap-types">국회의원 <b>${summary.byType.assembly}</b><br>광역단체장 <b>${summary.byType.metropolitan}</b><br>기초단체장 <b>${summary.byType.basic}</b></div>`:''}<div class="pmap-party-list">${partyRows(summary,state,false)}</div>${state.party!=='all'?`<button data-map-party="all" class="pmap-clear">정당 선택 해제</button>`:''}<p class="pmap-subnote">전국 집계는 비례대표를 포함합니다. 지역별 지도에는 비례대표를 배정하지 않습니다.</p></aside></div><section class="pmap-roster"><header><h2>${esc(state.region==='all'?'전체 지역':state.region)} 인물 <span>${people.length}</span></h2><form data-map-search><label><span class="pmap-sr">이름 또는 지역 검색</span><input name="q" value="${esc(state.q)}" placeholder="이름 또는 지역 검색"></label><button>검색</button></form></header><div class="pmap-people">${people.slice(0,state.limit).map(p=>`<a href="/person/${encodeURIComponent(p.id)}" data-layout-route="/person/${esc(p.id)}"><i style="background:${color(partyOf(p))}"></i><div><strong>${esc(p.name||'공석')}</strong><span>${esc(p.jurisdiction||p.region)}</span></div><div><b>${esc(partyOf(p))}</b><span>${labels[p.type]}</span></div></a>`).join('')||'<p>조건에 맞는 인물이 없습니다.</p>'}</div>${people.length>state.limit?'<button class="pmap-more" data-map-more>인물 더 보기</button>':''}</section><footer class="pmap-source">${esc(data.basis)} · 조회 ${esc(new Date(data.asOf).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}<br>등록 정보 기준이며 선거 결과·득표율을 의미하지 않습니다. 경계와 등록 지역이 일치하지 않으면 회색으로 표시하며, 인물은 목록에서 확인할 수 있습니다. 지도: 통계청 SGIS / <a href="https://github.com/DevMinGeonPark/mapcn-kr" target="_blank" rel="noopener">mapcn-kr</a> (CC BY 4.0), 경계 단순화.</footer>`;
}
export async function mountPoliticalMap(root){if(mounted.has(root))return;mounted.add(root);const compact=root.dataset.politicalMap==='home',params=new URLSearchParams(globalThis.location?.search||''),state={type:labels[params.get('type')]?params.get('type'):'all',region:'all',party:'all',q:'',limit:24,zoom:false,district:''};let data;const mount=root.querySelector('[data-pmap-content]');
 const draw=()=>{mount.innerHTML=renderPoliticalMapContent(data,state,compact);};
 try{data=await load();draw();}catch{mount.innerHTML='<p class="pmap-loading">정보를 불러오지 못했습니다. <button data-map-retry>다시 시도</button></p>';}
 root.addEventListener('click',async e=>{const b=e.target.closest('[data-map-type],[data-map-region],[data-map-party],[data-map-reset],[data-map-more],[data-map-zoom],[data-map-retry]');if(!b||compact&&b.closest('a'))return;if(b.hasAttribute('data-map-retry')){try{data=await load();draw();}catch{b.textContent='연결 실패 · 다시 시도';}return;}if(!data)return;
 if(b.dataset.mapType){state.district='';state.type=b.dataset.mapType;state.party='all';state.limit=24;}
 else if(b.dataset.mapRegion){state.region=b.dataset.mapRegion;const district=MAP_DISTRICTS.find(d=>d.name===b.dataset.mapDistrict&&d.region===state.region);state.district=district?matchDistrict(district,data.items)?.id||'unmatched':'';state.limit=24;state.party='all';}
 else if(b.dataset.mapParty){state.party=state.party===b.dataset.mapParty?'all':b.dataset.mapParty;state.limit=24;}
 else if(b.hasAttribute('data-map-more'))state.limit+=24;
 else if(b.hasAttribute('data-map-zoom'))state.zoom=!state.zoom;
 else {state.district='';state.region='all';state.party='all';state.zoom=false;state.q='';state.limit=24;}
 draw();});
 root.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('[data-map-region]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
 root.addEventListener('change',e=>{if(e.target.matches('[data-map-region-select]')){state.district='';state.region=e.target.value;state.limit=24;state.party='all';draw();}});
 root.addEventListener('submit',e=>{if(e.target.matches('[data-map-search]')){e.preventDefault();state.district='';state.q=new FormData(e.target).get('q').trim();state.limit=24;draw();}});
}
