import {renderRegionStage,loadRegionPhotos} from './political-map-region.js?v=0.0.31.451';
import {districtCity} from './political-map-labels.js?v=0.0.31.450';
import {renderElectionCountdown,updateElectionCountdowns} from './election-countdown.js?v=0.0.31.426';
import {politicalMapSummary,normalizeRegion,normalizeParty,POLITICAL_MAP_REGIONS} from '../core/political-map-model.js?v=0.0.31.391';
import {MAP_REGIONS,MAP_DISTRICTS,MAP_VIEWBOX} from '../data/political-map-geometry.js?v=0.0.31.391';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={all:'전체',assembly:'국회의원',metropolitan:'광역단체장',basic:'기초단체장'};
const colors={'더불어민주당':'#245cce','국민의힘':'#d83c4b','조국혁신당':'#164a86','개혁신당':'#e8791c','진보당':'#ac2259','기본소득당':'#137f79','사회민주당':'#b46427','무소속':'#64748b','미분류':'#9798a5','공석':'#c8cbd3'};
const color=p=>colors[p]||'#8064a2',partyOf=p=>p?.isVacant?'공석':normalizeParty(p?.party);
const mounted=new WeakSet();
const anchors={서울:[175,135],인천:[140,200],경기:[280,192],세종:[210,250],대전:[290,335],충남:[173,305],충북:[300,267],대구:[372,350],경북:[423,283],울산:[478,395],부산:[430,466],경남:[320,425]};
// Place flags on the map, staggering nearby metropolitan areas instead of using outside columns.
export const flagAnchors={서울:[230,150],인천:[180,210],경기:[278,210],강원:[350,125],세종:[260,260],충남:[195,295],대전:[275,325],충북:[328,260],경북:[415,280],대구:[380,350],울산:[442,402],경남:[330,420],부산:[412,465],전북:[235,380],전남광주:[227,480],제주:[191,617]};
let snapshot;const load=()=>{if(!snapshot){snapshot=fetch('/api/v3/politicians?map=1',{credentials:'same-origin'}).then(async r=>{const d=await r.json();if(!r.ok||!d.ok)throw Error();return d;}).catch(e=>{snapshot=null;throw e;});setTimeout(()=>{snapshot=null;},300000).unref?.();}return snapshot;};
const key=s=>String(s||'').replace(/\s+/g,'');
// District geometries include administrative wards; a city mayor covers all of that city's wards.
export function matchDistrict(d,items){const candidates=items.filter(p=>p.type==='basic'&&normalizeRegion(p)===d.region);return candidates.filter(p=>{const j=key(p.jurisdiction),n=key(d.name);const local=key(j.replace(/^(서울특별시|부산광역시|대구광역시|인천광역시|대전광역시|울산광역시|경기도|강원특별자치도|강원도|충청북도|충청남도|전북특별자치도|전라북도|전남광주통합특별시|전라남도|광주광역시|경상북도|경상남도)\s*/,''));return !!local&&(n===local||(local.endsWith('시')&&n.startsWith(local)));}).sort((a,b)=>b.jurisdiction.length-a.jurisdiction.length)[0];}
// Fixed hexagonal cartogram shared by every category. Cells are visual units, not seats.
const regionRings=MAP_REGIONS.map(r=>({...r,rings:r.d.split(/Z/i).map(part=>[...part.matchAll(/([\d.-]+),([\d.-]+)/g)].map(m=>[+m[1],+m[2]])).filter(r=>r.length>2)}));
const inside=(x,y,ring)=>{let hit=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>y)!==(yj>y)&&x<(xj-xi)*(y-yi)/(yj-yi)+xi)hit=!hit;}return hit;};
const hexCells=[];const radius=11,step=Math.sqrt(3)*radius;
for(let row=0;row<41;row++)for(let col=0;col<32;col++){const x=20+col*step+(row%2)*step/2,y=50+row*radius*1.5;const region=regionRings.find(r=>r.rings.reduce((hit,ring)=>hit!==inside(x,y,ring),false));if(region)hexCells.push({x,y,region:region.name});}
export function mapSvg(items,state,compact){
 const summary=politicalMapSummary(items,{type:state.type}),regions=new Map(summary.regions.map(r=>[r.id,r]));let defs='',paths='',texts='';
 for(const [index,r] of MAP_REGIONS.entries()){
  const cells=hexCells.filter(c=>c.region===r.name);if(!cells.length)continue;
  const data=regions.get(r.name),parties=data?.parties||[],min=Math.min(...cells.map(c=>c.x))-step/2,max=Math.max(...cells.map(c=>c.x))+step/2,id='hex-'+(compact?'home':'detail')+'-'+index;
  let at=0;const stops=parties.flatMap((p,i)=>{const start=at;at+=p.share*100;const blend=Math.min(.6,p.share*100/8);const paint=state.party!=='all'&&state.party!==p.party?'#e3e5eb':color(p.party);return '<stop offset="'+(start+(i?blend:0))+'%" stop-color="'+paint+'"/><stop offset="'+(at-(i<parties.length-1?blend:0))+'%" stop-color="'+paint+'"/>';}).join('');
  defs+='<linearGradient id="'+id+'" gradientUnits="userSpaceOnUse" x1="'+min+'" x2="'+max+'" y1="0" y2="0">'+stops+'</linearGradient>';
  const fill=parties.length?'url(#'+id+')':'#dfe3ea',dim=state.region!=='all'&&state.region!==r.name;
  paths+='<g data-map-region="'+esc(r.name)+'" tabindex="0" role="button" aria-label="'+esc(r.name+' '+(data?.total||0)+'명')+'" opacity="'+(dim?.28:1)+'"><title>'+esc(r.name+': '+parties.map(p=>p.party+' '+p.count+'명').join(', '))+'</title>'+cells.map(c=>{const d=Array.from({length:6},(_,i)=>{const t=(i*60-30)*Math.PI/180;return (i?'L':'M')+(c.x+radius*Math.cos(t)).toFixed(2)+','+(c.y+radius*Math.sin(t)).toFixed(2);}).join('')+'Z';return '<path d="'+d+'" fill="'+fill+'"/>';}).join('')+'</g>';
  const label=({서울:[226,166],인천:[190,205],경기:[270,215],세종:[245,275],대전:[273,319],충남:[205,290],대구:[375,358],경북:[420,286]})[r.name]||r.center;
  texts+='<text class="pmap-label" data-map-region="'+esc(r.name)+'" x="'+label[0]+'" y="'+label[1]+'" text-anchor="middle">'+esc(r.name==='전남광주'?'전남·광주':r.name)+'</text>';
 }
 const selected=MAP_REGIONS.find(r=>r.name===state.region),bounds=selected?.bounds;
 const box=!compact&&state.zoom&&bounds?[bounds[0]-25,bounds[1]-25,bounds[2]+50,bounds[3]+50].join(' '):compact?'90 30 430 670':'100 40 395 635';
 return '<svg viewBox="'+box+'" aria-label="대한민국 '+labels[state.type]+' 정당 구성 육각형 지도" class="pmap-svg pmap-hex"><defs>'+defs+'</defs><g class="pmap-boundaries">'+paths+'</g>'+texts+'</svg>';
}
function partyRows(summary,state,compact){const rows=compact?summary.parties.slice(0,3):summary.parties;return rows.map(p=>`<button type="button" data-map-party="${esc(p.party)}" aria-pressed="${state.party===p.party}" class="pmap-party"><i style="--party:${color(p.party)}"></i><span>${esc(p.party)}</span><b>${p.count}<small>${state.type==='assembly'?'석':'명'}</small></b>${compact?'':`<em>${(p.share*100).toFixed(1)}%</em><span class="pmap-party-track"><span style="width:${p.share*100}%;background:${color(p.party)}"></span></span>`}</button>`).join('')||'<p>등록된 정보가 없습니다.</p>';}
export function renderPoliticalMapContent(data,state,compact){const all=politicalMapSummary(data.items,{type:state.type}),summary=politicalMapSummary(data.items,{type:state.type,region:state.region}),filtered=politicalMapSummary(data.items,{type:state.type,region:state.region,party:state.party}),people=filtered.items.filter(p=>(!state.district||p.id===state.district)&&(p.name+' '+p.jurisdiction).includes(state.q));
 const tabs=`<nav class="pmap-tabs" aria-label="정치지도 분류">${Object.entries(labels).map(([k,v])=>`<button data-map-type="${k}" aria-pressed="${state.type===k}">${v}</button>`).join('')}</nav>`;
 if(compact)return tabs+renderElectionCountdown(state.type)+`<div class="pmap-preview"><a class="pmap-mini-map" href="/political-map?type=${state.type}" data-layout-route="/political-map?type=${state.type}" aria-label="${labels[state.type]} 지도 확대">${mapSvg(data.items,state,true)}</a><div class="pmap-mini-stats"><div class="pmap-total"><span>${labels[state.type]} 등록 현황</span><strong>${all.total}<small>${state.type==='assembly'?'석':'명'}</small></strong></div>${partyRows(all,state,true)}${state.type==='all'?`<div class="pmap-home-categories"><span>국회의원 <b>${all.byType.assembly}석</b></span><span>광역단체장 <b>${all.byType.metropolitan}명</b></span><span>기초단체장 <b>${all.byType.basic}명</b></span></div>`:''}</div></div>`;
 if(state.region!=='all'){
 const overview=mapSvg(data.items,{...state,party:'all',zoom:false},false).replaceAll('hex-detail-','hex-navigator-');
 const navigator='<nav class="pmap-region-navigator" aria-label="다른 지역 탐색"><div class="pmap-navigator-heading"><strong>전국 지역 탐색</strong><span>지역을 눌러 이동</span></div><div class="pmap-navigator-body"><div class="pmap-navigator-map">'+overview+'</div><div class="pmap-navigator-regions">'+MAP_REGIONS.map(r=>'<button type="button" data-map-region="'+esc(r.name)+'" aria-pressed="'+(state.region===r.name)+'">'+esc(r.name==='전남광주'?'전남·광주':r.name)+'</button>').join('')+'</div></div></nav>';
 return tabs+renderElectionCountdown(state.type)+renderRegionStage(data,state,color,navigator);
 }
 const regionOptions=POLITICAL_MAP_REGIONS.filter(r=>r.id!=='미분류'||all.regions.find(x=>x.id===r.id)?.total);
 return tabs+renderElectionCountdown(state.type)+`<div class="pmap-toolbar"><label>지역<select data-map-region-select><option value="all">전국</option>${regionOptions.map(r=>`<option value="${r.id}" ${state.region===r.id?'selected':''}>${r.label}</option>`).join('')}</select></label><button data-map-reset>전국으로</button><button data-map-zoom ${state.region==='all'?'disabled':''} aria-pressed="${state.zoom}">${state.zoom?'전체 지도':'선택 지역 확대'}</button></div><div class="pmap-layout"><div class="pmap-map-panel">${mapSvg(data.items,state,false)}<p class="pmap-map-note">지역별 정당 구성</p></div><aside class="pmap-summary"><div class="pmap-total"><span>${esc(state.region==='all'?'전국':state.region)} · ${labels[state.type]}</span><strong>${summary.total}<small>${state.type==='assembly'?'석':'명'}</small></strong></div><p class="pmap-counts">현원 ${summary.occupied} · 공석 ${summary.vacant}</p>${state.type==='all'?`<div class="pmap-types">국회의원 <b>${summary.byType.assembly}</b><br>광역단체장 <b>${summary.byType.metropolitan}</b><br>기초단체장 <b>${summary.byType.basic}</b></div>`:''}<div class="pmap-party-list">${partyRows(summary,state,false)}</div>${state.party!=='all'?`<button data-map-party="all" class="pmap-clear">정당 선택 해제</button>`:''}<p class="pmap-subnote">전국 집계는 비례대표를 포함합니다. 지역별 지도에는 비례대표를 배정하지 않습니다.</p></aside></div><section class="pmap-roster"><header><h2>${esc(state.region==='all'?'전체 지역':state.region)} 인물 <span>${people.length}</span></h2><form data-map-search><label><span class="pmap-sr">이름 또는 지역 검색</span><input name="q" value="${esc(state.q)}" placeholder="이름 또는 지역 검색"></label><button>검색</button></form></header><div class="pmap-people">${people.slice(0,state.limit).map(p=>`<a href="/person/${encodeURIComponent(p.id)}" data-layout-route="/person/${esc(p.id)}"><i style="background:${color(partyOf(p))}"></i><div><strong>${esc(p.name||'공석')}</strong><span>${esc(p.jurisdiction||p.region)}</span></div><div><b>${esc(partyOf(p))}</b><span>${labels[p.type]}</span></div></a>`).join('')||'<p>조건에 맞는 인물이 없습니다.</p>'}</div>${people.length>state.limit?'<button class="pmap-more" data-map-more>인물 더 보기</button>':''}</section><footer class="pmap-source">${esc(data.basis)} · 조회 ${esc(new Date(data.asOf).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}<br>등록 정보 기준이며 선거 결과·득표율을 의미하지 않습니다. 경계와 등록 지역이 일치하지 않으면 회색으로 표시하며, 인물은 목록에서 확인할 수 있습니다. 지도: 통계청 SGIS / <a href="https://github.com/DevMinGeonPark/mapcn-kr" target="_blank" rel="noopener">mapcn-kr</a> (CC BY 4.0), 경계 단순화.</footer>`;
}
export async function mountPoliticalMap(root){if(mounted.has(root))return;mounted.add(root);const compact=root.dataset.politicalMap==='home',params=new URLSearchParams(globalThis.location?.search||''),state={type:labels[params.get('type')]?params.get('type'):'all',region:POLITICAL_MAP_REGIONS.some(r=>r.id===params.get('region'))?params.get('region'):'all',local:'',city:'',party:'all',q:'',limit:24,zoom:false,district:''};let data;const mount=root.querySelector('[data-pmap-content]');
 const draw=()=>{mount.innerHTML=renderPoliticalMapContent(data,state,compact);if(!compact)void loadRegionPhotos(mount);};
 const timer=setInterval(()=>{if(!root.isConnected){clearInterval(timer);return;}updateElectionCountdowns(root);},30000);timer.unref?.();
 try{data=await load();draw();}catch{mount.innerHTML='<p class="pmap-loading">정보를 불러오지 못했습니다. <button data-map-retry>다시 시도</button></p>';}
 root.addEventListener('click',async e=>{const b=e.target.closest('[data-map-type],[data-map-region],[data-map-party],[data-map-reset],[data-map-more],[data-map-zoom],[data-map-retry],[data-map-local],[data-map-city],[data-map-city-back]');if(!b)return;if(compact&&b.dataset.mapRegion){e.preventDefault();e.stopPropagation();window.dispatchEvent(new CustomEvent('jcs:layout-route',{detail:{route:'/political-map?type='+state.type+'&region='+encodeURIComponent(b.dataset.mapRegion)}}));return;}if(compact&&b.closest('a'))return;if(b.hasAttribute('data-map-retry')){try{data=await load();draw();}catch{b.textContent='연결 실패 · 다시 시도';}return;}if(!data)return;
 if(b.hasAttribute('data-map-city')){state.district='';state.city=b.dataset.mapCity;state.local='';state.party='all';state.q='';state.limit=24;}
 else if(b.hasAttribute('data-map-city-back')){state.district='';state.city='';state.local='';state.party='all';state.q='';state.limit=24;}
 else if(b.hasAttribute('data-map-local')){state.district='';state.local=state.local===b.dataset.mapLocal?'':b.dataset.mapLocal;state.party='all';state.q='';state.limit=24;}
 else if(b.dataset.mapType){state.district='';state.type=b.dataset.mapType;state.party='all';state.limit=24;}
 else if(b.dataset.mapRegion){state.region=b.dataset.mapRegion;state.local='';state.city='';state.q='';const district=MAP_DISTRICTS.find(d=>d.name===b.dataset.mapDistrict&&d.region===state.region);state.district=district?matchDistrict(district,data.items)?.id||'unmatched':'';state.limit=24;state.party='all';}
 else if(b.dataset.mapParty){state.party=state.party===b.dataset.mapParty?'all':b.dataset.mapParty;state.limit=24;}
 else if(b.hasAttribute('data-map-more'))state.limit+=24;
 else if(b.hasAttribute('data-map-zoom'))state.zoom=!state.zoom;
 else {state.district='';state.region='all';state.local='';state.city='';state.party='all';state.zoom=false;state.q='';state.limit=24;}
 draw();});
 root.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('[data-map-region],[data-map-local],[data-map-city]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
 root.addEventListener('change',e=>{if(e.target.matches('[data-map-local-select]')){state.district='';state.local=e.target.value;if(state.local){const parent=districtCity(state.local);state.city=parent!==state.local?parent:'';}state.party='all';state.q='';state.limit=24;draw();return;}if(e.target.matches('[data-map-region-select]')){state.district='';state.region=e.target.value;state.local='';state.city='';state.q='';state.limit=24;state.party='all';draw();}});
 root.addEventListener('submit',e=>{if(e.target.matches('[data-map-search]')){e.preventDefault();state.district='';state.q=new FormData(e.target).get('q').trim();state.limit=24;draw();}});
}
