const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderHourly(data){
 const max=Math.max(1,...data.hourly.map(x=>x.count));
 const local=new Date(Date.now()+9*3600000).toISOString();
 return `<section style="margin:28px 0"><h2>${esc(data.day)} 시간대별 방문</h2><p>한국 시간 · 1시간 단위 · 중복 포함</p><p>시간대 집계 시작: ${esc(data.hourlyStartedAt?.replace('T',' ')||'집계 대기')}${data.unallocated?' · 시간대 미분류 '+Number(data.unallocated).toLocaleString('ko-KR')+'회 (시간대 집계 도입 전 기록)':''}</p><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:8px">시간대</th><th style="text-align:right;padding:8px">방문 횟수</th><th style="width:40%;padding:8px">방문 분포</th></tr></thead><tbody>${data.hourly.map(x=>{const future=data.day+'T'+x.hour>local.slice(0,13);return `<tr><td style="padding:7px;border-top:1px solid #eee;white-space:nowrap">${x.hour}:00–${String(Number(x.hour)+1).padStart(2,'0')}:00</td><td style="text-align:right;padding:7px;border-top:1px solid #eee">${future?'예정':x.tracked?Number(x.count).toLocaleString('ko-KR')+'회':'집계 전'}</td><td style="padding:7px;border-top:1px solid #eee"><div aria-hidden="true" style="height:8px;border-radius:4px;background:#f1f5f7;overflow:hidden"><div style="height:100%;width:${x.count/max*100}%;background:#659baf"></div></div></td></tr>`;}).join('')}</tbody></table></section>`;
}
export async function renderAdminVisits(params){
 const query=new URLSearchParams();for(const key of ['from','to','day'])if(params.get(key))query.set(key,params.get(key));
 let data;try{const r=await fetch('/api/v3/admin/site-visits?'+query,{cache:'no-store',credentials:'same-origin'});data=await r.json();if(!r.ok)throw Error();}catch{return '<section class="module"><h2>방문 통계를 불러오지 못했습니다.</h2><p>오늘 이전의 날짜로 최대 366일 범위를 선택해 주세요.</p><button data-layout-route="/admin/visits">최근 30일 보기</button></section>';}
 const n=v=>Number(v||0).toLocaleString('ko-KR');
 return `<section class="module"><p>한국 시간 기준 · 중복 포함 방문 횟수</p><p>새로고침, 페이지 재방문, 메인·사이드 배너 자동 전환, 나우랭크·여론조사 데이터 갱신을 포함합니다. 고유 방문자 수가 아닙니다.</p><form data-visit-range style="display:flex;gap:12px;flex-wrap:wrap;align-items:end;margin:20px 0"><label>시작일 <input type="date" name="from" required value="${esc(data.from)}" max="${esc(data.today)}"></label><label>종료일 <input type="date" name="to" required value="${esc(data.to)}" max="${esc(data.today)}"></label><label>시간대 조회일 <input type="date" name="day" required value="${esc(data.day)}" max="${esc(data.today)}"></label><button class="primary-btn" type="submit">조회하기</button></form><div class="admin-overview-metrics"><article class="admin-metric"><span>오늘 방문 횟수</span><strong>${n(data.todayCount)}<small>회</small></strong></article><article class="admin-metric"><span>조회 기간 합계</span><strong>${n(data.total)}<small>회</small></strong></article><article class="admin-metric"><span>집계 시작일</span><strong style="font-size:20px">${esc(data.startedAt||'집계 대기')}</strong></article></div>${renderHourly(data)}<p>집계 시작 전 기록은 소급하지 않습니다. 오늘 수치는 계속 증가합니다.</p><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:left;padding:12px">날짜</th><th style="text-align:right;padding:12px">방문 횟수</th></tr></thead><tbody>${data.items.map(x=>`<tr><td style="padding:12px;border-top:1px solid #eee">${esc(x.date)}${x.date===data.today?' · 오늘':''}</td><td style="text-align:right;padding:12px;border-top:1px solid #eee">${x.tracked?n(x.count)+'회':'집계 전'}</td></tr>`).join('')}</tbody></table></div></section>`;
}
