import { campaignUrl } from '../core/campaign-model.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fields=['headline','accentLine','intro','personId','name','party','office','region','photoUrl','topic','startDate','endDate','whyTitle','whyBody','selectionReason','quote','storyBody','needsBody','policyTitle','videoUrl','productionDisclosure'];
export const CAMPAIGN_EDITOR_LIMITS=Object.freeze({headline:120,accentLine:120,intro:600,personId:120,name:80,party:100,office:100,region:120,photoUrl:1000,topic:80,startDate:10,endDate:10,whyTitle:180,whyBody:5000,selectionReason:1600,quote:1000,storyBody:7000,needsBody:3000,policyTitle:180,videoUrl:1000,productionDisclosure:1600});
const publicationRequired=new Set(['headline','intro','name','photoUrl','topic','whyBody','storyBody','policyTitle']);
const value=(draft,key)=>esc(draft?.[key]||'');
const labelText=(key,label)=>`${label}${publicationRequired.has(key)?'<em class="campaign-publish-required">게시 필수</em>':''}`;
const input=(draft,key,label,type='text',extra='')=>`<label class="campaign-field"><span>${labelText(key,label)}</span><input type="${type}" name="${key}" value="${value(draft,key)}" maxlength="${CAMPAIGN_EDITOR_LIMITS[key]}" ${extra}></label>`;
const area=(draft,key,label,rows=4)=>`<label class="campaign-field campaign-field-wide"><span>${labelText(key,label)}</span><textarea name="${key}" rows="${rows}" maxlength="${CAMPAIGN_EDITOR_LIMITS[key]}">${value(draft,key)}</textarea></label>`;

function policyRow(item={},index=0){return `<div class="campaign-repeat-row" data-campaign-policy-row><label><span>정책 제목 <em class="campaign-publish-required">게시 필수</em></span><input name="policies[${index}].title" value="${esc(item.title||'')}" maxlength="180"></label><label><span>정책 내용 <em class="campaign-publish-required">게시 필수</em></span><textarea name="policies[${index}].body" rows="3" maxlength="3000">${esc(item.body||'')}</textarea></label><button type="button" data-campaign-remove-row aria-label="정책 삭제">삭제</button></div>`;}
function sourceRow(item={},index=0){return `<div class="campaign-repeat-row campaign-source-row" data-campaign-source-row><label><span>출처 이름</span><input name="sources[${index}].label" value="${esc(item.label||'')}" maxlength="180"></label><label><span>출처 URL</span><input type="url" name="sources[${index}].url" value="${esc(item.url||'')}" maxlength="1000"></label><button type="button" data-campaign-remove-row aria-label="출처 삭제">삭제</button></div>`;}

export function renderCampaignEditor(record=null,session={}){
  if(session?.authenticated!==true||session?.user?.role!=='admin')return `<main class="campaign-editor-page"><section class="content-card campaign-editor-guard"><h1>CAMPAIGN</h1><p>관리자만 캠페인을 등록하고 편집할 수 있습니다.</p><a href="/campaigns" data-layout-route="/campaigns">캠페인 게시판으로</a></section></main>`;
  const draft=record?.draft||{},policies=Array.isArray(draft.policies)&&draft.policies.length?draft.policies:[{}],sources=Array.isArray(draft.sources)&&draft.sources.length?draft.sources:[{}],published=!!record?.published,ended=!!record?.endedAt;
  const title=record?.id?'캠페인 수정':'캠페인 등록';
  return `<main class="campaign-editor-page"><header class="campaign-editor-head"><span>CAMPAIGN EDITOR</span><h1>${title}</h1><p>초안은 미완성 상태로 저장할 수 있으며, 공개할 때 서버가 필수 정보를 확인합니다. 날짜는 한국 표준시(KST)를 기준으로 합니다.</p></header><form data-campaign-form data-campaign-existing="${record?.id?'true':'false'}" novalidate>
  <input type="hidden" name="id" value="${esc(record?.id||'')}"><input type="hidden" name="version" value="${esc(record?.version||0)}"><input type="hidden" name="personId" value="${value(draft,'personId')}">
  <section class="content-card campaign-editor-section"><h2>인물과 캠페인</h2><div class="campaign-form-grid">
  ${input(draft,'headline','제목')}${input(draft,'accentLine','강조 문구')}${area(draft,'intro','소개',3)}
  <label class="campaign-field politician-autocomplete-field"><span>${labelText('name','정치인 검색 또는 이름 직접 입력')}</span><input type="search" name="name" value="${value(draft,'name')}" maxlength="80" autocomplete="off" data-politician-autocomplete data-politician-select-mode="value" data-politician-target="[name=personId]" placeholder="이름·정당·지역 검색"></label>
  ${input(draft,'party','정당','text',draft.personId?'data-campaign-linked-profile':'')}${input(draft,'office','직책','text',draft.personId?'data-campaign-linked-profile':'')}${input(draft,'region','지역','text',draft.personId?'data-campaign-linked-profile':'')}${input(draft,'topic','주제')}
  <div class="campaign-photo-field"><label><span>${labelText('photoUrl','사진 URL')}</span><input type="url" name="photoUrl" value="${value(draft,'photoUrl')}" maxlength="1000" data-campaign-photo-url ${draft.personId?'data-campaign-linked-profile':''}></label><label class="campaign-upload"><span>사진 업로드 · JPG/PNG/WEBP, 최대 2MB</span><input type="file" accept="image/jpeg,image/png,image/webp" data-campaign-photo-upload></label><div data-campaign-photo-preview>${campaignUrl(draft.photoUrl,{local:true})?`<img src="${esc(campaignUrl(draft.photoUrl,{local:true}))}" alt="현재 캠페인 사진">`:''}</div></div>
  ${input(draft,'startDate','시작일 (KST)','date')}${input(draft,'endDate','종료일 (KST)','date')}</div></section>
  <section class="content-card campaign-editor-section"><h2>본문</h2><div class="campaign-form-grid">${input(draft,'whyTitle','WHY 제목')}${area(draft,'whyBody','WHY 본문')}${area(draft,'selectionReason','선정 이유')}${area(draft,'quote','인용문')}${area(draft,'storyBody','이야기')}${area(draft,'needsBody','필요성')}${input(draft,'policyTitle','정책 묶음 제목')}${input(draft,'videoUrl','영상 URL','url')}</div></section>
  <section class="content-card campaign-editor-section"><div class="campaign-section-title"><h2>정책</h2><button type="button" data-campaign-add-policy>정책 추가</button></div><div data-campaign-policy-list>${policies.slice(0,8).map(policyRow).join('')}</div><p>최대 8개</p></section>
  <section class="content-card campaign-editor-section"><div class="campaign-section-title"><h2>출처</h2><button type="button" data-campaign-add-source>출처 추가</button></div><div data-campaign-source-list>${sources.slice(0,10).map(sourceRow).join('')}</div><p>최대 10개</p></section>
  <section class="content-card campaign-editor-section"><h2>제작 관계와 공개</h2><div class="campaign-form-grid"><label class="campaign-field"><span>제작 관계</span><select name="productionRelation">${[['editorial','편집 제작'],['commissioned','의뢰 제작'],['ad','광고']].map(([key,label])=>`<option value="${key}" ${draft.productionRelation===key?'selected':''}>${label}</option>`).join('')}</select></label>${area(draft,'productionDisclosure','제작 관계 고지',3)}<label class="campaign-check"><input type="checkbox" name="featured" value="true" ${draft.featured?'checked':''}> 캠페인 게시판 대표로 표시</label><p class="campaign-feature-note">대표 캠페인은 캠페인 게시판 안에서만 적용되며 메인 배너와 연결되지 않습니다.</p></div></section>
  <div class="campaign-editor-actions"><button type="submit" data-campaign-operation="save">초안 저장</button><button type="submit" data-campaign-operation="publish">${published?'수정 게시':'게시'}</button>${published?`<button type="submit" data-campaign-operation="hide">비공개</button>${ended?'':'<button type="submit" data-campaign-operation="end">종료</button>'}`:''}${!published&&record?.id?'<button type="submit" class="danger" data-campaign-operation="delete">초안 삭제</button>':''}<a href="/campaigns?view=manage" data-layout-route="/campaigns?view=manage">관리 목록</a><span data-campaign-state role="status"></span></div>
  </form></main>`;
}

export const campaignEditorFields=Object.freeze(fields);
