import { cageArena } from '../layout/home-layout.js?v=0.0.31.113';
import { badgeByKey, badgeCrestSvg } from '../data/badge-catalog.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleString('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});};
const route=d=>d==='columns'?'column':d;
const label=d=>({community:'커뮤니티 X 케이지',itsme:'IT’S ME',columns:'COLUMN',news:'정참시 NEWS',inquiry:'1:1 문의'}[d]||d);
const body=v=>String(v||'').split(/\n\s*\n/).filter(Boolean).map(s=>`<p>${esc(s).replace(/\n/g,'<br>')}</p>`).join('');
const image=v=>/^(https:\/\/|\/(?!\/))/i.test(String(v||''))?String(v):'';
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({share:'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m9 10 6-4M9 14l6 4"/>',zap:'<path d="m13 2-9 12h7l-1 8 10-13h-7l1-7Z"/>',swords:'<path d="m3 3 14 14m-3 3 6-6M21 3 7 17m3 3-6-6M3 3l1 5 4-4-5-1ZM21 3l-1 5-4-4 5-1Z"/>',crown:'<path d="m3 6 5 4 4-7 4 7 5-4-3 14H6L3 6Z"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',bookmark:'<path d="M5 3h14v18l-7-4-7 4V3Z"/>',list:'<path d="M9 6h12M9 12h12M9 18h12M3 6h1M3 12h1M3 18h1"/>',pencil:'<path d="m16 3 5 5-13 13H3v-5L16 3ZM13 6l5 5"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',comment:'<path d="M21 11a9 9 0 0 1-9 9H4l-3 2 1-6a9 9 0 1 1 19-5Z"/>'})[name]||'<path d="m14 6-6 6 6 6"/>'}</svg>`;
export const authorIdentity=item=>{const badge=badgeByKey(item?.representativeBadge);return `<span class="author-identity"><span class="author-nickname">${esc(item?.author||'정참시')}</span>${badge?`<span class="author-representative-badge" title="대표배지 · ${esc(badge.name)}">${badgeCrestSvg(badge.key)}</span>`:''}</span>`;};
const canManage=(session,item)=>!!session?.authenticated&&(session.user?.role==='admin'||!!item.ownerId&&String(item.ownerId)===String(session.user?.id));
const tag=item=>item.pinKind==='notice'?'<span class="jc-tag gold">공지</span>':item.cageEnabled?'<span class="jc-tag gold">케이지</span>':item.camp?`<span class="jc-tag ${item.camp==='progressive'?'blue':'red'}">${item.camp==='progressive'?'진보':'보수'}진영</span>`:'';
const field=(name,title,value='',large=false)=>`<label class="jc-field"><span>${title}</span>${large?`<textarea name="${name}" ${name==='body'?'required':''}>${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}" ${name==='title'?'required maxlength="200"':''}>`}</label>`;
export const ITSME_CATEGORIES=['내가 대통령이라면','내가 국회의원이라면','내가 시장이라면','내가 장관이라면','내가 시/도의원이라면'];
const categoryField=(value='',categories=ITSME_CATEGORIES)=>{const choices=[...new Set([...(categories.length?categories:ITSME_CATEGORIES),...(value?[value]:[])])];return `<label class="jc-field"><span>말머리</span><select name="category" required><option value="" disabled ${value?'':'selected'}>말머리를 선택해 주세요</option>${choices.map(category=>`<option value="${esc(category)}" ${category===value?'selected':''}>${esc(category)}</option>`).join('')}</select></label>`;};
export function pinFields(item={},session={}){return session.user?.role==='admin'&&!item.cageParentId?`<div class="jc-field"><span>상단 고정 · 관리자 전용</span><input type="hidden" name="pinKind" value="${esc(item.pinKind||'')}"><div class="jc-pin-options"><label><input type="checkbox" name="pinNotice" ${item.pinKind==='notice'?'checked':''}>공지</label><label><input type="checkbox" name="pinCage" ${item.pinKind==='cage'?'checked':''}>케이지</label></div><small class="jc-admin-note">선택한 글은 상단에 고정됩니다. 해제하면 원래 작성일 순서로 돌아갑니다.</small></div>`:'';}
const imageField=item=>`<label class="jc-field"><span>대표 사진 · 16:9 · JPG·PNG·WEBP, 최대 1MB</span><input type="file" name="coverFile" accept="image/jpeg,image/png,image/webp"></label>${field('coverImage','사진 주소',item.coverImage||'')}`;
export function postMenu(domain,item,session={}){
 const manage=canManage(session,item),share=['community','itsme','columns','news'].includes(domain);if(!manage&&!share)return '';
 const shareButton=share?`<button type="button" data-post-share data-domain="${esc(domain)}" data-post-id="${esc(item.id)}" data-post-title="${esc(item.title)}">${icon('share')}공유하기</button>`:'';
 if(!manage)return `<details class="jc-menu"><summary aria-label="게시글 메뉴">⋯</summary><div class="jc-popover">${shareButton}</div></details>`;
 return `<details class="jc-menu"><summary aria-label="게시글 관리 메뉴">⋯</summary><div class="jc-popover">${shareButton}<button type="button" data-jc-edit>${icon('pencil')}수정</button>${domain==='community'&&item.pinKind?`<button type="button" data-jc-unpin data-domain="community" data-post-id="${esc(item.id)}">상단 고정 해제</button>`:''}<button type="button" class="jc-danger" data-jc-delete data-domain="${esc(domain)}" data-post-id="${esc(item.id)}" data-return-route="/${route(domain)}${item.cageParentId?'/'+esc(item.cageParentId):''}">${icon('trash')}삭제</button></div><template data-jc-editor><form data-stage-form="post-edit" data-domain="${esc(domain)}" data-post-id="${esc(item.id)}"><h2>게시글 수정</h2>${domain==='community'?pinFields(item,session):''}${field('title','제목',item.title)}${field('body','내용',item.body,true)}${domain==='itsme'?categoryField(item.category):''}${['columns','news'].includes(domain)?imageField(item):''}<div class="jc-editor-bottom"><button type="button" class="jc-subtle" data-jc-close>취소</button><button class="jc-primary" type="submit">수정 저장</button></div><span data-form-state role="status"></span></form></template></details>`;
}
const byline=(domain,item,session)=>`<div class="jc-byline"><div class="jc-author"><span class="jc-avatar">${esc(String(item.author||'정')[0])}</span><div><b>${authorIdentity(item)}</b><small>${date(item.createdAt)} · 조회 ${Number(item.views||0).toLocaleString('ko-KR')}</small></div></div>${postMenu(domain,item,session)}</div>`;
const campPicker=()=>`<div class="jc-camp-choice"><label><input type="radio" name="camp" value="progressive" required><span>진보진영 힘보태기</span></label><label><input type="radio" name="camp" value="conservative" required><span>보수진영 힘보태기</span></label></div>`;
function commentComposer(domain,item,session,parentId=''){
 if(!session.authenticated)return '<div class="jc-compose-bottom"><small>댓글은 로그인 후 작성할 수 있습니다.</small><button class="jc-primary" data-layout-route="/login">로그인</button></div>';
 const cage=!!(item.cageParentId||item.cageEnabled);
 return `<form class="jc-composer" data-stage-form="comment" data-domain="${esc(domain)}" data-post-id="${esc(item.id)}">${parentId?`<input type="hidden" name="parentId" value="${esc(parentId)}">`:''}${cage?campPicker():''}<fieldset data-camp-body ${cage?'disabled':''}><textarea name="text" aria-label="${parentId?'답글':'댓글'} 입력" placeholder="${cage?'참여 진영을 선택한 후 생각을 남겨 주세요.':'생각을 남겨 주세요.'}" required maxlength="1000"></textarea><div class="jc-compose-bottom"><small>${esc(session.user?.nickname||session.user?.id||'회원')}님으로 작성</small><button class="jc-primary" type="submit">${parentId?'답글 등록':'등록'}</button></div></fieldset><span data-form-state role="status"></span></form>`;
}
export async function sharedComments(domain,item,content,session={}){
 const comments=(await content.commentsFor(domain,item.id)).filter(c=>c.published!==false).sort((a,b)=>String(a.createdAt||'').localeCompare(String(b.createdAt||''))),ids=new Set(comments.map(c=>String(c.id)));
 const renderComment=(c,reply=false)=>`<article class="jc-comment ${reply?'jc-reply':''}"><div class="jc-comment-top"><div class="jc-author"><span class="jc-avatar">${c.deleted?'·':esc(String(c.author||'회')[0])}</span><div><b>${c.deleted?'삭제된 댓글':authorIdentity(c)}</b><small>${c.deleted?'':tag(c)}<time>${date(c.createdAt)}</time></small></div></div>${!c.deleted&&canManage(session,c)?`<details class="jc-menu"><summary aria-label="댓글 관리 메뉴">⋯</summary><div class="jc-popover"><button type="button" data-jc-edit>${icon('pencil')}수정</button><button type="button" class="jc-danger" data-jc-comment-delete data-domain="${esc(domain)}" data-post-id="${esc(item.id)}" data-comment-id="${esc(c.id)}">${icon('trash')}삭제</button></div><template data-jc-editor><form data-stage-form="comment-edit" data-domain="${esc(domain)}" data-post-id="${esc(item.id)}" data-comment-id="${esc(c.id)}"><h2>댓글 수정</h2>${field('text','댓글',c.text,true)}<div class="jc-editor-bottom"><button class="jc-subtle" type="button" data-jc-close>취소</button><button class="jc-primary" type="submit">수정 저장</button></div><span data-form-state role="status"></span></form></template></details>`:''}</div><p>${c.deleted?'작성자가 삭제한 댓글입니다.':esc(c.text).replace(/\n/g,'<br>')}</p>${!c.deleted?`<div class="jc-comment-tools"><button class="jc-text" type="button" data-jc-comment-like data-domain="${esc(domain)}" data-post-id="${esc(item.id)}" data-comment-id="${esc(c.id)}" aria-pressed="${!!c.liked}">${icon('heart')}좋아요 ${Number(c.likes||0)}</button>${session.authenticated?`<button class="jc-text" type="button" data-jc-reply>${icon('comment')}답글</button>`:''}</div><div data-jc-reply-body hidden>${commentComposer(domain,item,session,c.id)}</div>`:''}</article>`;
 const roots=comments.filter(c=>!c.parentId||!ids.has(String(c.parentId)));
 return `<section class="jc-paper jc-comments"><div class="jc-comments-head"><h3>댓글 <span>${comments.filter(c=>!c.deleted).length}</span></h3><small>등록순</small></div>${commentComposer(domain,item,session)}${roots.map(c=>{const replies=comments.filter(r=>String(r.parentId)===String(c.id));return renderComment(c)+(replies.length?`<details class="jc-reply-thread"><summary>답글 ${replies.length}개</summary>${replies.map(r=>renderComment(r,true)).join('')}</details>`:'');}).join('')||'<div class="jc-empty">첫 번째 의견을 남겨 주세요.</div>'}</section>`;
}
const postActions=(domain,item,dashboard,parent)=>{const saved=(dashboard.favoriteKeys||[]).includes(`post:${domain}:${item.id}`);return `<div class="jc-actions"><div class="jc-actions-left"><button class="jc-reaction" type="button" data-post-like data-domain="${esc(domain)}" data-post-id="${esc(item.id)}" aria-pressed="${!!item.liked}">${icon('heart')}좋아요 <b>${Number(item.likes||0).toLocaleString('ko-KR')}</b></button><button class="jc-reaction favorite-control" type="button" data-stage-action="favorite-toggle" data-favorite-kind="post" data-favorite-domain="${esc(domain)}" data-favorite-id="${esc(item.id)}" aria-pressed="${saved}">${icon('bookmark')}${saved?'저장됨':'즐겨찾기'}</button></div><button class="jc-text" type="button" data-layout-route="${esc(parent)}">${icon('list')}목록으로</button></div>`;};
export async function sharedPost(domain,item,content,session={},dashboard={}){
 const saved=(dashboard.favoriteKeys||[]).includes(`post:${domain}:${item.id}`),parent=item.cageParentId?`/community/${item.cageParentId}`:`/${route(domain)}`,comments=await sharedComments(domain,item,content,session);
 return `<div class="subpage jc49"><div class="jc-breadcrumb"><button data-layout-route="${esc(parent)}">${item.cageParentId?'케이지로':label(domain)}</button><span>/</span><span>게시글</span></div><article class="jc-paper jc-article"><div class="jc-category">${tag(item)||`<span class="jc-tag gold">${label(domain)}</span>`}${item.category?`<span class="jc-tag">${esc(item.category)}</span>`:''}</div><h2>${esc(item.title)}</h2>${byline(domain,item,session)}${image(item.coverImage)?`<img class="jc-cover" src="${esc(image(item.coverImage))}" alt="${esc(item.title)}">`:''}${item.summary?`<div class="jc-lead">${esc(item.summary)}</div>`:''}<div class="jc-copy">${body(item.body)}</div>${postActions(domain,item,dashboard,parent)}</article>${comments}</div>`;
}
const percent=(counts,key)=>{const total=Number(counts?.progressive||0)+Number(counts?.conservative||0);return total?Math.round(Number(counts[key]||0)/total*1000)/10:0;};
const ratio=(name,counts={})=>{const left=percent(counts,'progressive'),total=Number(counts.progressive||0)+Number(counts.conservative||0),right=total?Math.round((100-left)*10)/10:0;return `<div class="jc-ratio-row"><span>${name}</span><div><div class="jc-ratio-labels"><span><b>${left}%</b><small>${Number(counts.progressive||0)}개</small></span><span><b>${right}%</b><small>${Number(counts.conservative||0)}개</small></span></div><div class="jc-track" role="img" aria-label="${name}: 진보 ${left}%, 보수 ${right}%"><span style="width:${left}%"></span><span style="width:${right}%"></span></div></div></div>`;};
export async function communityBoard(content,session={},url=''){
 const all=await content.list('community'),data=content.peekDomain?.('community')||{},filter=new URLSearchParams(String(url).split('?')[1]||'').get('filter')||'all';
 const rows=all.filter(x=>x.published!==false&&!x.cageParentId).sort((a,b)=>Number(!!b.pinKind)-Number(!!a.pinKind)||String(b.createdAt||'').localeCompare(String(a.createdAt||''))).filter(x=>filter==='all'||(filter==='cage'?x.cageEnabled:x.pinKind==='notice'));
 return `<div class="subpage jc49"><div class="jc-heading"><div><span class="jc-eyebrow">COMMUNITY × CAGE</span><h1>커뮤니티 X 케이지</h1><p>생각을 나누고, 참여로 힘을 보태는 곳.</p></div><button class="jc-primary" type="button" data-layout-route="${session.authenticated?'/community/write':'/login'}">${icon('pencil')}글쓰기</button></div><a class="point-open-link" href="/community/write" data-layout-route="/community/write">케이지 개설</a><nav class="jc-tabs">${[['all','전체 글'],['notice','공지'],['cage','케이지']].map(([key,title])=>`<button aria-selected="${filter===key}" data-layout-route="/community${key==='all'?'':'?filter='+key}">${title}</button>`).join('')}<small>고정글 우선 · 최신순</small></nav><section class="jc-paper jc-list">${rows.map((item,i)=>`<article class="jc-list-row ${item.pinKind?'pinned':''}"><div>${tag(item)||`<span class="jc-row-number">${rows.length-i}</span>`}</div><button class="jc-row-link" type="button" data-layout-route="/community/${esc(item.id)}"><strong>${esc(item.title)}</strong><small>${authorIdentity(item)} · ${date(item.createdAt)}</small>${item.cageEnabled?`<div class="jc-mini-ratio"><span>게시글</span><span>진보 ${percent(data.cageStats?.[item.id]?.posts,'progressive')}%</span><span>보수 ${percent(data.cageStats?.[item.id]?.posts,'conservative')}%</span></div>`:''}</button><div class="jc-list-stats"><span>조회 ${Number(item.views||0)}</span>${postMenu('community',item,session)}</div></article>`).join('')||'<div class="jc-empty">등록된 게시글이 없습니다.</div>'}</section></div>`;
}
export function sharedWrite(domain,session={},wallet={},categories=ITSME_CATEGORIES){return `<div class="subpage jc49"><div class="jc-breadcrumb"><button data-layout-route="/${route(domain)}">${label(domain)}</button><span>/ 글쓰기</span></div><div class="jc-heading"><div><span class="jc-eyebrow">WRITE</span><h1>이야기를 시작해 주세요</h1></div></div><section class="jc-paper jc-editor"><form data-stage-form="${domain==='itsme'?'itsme':'board'}" data-domain="${domain}">${domain==='community'?cageWriteOptions(session,wallet):''}${field('title',domain==='itsme'?'제안 제목':'제목')}${domain==='itsme'?categoryField('',categories):''}${field('body','내용','',true)}${['columns','news'].includes(domain)?imageField({}):''}<div class="jc-editor-bottom"><button class="jc-text" type="button" data-layout-route="/${route(domain)}">목록으로</button><button class="jc-primary" type="submit">게시글 등록</button></div><span data-form-state role="status"></span></form></section></div>`;}

const count=v=>Number.isFinite(Number(v))?Math.max(0,Math.floor(Number(v))):0;
const newest=(a,b)=>(Date.parse(b.createdAt)||0)-(Date.parse(a.createdAt)||0)||String(b.id).localeCompare(String(a.id));
const campName=camp=>camp==='progressive'?'진보진영':'보수진영';
export function cagePageData(items,rootId,requestedPage=1){
 const children=(items||[]).filter(p=>p.published!==false&&!p.deleted&&String(p.cageParentId||'')===String(rootId)).sort(newest);
 const winners=['progressive','conservative'].map(camp=>children.filter(p=>p.camp===camp&&count(p.likes)>0).sort((a,b)=>count(b.likes)-count(a.likes)||newest(a,b))[0]).filter(Boolean);
 const pinned=new Set(winners.map(p=>String(p.id))),ordinary=children.filter(p=>!pinned.has(String(p.id))),pages=Math.max(1,Math.ceil(ordinary.length/20));
 const page=Math.min(pages,Math.max(1,Math.floor(Number(requestedPage))||1));
 return {winners,items:ordinary.slice((page-1)*20,page*20),page,pages,total:children.length,ordinaryTotal:ordinary.length};
}
export function cageScore(stats={},mode='posts'){
 const counts=stats?.[mode==='comments'?'comments':'posts']||{},blue=count(counts.progressive),red=count(counts.conservative),total=blue+red,bluePercent=total?Math.round(blue/total*1000)/10:0;
 return {blue,red,total,bluePercent,redPercent:total?Math.round((100-bluePercent)*10)/10:0};
}
export function renderCageArena(stats={},mode='posts',showHeader=true){
 const selected=mode==='comments'?'comments':'posts',score=cageScore(stats,selected),other=cageScore(stats,selected==='posts'?'comments':'posts'),metric=selected==='posts'?'게시글':'댓글';
 const team=(camp,n,pct,lead)=>`<div class="ca-team ca-team-${camp==='progressive'?'blue':'red'}"><div class="ca-lead" data-empty="${!lead}">${icon('crown')}우세</div><div class="ca-team-main"><div class="ca-crest" aria-hidden="true"><span>${camp==='progressive'?'진':'보'}</span></div><div><div class="ca-team-label">${campName(camp)}</div><div class="ca-percent"><span>${pct}</span><small>%</small></div></div></div><div class="ca-count">${metric} ${n.toLocaleString('ko-KR')}개</div></div>`;
 const message=!score.total?'첫 참여를 기다리고 있습니다':score.blue===score.red?`팽팽한 접전 · ${score.blue} : ${score.red}`:`${campName(score.blue>score.red?'progressive':'conservative')}이 ${metric} ${Math.abs(score.blue-score.red).toLocaleString('ko-KR')}개 앞서고 있습니다`;
 return `<section class="ca-arena${score.total?'':' ca-no-participation'}" data-cage-arena data-mode="${selected}" aria-label="케이지 진영별 참여 경기장">${showHeader?`<header class="ca-arena-head"><span class="ca-mark">${icon('swords')} THE CAGE</span><span class="ca-mini">이 케이지의 참여 집계</span></header>`: ""}<div class="ca-modes" role="group" aria-label="참여 집계 선택">${['posts','comments'].map(m=>`<button type="button" data-cage-mode="${m}" aria-pressed="${m===selected}">${m==='posts'?'게시글전':'댓글전'} <span>${cageScore(stats,m).total.toLocaleString('ko-KR')}개</span></button>`).join('')}</div><div class="ca-approved-battle">${cageArena(Math.round(score.bluePercent),score.total>0,metric)}</div><p class="ca-match-state" role="status">${message}</p><footer class="ca-bottom"><span>${selected==='posts'?'댓글':'게시글'}전 <b>진보 ${other.bluePercent}% : 보수 ${other.redPercent}%</b></span><span>게시글·댓글 각각 집계</span></footer></section>`;
}
const cageLike=p=>`<button class="ca-applause" type="button" data-post-like data-domain="community" data-post-id="${esc(p.id)}" aria-label="${esc(p.title)} 좋아요 ${count(p.likes)}" aria-pressed="${!!p.liked}">${icon('heart')}<span>${count(p.likes).toLocaleString('ko-KR')}</span></button>`;
const commentCount=p=>count(p.commentCount);
export function renderCageHits(data){
 return `<section class="ca-hits" aria-label="양쪽 진영의 유효타">${['progressive','conservative'].map(camp=>{
 const p=data.winners.find(x=>x.camp===camp);return `<article class="ca-hit-card${camp==='conservative'?' red':''}"><div class="ca-hit-heading"><span>${campName(camp)}</span>${p?`<span class="ca-hit-tag">${icon('zap')}유효타</span>`:''}</div>${p?`<h3 class="ca-hit-title"><button type="button" data-layout-route="/community/${esc(p.id)}">${esc(p.title)}</button></h3><div class="ca-hit-meta">${authorIdentity(p)} · ${date(p.createdAt)}</div><div class="ca-hit-bottom"><span>댓글 ${commentCount(p)}</span>${cageLike(p)}</div>`:'<p class="ca-hit-empty">좋아요를 받은 첫 의견을 기다립니다.</p>'}</article>`;
 }).join('')}</section>`;
}
export function renderCagePosts(items,rootId,page=1){
 const data=cagePageData(items,rootId,page),start=data.ordinaryTotal?(data.page-1)*20+1:0,end=Math.min(data.page*20,data.ordinaryTotal);
 // Keep large threads usable without rendering thousands of page buttons.
 const numbers=new Set([1,data.pages]);for(let n=Math.max(1,data.page-3);n<=Math.min(data.pages,data.page+3);n++)numbers.add(n);
 if(data.pages<=9)for(let n=1;n<=data.pages;n++)numbers.add(n);
 const pages=[...numbers].sort((a,b)=>a-b),button=(text,target,current=false,disabled=false)=>`<button type="button" data-cage-page="${target}"${current?' aria-current="page"':''}${disabled?' disabled':''}>${text}</button>`;
 return `<section class="ca-all-posts" data-cage-posts data-current-page="${data.page}" aria-label="케이지 게시글 목록"><div class="ca-all-heading"><span tabindex="-1" data-cage-list-title>케이지 게시글 ${data.ordinaryTotal.toLocaleString('ko-KR')}개</span><small>최신순 · 20개씩</small></div>${data.items.map(p=>`<article class="ca-post-row"><span class="ca-row-camp${p.camp==='conservative'?' red':''}">${p.camp==='progressive'?'진보':p.camp==='conservative'?'보수':'의견'}</span><div class="ca-row-main"><button type="button" class="ca-row-title" data-layout-route="/community/${esc(p.id)}">${esc(p.title)}</button><div class="ca-row-meta">${authorIdentity(p)} · ${date(p.createdAt)} · 댓글 ${commentCount(p)}</div></div>${cageLike(p)}</article>`).join('')||'<div class="jc-empty">새 의견을 남겨 주세요.</div>'}<nav class="ca-pagination" aria-label="게시글 페이지">${button('이전',data.page-1,false,data.page===1)}${pages.map((n,i)=>(i&&n-pages[i-1]>1?'<span aria-hidden="true">…</span>':'')+button(n,n,n===data.page)).join('')}${button('다음',data.page+1,false,data.page===data.pages)}</nav><p class="ca-range" role="status">${start}–${end} / ${data.ordinaryTotal.toLocaleString('ko-KR')}개 · 상단 유효타 ${data.winners.length}개 별도</p></section>`;
}
export async function cageDetail(item,content,session={},dashboard={},url=''){
 const comments=await sharedComments('community',item,content,session),data=content.peekDomain?.('community')||await content.readDomain('community'),params=new URLSearchParams(String(url).split('?')[1]||''),page=cagePageData(data.items,item.id,params.get('page')),mode=params.get('mode')==='comments'?'comments':'posts';
 return `<div class="subpage jc49 jc55" data-cage-id="${esc(item.id)}"><div class="jc-breadcrumb"><button data-layout-route="/community">커뮤니티 X 케이지</button><span>/ 케이지</span></div><article class="ca-match-shell"><header class="ca-match-header"><span class="ca-mark">${icon('swords')} THE CAGE</span><div class="ca-match-intro"><h2>${esc(item.title)}</h2><div class="ca-match-copy">${body(item.body)}</div><div class="ca-match-meta">${authorIdentity(item)}<span>${date(item.createdAt)} · 조회 ${Number(item.views||0).toLocaleString('ko-KR')}</span></div></div><div class="ca-match-tools"><span class="ca-mini">이 케이지의 참여 집계</span>${item.cageEndsAt?`<strong class="cage-countdown" data-cage-ends="${Number(item.cageEndsAt)}">남은 시간 확인 중</strong>`:''}${postMenu('community',item,session)}</div></header>${renderCageArena(data.cageStats?.[item.id],mode,false)}${postActions('community',item,dashboard,'/community')}</article><div class="ca-hits-note">${icon('zap')}진영별 최다 좋아요 게시글 · 유효타</div>${renderCageHits(page)}<section class="jc-join-box">${session.authenticated?`<form data-stage-form="board" data-domain="community"><input type="hidden" name="cageParentId" value="${esc(item.id)}"><div class="jc-join-label">어느 진영에 힘을 보태시겠어요?</div>${campPicker()}<div class="jc-cage-write"><small>진영을 선택한 뒤 의견을 작성해 주세요.</small><button class="jc-primary" type="button" data-jc-compose disabled>${icon('pencil')}의견 쓰기</button></div><div data-cage-fields hidden><fieldset data-camp-body disabled>${field('title','의견 제목')}${field('body','내용','',true)}<div class="jc-editor-bottom"><button class="jc-primary" type="submit">의견 등록</button></div></fieldset></div><span data-form-state role="status"></span></form>`:'<div class="jc-compose-bottom"><small>로그인 후 진영을 선택해 참여할 수 있습니다.</small><button class="jc-primary" data-layout-route="/login">로그인</button></div>'}</section>${renderCagePosts(data.items,item.id,page.page)}<p class="ca-status" data-cage-status role="status" aria-live="polite"></p>${comments}</div>`;
}

function cageWriteOptions(session,wallet){
 const n=x=>Number(x||0).toLocaleString('ko-KR'),token=globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
 return `<section class="community-cage-options" data-cage-writer data-user-id="${esc(session.user?.id||'')}"><input type="hidden" name="requestId" value="${token}"><div class="jc-pin-options"><label><input type="radio" name="writeMode" value="normal" checked>일반 게시글</label><label><input type="radio" name="writeMode" value="cage">케이지 열기</label></div><div data-cage-write-settings hidden><p>보유 포인트 <b>${wallet.ok?n(wallet.wallet?.balance)+' P':'조회 확인 필요'}</b></p><label>사용 포인트<select name="fee">${[50000,60000,70000,80000,90000,100000].map((x,i)=>`<option value="${x}">${n(x)} P · ${30+i*6}분</option>`).join('')}</select></label><p>등록 즉시 시작하며 최대 60분 동안 참여할 수 있습니다.</p></div>${session.user?.role==='admin'?'<div data-normal-post-pin><input type="hidden" name="pinKind" value=""><label><input type="checkbox" name="pinNotice">공지로 상단 고정</label></div>':''}</section>`;
}
