const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=at=>new Date(at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});
export function appPushSettings(){const version=Number(/JCSAndroid\/1\.1\.(\d+)/.exec(globalThis.navigator?.userAgent||'')?.[1]||0);return version>=383?'<a class="group-primary" href="jcs-push://settings">앱 알림 설정</a>':`<p class="group-push-help">${version?'모임 푸시는 최신 APK로 업데이트한 뒤 알림을 켜 주세요.':'앱을 설치하고 알림을 허용하면 모임 소식을 푸시로 받을 수 있습니다. 웹에서는 이 페이지의 공지 알림을 확인해 주세요.'}</p>`;}
export function renderGroupPush(item){
 const p=item.push;if(!p)return '<section class="group-state">가입 승인된 모임원에게 공개되는 공지입니다.</section>';
 const u=p.usage||{},remainingDay=Math.max(0,(u.daily||0)-(u.today||0)),remainingMonth=Math.max(0,(u.monthly||0)-(u.month||0)),token=globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
 const blocked=u.disabled||!remainingDay||!remainingMonth||u.nextAt>Date.now();
 const form=p.canSend?`<section class="group-push-compose"><span class="group-push-eyebrow">MEMBER NOTICE</span><h2>모임원에게 소식을 전하세요</h2><p>앱 알림을 켠 모임원에게 전달됩니다. 같은 내용은 이곳에도 남습니다.</p><div class="group-push-quota"><span>오늘 남은 발송 <b>${remainingDay}<small> / ${u.daily}회</small></b></span><span>이번 달 남은 발송 <b>${remainingMonth}<small> / ${u.monthly}회</small></b></span></div><p class="group-push-help">한국시간 기준 · 최소 30분 간격 · 모임장 변경 후에도 사용량 유지${u.nextAt>Date.now()?`<br>다음 발송: ${when(u.nextAt)}`:''}${u.disabled?'<br>관리자가 이 모임의 발송을 중지했습니다.':''}</p><form data-group-action-form><input type="hidden" name="operation" value="push-send"><input type="hidden" name="requestId" value="${esc(token)}"><label>알림 제목<input name="title" maxlength="60" required placeholder="예: 이번 주 모임 장소 안내"></label><label>전달할 내용<textarea name="body" maxlength="300" required placeholder="모임원에게 전할 소식을 300자 이내로 적어 주세요."></textarea></label><p class="group-push-help">공지 1건 등록 시 발송 한도 1회를 사용합니다. 수신 기기가 없어도 웹 공지는 등록됩니다.</p><button type="submit" ${blocked?'disabled':''}>공지 등록 · 푸시 보내기</button><p data-group-state role="status"></p></form>${!p.configured?'<p class="group-push-help">푸시 서버 연결이 준비되지 않아 기기 전달은 대기할 수 있습니다.</p>':''}</section>`:'';
 const policies=p.canSetPolicy?`<details class="group-push-policy"><summary>최고관리자 · 발송 한도 설정</summary><form data-group-action-form><input type="hidden" name="operation" value="push-policy"><label>하루 한도<input type="number" min="1" max="20" name="daily" value="${u.daily}" required></label><label>월간 한도<input type="number" min="1" max="200" name="monthly" value="${u.monthly}" required></label><label><input type="checkbox" name="disabled" ${u.disabled?'checked':''}>이 모임의 푸시 발송 중지</label><button>설정 저장</button><p data-group-state role="status"></p></form></details>`:'';
 const state={queued:'발송 대기·처리 중',complete:'발송 처리 완료',expired:'발송 기한 종료',cancelled:'발송 중지'};
 return `<div class="group-push-panel">${appPushSettings()}${form}${policies}<section class="group-push-history"><header><h2>모임 공지 알림</h2><a href="/groups/${esc(item.id)}?tab=notifications" data-layout-route="/groups/${esc(item.id)}?tab=notifications">새로고침</a></header><p>최근 90일의 공지를 확인할 수 있습니다.</p>${p.messages.map(m=>`<article><time>${when(m.at)}</time><h3>${esc(m.title)}</h3><p>${esc(m.body).replace(/\n/g,'<br>')}</p>${m.delivery?`<div class="group-push-delivery"><b>${state[m.delivery.status]||'처리 중'}</b><span>수신 설정 회원 ${m.delivery.eligible}명 · 기기 접수 ${m.delivery.accepted}건 · 등록 기기 없음 ${m.delivery.noDevice}명 · 제외 ${m.delivery.skipped}건 · 실패 ${m.delivery.failed}건</span><small>기기 접수는 FCM 접수 기준이며, 실제 수신·열람을 뜻하지 않습니다.</small></div>`:''}</article>`).join('')||'<div class="group-state">아직 등록된 공지 알림이 없습니다.</div>'}</section></div>`;
}
