const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>esc(v).replace(/\r?\n/g,'<br>');
const link=(href,label,cls='')=>`<a${cls?` class="${cls}"`:''} href="${esc(href)}" data-layout-route="${esc(href)}">${label}</a>`;
const category={politics:'정치·정책',culture:'문화·예술',social:'지역·교류'};
const status={pending:'승인 대기',approved:'운영 중',rejected:'반려',closed:'종료'},roles={owner:'모임장',moderator:'운영진',member:'모임원',admin:'사이트 관리자',applicant:'개설 신청자'},memberStates={pending:'승인 대기',active:'활동 중',rejected:'반려',removed:'내보냄',left:'탈퇴'},kinds={post:'이야기',gallery:'사진',notice:'공지'};
const operation=(name,fields,label,cls='')=>`<form class="group-action ${cls}" data-group-action-form><input type="hidden" name="operation" value="${name}">${fields}<button type="submit">${label}</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state role="status"></p></form>`;
const field=(name,label,{type='text',value='',required=false,maxlength='',options=null}={})=>`<label>${label}${options?`<select name="${name}"${required?' required':''}>${options.map(([v,l])=>`<option value="${v}"${v===value?' selected':''}>${l}</option>`).join('')}</select>`:`<input type="${type}" name="${name}" value="${esc(value)}"${required?' required':''}${maxlength?` maxlength="${maxlength}"`:''}>`}</label>`;
const textarea=(name,label,value='',max=0,required=false)=>`<label>${label}<textarea name="${name}"${required?' required':''}${max?` maxlength="${max}"`:''}>${esc(value)}</textarea></label>`;
function safeMediaUrl(value){const url=String(value||'');return !/[\x00-\x20'"()\\]/.test(url)&&(url.startsWith('/api/v3/groups?')||/^\/assets\/groups\/[a-z0-9._/-]+$/i.test(url))?url:'';}
function mediaImage(url,crop,alt,klass=''){
 const safe=safeMediaUrl(url),tile=/^(politics|culture|social)-(a|b)$/.test(crop||'')?crop:'';if(!safe)return '';
 if(tile){const [kind,column]=tile.split('-'),x=column==='b'?627:0,y={politics:0,culture:418,social:836}[kind];return `<span class="group-media group-atlas ${esc(klass)}"><svg class="crop-${tile}" viewBox="${x} ${y} 627 418" preserveAspectRatio="xMidYMid slice" role="img" aria-label="${esc(alt)}"><image href="${esc(safe)}" x="0" y="0" width="1254" height="1254"/></svg></span>`;}
 return `<span class="group-media ${esc(klass)}"><img src="${esc(safe)}" alt="${esc(alt)}" loading="lazy"></span>`;
}
export function renderGroupCover(item){const image=mediaImage(item.coverUrl,item.coverCrop,`${item.name} 모임 대표 이미지`,'group-cover-image');return image?`<div class="group-cover">${image}</div>`:`<div class="group-cover group-cover-${esc(item.category)}" role="img" aria-label="${esc(item.name)} 기본 대표 이미지"></div>`;}
function card(item){const route=`/groups/${encodeURIComponent(item.id)}`;return `<article class="group-card${item.isExample?' is-example':''}">${link(route,`${renderGroupCover(item)}<div class="group-card-copy"><span>${esc(category[item.category]||item.category)} · ${esc(status[item.status]||item.status)}</span><h3>${esc(item.name)}</h3><p>${text(item.description)}</p><small>${esc(item.region)} · 모임원 ${Number(item.memberCount)||0} · 글 ${Number(item.postCount)||0}</small>${item.unread?'<b class="group-unread">새 소식</b>':''}</div>`)}</article>`;}
function directoryCard(item,view){const leave=view==='mine'&&item.canLeave===true?operation('leave',`<input type="hidden" name="id" value="${esc(item.id)}"><input type="hidden" name="version" value="${Number(item.version)||0}">`,item.membershipStatus==='pending'?'가입 신청 취소':'모임 나가기'):'';return card(item).replace(/<\/article>$/,`${leave}</article>`);}
export function renderGroupDirectory(result,session={},view='browse',categoryKey='all',q=''){
  const admin=session?.authenticated&&session.user?.role==='admin';
  if(view==='mine'&&!session?.authenticated)return `<main class="groups-page"><section class="group-state"><h1>로그인이 필요합니다.</h1><p>내 모임은 로그인한 회원만 볼 수 있습니다.</p></section></main>`;
  if(view==='manage'&&!admin)return `<main class="groups-page"><section class="group-state"><h1>접근할 수 없습니다.</h1><p>모임 관리는 사이트 관리자만 이용할 수 있습니다.</p></section></main>`;
  if(!result?.ok)return `<main class="groups-page"><section class="group-state" role="alert"><h1>모임을 불러오지 못했습니다.</h1><p>${esc(result?.error||'잠시 후 다시 시도해 주세요.')}</p></section></main>`;
  const items=result.items||[],examples=result.examples||[];
  const page=Math.max(1,Number(result.page)||1),params=n=>{const p=new URLSearchParams();if(view!=='browse')p.set('view',view);if(categoryKey!=='all')p.set('category',categoryKey);if(q)p.set('q',q);p.set('page',String(n));return `/groups?${p}`;};
  const pagination=page>1||result.hasMore?`<nav class="group-pagination" aria-label="모임 페이지">${page>1?link(params(page-1),'이전'):''}<span>${page} 페이지</span>${result.hasMore?link(params(page+1),'다음'):''}</nav>`:'';
  const notifications=session?.authenticated&&(result.notifications||[]).length?`<section class="group-notifications"><h2>새 소식</h2>${result.notifications.map(n=>`<article>${link(`/groups/${encodeURIComponent(n.groupId)}`,`<b>${esc(n.groupName)}</b> ${esc(n.title)}`)}<time>${esc(n.createdAt)}</time></article>`).join('')}</section>`:'';
  return `<main class="groups-page">${notifications}<header class="groups-hero"><span>COMMUNITY GROUPS</span><h1>생각과 관심사가 만나는 모임</h1><p>모임 개설과 가입은 승인 후 시작됩니다.</p><div>${link('/groups','둘러보기',view==='browse'?'is-active':'')}${session?.authenticated?link('/groups?view=mine','내 모임',view==='mine'?'is-active':''):''}${admin?link('/groups?view=manage','승인 관리',view==='manage'?'is-active':''):''}${session?.authenticated?link('/groups/new','모임만들기','group-primary'):''}</div></header><form class="group-filter" method="get" data-group-filter><input type="hidden" name="view" value="${esc(view)}">${field('category','분야',{value:categoryKey,options:[['all','전체'],['politics','정치·정책'],['culture','문화·예술'],['social','지역·교류']]})}${field('q','검색',{value:q})}<button>찾기</button></form><section><div class="group-section-head"><h2>${view==='browse'?`실제 모임 ${Number(result.total)||0}개`:view==='mine'?'내 모임':'승인 관리'}</h2></div>${items.length?`<div class="group-grid">${items.map(item=>directoryCard(item,view)).join('')}</div>`:'<div class="group-state"><p>표시할 모임이 없습니다.</p></div>'}</section>${pagination}${examples.length?`<section class="group-examples"><div class="group-section-head"><h2>예시 모임</h2><p>화면 이해를 위한 읽기 전용 예시이며 실제 모임 수에 포함되지 않습니다.</p></div><div class="group-grid">${examples.map(card).join('')}</div></section>`:''}</main>`;
}
export function renderGroupCreate(session={}){
 if(!session?.authenticated)return `<main class="groups-page"><section class="group-state"><h1>로그인이 필요합니다.</h1><p>로그인한 회원만 모임을 만들 수 있습니다.</p></section></main>`;
 return `<main class="groups-page group-editor"><header><span>NEW GROUP</span><h1>새 모임 제안</h1><p>사이트 관리자 승인 후 공개되며, 가입 신청은 모임 운영진이 검토합니다.</p></header><form data-group-create-form>${field('name','모임 이름',{required:true,maxlength:60})}${field('category','분야',{required:true,options:[['politics','정치·정책'],['culture','문화·예술'],['social','지역·교류']]})}${textarea('description','소개', '',1500,true)}${field('region','지역',{maxlength:80})}${textarea('rules','모임 규칙','',4000)}${field('visibility','공개 범위',{options:[['public','전체 공개'],['members','모임원만'],['invite','초대 전용']]})}<label class="group-consent"><input type="checkbox" name="privacyAccepted" required> 모임 운영을 위한 개인정보 처리와 모임 규칙에 동의합니다.</label><button class="group-primary" type="submit">승인 요청하기</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state role="status"></p></form></main>`;
}
function postForm(manager=false,post=null,defaultKind='post'){post=post||{kind:defaultKind};const notices=manager?`<option value="notice"${post?.kind==='notice'?' selected':''}>공지</option>`:'';return `<form data-group-post-form><input type="hidden" name="operation" value="post"><input type="hidden" name="postId" value="${esc(post?.id||'')}"><label>형식<select name="kind"><option value="post"${post?.kind==='post'?' selected':''}>글</option><option value="gallery"${post?.kind==='gallery'?' selected':''}>갤러리</option>${notices}</select></label>${field('title','제목',{value:post?.title||'',required:true,maxlength:120})}${textarea('body','내용',post?.body||'',10000)}<label>사진 (JPG·PNG·WebP, 장당 2MB, 최대 6장)<input type="file" accept="image/jpeg,image/png,image/webp" multiple data-group-upload></label><input type="hidden" name="imageIds" value="${esc((post?.images||[]).map(i=>i.id).join(','))}"><button>${post?'수정 저장':'게시하기'}</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state role="status"></p></form>`;}
function posts(item){const example=item.isExample===true,v=item.viewer||{};return [...(item.posts||[])].sort((a,b)=>Number(b.kind==='notice')-Number(a.kind==='notice')).map(p=>`<article class="group-post"><span>${esc(kinds[p.kind]||p.kind)} · ${esc(p.authorName)}</span><h3>${esc(p.title)}</h3><p>${text(p.body)}</p>${(p.images||[]).map(i=>mediaImage(i.url,i.crop,`${p.title} 첨부 이미지`,'group-post-image')).join('')}${(p.comments||[]).map(c=>`<div class="group-comment"><b>${esc(c.authorName)}</b> ${text(c.body)}${!example&&v.canWrite&&(v.canManage||c.authorId===v.userId)?operation('comment-delete',`<input type="hidden" name="postId" value="${esc(p.id)}"><input type="hidden" name="commentId" value="${esc(c.id)}">${v.canManage&&c.authorId!==v.userId?field('reason','삭제 사유',{required:true}):''}`,'댓글 삭제'):''}</div>`).join('')}${!example&&p.canEdit?`<details><summary>글 수정</summary>${postForm(v.canManage,p)}</details>`:''}${!example&&v.canWrite?operation('comment',`<input type="hidden" name="postId" value="${esc(p.id)}">${field('body','댓글',{required:true,maxlength:2000})}`,'댓글 남기기'):''}${!example&&p.canDelete?operation('post-delete',`<input type="hidden" name="postId" value="${esc(p.id)}">${v.canManage&&p.authorId!==v.userId?field('reason','삭제 사유',{required:true}):''}`,'삭제'):''}${!example&&p.canModerate?operation('post-hide',`<input type="hidden" name="postId" value="${esc(p.id)}"><input type="hidden" name="hidden" value="${p.hidden?'false':'true'}">${field('reason','사유',{required:true})}`,p.hidden?'숨김 해제':'숨기기'):''}${!example&&v.canWrite?operation('report',`<input type="hidden" name="postId" value="${esc(p.id)}">${field('body','신고 사유',{required:true,maxlength:1000})}`,'운영진에게 신고'):''}</article>`).join('');}
function koreaInput(value){if(!value)return '';const d=new Date(value);if(!Number.isFinite(d.getTime()))return '';return new Date(d.getTime()+9*3600000).toISOString().slice(0,16);}
function koreaDate(value){if(!value)return '';const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'}).format(d):'';}
function eventForm(event=null){return `<form data-group-event-form><input type="hidden" name="operation" value="event"><input type="hidden" name="eventId" value="${esc(event?.id||'')}">${field('title','일정 제목',{value:event?.title||'',required:true,maxlength:120})}${textarea('body','설명',event?.body||'',4000)}${field('startsAt','시작',{type:'datetime-local',value:event?.startsAt?koreaInput(event.startsAt):'',required:true})}${field('place','장소',{value:event?.place||'',maxlength:160})}<button>${event?'일정 수정':'일정 등록'}</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state></p></form>`;}
function eventRows(item){return (item.events||[]).map(e=>`<article class="group-event"><h3>${esc(e.title)}</h3><p>${text(e.body)}</p><p>${esc(koreaDate(e.startsAt))} · ${esc(e.place)}</p><b>참석 ${Number(e.yesCount)||0} · 불참 ${Number(e.noCount)||0}</b>${e.canEdit?`<details><summary>일정 수정</summary>${eventForm(e)}</details>`:''}${e.canDelete?operation('event-delete',`<input type="hidden" name="eventId" value="${esc(e.id)}">${field('reason','삭제 사유',{required:true})}`,'일정 삭제'):''}${item.viewer.canWrite?`${operation('rsvp',`<input type="hidden" name="eventId" value="${esc(e.id)}"><input type="hidden" name="response" value="yes">`,'참석')}${operation('rsvp',`<input type="hidden" name="eventId" value="${esc(e.id)}"><input type="hidden" name="response" value="no">`,'불참')}`:''}</article>`).join('');}
function gallery(item,page=1,invite=''){const images=(item.posts||[]).filter(p=>p.kind==='gallery').flatMap(p=>(p.images||[]).map(i=>({post:p,image:i}))),current=Math.max(1,Number(page)||1),start=(current-1)*24,shown=images.slice(start,start+24),route=n=>`/groups/${encodeURIComponent(item.id)}?${new URLSearchParams({tab:'gallery',galleryPage:String(n),...(invite?{invite}:{})})}`;return shown.length?`<div class="group-gallery">${shown.map(({post,image})=>`<figure>${mediaImage(image.url,image.crop,post.title,'group-gallery-image')}<figcaption>${esc(post.title)} · ${esc(post.authorName)}</figcaption></figure>`).join('')}</div>${current>1||start+24<images.length?`<nav class="group-pagination">${current>1?link(route(current-1),'이전'):''}<span>${current} 페이지</span>${start+24<images.length?link(route(current+1),'다음'):''}</nav>`:''}`:'<div class="group-state"><p>등록된 갤러리 사진이 없습니다.</p></div>';}

function settingsForm(item){return `<form data-group-settings-form><input type="hidden" name="operation" value="settings">${field('name','이름',{value:item.name,required:true,maxlength:60})}${field('category','분야',{value:item.category,options:[['politics','정치·정책'],['culture','문화·예술'],['social','지역·교류']]})}${textarea('description','소개',item.description,1500,true)}${field('region','지역',{value:item.region,maxlength:80})}${textarea('rules','규칙',item.rules,4000)}${field('visibility','공개 범위',{value:item.visibility,options:[['public','전체 공개'],['members','모임원만'],['invite','초대 전용']]})}<label>대표 이미지<input type="file" accept="image/jpeg,image/png,image/webp" data-group-upload data-purpose="cover"></label><input type="hidden" name="coverImageId"><label class="group-consent"><input type="checkbox" name="removeCover"> 현재 대표 이미지 제거</label><button>설정 저장</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state role="status"></p></form>`;}
export function renderGroupDetail(item,session={},tab='posts',galleryPage=1,invite=''){
 if(!item?.id)return `<main class="groups-page"><section class="group-state"><h1>모임을 찾을 수 없습니다.</h1></section></main>`;
 const example=item.isExample===true,raw=item.viewer||{},v=example?{...raw,canWrite:false,canManage:false,canEditSettings:false,canReview:false}:raw,read=v.canRead===true,manage=v.canManage===true,mutatingManage=v.canManage===true&&v.canWrite===true,ownerish=['owner','admin'].includes(v.role);
 const safeItem={...item,isExample:example,viewer:v,posts:(item.posts||[]).map(p=>example?{...p,canEdit:false,canDelete:false,canModerate:false}:p),events:(item.events||[]).map(e=>example?{...e,canEdit:false,canDelete:false}:e)};
 const detailRoute=key=>`/groups/${encodeURIComponent(item.id)}?${new URLSearchParams({tab:key,...(invite?{invite}:{})})}`;
 const tabs=[['posts','글'],['gallery','갤러리'],['events','일정'],...(manage?[['members','모임원']]:[]),...(v.canEditSettings?[['settings','설정']]:[])];let body='';
 if(!read)body=`<section class="group-locked"><h2>승인된 모임원에게 공개됩니다.</h2><p>${text(item.rules)}</p></section>`;
 else if(tab==='gallery')body=`${v.canWrite?postForm(manage,null,'gallery'):''}${gallery(safeItem,galleryPage,invite)}`;
 else if(tab==='events')body=`${mutatingManage?eventForm():''}${eventRows(safeItem)}`;
 else if(tab==='members'&&manage){
  const rows=(item.members||[]).map(m=>{const peer=m.role==='moderator',choices=[];if(m.status==='pending')choices.push(['approve','승인'],['reject','반려']);if(['active','pending'].includes(m.status)&&m.role!=='owner'&&(!peer||ownerish))choices.push(['remove','내보내기']);if(ownerish&&m.status==='active'&&m.role==='member')choices.push(['promote','운영진 지정']);if(ownerish&&m.status==='active'&&m.role==='moderator')choices.push(['demote','일반 모임원 전환']);const form=mutatingManage&&choices.length?`<form data-group-member-form><input type="hidden" name="operation" value="member"><input type="hidden" name="userId" value="${esc(m.userId)}"><select name="decision" data-group-member-decision>${choices.map(([x,l])=>`<option value="${x}">${l}</option>`).join('')}</select>${field('reason','사유')}<button>적용</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state></p></form>`:'';const transfer=mutatingManage&&ownerish&&m.status==='active'&&m.role!=='owner'?operation('transfer',`<input type="hidden" name="userId" value="${esc(m.userId)}">`,'모임장 위임'):'';return `<article><b>${esc(m.nickname)}</b> ${esc(roles[m.role]||m.role)} · ${esc(memberStates[m.status]||m.status)}${form}${transfer}</article>`;}).join('');
  body=`<div class="group-members">${rows}</div>${item.inviteUrl?`<p class="group-invite"><b>초대 링크</b> <code>${esc(item.inviteUrl)}</code></p>`:''}${mutatingManage&&ownerish?operation('invite-reset','','초대 링크 재설정'):''}<section><h2>신고</h2>${(item.reports||[]).map(r=>`<p>${esc(r.authorName)} · ${text(r.body)}</p>`).join('')}</section><section><h2>감사 기록</h2>${(item.audit||[]).map(a=>`<p>${esc(a.actorName)} · ${esc(a.action)} ${text(a.reason||'')}</p>`).join('')}</section>`;
 } else if(tab==='settings'&&v.canEditSettings&&item.status!=='closed')body=`${settingsForm(item)}${item.status==='rejected'?operation('resubmit','','재심사 요청'):''}${item.status==='approved'?operation('close',field('reason','종료 사유',{required:true,maxlength:500}),'모임 종료'):''}`;
 else if(tab==='settings')body='<section class="group-state"><p>종료된 모임의 설정은 읽기 전용입니다.</p></section>';
 else body=`${v.canWrite?postForm(manage):''}${posts(safeItem)}`;
 const review=v.canReview&&item.status==='pending'?`<form data-group-review-form><input type="hidden" name="operation" value="review"><select name="decision" data-group-review-decision><option value="approve">승인</option><option value="reject">반려</option></select>${field('reason','검토 사유',{maxlength:500})}<button>검토 저장</button><button type="button" data-group-conflict-accept hidden>최신 저장 내용 확인 완료</button><p data-group-state></p></form>`:'';
 const returnTo=`/groups/${encodeURIComponent(item.id)}${invite?`?invite=${encodeURIComponent(invite)}`:''}`,membership=!example&&item.status==='approved'&&['none','left'].includes(v.membershipStatus)?(v.userId?operation('join','<label class="group-consent"><input type="checkbox" name="privacyAccepted" required> 개인정보 처리에 동의합니다.</label>','가입 신청'):link(`/login?return=${encodeURIComponent(returnTo)}`,'로그인 후 가입 신청','group-primary')):!example&&v.membershipStatus==='pending'&&v.canLeave===true?operation('leave','','가입 신청 취소'):v.membershipStatus==='pending'?'<p class="group-pending">가입 승인 대기 중입니다.</p>':'';
 return `<main class="groups-page group-detail" data-group-id="${esc(item.id)}" data-group-version="${Number(item.version)||0}">${renderGroupCover(item)}<header><span>${esc(category[item.category])} · ${esc(status[item.status])}</span><h1>${esc(item.name)}</h1><p>${text(item.description)}</p><small>${esc(item.region)} · 운영 ${esc(item.ownerName)}</small>${example?'<strong class="group-example-banner">예시 모임 · 읽기 전용</strong>':''}</header>${item.reviewReason?`<p class="group-review-reason">검토 안내: ${text(item.reviewReason)}</p>`:''}${read&&item.rules?`<details class="group-rules"><summary>모임 규칙</summary><p>${text(item.rules)}</p></details>`:''}${review}<nav>${tabs.map(([key,label])=>link(detailRoute(key),label,key===tab?'is-active':'')).join('')}</nav>${membership}${body}${read&&v.membershipStatus==='active'&&v.canWrite?`${operation('notify',`<input type="hidden" name="enabled" value="${v.notify?'false':'true'}">`,v.notify?'소식 알림 끄기':'소식 알림 받기')}${v.canLeave===true?operation('leave','','모임 나가기'):''}`:''}</main>`;
}
