import {MOCK_BILL,ballots,tally} from '../data/mock-bill.js?v=0.0.31.409';
import {moduleActionIconSvg} from '../ui/service-icons.js?v=0.0.31.394';
import {renderShareMenu} from '../ui/page-share.js?v=0.0.31.409';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=MOCK_BILL;
const counts=t=>`<div class="bill-counts"><span class="bill-yes">찬성 <strong>${t.yes}</strong></span><span class="bill-no">반대 <strong>${t.no}</strong></span><span class="bill-abstain">기권 <strong>${t.abstain}</strong></span></div>`;
export function renderMockBillHome(){const t=tally(b);return `<section class="module bill-home"><div class="module-header"><div><span class="eyebrow">JCS AI MODEL ASSEMBLY</span><h2>JCS AI 모의법안 발의</h2></div><button type="button" class="module-icon-action" data-layout-route="/mock-bill/${b.id}" aria-label="모의법안 상세보기">${moduleActionIconSvg('column')}</button></div><a class="bill-home-body" href="/mock-bill/${b.id}" data-layout-route="/mock-bill/${b.id}"><div class="bill-home-copy"><span class="bill-number">제${b.number}호 · 제안 ${esc(b.author)}</span><h3>${esc(b.title)}</h3><p>국민회복계좌로 다시 시작하는 금융생활</p></div><div class="bill-home-vote"><span class="bill-status">모의 ${t.passed?'가결':'부결'}</span>${counts(t)}<small>가상 의원 300명 · 전체 출석 기준</small></div></a></section>`;}
function chamber(){const rows=ballots(b),names={yes:'찬성',no:'반대',abstain:'기권'},colors={yes:'#67dbbd',no:'#ff898b',abstain:'#b8c2d6'};return `<svg class="bill-chamber" viewBox="0 0 840 360" role="img" aria-labelledby="bill-chamber-title"><title id="bill-chamber-title">가상 의원 300석의 찬성·반대·기권 배치</title><defs><linearGradient id="bill-podium" x2="0" y2="1"><stop stop-color="#b8a277"/><stop offset="1" stop-color="#594c3b"/></linearGradient></defs><path d="M28 328 A392 292 0 0 1 812 328" fill="none" stroke="#bc9d6440" stroke-width="20"/><path d="M68 328 A352 264 0 0 1 772 328" fill="none" stroke="#bc9d6420" stroke-width="2"/>${rows.map((v,i)=>{const row=Math.floor(i/50),j=i%50,a=Math.PI+(j+.5)/50*Math.PI,r=365-row*35,x=420+Math.cos(a)*r,y=320+Math.sin(a)*r*.73;return `<rect x="${(x-3.8).toFixed(2)}" y="${(y-4.5).toFixed(2)}" width="7.6" height="9" rx="2" fill="${colors[v.vote]}"><title>${names[v.vote]}</title></rect>`;}).join('')}<path d="M333 326 L345 284 Q420 263 495 284 L507 326 Z" fill="url(#bill-podium)"/><rect x="385" y="267" width="70" height="32" rx="5" fill="#3a3e42" stroke="#b8a277"/><text x="420" y="288" text-anchor="middle" fill="#f4e8d0" font-size="15" font-weight="700">JCS</text><text x="420" y="351" text-anchor="middle" fill="#bac5d9" font-size="14">가상 본회의장 · 300석</text></svg>`;}
function party(p){return `<details class="bill-party"><summary><span class="bill-party-name"><i style="background:${p.color}"></i>${esc(p.name)} <small>${p.seats}석</small></span><span class="bill-party-numbers"><span>${p.yes}<small>찬성</small></span><span>${p.no}<small>반대</small></span><span>${p.abstain}<small>기권</small></span><span class="bill-expand">⌄</span></span></summary><div class="bill-party-explain"><p>${esc(p.reason)}</p>${p.id!=='vacant'?`<dl><div><dt>찬성 논거</dt><dd>${esc(p.support)}</dd></div><div><dt>우려 쟁점</dt><dd>${esc(p.concern)}</dd></div><div><dt>보완 조건</dt><dd>${esc(p.condition)}</dd></div></dl>`:''}</div></details>`;}
export function renderMockBillPage(){const t=tally(b);return `<article class="bill-page"><header class="bill-page-header"><div><span class="bill-kicker">JCS AI MODEL ASSEMBLY</span><h1>JCS AI 모의법안 발의</h1></div>${renderShareMenu('/mock-bill/'+b.id)}</header><section class="bill-hall"><div class="bill-hall-top"><span>제${b.number}호 모의의안</span><span>첫 평가 · ${b.date}</span></div><h2>${esc(b.title)}</h2><p class="bill-hall-sub">제안 ${esc(b.author)} · 국민회복계좌 도입</p><div class="bill-scoreboard"><div><span class="bill-board-label">표결 결과</span><strong class="bill-verdict">모의 ${t.passed?'가결':'부결'}</strong></div>${counts(t)}<div class="bill-quorum"><b>${t.passed?'가결 기준 충족':`가결까지 ${t.needed}표`}</b><span>찬성 151명 이상</span></div></div>${chamber()}<p class="bill-hall-note">${esc(b.rules)}</p></section><nav class="bill-detail-nav" aria-label="법안 상세 내용"><a href="#bill-results" data-bill-jump="bill-results">정당별 표결</a><a href="#bill-proposal" data-bill-jump="bill-proposal">법안 내용</a><a href="${b.document}" target="_blank" rel="noopener">PDF 원문 ↗</a></nav><section class="bill-section" id="bill-results"><div class="bill-section-title"><h2>정당별 표결</h2><span>정당을 누르면 판단 이유가 열립니다.</span></div><p class="bill-method">${esc(b.methodology)}</p><div class="bill-party-list">${b.parties.map(party).join('')}</div><details class="bill-basis"><summary>의석 구성 기준</summary><p>${b.seatDate} 확인 자료 기준 299석과 공석 대응 1석으로 구성했습니다. 공석 대응 패널은 요청에 따라 기권 고정입니다. 실제 개인의 이름이나 표결은 표시하지 않습니다.</p><a href="${b.seatSource}" target="_blank" rel="noopener">정당별 의석 집계 자료 ↗</a></details></section><section class="bill-section" id="bill-proposal"><div class="bill-section-title"><h2>법안 내용</h2><span>제안서 기준 ${b.documentDate}</span></div><p class="bill-lead">${esc(b.summary)}</p><div class="bill-facts">${b.facts.map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('')}</div>${b.sections.map(([h,p])=>`<div class="bill-proposal-row"><h3>${esc(h)}</h3><p>${esc(p)}</p></div>`).join('')}<a class="bill-document" href="${b.document}" target="_blank" rel="noopener">제안서 원문 26쪽 보기 ↗</a></section><footer class="bill-footer">JCS AI 모의법안 발의 · 실제 국회 의안 또는 표결이 아닙니다.</footer></article>`;}
export function bindMockBillNavigation(root){root.addEventListener('click',e=>{const link=e.target.closest('[data-bill-jump]');if(!link)return;e.preventDefault();e.stopPropagation();document.getElementById(link.dataset.billJump)?.scrollIntoView({behavior:globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});}
