import {resolveBill,renderProposalEditor} from '../ui/mock-bill-editing.js?v=0.0.31.421';
import {renderChamber} from '../ui/bill-chamber.js?v=0.0.31.421';
import {MOCK_BILL,ballots,tally} from '../data/mock-bill.js?v=0.0.31.429';
import {moduleActionIconSvg} from '../ui/service-icons.js?v=0.0.31.394';
import {renderShareMenu} from '../ui/page-share.js?v=0.0.31.431';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=MOCK_BILL;
const counts=t=>`<div class="bill-counts"><span class="bill-yes"><img class="bill-vote-plate" src="/assets/bills/plates/yes-414.svg" alt="찬성"><strong>${t.yes}</strong></span><span class="bill-no"><img class="bill-vote-plate" src="/assets/bills/plates/no-414.svg" alt="반대"><strong>${t.no}</strong></span><span class="bill-abstain"><img class="bill-vote-plate" src="/assets/bills/plates/abstain-414.svg" alt="기권"><strong>${t.abstain}</strong></span></div>`;
export function renderMockBillHome(){
 return `<section class="module bill-home"><div class="module-header"><div><span class="eyebrow">JCS AI MODEL ASSEMBLY</span><h2>JCS AI 모의법안 발의</h2></div><button type="button" class="module-icon-action" data-layout-route="/mock-bill/${b.id}" aria-label="모의법안 상세보기">${moduleActionIconSvg('column')}</button></div><a class="bill-home-body" href="/mock-bill/${b.id}" data-layout-route="/mock-bill/${b.id}"><img class="bill-home-illustration" src="/assets/bills/home-assembly-wide-459.webp" alt="밝은 국회의사당을 배경으로 놓인 법안 문서와 펜" width="1800" height="600" loading="lazy" decoding="async"><div class="bill-home-copy"><span class="bill-number">제${b.number}호 · 제안 ${esc(b.author)}</span><h3>${esc(b.title)}</h3><p>국민회복계좌로 다시 시작하는 금융생활</p><div class="bill-home-entry"><small>AI 가상 국회 시뮬레이션</small><strong>본회의장 입장하기</strong></div></div></a></section>`;
}

function party(p){return `<div class="bill-party"><div class="bill-party-row"><span class="bill-party-name"><i style="background:${p.color}"></i>${esc(p.name)} <small>${p.seats}석</small></span><span class="bill-party-numbers"><span>${p.yes}<small>찬성</small></span><span>${p.no}<small>반대</small></span><span>${p.abstain}<small>기권</small></span></span></div></div>`;}
export function renderMockBillPage(settings={},canEdit=false){const b=resolveBill(settings),t=tally(b);return `<article class="bill-page bill-immersive"><header class="bill-page-header"><div><span class="bill-kicker">JCS AI MODEL ASSEMBLY</span><h1>JCS AI 모의법안 발의</h1></div><div class="bill-header-actions"><button type="button" data-bill-fullscreen>전체화면</button>${renderShareMenu('/mock-bill/'+b.id)}<a href="/" data-layout-route="/" aria-label="본회의장 나가기">나가기</a></div></header><section class="bill-hall is-voting" data-vote-state="idle" data-vote-yes="${t.yes}" data-vote-no="${t.no}" data-vote-abstain="${t.abstain}" data-result="${t.passed?'passed':'rejected'}"><div class="bill-hall-top"><span>제${b.number}호 모의의안</span><span>첫 평가 · ${b.date}</span></div><h2>${esc(b.title)}</h2><p class="bill-hall-sub">제안 ${esc(b.author)} · 국민회복계좌 도입</p><div class="bill-scoreboard"><div><span class="bill-board-label"><img src="/assets/bills/plates/header-414.svg" alt="표결 결과"></span><strong class="bill-verdict">표결 대기</strong></div>${counts({yes:0,no:0,abstain:0})}<div class="bill-quorum"><b>집계 준비 중</b><span>찬성 151명 이상</span></div></div>${renderChamber(b)}<p class="bill-hall-note">${esc(b.rules)}</p></section><nav class="bill-detail-nav" aria-label="법안 상세 내용"><button type="button" data-bill-jump="bill-results" disabled>정당별 표결</button><button type="button" data-bill-jump="bill-proposal">법안 내용</button></nav><dialog class="bill-drawer"><button type="button" class="bill-drawer-close" data-bill-close>닫기</button><section class="bill-section" id="bill-results" hidden><div class="bill-section-title"><h2>정당별 표결</h2></div><p class="bill-method">${esc(settings.introduction??b.methodology)}</p><div class="bill-party-list">${b.parties.map(party).join('')}</div><details class="bill-basis"><summary>의석 구성 기준</summary><p>${b.seatDate} 확인 자료 기준 299석과 공석 대응 1석으로 구성했습니다. 공석 대응 패널은 요청에 따라 기권 고정입니다.</p><a href="${b.seatSource}" target="_blank" rel="noopener">정당별 의석 집계 자료 ↗</a></details></section><section class="bill-section" id="bill-proposal" hidden><div class="bill-section-title"><h2>법안 내용</h2><span>제안서 기준 ${b.documentDate}</span></div>${canEdit?renderProposalEditor(b):''}<p class="bill-lead">${esc(b.summary)}</p><div class="bill-facts">${b.facts.map(([v,l])=>`<div><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('')}</div>${b.sections.map(([h,p])=>`<div class="bill-proposal-row"><h3>${esc(h)}</h3><p>${esc(p)}</p></div>`).join('')}</section></dialog><footer class="bill-footer">JCS AI 모의법안 발의 · 실제 국회 의안 또는 표결이 아닙니다.</footer></article>`;}
export function bindMockBillNavigation(root){root.addEventListener('click',e=>{const close=e.target.closest('[data-bill-close]');if(close){close.closest('dialog').close();return;}const link=e.target.closest('[data-bill-jump]');if(!link)return;e.preventDefault();e.stopPropagation();const page=link.closest('.bill-page'),dialog=page.querySelector('.bill-drawer');for(const section of dialog.querySelectorAll('.bill-section'))section.hidden=section.id!==link.dataset.billJump;dialog.showModal();dialog.scrollTop=0;});}
