import {renderChamber} from '../ui/bill-chamber.js?v=0.0.31.411';
import {MOCK_BILL,ballots,tally} from '../data/mock-bill.js?v=0.0.31.411';
import {moduleActionIconSvg} from '../ui/service-icons.js?v=0.0.31.394';
import {renderShareMenu} from '../ui/page-share.js?v=0.0.31.411';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=MOCK_BILL;
const counts=t=>`<div class="bill-counts"><span class="bill-yes">찬성 <strong>${t.yes}</strong></span><span class="bill-no">반대 <strong>${t.no}</strong></span><span class="bill-abstain">기권 <strong>${t.abstain}</strong></span></div>`;
export function renderMockBillHome(){const t=tally(b);return `<section class="module bill-home"><div class="module-header"><div><span class="eyebrow">JCS AI MODEL ASSEMBLY</span><h2>JCS AI 모의법안 발의</h2></div><button type="button" class="module-icon-action" data-layout-route="/mock-bill/${b.id}" aria-label="모의법안 상세보기">${moduleActionIconSvg('column')}</button></div><a class="bill-home-body" href="/mock-bill/${b.id}" data-layout-route="/mock-bill/${b.id}"><div class="bill-home-copy"><span class="bill-number">제${b.number}호 · 제안 ${esc(b.author)}</span><h3>${esc(b.title)}</h3><p>국민회복계좌로 다시 시작하는 금융생활</p></div><div class="bill-home-vote"><span class="bill-status">모의 ${t.passed?'가결':'부결'}</span>${counts(t)}<small>가상 의원 300명 · 전체 출석 기준</small></div></a></section>`;}
function party(p){return `<div class="bill-party"><div class="bill-party-row"><span class="bill-party-name"><i style="background:${p.color}"></i>${esc(p.name)} <small>${p.seats}석</small></span><span class="bill-party-numbers"><span>${p.yes}<small>찬성</small></span><span>${p.no}<small>반대</small></span><span>${p.abstain}<small>기권</small></span></span></div></div>`;}
export function renderMockBillPage(settings={}){const t=tally(b);return `<article class="bill-page"><header class="bill-page-header"><div><span class="bill-kicker">JCS AI MODEL ASSEMBLY</span><h1>JCS AI 모의법안 발의</h1></div>${renderShareMenu('/mock-bill/'+b.id)}</header><section class="bill-hall"><div class="bill-hall-top"><span>제${b.number}호 모의의안</span><span>첫 평가 · ${b.date}</span></div><h2>${esc(b.title)}</h2><p class="bill-hall-sub">제안 ${esc(b.author)} · 국민회복계좌 도입</p><div class="bill-scoreboard"><div><span class="bill-board-label">표결 결과</span><strong class="bill-verdict">모의 ${t.passed?'가결':'부결'}</strong></div>${counts(t)}<div class="bill-quorum"><b>${t.passed?'가결 기준 충족':`가결까지 ${t.needed}표`}</b><span>찬성 151명 이상</span></div></div>${renderChamber()}<p class="bill-hall-note">${esc(b.rules)}</p></section><nav class="bill-detail-nav" aria-label="법안 상세 내용"><a href="#bill-results" data-bill-jump="bill-results">정당별 표결</a><a href="#bill-proposal" data-bill-jump="bill-proposal">법안 내용</a></nav><section class="bill-section" id="bill-results"><div class="bill-section-title"><h2>정당별 표결</h2></div><p class="bill-method">${esc(settings.introduction??b.methodology)}</p><div class="bill-party-list">${b.parties.map(party).join('')}</div><details class="bill-basis"><summary>의석 구성 기준</summary><p>${b.seatDate} 확인 자료 기준 299석과 공석 대응 1석으로 구성했습니다. 공석 대응 패널은 요청에 따라 기권 고정입니다.</p><a href="${b.seatSource}" target="_blank" rel="noopener">정당별 의석 집계 자료 ↗</a></details></section><section class="bill-section" id="bill-proposal"><div class="bill-section-title"><h2>법안 내용</h2><span>제안서 기준 ${b.documentDate}</span></div><p class="bill-lead">${esc(b.summary)}</p><div class="bill-facts">${b.facts.map(([v,l])=>`<div><strong>${v}</strong><span>${l}</span></div>`).join('')}</div>${b.sections.map(([h,p])=>`<div class="bill-proposal-row"><h3>${esc(h)}</h3><p>${esc(p)}</p></div>`).join('')}</section><footer class="bill-footer">JCS AI 모의법안 발의 · 실제 국회 의안 또는 표결이 아닙니다.</footer></article>`;}
export function bindMockBillNavigation(root){root.addEventListener('click',e=>{const link=e.target.closest('[data-bill-jump]');if(!link)return;e.preventDefault();e.stopPropagation();document.getElementById(link.dataset.billJump)?.scrollIntoView({behavior:globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});}
