import { NATIONAL_EVALUATION_SLOT_KEYS, nationalEvaluationTypeLabel, normalizeNationalEvaluation, voteShare, votesForEvaluationSlot } from '../core/national-evaluation-model.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const queryOf=route=>new URLSearchParams(String(route||'').split('?')[1]||'');
const page=(eyebrow,title,description,body,klass='')=>`<main class="subpage ${klass}"><section class="page-hero"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></section>${body}</main>`;
const photo=(person,klass='participation-avatar')=>person?.photo?.localPath?`<span class="${klass} has-photo" data-politician-avatar style="--photo-position:${esc(person.photo.focus||'50% 28%')}"><span class="politician-photo-initial">${esc(person.name?.slice(0,1)||'?')}</span><img data-politician-photo src="${esc(person.photo.localPath)}" alt="" loading="lazy"></span>`:`<span class="${klass} is-empty" data-politician-avatar><span class="politician-photo-initial">${esc(person?.name?.slice(0,1)||'?')}</span></span>`;
async function personFor(politicians,id){
  if(!id)return null;
  const result=await politicians?.get?.(id).catch(()=>null);
  return result?.ok&&result.item?result.item:{id,name:String(id),party:'',jurisdiction:''};
}

export async function renderPollBoard({content,session={},route='/poll'}={}){
  const data=await content.readDomain('polls'),items=(Array.isArray(data?.items)?data.items:[]).filter(item=>item?.published!==false),focus=queryOf(route).get('pollId')||'';
  const cards=items.map((poll,index)=>{const options=Array.isArray(poll.options)?poll.options:[],total=options.reduce((sum,item)=>sum+Number(item.votes||0),0);return `<article class="content-card poll-board-card ${focus===String(poll.id)?'is-focused':''}" id="poll-${esc(poll.id)}"><header><span>${String(index+1).padStart(2,'0')}</span><div><small>${poll.closedAt?'마감':'진행중'} · ${total.toLocaleString('ko-KR')}명 참여</small><h2>${esc(poll.question||poll.title||'시민 설문')}</h2>${poll.description?`<p>${esc(poll.description)}</p>`:''}</div></header><form data-poll-vote-form data-stage-form="poll-vote" data-vote-scope="poll:${esc(poll.id)}"><div class="poll-board-options">${options.map(option=>{const percent=total?Math.round(Number(option.votes||0)*100/total):0;return `<label><input type="radio" name="option" value="${esc(option.id)}" required><span>${esc(option.label||option.title)}</span><i><em style="width:${percent}%"></em></i><b>${percent}%</b></label>`;}).join('')}</div><div class="poll-board-confirm"><span>${session.authenticated?'한 항목을 선택한 뒤 확인해 주세요.':'투표는 로그인 후 참여할 수 있습니다.'}</span><button class="primary-btn" type="submit" ${session.authenticated?'':'disabled'}>투표 확인</button><em data-form-state></em></div></form></article>`;}).join('');
  return page('CITIZENS’ CHOICE · POLL BOARD','귀담아 들어야 합니다','시민의 선택을 하나씩 정확히 확인하고 정책과 정치의 신호로 기록합니다.',cards||'<section class="content-card"><div class="schedule-empty">진행 중인 설문이 없습니다</div></section>','poll-board-page');
}

export async function renderGenerationPresident({content,politicians,session={},route='/generation-president'}={}){
  const data=await content.readDomain('generation'),ages=['10대','20대','30대','40대','50대','60대+'],query=queryOf(route),age=ages.includes(query.get('age'))?query.get('age'):'20대',term=String(query.get('q')||'').trim(),candidateIds=Array.isArray(data?.candidates)?data.candidates:[];
  const candidates=await Promise.all(candidateIds.map(id=>personFor(politicians,id))),results=data?.results?.[age]||{},ordered=candidates.map((person,index)=>({person,id:candidateIds[index],votes:Number(results[candidateIds[index]]||0)})).sort((a,b)=>b.votes-a.votes).slice(0,15),total=ordered.reduce((sum,item)=>sum+item.votes,0);
  const search=term?await politicians?.search?.(term,12).catch(()=>({items:[]})):{items:[]};
  const tabs=ages.map(item=>`<button type="button" class="${item===age?'active':''}" data-layout-route="/generation-president?age=${encodeURIComponent(item)}">${item}</button>`).join('');
  const rows=ordered.map((entry,index)=>`<article class="generation-ranking-row"><strong>${index+1}</strong>${photo(entry.person,'generation-person-avatar')}<div><b>${esc(entry.person.name)}</b><small>${esc([entry.person.party,entry.person.jurisdiction].filter(Boolean).join(' · '))}</small></div><span>${total?Math.round(entry.votes*100/total):0}%<small>${entry.votes.toLocaleString('ko-KR')}표</small></span>${session.authenticated?`<button type="button" data-stage-vote="generation:${esc(age)}" data-option="${esc(entry.id)}">선택</button>`:''}</article>`).join('');
  const searchRows=(search?.items||[]).filter(item=>!candidateIds.includes(item.id)).map(item=>`<button type="button" data-stage-vote="generation:${esc(age)}" data-option="${esc(item.id)}">${photo(item,'generation-search-avatar')}<span><b>${esc(item.name)}</b><small>${esc([item.party,item.jurisdiction].filter(Boolean).join(' · '))}</small></span><em>선택</em></button>`).join('');
  return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령','같은 대통령 후보를 세대별로 바라보면 선택은 어떻게 달라질까요? 정참시 모의투표로 비교합니다.',`<section class="content-card generation-choice-panel"><div class="generation-age-tabs">${tabs}</div><div class="section-title"><h2>${esc(age)} 선택 TOP 15</h2><span>${total.toLocaleString('ko-KR')}명 참여</span></div><div class="generation-ranking-list">${rows||'<div class="schedule-empty">아직 등록된 후보가 없습니다</div>'}</div></section><section class="content-card generation-search-panel"><div class="section-title"><h2>정치인 검색</h2><span>후보를 검색해 선택</span></div><form data-generation-search role="search"><input type="search" name="q" value="${esc(term)}" placeholder="정치인 이름·정당·지역"><input type="hidden" name="age" value="${esc(age)}"><button class="primary-btn" type="submit">검색</button></form>${term?`<div class="generation-search-results">${searchRows||'<div class="schedule-empty">추가 검색 결과가 없습니다</div>'}</div>`:''}${session.authenticated?'':'<p class="module-desc">로그인 후 모의투표에 참여할 수 있습니다.</p>'}</section>`,'generation-choice-page');
}

export async function renderNationalEvaluationPage({content,politicians,session={}}={}){
  const data=normalizeNationalEvaluation(await content.readDomain('nationalEvaluation'));
  const personIds=[...NATIONAL_EVALUATION_SLOT_KEYS.map(key=>data.slots[key]?.subjectId),...data.history.map(item=>item?.subjectId)].filter(Boolean),people=new Map();
  await Promise.all([...new Set(personIds)].map(async id=>people.set(id,await personFor(politicians,id))));
  const cards=NATIONAL_EVALUATION_SLOT_KEYS.map((slotKey,index)=>{const slot=data.slots[slotKey];if(!slot?.subjectId)return '';const person=people.get(slot.subjectId),votes=votesForEvaluationSlot(data,slot),total=votes.positive+votes.neutral+votes.negative,ended=!!slot.closedAt,active=slot.enabled&&!ended;return `<article class="content-card national-evaluation-slot ${active?'active':ended?'ended':'paused'}"><div class="national-evaluation-slot-kicker"><span>SLOT ${index?'B':'A'}</span><b>${nationalEvaluationTypeLabel(slot.subjectId)}</b><em>${ended?'평가 종료':active?'평가 진행중':'일시중지'}</em></div><div class="national-evaluation-person-head">${photo(person,'national-evaluation-avatar')}<div><small>현재 평가 대상</small><h2>${esc(person.name)}</h2><p>${esc([person.party,person.jurisdiction].filter(Boolean).join(' · '))}</p><button class="ghost-btn" type="button" data-layout-route="/person/${esc(person.id)}">상세페이지</button></div></div><div class="evaluation-result-grid"><article><small>긍정</small><strong>${voteShare(votes,'positive')}%</strong><span>${votes.positive.toLocaleString('ko-KR')}표</span></article><article><small>보통</small><strong>${voteShare(votes,'neutral')}%</strong><span>${votes.neutral.toLocaleString('ko-KR')}표</span></article><article><small>부정</small><strong>${voteShare(votes,'negative')}%</strong><span>${votes.negative.toLocaleString('ko-KR')}표</span></article></div>${active&&session.authenticated?`<div class="national-evaluation-actions"><button data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="positive">긍정 평가</button><button data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="neutral">보통</button><button data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="negative">부정 평가</button></div>`:`<p class="module-desc">${session.authenticated?'현재 평가에 참여할 수 없습니다.':'평가 참여는 로그인 후 가능합니다.'}</p>`}</article>`;}).join('');
  const current=new Set(NATIONAL_EVALUATION_SLOT_KEYS.map(key=>data.slots[key]?.evaluationId)),history=data.history.filter(item=>!current.has(item.evaluationId)).map(item=>{const person=people.get(item.subjectId),votes={positive:Number(item.positive||0),neutral:Number(item.neutral||0),negative:Number(item.negative||0)},total=votes.positive+votes.neutral+votes.negative;return `<article><div><b>${esc(person?.name||item.subjectId)} <small>${nationalEvaluationTypeLabel(item.subjectId)}</small></b><span>${total.toLocaleString('ko-KR')}명 참여 · ${esc(item.closedAt||'')}</span></div><p>긍정 ${voteShare(votes,'positive')}% · 보통 ${voteShare(votes,'neutral')}% · 부정 ${voteShare(votes,'negative')}%</p></article>`;}).join('');
  return page('NATIONAL EVALUATION · JEONGCHAMSI CITIZENS','정참시민 전국 평가제','국회의원 한 명과 광역·기초단체장 중 한 명을 정참시민이 각각 독립적으로 평가합니다.',`<div class="national-evaluation-two-slot-page">${cards||'<section class="content-card"><div class="schedule-empty">진행 중인 평가가 없습니다</div></section>'}</div><section class="content-card"><div class="section-title"><h2>지난 전국 평가</h2><span>${data.history.length}건</span></div><div class="evaluation-history-list">${history||'<div class="schedule-empty">아직 종료된 이전 평가가 없습니다</div>'}</div></section>`,'national-evaluation-page');
}
