const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arr=v=>Array.isArray(v)?v:[];
const text=v=>v===null||v===undefined||v===''?'미제공':String(v);
const parties={democratic:['더불어민주당','#2465bf'],ppp:['국민의힘','#d84343'],rebuilding:['조국혁신당','#25678c'],reform:['개혁신당','#de7732'],progressive:['진보당','#a84770'],other:['기타 정당','#787381'],none:['지지 정당 없음','#89858e'],undecided:['모름·무응답','#a09ba6']};
const valid=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=100;
function source(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">조사 원문 ↗</a>`:'';}catch{return '';}}
export function renderPartyBars(result={},previous=null){
 const rows=arr(result?.parties).filter(p=>p&&typeof p==='object');
 if(!rows.some(p=>valid(p.value)))return '<p class="party-poll-empty">정당별 수치 확인 중</p>';
 return `<ul class="party-poll-bars">${rows.map(p=>{const known=parties[p.id],v=valid(p.value)?p.value:null,old=arr(previous?.results?.parties).find(row=>row.id===p.id),delta=v!==null&&valid(old?.value)?Number((v-old.value).toFixed(1)):null;return `<li><div class="party-poll-label"><span>${esc(p.name||known?.[0]||'기타')}</span><strong>${v===null?'미제공':`${Number(v.toFixed(1))}%`}</strong></div>${delta!==null?`<small class="party-poll-delta">이전 조사 대비 ${delta>0?'+':''}${delta}%P</small>`:''}<div class="party-poll-bar" aria-hidden="true"><span style="width:${v??0}%;background:${known?.[1]||'#787381'}"></span></div></li>`;}).join('')}</ul>`;
}
function card(p,name,ai=false,{stale=false,previous=null}={}){
 const ready=p&&arr(p.results?.parties).some(x=>valid(x?.value))&&p.state!=='pending';
 return `<article class="ai-result ${ai?'synthetic':'human'} party-poll-card"><span class="ai-kicker">${ai?'JCS AI · 가상패널':'HUMAN · 실제 여론조사'}</span><h3>${esc(name)}</h3>${ready?renderPartyBars(p.results,previous):`<p class="party-poll-empty">${ai?'가상패널 준비 중':'원자료 확인 중'}</p>`}<div class="party-poll-source">${stale?'<small class="party-poll-stale">이전 결과 유지 · 갱신 확인 필요</small>':''}${ai&&Number.isInteger(p?.syntheticPanelSize??p?.sampleSize??p?.panelSize)?`<small>가상패널 N${esc(p.syntheticPanelSize??p.sampleSize??p.panelSize)}</small>`:''}${previous?`<small>이전 조사 ${esc(previous.publishedDate||previous.endDate)} 대비</small>`:''}${p?`<small>${esc(text(p.publishedDate||p.basisDate))} ${ai?'기준':'발표'}${p.startDate||p.endDate?`<br>${esc(text(p.startDate))}–${esc(text(p.endDate))} 조사`:''}</small>${!ai?source(p.sourceUrl):''}`:''}</div></article>`;
}
function metadata(p){return `<dl class="ai-meta">${[['조사기관',p.institution],['발표일',p.publishedDate],['조사 기간',`${text(p.startDate)}–${text(p.endDate)}`],['표본수',p.sampleSize],['조사방법',p.method],['응답률',typeof p.responseRate==='number'?`${p.responseRate}%`:p.responseRate],['표본오차',typeof p.marginOfError==='number'?`±${p.marginOfError}%P (95% 신뢰수준)`:p.marginOfError]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(text(v))}</dd></div>`).join('')}</dl>${source(p.sourceUrl)}`;}
export function renderPartyPoll(data={},detail=false){
 const polls=arr(data?.items).filter(p=>p?.topic==='party-support').slice().sort((a,b)=>String(b.publishedDate||b.endDate||'').localeCompare(String(a.publishedDate||a.endDate||'')));
 const providers=[['한국갤럽',/갤럽|gallup/i,'gallup'],['리얼미터',/리얼미터|realmeter/i,'realmeter'],['NBS',/NBS|전국지표/i,'nbs']];
 const chosen=providers.map(([name,re,id])=>{const p=polls.find(p=>re.test(`${p.institution||''} ${p.provenance?.provider||''}`)),previous=p?arr(data?.history).filter(old=>old?.topic==='party-support'&&re.test(`${old.institution||''} ${old.provenance?.provider||''}`)&&String(old.endDate||old.publishedDate)<String(p.endDate||p.publishedDate)).sort((a,b)=>String(b.endDate||b.publishedDate).localeCompare(String(a.endDate||a.publishedDate)))[0]:null,stale=arr(data?.providers).some(status=>(status.id===id||re.test(status.institution||''))&&(status.error||['error','failed','partial'].includes(status.state)));return [name,p,{previous,stale}];});
 return `<section class="ai-section party-poll-section"><h2>정당 지지도</h2><div class="ai-results party-poll-carousel" data-ai-poll-track tabindex="0" aria-label="정당 지지도 결과 · 좌우로 이동">${card(data?.ai,'JCS AI',true,{stale:!!data?.ai?.stale})}${chosen.map(([name,p,context])=>card(p,name,false,context)).join('')}</div><nav class="ai-poll-controls party-poll-controls" aria-label="정당 지지도 카드 이동"><button type="button" data-ai-poll-scroll="-1" aria-label="이전 조사">←</button><span>JCS AI · 갤럽 · 리얼미터 · NBS<br>좌우로 밀어 다른 조사 보기</span><button type="button" data-ai-poll-scroll="1" aria-label="다음 조사">→</button></nav><p class="ai-disclosure">AI 패널 결과는 설정된 프로필에 따른 AI 응답입니다.</p>${data?.ok===false?'<p class="ai-muted">정당 지지도 자료를 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.</p>':''}${detail?`${chosen.filter(([,p])=>p).map(([name,p])=>`<details class="ai-section"><summary>${esc(name)} 조사 정보</summary>${metadata(p)}</details>`).join('')}`:''}</section>`;
}
export function renderPollTopicTabs(selected='approval',home=false){
 return `<nav class="poll-topic-tabs" ${home?'role="tablist"':'aria-label="조사 주제"'}>${[['approval','대통령 직무평가'],['party-support','정당 지지도']].map(([key,label])=>home?`<button type="button" role="tab" id="poll-home-tab-${key}" aria-controls="poll-home-panel-${key}" aria-selected="${key===selected}" tabindex="${key===selected?0:-1}" data-poll-topic="${key}">${label}</button>`:`<a href="#/ai-panel${key==='party-support'?'?topic=party-support':''}" data-layout-route="/ai-panel${key==='party-support'?'?topic=party-support':''}" ${key===selected?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;
}
