import { GENERATION_AGES, generationAgeGroup, hasGenerationVote, participationDisplay, demoLabel } from '../core/participation-model.js?v=0.0.31.79';
export { generationAgeGroup } from '../core/participation-model.js?v=0.0.31.79';
import { NATIONAL_EVALUATION_SLOT_KEYS, nationalEvaluationTypeLabel, normalizeNationalEvaluation, voteShare, votesForEvaluationSlot } from '../core/national-evaluation-model.js?v=0.0.31.61';

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const queryOf=route=>new URLSearchParams(String(route||'').split('?')[1]||'');
const page=(eyebrow,title,description,body,klass='')=>`<main class="subpage ${klass}"><section class="page-hero"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></section>${body}</main>`;
const photo=(person,klass='participation-avatar')=>{const src=person?.photo?.url||person?.photo?.localPath;return src?`<span class="${klass} has-photo" data-politician-avatar style="--photo-position:${esc(person.photo.focus||'50% 28%')}"><span class="politician-photo-initial">${esc(person.name?.slice(0,1)||'?')}</span><img data-politician-photo src="${esc(src)}" alt="" loading="lazy"></span>`:`<span class="${klass} is-empty" data-politician-avatar><span class="politician-photo-initial">${esc(person?.name?.slice(0,1)||'?')}</span></span>`;};
async function personFor(politicians,id){
  if(!id)return null;
  const result=await politicians?.get?.(id).catch(()=>null);
  return result?.ok&&result.item?result.item:{id,name:String(id),party:'',jurisdiction:''};
}
const isAdmin=session=>session?.user?.role==='admin';
export const generationVoteConfirmation=(name,age)=>`${age} 선택으로 ${name} 정치인에게 투표하시겠습니까? 한 번 투표하면 되돌릴 수 없습니다.`;
const featureButton=(domain,item)=>`<button type="button" class="participation-feature ${item.featured?'is-active':''}" data-participation-feature="${esc(domain)}:${esc(item.id)}">${item.featured?'메인 적용 중':'메인에 적용'}</button>`;
const participationEdit=(domain,item)=>`<details class="post-editor"><summary>수정·삭제</summary><form class="stage-form" data-participation-edit="${esc(domain)}" data-post-id="${esc(item.id)}"><label>제목<input name="title" value="${esc(item.title||item.question)}" required></label><label>내용<textarea name="body">${esc(item.body||item.description||'')}</textarea></label>${domain==='polls'?(item.options||[]).map(row=>`<label>선택지<input name="optionLabels" value="${esc(row.label)}" required></label>`).join(''):''}<button class="primary-btn" name="operation" value="edit">수정 저장</button><button class="ghost-btn" name="operation" value="delete">게시물 삭제</button><span data-form-state></span></form></details>`;

const pollAdminComposer=session=>isAdmin(session)?`<section class="content-card participation-admin-editor"><div class="section-title"><h2>시티즌 초이스 게시물 작성</h2><span>저장 후 메인 적용 가능</span></div><form class="stage-form compact" data-participation-admin-form="polls"><label class="form-field"><span>질문</span><input name="title" required></label><label class="form-field"><span>설명</span><textarea name="body" rows="3"></textarea></label><label class="form-field"><span>선택지</span><textarea name="options" rows="4" required placeholder="한 줄에 하나씩 입력"></textarea></label><label class="participation-apply-check"><input type="checkbox" name="applyToMain" value="true" checked> 저장과 동시에 메인 적용</label><button class="primary-btn" type="submit">새 게시물 저장</button><span class="save-state" data-form-state></span></form></section>`:'';
const evaluationAdminComposer=session=>isAdmin(session)?`<section class="content-card participation-admin-editor"><div class="section-title"><h2>전국 평가제 게시물 작성</h2><span>정치인 선택 후 메인 적용</span></div><form class="stage-form compact" data-participation-admin-form="nationalEvaluation"><label class="form-field"><span>제목</span><input name="title" required></label><label class="form-field politician-autocomplete-field"><span>평가 정치인</span><input name="politicianName" required autocomplete="off" data-politician-autocomplete data-politician-select-mode="value" data-politician-target="[name=subjectId]" placeholder="한 글자만 입력해도 검색"><input type="hidden" name="subjectId" required></label><label class="form-field"><span>분야</span><select name="slot"><option value="assembly">국회의원</option><option value="local">광역·기초단체장</option></select></label><label class="form-field"><span>게시물 내용</span><textarea name="body" rows="4"></textarea></label><label class="participation-apply-check"><input type="checkbox" name="applyToMain" value="true" checked> 저장과 동시에 메인 적용</label><button class="primary-btn" type="submit">새 게시물 저장</button><span class="save-state" data-form-state></span></form></section>`:'';
const generationAdminComposer=session=>isAdmin(session)?`<section class="content-card participation-admin-editor"><div class="section-title"><h2>세대별 대통령 모의투표 작성</h2><span>후보 2~15명을 검색해 등록</span></div><form class="stage-form compact" data-participation-admin-form="generation"><label class="form-field"><span>제목</span><input name="title" required></label><label class="form-field"><span>설명</span><textarea name="body" rows="3"></textarea></label>${Array.from({length:15},(_,index)=>`<label class="form-field politician-autocomplete-field"><span>후보 ${index+1}${index<2?' · 필수':''}</span><input name="candidateName" ${index<2?'required':''} autocomplete="off" data-politician-autocomplete data-politician-select-mode="value" data-politician-target="[name=candidateIds][data-candidate-index='${index}']" placeholder="한 글자만 입력해도 검색"><input type="hidden" name="candidateIds" data-candidate-index="${index}"></label>`).join('')}<label class="participation-apply-check"><input type="checkbox" name="applyToMain" value="true" checked> 저장과 동시에 메인 적용</label><button class="primary-btn" type="submit">새 모의투표 저장</button><span class="save-state" data-form-state></span></form></section>`:'';
const participationAdminDisclosure=content=>content?`<details class="participation-admin-editor-disclosure"><summary>관리자 수정 페이지 펼치기</summary>${content}</details>`:'';

export async function renderPollBoard({content,session={},route='/poll'}={}){
  const data=participationDisplay('polls',await content.readDomain('polls')),items=(Array.isArray(data?.items)?data.items:[]).filter(item=>item?.published!==false).sort((a,b)=>Number(b.featured===true)-Number(a.featured===true)),focus=queryOf(route).get('pollId')||'';
  const cards=items.filter(poll=>!poll.closedAt).map((poll,index)=>{const options=Array.isArray(poll.options)?poll.options:[],total=options.reduce((sum,item)=>sum+Number(item.votes||0),0);return `<article class="content-card poll-board-card ${focus===String(poll.id)?'is-focused':''}" id="poll-${esc(poll.id)}"><header><span>${String(index+1).padStart(2,'0')}</span><div>${demoLabel(poll.jcsDemo)}<small>${poll.closedAt?'마감':'진행중'} · ${total.toLocaleString('ko-KR')}명 참여</small><h2>${esc(poll.question||poll.title||'시민 설문')}</h2>${poll.description?`<p>${esc(poll.description)}</p>`:''}</div>${isAdmin(session)?featureButton('polls',poll)+participationEdit('polls',poll):''}</header><form data-poll-vote-form data-stage-form="poll-vote" data-vote-scope="poll:${esc(poll.id)}"><div class="poll-board-options">${options.map(option=>{const percent=total?Math.round(Number(option.votes||0)*100/total):0;return `<label><input type="radio" name="option" value="${esc(option.id)}" required><span>${esc(option.label||option.title)}</span><i><em style="width:${percent}%"></em></i><b>${percent}%</b></label>`;}).join('')}</div><div class="poll-board-confirm"><span>${poll.jcsDemo?'JCS 데모데이터 표시 중 · 내 투표는 실제 집계에 별도 반영됩니다.':session.authenticated?'한 항목을 선택한 뒤 확인해 주세요.':'투표는 로그인 후 참여할 수 있습니다.'}</span><button class="primary-btn" type="submit" ${session.authenticated?'':'disabled'}>투표 확인</button><em data-form-state></em></div></form>${isAdmin(session)?inlineDemoEditor("polls",poll):''}</article>`;}).join('');
  const ended=items.filter(poll=>poll.closedAt).sort((a,b)=>(Date.parse(b.closedAt)||0)-(Date.parse(a.closedAt)||0));
  const archive=ended.length?`<details class="content-card poll-archive" ${ended.some(poll=>String(poll.id)===focus)?'open':''}><summary><strong>종료된 시티즌 초이스</strong><span>${ended.length}건</span><span class="archive-toggle">펼치기 / 접기</span></summary><div class="poll-archive-list">${ended.map(poll=>{
    const options=Array.isArray(poll.options)?poll.options:[],total=options.reduce((sum,option)=>sum+Number(option.votes||0),0),closed=new Date(poll.closedAt),date=Number.isNaN(closed.getTime())?'':closed.toLocaleDateString('ko-KR');
    return `<details class="poll-archive-post" id="poll-${esc(poll.id)}" ${String(poll.id)===focus?'open':''}><summary><span class="poll-archive-status">마감</span><strong>${esc(poll.question||poll.title||'시민 설문')}</strong><small>${total.toLocaleString('ko-KR')}명 참여${date?' · '+date:''}</small></summary><div class="poll-archive-body">${demoLabel(poll.jcsDemo)}${poll.description?`<p>${esc(poll.description)}</p>`:''}<ul>${options.map(option=>`<li><span>${esc(option.label||option.title)}</span><b>${total?Math.round(Number(option.votes||0)*100/total):0}%</b><small>${Number(option.votes||0).toLocaleString('ko-KR')}표</small></li>`).join('')}</ul>${isAdmin(session)?participationEdit('polls',poll)+inlineDemoEditor('polls',poll):''}</div></details>`;
  }).join('')}</div></details>`:'';
  return page('CITIZENS’ CHOICE · POLL BOARD','귀담아 들어야 합니다','시민의 선택을 하나씩 정확히 확인하고 정책과 정치의 신호로 기록합니다.',`${cards||'<section class="content-card"><div class="schedule-empty">진행 중인 설문이 없습니다</div></section>'}${archive}${participationAdminDisclosure(pollAdminComposer(session))}`,'poll-board-page');
}

const generationCohortEditor=(active,data,age,people)=>{
 const pool=active?.candidateIds||data.candidates||[],byAge=active?.candidatesByAge||{},ids=byAge[age]||pool;
 const row=(id)=>`<div class="generation-manage-row"><input type="hidden" name="cohortIds" value="${esc(id)}"><span>${esc(people.get(id)?.name||id)}<small>${esc(people.get(id)?.party||'')}</small></span><label>데모 득표수<input type="number" min="0" max="100000000" step="1" required value="${Number(active?.demo?.counts?.[age]?.[id]||0)}" data-cohort-count></label><button type="button" data-cohort-remove>제외</button></div>`;
 const copy=Object.fromEntries(GENERATION_AGES.map(a=>[a,(byAge[a]||pool).map(id=>({id,name:people.get(id)?.name||id}))]));
 return `<form class="generation-cohort-editor" data-generation-cohort-editor data-age="${esc(age)}" data-item-id="${esc(active?.id||'')}" data-copy-pools="${esc(JSON.stringify(copy))}"><h3>${esc(age)} 후보·득표수 관리</h3><div class="generation-manage-search politician-autocomplete-field"><input placeholder="추가할 정치인 검색" autocomplete="off" data-politician-autocomplete data-politician-select-mode="value" data-politician-target="#cohort-add-id" data-cohort-add-name><input id="cohort-add-id" type="hidden"><button type="button" data-cohort-add>후보 추가</button></div><div class="generation-copy"><select data-cohort-copy-age>${GENERATION_AGES.filter(a=>a!==age).map(a=>`<option>${a}</option>`).join('')}</select><button type="button" data-cohort-copy>후보 목록 복사</button></div><div data-cohort-rows>${ids.map(row).join('')}</div><label class="generation-demo-toggle"><input type="checkbox" name="enabled" ${(active?.demo?.enabledByAge?.[age]??active?.demo?.enabled)?'checked':''}> 이 세대를 JCS 데모데이터로 표시</label><button type="submit" class="primary-btn">${esc(age)} 저장 · 메인 반영</button><span data-form-state role="status"></span></form>`;
};
export async function renderGenerationPresident({content,politicians,session={},route='/generation-president'}={}){
  const data=participationDisplay('generation',await content.readDomain('generation')),ages=GENERATION_AGES,query=queryOf(route),admin=isAdmin(session),memberAge=session.authenticated&&!admin?generationAgeGroup(session.user?.birthYear):'',requestedAge=ages.includes(query.get('age'))?query.get('age'):'20대',age=query.has('age')?requestedAge:(memberAge||requestedAge),term=String(query.get('q')||'').trim(),items=(Array.isArray(data?.items)?data.items:[]).filter(item=>item?.published!==false),active=items.find(item=>item.featured===true)||items.find(item=>String(item.id)===String(data.activeItemId))||null,candidateIds=active?.candidatesByAge?.[age]||data?.candidatesByAge?.[age]||active?.candidateIds||data?.candidates||[],allIds=[...new Set([...candidateIds,...items.flatMap(item=>item.candidateIds||[])])];
  const allPeople=await Promise.all(allIds.map(id=>personFor(politicians,id))),people=new Map(allIds.map((id,index)=>[id,allPeople[index]])),candidates=candidateIds.map(id=>people.get(id)),results=(active?.results||data?.results||{})[age]||{},ordered=candidates.map((person,index)=>({person,id:candidateIds[index],votes:Number(results[candidateIds[index]]||0)})).sort((a,b)=>b.votes-a.votes).slice(0,15),total=ordered.reduce((sum,item)=>sum+item.votes,0);
  const search=term?await politicians?.search?.(term,12).catch(()=>({items:[]})):{items:[]};
  const tabs=ages.map(item=>`<button type="button" class="${item===age?'active':''}" data-layout-route="/generation-president?age=${encodeURIComponent(item)}">${item}</button>`).join('');
  const voteScope=active?`generation:${active.id}:${age}`:`generation:${age}`;
  const voteState=session.authenticated&&!admin?await content.generationVotes?.().catch(()=>null):null;
  const voted=hasGenerationVote(voteState?.votes||{},active?.id||'')||active?.legacyVoting&&hasGenerationVote(voteState?.votes||{});
  const canVote=session.authenticated&&!!memberAge&&age===memberAge&&!admin&&!voted&&voteState?.ok===true;
  const rows=ordered.map((entry,index)=>`<article class="generation-ranking-row"><strong>${index+1}</strong>${photo(entry.person,'generation-person-avatar')}<div><b>${esc(entry.person.name)}</b><small>${esc([entry.person.party,entry.person.jurisdiction].filter(Boolean).join(' · '))}</small></div><span>${total?Math.round(entry.votes*100/total):0}%<small>${entry.votes.toLocaleString('ko-KR')}표</small></span>${canVote?`<button type="button" data-generation-vote-confirm="${esc(voteScope)}" data-option="${esc(entry.id)}" data-candidate-name="${esc(entry.person.name)}" data-generation-age="${esc(age)}">선택</button>`:''}</article>`).join('');
  const searchRows=(search?.items||[]).filter(item=>candidateIds.includes(item.id)).map(item=>`<button type="button" ${canVote?`data-generation-vote-confirm="${esc(voteScope)}" data-option="${esc(item.id)}" data-candidate-name="${esc(item.name)}" data-generation-age="${esc(age)}"`:'disabled aria-disabled="true"'}>${photo(item,'generation-search-avatar')}<span><b>${esc(item.name)}</b><small>${esc([item.party,item.jurisdiction].filter(Boolean).join(' · '))}</small></span><em>선택</em></button>`).join('');
  const history=items.filter(item=>item.id!==active?.id).map(item=>`<article><div class="participation-candidate-photos">${item.candidateIds?.slice(0,4).map(id=>photo(people.get(id),'evaluation-post-avatar')).join('')||''}</div><div class="participation-post-copy"><b>${esc(item.title)}</b><span>${esc(item.body||'세대별 모의투표')}</span></div>${isAdmin(session)?featureButton('generation',item)+participationEdit('generation',item)+inlineDemoEditor('generation',item,Object.fromEntries([...people].map(([id,p])=>[id,p?.name||id]))):item.featured?'<em>현재 메인 노출</em>':''}</article>`).join('');
  const accessNotice=!session.authenticated?'로그인 후 모의투표에 참여할 수 있습니다.':admin?'관리자는 5개 세대의 현황을 관리합니다.':!memberAge?'20대 이상 대상 모의투표입니다. 가입한 출생연도를 확인해 주세요.':voted?'이번 회차 투표를 완료했습니다. 다른 세대 결과도 확인할 수 있습니다.':voteState?.ok!==true?'투표 이력을 확인하지 못했습니다. 새로고침해 주세요.':`${memberAge}에서 후보 한 명에게 회차당 한 번 투표할 수 있습니다. 다른 세대는 결과만 확인할 수 있습니다.`;
  const composer=participationAdminDisclosure(generationAdminComposer(session));return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령','세대별 후보와 선택을 정참시 모의투표로 비교합니다.',`<div data-generation-cohort="${esc(age)}"><section class="content-card generation-choice-panel">${demoLabel(data.demoByAge?.[age]??data.jcsDemo)}<p class="module-desc">20대 이상 대상 모의투표 · ${esc(accessNotice)}</p>${(data.demoByAge?.[age]??data.jcsDemo)?'<p class="module-desc">데모 표시 중에도 내 투표는 실제 집계에 별도 반영됩니다.</p>':''}<div class="generation-age-tabs">${tabs}</div><div class="section-title"><h2>${esc(active?.title||`${age} 선택 TOP 15`)}</h2><span>${total.toLocaleString('ko-KR')}명 참여</span></div><div class="generation-ranking-list">${rows||'<div class="schedule-empty">아직 등록된 후보가 없습니다</div>'}</div>${admin?generationCohortEditor(active,data,age,people):''}</section><section class="content-card generation-search-panel"><div class="section-title"><h2>정치인 검색</h2><span>후보를 검색해 선택</span></div><form data-generation-search role="search"><input type="search" name="q" value="${esc(term)}" placeholder="정치인 이름·정당·지역" autocomplete="off" data-politician-autocomplete data-politician-select-mode="value" ${canVote||admin?'':'disabled'}><input type="hidden" name="age" value="${esc(age)}"><button class="primary-btn" type="submit" ${canVote||admin?'':'disabled'}>검색</button></form>${term?`<div class="generation-search-results">${searchRows||'<div class="schedule-empty">추가 검색 결과가 없습니다</div>'}</div>`:''}<p class="module-desc">${accessNotice}</p></section><section class="content-card participation-post-list"><div class="section-title"><h2>지난 모의투표</h2><span>${items.filter(item=>item.id!==active?.id).length}건</span></div>${history||'<div class="schedule-empty">작성된 모의투표가 없습니다</div>'}</section>${composer}</div>`,'generation-choice-page');
}

export async function renderNationalEvaluationPage({content,politicians,session={}}={}){
  const data=normalizeNationalEvaluation(participationDisplay('nationalEvaluation',await content.readDomain('nationalEvaluation')));
  const posts=Array.isArray(data.items)?data.items.filter(item=>item?.published!==false):[],personIds=[...NATIONAL_EVALUATION_SLOT_KEYS.map(key=>data.slots[key]?.subjectId),...data.history.map(item=>item?.subjectId),...posts.map(item=>item?.subjectId)].filter(Boolean),people=new Map();
  await Promise.all([...new Set(personIds)].map(async id=>people.set(id,await personFor(politicians,id))));
  const cards=NATIONAL_EVALUATION_SLOT_KEYS.map((slotKey,index)=>{const slot=data.slots[slotKey];if(!slot?.subjectId)return '';const person=people.get(slot.subjectId),votes=votesForEvaluationSlot(data,slot),total=votes.positive+votes.neutral+votes.negative,ended=!!slot.closedAt,active=slot.enabled&&!ended;return `<article class="content-card national-evaluation-slot ${active?'active':ended?'ended':'paused'}"><div class="national-evaluation-slot-kicker">${demoLabel(slot.jcsDemo)}<span>SLOT ${index?'B':'A'}</span><b>${nationalEvaluationTypeLabel(slot.subjectId)}</b><em>${ended?'평가 종료':active?'평가 진행중':'일시중지'}</em></div><div class="national-evaluation-person-head">${photo(person,'national-evaluation-avatar')}<div><small>현재 평가 대상</small><h2>${esc(person.name)}</h2><p>${esc([person.party,person.jurisdiction].filter(Boolean).join(' · '))}</p><button class="ghost-btn" type="button" data-layout-route="/person/${esc(person.id)}">상세페이지</button></div></div><div class="evaluation-result-grid"><article><small>긍정</small><strong>${voteShare(votes,'positive')}%</strong><span>${votes.positive.toLocaleString('ko-KR')}표</span></article><article><small>보통</small><strong>${voteShare(votes,'neutral')}%</strong><span>${votes.neutral.toLocaleString('ko-KR')}표</span></article><article><small>부정</small><strong>${voteShare(votes,'negative')}%</strong><span>${votes.negative.toLocaleString('ko-KR')}표</span></article></div>${slot.jcsDemo?'<p class="module-desc">JCS 데모데이터 표시 중 · 내 평가는 실제 집계에 별도 반영됩니다.</p>':''}${active&&session.authenticated?`<div class="national-evaluation-actions"><button data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="positive">긍정 평가</button><button data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="neutral">보통</button><button data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="negative">부정 평가</button></div>`:`<p class="module-desc">${session.authenticated?'현재 평가에 참여할 수 없습니다.':'평가 참여는 로그인 후 가능합니다.'}</p>`}${isAdmin(session)?inlineDemoEditor('nationalEvaluation',posts.find(x=>x.id===slot.itemId||`evaluation-${x.id}`===slot.evaluationId)):''}</article>`;}).join('');
  const current=new Set(NATIONAL_EVALUATION_SLOT_KEYS.map(key=>data.slots[key]?.evaluationId)),history=data.history.filter(item=>!current.has(item.evaluationId)).map(item=>{const person=people.get(item.subjectId),votes={positive:Number(item.positive||0),neutral:Number(item.neutral||0),negative:Number(item.negative||0)},total=votes.positive+votes.neutral+votes.negative;return `<article>${photo(person,'evaluation-history-avatar')}<div><b>${esc(person?.name||item.subjectId)} <small>${nationalEvaluationTypeLabel(item.subjectId)}</small></b><span>${total.toLocaleString('ko-KR')}명 참여 · ${esc(item.closedAt||'')}</span><p>긍정 ${voteShare(votes,'positive')}% · 보통 ${voteShare(votes,'neutral')}% · 부정 ${voteShare(votes,'negative')}%</p></div></article>`;}).join('');
  const postList=`<section class="content-card participation-post-list"><div class="section-title"><h2>전국 평가 게시물</h2><span>${posts.length}건</span></div>${posts.map(item=>{const person=people.get(item.subjectId);return `<article>${photo(person,'evaluation-post-avatar')}<div><b>${esc(item.title)}</b><span>${esc(person?.name||item.subjectId)} · ${item.slot==='local'?'광역·기초단체장':'국회의원'}</span>${item.body?`<p>${esc(item.body)}</p>`:''}</div>${isAdmin(session)?featureButton('nationalEvaluation',item)+participationEdit('nationalEvaluation',item)+inlineDemoEditor('nationalEvaluation',item):item.featured?'<em>현재 메인 노출</em>':''}</article>`;}).join('')||'<div class="schedule-empty">작성된 평가 게시물이 없습니다</div>'}</section>`;
  return page('NATIONAL EVALUATION · JEONGCHAMSI CITIZENS','정참시민 전국 평가제','국회의원 한 명과 광역·기초단체장 중 한 명을 정참시민이 각각 독립적으로 평가합니다.',`<div class="national-evaluation-two-slot-page">${cards||'<section class="content-card"><div class="schedule-empty">진행 중인 평가가 없습니다</div></section>'}</div>${postList}<section class="content-card"><div class="section-title"><h2>지난 전국 평가</h2><span>${data.history.length}건</span></div><div class="evaluation-history-list">${history||'<div class="schedule-empty">아직 종료된 이전 평가가 없습니다</div>'}</div></section>${participationAdminDisclosure(evaluationAdminComposer(session))}`,'national-evaluation-page');
}


function inlineDemoEditor(domain,item,candidateLabels={}){
 if(!item?.id)return "";
 const input=(key,label,value,age='')=>`<label class="demo-count-field"><span>${esc(label)}</span><input type="number" min="0" max="100000000" step="1" required data-demo-key="${esc(key)}" data-demo-age="${esc(age)}" value="${Number(value)||0}"></label>`;
   const counts=item.demo?.counts||{};
   const fields=domain==='polls'?(item.options||[]).map(o=>input(o.id,o.label,counts[o.id])).join(''):domain==='nationalEvaluation'?[['positive','긍정'],['neutral','보통'],['negative','부정']].map(([key,label])=>input(key,label,counts[key])).join(''):GENERATION_AGES.map(age=>`<fieldset><legend>${age}</legend>${(item.candidateIds||[]).map(id=>input(id,candidateLabels[id]||id,counts[age]?.[id],age)).join('')}</fieldset>`).join('');
   return `<details class="demo-item-editor"><summary>관리자 숫자 조정 · ${esc(item.title||item.question)} ${item.demo?.enabled?'· 데모 표시 중':''}</summary><form data-participation-demo data-domain="${domain}" data-post-id="${esc(item.id)}"><label class="demo-enable"><input type="checkbox" name="enabled" ${item.demo?.enabled?'checked':''}> JCS 데모데이터 공개 표시</label><div class="demo-count-grid">${fields}</div><button class="primary-btn" type="submit">데모 설정 저장</button><span data-form-state role="status"></span></form></details>`;
}

export function renderParticipationAdminSettings(data={}){
 const links=[['operations','운영현황'],['members','회원관리'],['politicians','정치인정보'],['pipeline','데이터수집·게시'],['site','풋터정보'],['keywords','정치키워드'],['participation','참여·데모']];
 const nav=`<nav class="admin-tabs">${links.map(([key,label])=>`<button data-admin-tab="${key}" class="${key==='participation'?'is-active':''}">${label}</button>`).join('')}</nav>`;
 const sections=[['polls','시티즌 초이스','/poll'],['generation','세대별 대통령','/generation-president'],['nationalEvaluation','전국 평가제','/national-evaluation']].map(([domain,title,route])=>{
  const forms=(data[domain]?.items||[]).filter(x=>x.published!==false).map(item=>{
   return inlineDemoEditor(domain,item,data.generation?.candidateLabels||{});
  }).join('');
  return `<section class="content-card"><div class="section-title"><h2>${title}</h2><button class="ghost-btn" data-layout-route="${route}">게시물·후보 생성 및 관리 →</button></div>${forms||'<p>먼저 게시물을 생성해 주세요.</p>'}</section>`;
 }).join('');
 const cages=(data.community?.items||[]).filter(x=>x.published!==false&&!x.deleted&&x.cageEnabled&&!x.cageParentId);
 return page('ADMIN · PARTICIPATION','참여 게시판 · 데모 관리','데모 수치는 실제 참여와 별도로 저장됩니다. 표시를 끄면 실제 결과로 돌아갑니다.',`${nav}<section class="content-card"><h2>메인 케이지 미리보기</h2><form data-home-cage-form class="stage-form"><label>노출할 케이지<select name="id"><option value="">최신 케이지 자동 선택</option>${cages.map(x=>`<option value="${esc(x.id)}" ${data.community?.featuredCageId===x.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><button class="primary-btn" type="submit">미리보기 저장</button><span data-form-state role="status"></span></form></section>${sections}`,'participation-settings-page');
}

export function renderPointShop(result={},session={},view='shop'){
 if(result.ok!==true)return page('POINT SHOP','포인트 충전소','',`<p role="alert">충전소를 불러오지 못했습니다. 새로고침해 주세요.</p>`);
 const admin=isAdmin(session),logged=session.authenticated,bank=result.bank||{},wallet=result.wallet||{},ready=!!(bank.bank&&bank.account&&bank.holder),first=!wallet.firstPaid,packages=[10000,30000,50000,100000,500000,1000000],number=n=>Number(n||0).toLocaleString('ko-KR'),rate=n=>first?20:n>=1000000?20:n>=500000?15:n>=100000?10:0;
 const orders=result.orders||[],status={pending:'입금 확인 대기',approved:'지급 완료',rejected:'신청 반려'};
 const bankEditor=admin?`<section class="module point-panel"><h2>관리자 · 충전 계좌 설정</h2><form data-point-form="bank">${[['bank','은행명'],['account','계좌번호'],['holder','예금주']].map(([key,label])=>`<label>${label}<input name="${key}" required maxlength="80" value="${esc(bank[key]||'')}"></label>`).join('')}<button type="submit" class="point-primary">계좌 저장</button><p data-form-state role="status"></p></form></section>`:'';
 if(view==='support')return `<div class="point-shop donation-only">${renderDonationCheque(bank)}${bankEditor}</div>`;
 return `<div class="point-shop"><header class="point-hero"><span class="point-kicker">JCS POINT SHOP</span><h1>목소리에 힘을 충전하세요</h1><p>포인트로 직접 케이지를 열고, 토론의 주제를 만들어보세요.</p><div class="point-wallet"><span>보유 포인트</span><b>${number(wallet.balance)}<small> P</small></b>${!logged?'<a href="/login" data-layout-route="/login">로그인</a>':''}</div><span class="point-offer">${first?'첫 구매 보너스 20% · 중복 적용 없음':'10만 원부터 구매 금액별 보너스'}</span></header>
 <section class="point-packages" aria-label="충전 상품">${packages.map((amount,i)=>`<button type="button" class="point-package" data-point-package="${amount}" data-point-total="${amount*(100+rate(amount))/100}" aria-pressed="false"><span class="point-treasure tier-${i}" aria-hidden="true">${Array.from({length:i+1},(_,j)=>`<i style="--coin:${j}">P</i>`).join('')}</span><b>${number(amount*(100+rate(amount))/100)} P</b><span>${number(amount)}원</span><small>${rate(amount)?`+${rate(amount)}% 보너스 · ${number(amount*rate(amount)/100)}P`:'기본 포인트'}</small></button>`).join('')}</section>
 <section class="module point-panel"><h2>계좌이체로 충전하기</h2>${ready?`<div class="point-bank"><b>${esc(bank.bank)}</b><strong>${esc(bank.account)}</strong><span>예금주 ${esc(bank.holder)}</span></div>`:'<p>충전 계좌를 준비 중입니다. 계좌 등록 후 신청할 수 있습니다.</p>'}${logged?`<form data-point-form="order"><label>충전 상품<select name="amount">${packages.map(n=>`<option value="${n}">${number(n)}원</option>`).join('')}</select></label><label>입금자명<input name="depositor" maxlength="60" required placeholder="실제 이체할 입금자명"></label><input name="requestId" type="hidden" value="${globalThis.crypto?.randomUUID?.()||'req-'+Date.now()+'-'+Math.random().toString(36).slice(2)}"><p data-point-quote>상품을 선택해 주세요.</p><button type="submit" class="point-primary" ${ready?'':'disabled'}>충전 신청</button><p data-form-state role="status"></p></form>`:'<a href="/login" data-layout-route="/login">로그인 후 충전 신청</a>'}<p class="point-note">신청 후 안내된 계좌로 이체해 주세요. 관리자 입금 확인 후 포인트가 지급됩니다. 첫 구매 20%는 최초 승인된 충전에 한 번 적용하며, 여러 신청이 대기 중이면 실제 지급 보너스가 달라질 수 있습니다.</p></section>

 ${bankEditor}
 ${logged?`<section class="module point-panel">${admin?'<details class="point-admin-disclosure"><summary><h2>관리자 · 충전 신청 및 입금 확인</h2><span class="point-admin-show">관리자 보기</span><span class="point-admin-hide">접기</span></summary>':'<h2>내 충전 신청</h2>'}<div class="point-orders">${orders.map(o=>`<article><div><b>${number(o.amount)}원 · ${esc(o.depositor)}</b><small>${esc(o.nickname||'')} · ${new Date(o.createdAt).toLocaleString('ko-KR')}</small><small>신청 계좌: ${esc(o.bank?.bank)} ${esc(o.bank?.account)} · ${esc(o.bank?.holder)}</small><small>신청번호 ${esc(o.id)}</small></div><div><strong>${status[o.status]||esc(o.status)}</strong>${o.status==='approved'?`<p>${number(o.points)}P 지급 · 보너스 ${o.bonus}%</p>`:''}${admin&&o.status==='pending'?`<form data-point-form="review"><input type="hidden" name="id" value="${esc(o.id)}"><label class="point-check"><input type="checkbox" name="confirmed"> ${number(o.amount)}원 입금을 확인했습니다</label><div><button type="submit" name="decision" value="approve">확인·지급</button><button type="submit" name="decision" value="reject">반려</button></div><p data-form-state role="status"></p></form>`:''}</div></article>`).join('')||'<p>충전 신청 내역이 없습니다.</p>'}</div>${admin?'</details>':''}</section><section class="module point-panel"><h2>내 포인트 이용 내역</h2>${[...(wallet.ledger||[])].reverse().map(l=>`<div class="point-ledger"><span>${l.type==='charge'?'충전':'케이지 개설'} · ${new Date(l.at).toLocaleString('ko-KR')}</span><b>${l.points>0?'+':''}${number(l.points)}P</b></div>`).join('')||'<p>이용 내역이 없습니다.</p>'}</section>`:''}</div>`;
}

export function renderDonationCheque(bank={}){
 const ready=!!(bank.bank&&bank.account&&bank.holder);
 return `<section class="module point-panel donation-panel" id="jcs-support"><div class="donation-heading"><span>SUPPORT JEONGCHAMSI</span><h2 tabindex="-1">정참시 후원하기</h2><p>정참시의 내일에, 당신의 마음을 더해주세요.</p></div><div class="donation-cheque"><div class="donation-cheque-top"><b>JEONGCHAMSI</b><span>마음을 담는 백지수표</span></div><div class="donation-cheque-to"><span>받는 곳</span><strong>정참시</strong></div><label class="donation-amount"><span>후원 금액</span><div><span aria-hidden="true">₩</span><input type="text" inputmode="numeric" pattern="[0-9,]*" aria-label="자유 후원 금액" placeholder="원하는 금액을 적어주세요" autocomplete="off"><b>원</b></div></label><div class="donation-cheque-bottom"><span>정해진 금액 없이, 자유롭게</span><b>정치에 참여할 시간</b></div></div><div class="donation-bank"><h3>후원 계좌 안내</h3>${ready?`<div class="point-bank"><b>${esc(bank.bank)}</b><strong>${esc(bank.account)}</strong><span>예금주 ${esc(bank.holder)}</span></div><p>원하는 금액을 위 계좌로 이체해 주세요.</p>`:'<p>후원 계좌를 준비 중입니다. 계좌가 등록되면 이곳에 표시됩니다.'+'</p>'}<small>수표에 금액을 적어도 자동으로 결제되지 않습니다. 후원은 포인트 충전과 별개이며 포인트가 지급되지 않습니다.</small></div></section>`;
}
