import {POLIMARBLE_BOARD as BOARD,POLIMARBLE_CARDS as CARDS} from '../core/polimable-data.js?v=0.0.31.206';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>Number(v||0).toLocaleString('ko-KR');

/*
 * DESIGN SOURCE OF TRUTH: assets/polimable/DESIGN_SOURCE_OF_TRUTH_31_205.webp
 * 24 real movement anchors are pinned to the board perimeter. The art is not
 * reinterpreted: gameplay is layered on top of the approved illustration.
 */
const TRACK_POSITIONS=Object.freeze([
  [16.3,28.4],
  [23.9,27.0],[31.4,27.0],[39.0,27.0],[46.6,27.0],[54.1,27.0],
  [61.5,32.2],[61.5,42.8],[61.5,53.4],[61.5,63.8],[61.5,74.1],[61.5,84.2],
  [54.0,88.0],[46.5,88.0],[39.0,88.0],[31.5,88.0],[24.0,88.0],[16.5,88.0],
  [15.0,76.6],[15.0,66.2],[15.0,55.8],[15.0,45.4],[15.0,37.3],[15.0,31.4]
]);

function mascotHead(size=52){return `<svg width="${size}" height="${size}" viewBox="0 0 72 72" aria-hidden="true"><path d="M19 28c0-16 9-24 20-24 11 0 20 9 20 24-3-3-5-7-7-10-3 4-8 7-15 8-7 1-13 0-18-2z" fill="#6d3c20" stroke="#3b245f" stroke-width="3"/><circle cx="36" cy="31" r="18" fill="#ffdbbf" stroke="#3b245f" stroke-width="3"/><path d="M20 25c2-13 10-20 20-20 11 0 18 8 19 20-6-3-10-8-12-13-5 7-13 11-27 13z" fill="#8b542a"/><circle cx="30" cy="32" r="2.2" fill="#2a163d"/><circle cx="43" cy="32" r="2.2" fill="#2a163d"/><path d="M31 40c3 3 7 3 10 0" fill="none" stroke="#c65a6b" stroke-width="2.2" stroke-linecap="round"/><circle cx="25" cy="37" r="3" fill="#f7a5a7" opacity=".55"/><circle cx="47" cy="37" r="3" fill="#f7a5a7" opacity=".55"/></svg>`;}

function chibiPawn(size=62){return `<svg width="${size}" height="${size}" viewBox="0 0 84 96" aria-label="폴리마블 플레이어" role="img"><defs><linearGradient id="pmHair205" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#9b6231"/><stop offset="1" stop-color="#5a321b"/></linearGradient><linearGradient id="pmJacket205" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f9fbff"/><stop offset="1" stop-color="#dbe7f4"/></linearGradient></defs><ellipse cx="42" cy="89" rx="23" ry="5" fill="rgba(43,26,71,.20)"/><path d="M18 29c0-19 10-27 24-27 15 0 25 10 25 27-5-5-7-10-9-15-4 5-9 9-16 11-7 2-15 3-24 1z" fill="url(#pmHair205)" stroke="#40224d" stroke-width="3"/><path d="M17 24l-7 4 7 5-4 7 8 1 2 8 7-4 6 6 5-7 8 4 3-8 8 1-1-8 7-3-6-6 3-7-8-1-2-8-8 4-6-6-5 7-8-4-3 8-8-1 2 7z" fill="#7b4626" opacity=".96"/><circle cx="42" cy="33" r="19" fill="#ffd9bc" stroke="#40224d" stroke-width="3"/><path d="M25 25c7 2 19-2 28-12 3 7 8 11 12 13" fill="none" stroke="#6a3b22" stroke-width="6" stroke-linecap="round"/><circle cx="35" cy="33" r="2.4" fill="#2d1835"/><circle cx="50" cy="33" r="2.4" fill="#2d1835"/><circle cx="29" cy="39" r="3.2" fill="#f29a9d" opacity=".55"/><circle cx="55" cy="39" r="3.2" fill="#f29a9d" opacity=".55"/><path d="M37 42c3 3 7 3 10 0" fill="none" stroke="#b64f65" stroke-width="2.2" stroke-linecap="round"/><path d="M25 55c6-7 29-7 35 0l7 27H18z" fill="url(#pmJacket205)" stroke="#40224d" stroke-width="3"/><path d="M34 53l8 12 8-12" fill="#486dbd" stroke="#40224d" stroke-width="2"/><path d="M41 61l-4 13 5 5 5-5-4-13z" fill="#e64c59" stroke="#40224d" stroke-width="1.6"/><path d="M18 60l-9 16M66 60l9 16" stroke="#ffd9bc" stroke-width="7" stroke-linecap="round"/><path d="M29 81v10M55 81v10" stroke="#263453" stroke-width="8" stroke-linecap="round"/><path d="M24 91h12M49 91h12" stroke="#2a2440" stroke-width="5" stroke-linecap="round"/></svg>`;}


function boardAnchors(state){return `<div class="pm-start-art" aria-hidden="true"><span>START</span></div><div class="pm-board-anchors" aria-label="JCS 폴리마블 실제 24칸 이동 경로">${BOARD.map((tile,i)=>{const [x,y]=TRACK_POSITIONS[i],hasPlayer=state?.position===i;return `<div class="pm-cell-anchor${hasPlayer?' has-player':''}${state?._moving&&hasPlayer?' is-moving':''}" style="--x:${x}%;--y:${y}%" data-pm-cell="${i}" aria-label="${i===0?'START':`${i}번`} ${esc(tile.title)}">${hasPlayer?`<span class="pm-moving-avatar">${chibiPawn(56)}</span>`:''}</div>`;}).join('')}</div>`;}

function scoreOverlay(state){return `<section class="pm-score-live" aria-label="민심 점수"><span>💗 민심 SCORE</span><strong>${number(state?.score??1000)}</strong><small>👑 최고 기록 ${number(state?.peakScore??1000)}</small></section>`;}

function playControls(state,authenticated,busy,moving){if(!state)return authenticated?`<button type="button" class="pm-hit pm-hit-roll is-start" data-pm-start ${busy?'disabled':''}><span>🎲 GAME START</span></button>`:`<button type="button" class="pm-hit pm-hit-roll is-login" data-pm-login><span>🔐 로그인하고 시작</span></button>`;if(state.status==='playing'&&!state.pendingChoice)return `<button type="button" class="pm-hit pm-hit-roll" data-pm-roll ${busy||moving?'disabled':''}><span>🎲 주사위 굴리기</span></button><button type="button" class="pm-hit pm-hit-continue" data-pm-roll ${busy||moving?'disabled':''} aria-label="계속 도전"></button><button type="button" class="pm-hit pm-hit-record" data-pm-record-open ${busy||moving?'disabled':''} aria-label="기록하고 종료"></button>`;if(state.status==='cashed_out')return `<button type="button" class="pm-hit pm-hit-roll is-start" data-pm-start ${busy?'disabled':''}><span>🎲 다시 도전하기</span></button>`;return '';}

function diceOverlay(state){const dice=state?.lastDice?.length?state.lastDice:[];if(!dice.length)return `<div class="pm-dice-live is-ready">READY</div>`;return `<div class="pm-dice-live" aria-live="polite"><span>🎲 ${dice.join(' + ')}</span><b>= ${dice.reduce((a,b)=>a+b,0)}칸</b></div>`;}
function effects(state){if(!state)return '';const rows=[state.effects?.shieldCharges?`🛡 방어 ${state.effects.shieldCharges}`:'',state.effects?.favorPassTurns?`⭐ 우대 ${state.effects.favorPassTurns}턴`:'',state.effects?.doubleGainTurns?`✨ 2배 ${state.effects.doubleGainTurns}`:'',state.effects?.halfLossTurns?`🧯 반감 ${state.effects.halfLossTurns}`:'',state.effects?.bonusDice?`🎲 추가 ${state.effects.bonusDice}`:'',state.effects?.recordInsuranceRatio?`📜 보험 ${Math.round(state.effects.recordInsuranceRatio*100)}%`:'',state.effects?.doubleOrNothingTurns?`⚡ 승부수 ${state.effects.doubleOrNothingTurns}`:''].filter(Boolean);return rows.length?`<div class="pm-effects-live">${rows.map(x=>`<span>${x}</span>`).join('')}</div>`:'';}

function cards(state,busy){const held=state?.cards||[];return `<section class="pm-card-live" aria-label="전략카드"><header><b>⚡ 전략카드 <small>(보유 ${held.length}/3)</small></b></header><div class="pm-card-live-grid">${Array.from({length:3},(_,idx)=>{const id=held[idx];if(!id)return `<div class="pm-card-slot is-empty"><span>✦</span><b>전략카드</b><small>${idx+1}</small></div>`;const c=CARDS[id];return `<button type="button" class="pm-card-slot rarity-${c.rarity}" data-pm-card="${esc(id)}" ${busy||state?.status!=='playing'||state?.pendingChoice||state?._moving?'disabled':''}><span>${c.icon}</span><b>${esc(c.shortLabel)}</b><em>${esc(c.description)}</em><small>${idx+1}</small></button>`;}).join('')}</div></section>`;}

function ranking(leaderboard,scope){const entries=leaderboard?.entries||[],me=leaderboard?.me;return `<section class="pm-ranking-live" aria-label="폴리마블 랭킹"><header><b>🏆 ${scope==='today'?'TODAY':scope==='week'?'WEEK':'ALL'} RANKING</b><div>${['today','week','all'].map(s=>`<button type="button" data-pm-scope="${s}" class="${scope===s?'active':''}">${s==='today'?'TODAY':s==='week'?'WEEK':'ALL'}</button>`).join('')}</div></header><ol>${entries.slice(0,5).map((e,idx)=>`<li class="${e.isMe?'me':''}"><span><i>${e.rank===1?'👑':e.rank}</i>${idx===0?mascotHead(24):''}<strong>${esc(e.initials||'JCS')}</strong></span><b>${number(e.score)}</b>${e.isMe?'<em>나의 순위!</em>':''}</li>`).join('')||'<li class="pm-rank-empty">첫 기록을 기다리고 있어요!</li>'}</ol>${me&&!entries.some(e=>e.userId===me.userId)?`<div class="pm-my-rank">내 순위 <b>#${me.rank}</b> · ${number(me.score)}</div>`:''}</section>`;}

function status(state,message,busy,moving){const current=state?BOARD[state.position]:BOARD[0];return `<div class="pm-status-live" aria-live="polite"><b>${current.icon} ${esc(current.title)}</b><span>${busy&&!moving?'✨ 처리 중...':esc(message)}</span></div>`;}

function choice(state,busy){if(!state?.pendingChoice)return '';const c=state.pendingChoice;return `<div class="pm-choice-live" role="dialog" aria-label="운명의 선택"><b>⚖️ 운명의 선택</b><p>${esc(c.description)}</p><div><button type="button" data-pm-choice="safe" ${busy?'disabled':''}>🫶 ${esc(c.safeLabel)}</button><button type="button" data-pm-choice="risk" ${busy?'disabled':''}>⚡ ${esc(c.riskLabel)}</button></div></div>`;}

function modal(state,recordMode,busy){if(!state||(state.status!=='game_over'&&!recordMode))return '';const gameOver=state.status==='game_over',recordable=gameOver?Number(state.insuredScore||0):Number(state.score||0);return `<div class="pm-modal" role="dialog" aria-modal="true" aria-label="점수 기록"><div class="pm-modal-card"><div class="pm-modal-avatar">${mascotHead(72)}</div><b>${gameOver?'GAME OVER':'SCORE REGISTER'}</b><p>${gameOver?'오늘의 도전은 여기까지!':'지금 점수를 안전하게 기록할까요?'}</p><div class="pm-final-score">${number(recordable)}</div>${gameOver&&!recordable?'<p class="pm-modal-note">기록 보험이 없어 이번 점수는 랭킹에 남지 않습니다.</p>':''}${(!gameOver||recordable>0)?`<label>이니셜<input data-pm-initials maxlength="3" value="${esc(state.initials||'JCS')}" autocomplete="off"></label><button type="button" class="pm-modal-primary" data-pm-record ${busy?'disabled':''}>🏆 기록하기</button>`:''}${!gameOver?`<button type="button" class="pm-modal-secondary" data-pm-record-cancel ${busy?'disabled':''}>계속 도전</button>`:`<button type="button" class="pm-modal-secondary" data-pm-start ${busy?'disabled':''}>다시 시작</button>`}</div></div>`;}

export function renderPoliMarblePage({session,state=null,leaderboard=null,scope='today',message='주사위를 굴려 정참시의 오늘을 만들어봐요! 💜',recordMode=false,busy=false}={}){
 const authenticated=!!session?.authenticated,moving=state?._moving;
 return `<section class="pm-page"><div class="pm-landscape-note"><b>📱 JCS 폴리마블</b><span>게임은 가로모드에서 플레이해 주세요.</span></div><div class="pm-game-root" data-pm-root data-authenticated="${authenticated?'true':'false'}"><div class="pm-art-stage"><img class="pm-design-source" src="/assets/polimable/DESIGN_SOURCE_OF_TRUTH_31_205.webp" alt="JCS 폴리마블 게임 보드">${boardAnchors(state)}${diceOverlay(state)}${scoreOverlay(state)}${playControls(state,authenticated,busy,moving)}${status(state,message,busy,moving)}${effects(state)}${cards(state,busy)}${ranking(leaderboard,scope)}${choice(state,busy)}${modal(state,recordMode,busy)}</div></div></section>`;
}

export function renderPoliMarbleSidebarCard(data={},session={}){return `<section class="side-card side-polimable"><button type="button" class="pm-side-entry" data-layout-route="/polimable" aria-label="JCS 폴리마블 게임 시작"><img src="/assets/polimable/sidebar-entry-31-204.webp" alt="JCS 폴리마블"><span>GAME START <b>→</b></span></button></section>`;}
