import {POLIMARBLE_BOARD as BOARD,POLIMARBLE_CARDS as CARDS} from '../core/polimable-data.js?v=0.0.31.203';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>Number(v||0).toLocaleString('ko-KR');
const miniAvatar=(size=42)=>`<svg width="${size}" height="${size}" viewBox="0 0 64 64" aria-label="JCS 미니미" role="img"><circle cx="32" cy="23" r="15" fill="#ffd9bd" stroke="#3b245f" stroke-width="2"/><path d="M18 23c0-13 8-18 15-18 10 0 16 7 16 18-4-5-8-7-12-8-5 0-9 3-11 7-2-2-5-2-8 1z" fill="#6b3b24" stroke="#3b245f" stroke-width="2"/><circle cx="27" cy="24" r="1.8" fill="#2a163d"/><circle cx="38" cy="24" r="1.8" fill="#2a163d"/><path d="M29 30c2 2 5 2 7 0" fill="none" stroke="#b34d64" stroke-width="1.8" stroke-linecap="round"/><path d="M21 39c4-4 18-4 22 0l5 17H16z" fill="#f8f7ff" stroke="#3b245f" stroke-width="2"/><path d="M27 38l5 8 5-8" fill="#6c42d8" stroke="#3b245f" stroke-width="1.5"/><path d="M23 42l-7 12M41 42l7 12" stroke="#ffd9bd" stroke-width="5" stroke-linecap="round"/><path d="M25 56v5M39 56v5" stroke="#334155" stroke-width="5" stroke-linecap="round"/></svg>`;

// Approved design의 보드 동선을 그대로 사용하되, 플레이를 위해 24칸으로 촘촘하게 확장.
const VISUAL_POSITIONS=[
 [19.0,27.5,-18],[26.0,29.0,-12],[33.0,30.5,-8],[40.2,32.0,-4],[47.4,34.0,0],[54.7,36.2,4],[62.0,38.8,7],[69.3,42.0,10],
 [75.2,47.0,7],[78.0,54.0,4],[77.0,61.5,0],[72.5,68.0,-5],[65.2,72.5,-7],[57.5,75.8,-5],[49.3,77.2,0],[41.2,75.2,5],
 [34.0,70.5,8],[27.7,64.2,10],[22.5,57.2,8],[18.8,50.0,4],[17.5,43.0,0],[17.0,36.7,-5],[17.6,31.4,-10],[18.4,28.2,-14]
];

const toneFor=kind=>({start:'start',gain:'blue',bonus:'gold',loss:'pink',percent_loss:'pink',strategy_card:'violet',public_card:'mint',choice:'navy',safe:'brown'}[kind]||'blue');
function board(state){
 return `<div class="pm-board-layer" aria-label="JCS 폴리마블 24칸 보드">${BOARD.map((tile,i)=>{const [x,y,r]=VISUAL_POSITIONS[i]||VISUAL_POSITIONS[0],active=state?.position===i;return `<div class="pm-track-tile pm-tone-${toneFor(tile.kind)}${active?' is-active':''}${state?._moving&&active?' is-moving':''}" style="--x:${x}%;--y:${y}%;--r:${r}deg"><span class="pm-track-icon">${tile.icon}</span><b>${esc(tile.title)}</b>${tile.value?`<small>${tile.kind==='loss'||tile.kind==='percent_loss'?'-':'+'}${number(tile.value)}${tile.kind==='percent_loss'?'%':''}</small>`:''}${active?`<span class="pm-moving-avatar">${miniAvatar(44)}</span>`:''}</div>`;}).join('')}</div>`;
}
function dieFace(n){const spots={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]}[n]||[5];return `<span class="pm-die" aria-label="주사위 ${n}">${Array.from({length:9},(_,i)=>`<i class="${spots.includes(i+1)?'on':''}"></i>`).join('')}</span>`;}
function effects(state){if(!state)return '';const rows=[state.effects?.shieldCharges?`🛡 방어 ${state.effects.shieldCharges}`:'',state.effects?.favorPassTurns?`⭐ 우대 ${state.effects.favorPassTurns}턴`:'',state.effects?.doubleGainTurns?`✨ 2배 ${state.effects.doubleGainTurns}`:'',state.effects?.halfLossTurns?`🧯 반감 ${state.effects.halfLossTurns}`:'',state.effects?.bonusDice?`🎲 추가 ${state.effects.bonusDice}`:'',state.effects?.recordInsuranceRatio?`📜 보험 ${Math.round(state.effects.recordInsuranceRatio*100)}%`:'',state.effects?.doubleOrNothingTurns?`⚡ 승부수 ${state.effects.doubleOrNothingTurns}`:''].filter(Boolean);return rows.length?`<div class="pm-effects">${rows.map(x=>`<span>${x}</span>`).join('')}</div>`:'';}
function cards(state,busy){const held=state?.cards||[];return `<section class="pm-card-section"><div class="pm-panel-heading"><b>⚡ 전략카드 <small>(보유 ${held.length}/3)</small></b><span>똑똑한 선택이<br>더 큰 기회를 만듭니다!</span></div><div class="pm-card-grid">${held.map((id,idx)=>{const c=CARDS[id];return `<button type="button" class="pm-strategy-card rarity-${c.rarity}" data-pm-card="${esc(id)}" ${busy||state?.status!=='playing'||state?.pendingChoice||state?._moving?'disabled':''}><span class="pm-card-icon">${c.icon}</span><b>${esc(c.shortLabel)}</b><small>${esc(c.description)}</small><i>${idx+1}</i></button>`;}).join('')}${Array.from({length:Math.max(0,3-held.length)},(_,i)=>`<div class="pm-card-empty"><span>✦</span><small>전략카드</small><i>${held.length+i+1}</i></div>`).join('')}</div></section>`;}
function ranking(leaderboard,scope){const entries=leaderboard?.entries||[],king=entries[0],me=leaderboard?.me;return `<section class="pm-ranking"><div class="pm-panel-heading"><b>🏆 TODAY RANKING</b><span>오늘도 멋진 시민이에요!</span></div><div class="pm-tabs">${['today','week','all'].map(s=>`<button type="button" data-pm-scope="${s}" class="${scope===s?'active':''}">${s==='today'?'TODAY':s==='week'?'WEEK':'ALL'}</button>`).join('')}</div><ol>${entries.slice(0,5).map(e=>`<li class="${e.isMe?'me':''}"><span><i>${e.rank===1?'👑':e.rank}</i><strong>${esc(e.initials||'JCS')}</strong></span><b>${number(e.score)}</b>${e.isMe?'<em>나의 순위!</em>':''}</li>`).join('')||'<li class="pm-rank-empty">첫 왕좌를 기다리고 있어요!</li>'}</ol>${me&&!entries.some(e=>e.userId===me.userId)?`<div class="pm-my-rank">내 순위 <b>#${me.rank}</b> · ${number(me.score)}</div>`:''}${king?`<div class="pm-today-king">👑 <b>${esc(king.initials)}</b> · ${number(king.score)} <span>TODAY KING</span></div>`:''}</section>`;}
function choice(state,busy){if(!state?.pendingChoice)return '';const c=state.pendingChoice;return `<div class="pm-choice"><b>⚖️ 운명의 선택</b><p>${esc(c.description)}</p><div><button type="button" data-pm-choice="safe" ${busy?'disabled':''}>🫶 ${esc(c.safeLabel)}</button><button type="button" data-pm-choice="risk" ${busy?'disabled':''}>⚡ ${esc(c.riskLabel)}</button></div></div>`;}
function modal(state,recordMode,busy){if(!state||(state.status!=='game_over'&&!recordMode))return '';const gameOver=state.status==='game_over',recordable=gameOver?Number(state.insuredScore||0):Number(state.score||0);return `<div class="pm-modal" role="dialog" aria-modal="true" aria-label="점수 기록"><div class="pm-modal-card"><div class="pm-modal-avatar">${miniAvatar(72)}</div><b>${gameOver?'GAME OVER':'SCORE REGISTER'}</b><p>${gameOver?'오늘의 도전은 여기까지!':'지금 점수를 안전하게 기록할까요?'}</p><div class="pm-final-score">${number(recordable)}</div>${gameOver&&!recordable?'<p class="pm-modal-note">기록 보험이 없어 이번 점수는 랭킹에 남지 않습니다.</p>':''}${(!gameOver||recordable>0)?`<label>이니셜<input data-pm-initials maxlength="3" value="${esc(state.initials||'JCS')}" autocomplete="off"></label><button type="button" class="pm-primary" data-pm-record ${busy?'disabled':''}>🏆 기록하기</button>`:''}${!gameOver?`<button type="button" class="pm-secondary" data-pm-record-cancel ${busy?'disabled':''}>계속 도전</button>`:`<button type="button" class="pm-secondary" data-pm-start ${busy?'disabled':''}>다시 시작</button>`}</div></div>`;}

export function renderPoliMarblePage({session,state=null,leaderboard=null,scope='today',message='주사위를 굴려 정참시의 오늘을 만들어봐요! 💜',recordMode=false,busy=false}={}){
 const authenticated=!!session?.authenticated,current=state?BOARD[state.position]:BOARD[0],dice=state?.lastDice?.length?state.lastDice:[5,3],moving=state?._moving;
 const middle=state?.pendingChoice?choice(state,busy):`<div class="pm-status" aria-live="polite"><span>${busy&&!moving?'✨ 처리 중...':esc(message)}</span></div>`;return `<section class="pm-page"><div class="pm-game-root" data-pm-root data-authenticated="${authenticated?'true':'false'}"><div class="pm-art-stage">${board(state)}<aside class="pm-control-panel"><div class="pm-control-top"><section class="pm-dice-box"><div class="pm-panel-heading"><b>🎲 주사위 굴리기</b><span>${state?`${state.turn+1}번째 걸음의 용기가<br>더 나은 정참시를 만듭니다!`:'첫 걸음을 시작해보세요!'}</span></div><div class="pm-dice-row">${dice.map(dieFace).join('')}</div><div class="pm-current-tile">${current.icon} ${esc(current.title)}</div>${!state?(authenticated?`<button type="button" class="pm-primary" data-pm-start ${busy?'disabled':''}>🎲 GAME START</button>`:`<button type="button" class="pm-primary" data-pm-login>🔐 로그인하고 시작</button>`):state.status==='playing'&&!state.pendingChoice?`<button type="button" class="pm-primary" data-pm-roll ${busy||moving?'disabled':''}>🎲 주사위 굴리기</button><button type="button" class="pm-secondary" data-pm-record-open ${busy||moving?'disabled':''}>🏁 기록하고 종료</button>`:state.status==='cashed_out'?`<button type="button" class="pm-primary" data-pm-start ${busy?'disabled':''}>다시 도전하기</button>`:''}</section><section class="pm-score-card"><span>💗 민심 SCORE</span><strong>${number(state?.score??1000)}</strong><small>👑 최고 기록 ${number(state?.peakScore??1000)}</small><em>STAGE ${state?.stage??1}</em></section></div>${middle}${effects(state)}${cards(state,busy)}${ranking(leaderboard,scope)}</aside>${modal(state,recordMode,busy)}</div></div></section>`;
}

export function renderPoliMarbleSidebarCard(data={},session={}){const board=data?.leaderboard||data||{},king=board?.entries?.[0],me=board?.me;return `<section class="side-card side-polimable"><div class="pm-side-art"><div class="pm-side-overlay"><div class="pm-side-heading"><b>🎲 JCS 폴리마블</b><span>TODAY</span></div><div class="pm-side-rank"><span>👑 TODAY KING</span><b>${king?`${esc(king.initials)} · ${number(king.score)}`:'도전자를 기다립니다'}</b></div>${session?.authenticated?`<div class="pm-side-me"><span>내 오늘 기록</span><b>${me?`${number(me.score)} · ${me.rank}위`:'아직 기록 없음'}</b></div>`:''}<button type="button" class="pm-side-start" data-layout-route="/polimable">GAME START <span>→</span></button></div></div></section>`;}
