const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>/^\/assets\/[a-zA-Z0-9_./-]+$/.test(v||'')||/^https:\/\//.test(v||'')?esc(v):'';
const link=(path,label,cls='')=>`<a class="${cls}" href="${path}" data-layout-route="${path}">${label}</a>`;
const issue=p=>String(p.number||1).padStart(2,'0');
const image=p=>`<img src="${safe(p.image)}" alt="${esc(p.title)} · 네 장면의 웹툰" loading="lazy" decoding="async" width="1536" height="1024">`;
const brand='<span class="comic-wordmark">정치<span>4</span>컷<i>JCS TOON</i></span>';
export function renderComicHome(result={}){
 const p=result.items?.[0];
 return `<section class="political-comic-home" id="political-comic"><header>${brand}${link('/political-comic','전체 회차 보기 ↗')}</header>${p?link(`/political-comic/${encodeURIComponent(p.id)}`,`<div class="comic-home-art">${image(p)}<span class="comic-issue">EP. ${issue(p)}</span></div><div class="comic-home-copy"><span class="comic-kicker">${esc(p.category)} · ${esc(p.date)}</span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p><strong>4컷으로 읽기 <span>→</span></strong></div>`,'comic-feature'):`<p class="comic-empty">${result.ok===false?'웹툰을 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.':'다음 이슈를 준비하고 있습니다.'}</p>`}<footer>오늘의 이슈, 네 장면으로 이해하다.</footer></section>`;
}
export function renderComicPage(result={},id=''){
 const list=result.items||[],p=list.find(p=>p.id===id);
 if(id&&!p)return `<section class="comic-page"><h1>${result.ok===false?'웹툰을 불러오지 못했습니다.':'게시된 회차를 찾을 수 없습니다.'}</h1>${link('/political-comic','목록으로 돌아가기')}</section>`;
 if(!id)return `<section class="comic-page"><nav>${link('/','← 정참시 메인')}</nav><header class="comic-page-heading">${brand}<h1>이슈의 맥락을 읽는 네 장면.</h1><p>지금 알아야 할 정치 이슈를, 사실과 출처를 담아 전합니다.</p></header><div class="comic-archive">${list.map(p=>link(`/political-comic/${encodeURIComponent(p.id)}`,`${image(p)}<span class="comic-kicker">EP. ${issue(p)} · ${esc(p.date)}</span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p><b>회차 읽기 →</b>`,'comic-archive-card')).join('')||'<p>게시된 회차가 없습니다.</p>'}</div></section>`;
 return `<article class="comic-page comic-reader"><nav>${link('/political-comic','← 정치4컷 전체 회차')}<span>EP. ${issue(p)}</span></nav><header class="comic-page-heading">${brand}<span class="comic-kicker">${esc(p.category)} · ${esc(p.date)} 기준</span><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p></header><p class="comic-editor-note">보도자료와 보도를 바탕으로 재구성한 AI 웹툰입니다. 인물·장면은 이해를 돕기 위한 삽화이며 실제 현장 사진이 아닙니다.</p><div class="comic-panels">${p.panels.map((panel,i)=>`<figure><div class="comic-panel-art comic-panel-${i}" role="img" aria-label="${esc(panel.alt)}"><img src="${safe(p.image)}" alt="" loading="lazy" decoding="async"></div><figcaption><span class="comic-panel-number">0${i+1}</span><div><h2>${esc(panel.title)}</h2><p>${esc(panel.text)}</p></div></figcaption></figure>`).join('')}</div><section class="comic-takeaway"><span class="comic-kicker">이 이슈의 핵심</span><p>${esc(p.takeaway)}</p></section><section class="comic-sources"><h2>직접 확인할 수 있는 출처</h2><p>${esc(p.date)}까지의 공개 자료를 기준으로 구성했습니다. 이후 발표에 따라 내용이 달라질 수 있습니다.</p><ul>${p.sources.map(s=>`<li><a href="${safe(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label)} ↗</a></li>`).join('')}</ul></section><footer>${link('/political-comic','다른 회차 보기 →','comic-button')}</footer></article>`;
}
export function renderComicAdmin(result={},id=''){
 if(result.ok===false)return '<p role="alert">회차를 불러오지 못했습니다. 새로고침해 주세요.</p>';
 const p=result.items?.find(p=>p.id===id)||{},panels=p.panels||Array.from({length:4},()=>({}));
 const field=(name,label,value='',type='text')=>`<label>${label}<input type="${type}" name="${name}" value="${esc(value)}" required></label>`;
 return `<div class="comic-admin"><section class="comic-admin-list"><h2>등록된 회차</h2>${link('/admin/political-comic','＋ 새 회차 만들기','comic-button')}${(result.items||[]).map(row=>link(`/admin/political-comic?id=${encodeURIComponent(row.id)}`,`<b>EP. ${issue(row)} ${esc(row.title)}</b><span>${row.published?'게시 중':'비공개'}</span>`)).join('')}</section><form data-comic-editor><h2>${p.id?'회차 수정':'새 정치4컷'}</h2><input type="hidden" name="id" value="${esc(p.id)}"><input type="hidden" name="updatedAt" value="${esc(p.updatedAt)}">${field('title','제목',p.title)}${field('category','주제',p.category||'정치 이슈')}${field('date','내용 기준일',p.date||new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),'date')}<label>소개<textarea name="summary" maxlength="300">${esc(p.summary)}</textarea></label><fieldset><legend>4컷 원화</legend><p>왼쪽 위 → 오른쪽 위 → 왼쪽 아래 → 오른쪽 아래 순서의 2×2 이미지 한 장. 권장 1536×1024px, JPG·PNG·WebP, 1MB 이하. 컷 사이 여백 없이 같은 크기로 제작하세요.</p><label>이미지 업로드<input type="file" data-comic-upload accept="image/jpeg,image/png,image/webp"></label>${field('image','이미지 주소',p.image)}<img data-comic-preview src="${safe(p.image)}" alt="등록 이미지 미리보기" ${p.image?'':'hidden'}></fieldset>${panels.map((q,i)=>`<fieldset><legend>${i+1}컷</legend>${field(`title${i}`,'장면 제목',q.title)}<label>설명<textarea name="text${i}" maxlength="600" required>${esc(q.text)}</textarea></label>${field(`alt${i}`,'그림 설명 (접근성)',q.alt)}</fieldset>`).join('')}<label>핵심 요약<textarea name="takeaway" maxlength="1000">${esc(p.takeaway)}</textarea></label><label>출처 (한 줄에 이름 | https://주소)<textarea name="sources" required rows="4">${esc((p.sources||[]).map(s=>`${s.label} | ${s.url}`).join('\n'))}</textarea></label><label class="comic-publish"><input name="published" type="checkbox" ${p.published?'checked':''}> 메인과 목록에 공개</label><button class="comic-button" type="submit">저장하기</button><p data-comic-status role="status" aria-live="polite"></p></form></div>`;
}
