const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const TYPES=Object.freeze({assembly:{label:'국회의원',count:300},metropolitan:{label:'광역단체장',count:16},basic:{label:'기초단체장',count:227}});
const empty=()=>'<span class="info-empty" aria-label="추가 데이터 준비중"></span>';
const value=text=>text?esc(text):empty();

function photoMarkup(item,className='person-photo-placeholder',size=160){
  const photo=item?.photo,src=String(photo?.localPath||'');
  if(!src)return `<div class="${className}"></div>`;
  return `<div class="${className} has-photo" style="--photo-position:${esc(photo.focus||'50% 28%')}"><img data-politician-photo src="${esc(src)}" alt="" width="${size}" height="${size}" loading="lazy" decoding="async"></div>`;
}
function card(item){
  const type=TYPES[item.type]||TYPES.assembly,meta=[item.party,item.jurisdiction].filter(Boolean).join(' · '),short=item.type==='assembly'?(item.terms||item.committee):(item.office||item.roleLabel);
  return `<button type="button" class="person-slot-card data-connected now-category-card${item.isVacant?' is-vacant':''}" data-layout-route="/person/${esc(item.id)}" aria-label="${esc(item.name)} 상세페이지"><span class="slot-no now-category-card-rank">${item.isVacant?'공석':`SLOT ${String(item.slot).padStart(3,'0')}`}</span>${photoMarkup(item)}<span class="slot-lines"><b class="slot-data-name">${esc(item.name)}</b><span class="slot-data-meta">${esc(meta)}</span><span class="slot-data-short">${esc(short)}</span><span class="now-category-card-meta"><b>집계 준비 중</b><em>${esc(type.label)} NOW 데이터 미반영</em></span></span></button>`;
}
export async function renderPoliticianDirectory(service,route='/now'){
  const query=new URLSearchParams(String(route).split('?')[1]||''),type=TYPES[query.get('type')]?query.get('type'):'assembly',offset=Math.max(0,Number(query.get('offset')||0)||0),limit=30;
  const result=await service.list(type,offset,limit),meta=TYPES[type];
  if(!result?.ok)return `<main class="subpage now-directory-page"><section class="page-hero"><span class="eyebrow">NOW RANK · CATEGORY LEAGUE</span><h1>NOW Rank · 분야별 순위</h1><p>정치인 DB 연결을 준비하고 있습니다.</p></section><section class="content-card"><div class="empty-state tall"><h2>정치인 데이터가 아직 이관되지 않았습니다</h2><p>${esc(result?.error||'POLITICIAN_DB_MISSING')}</p></div></section></main>`;
  const rows=Array.isArray(result.items)?result.items:[],total=Number(result.total||0),shownEnd=Math.min(total,offset+rows.length);
  const tabs=Object.entries(TYPES).map(([key,item])=>`<button type="button" class="${type===key?'active':''}" data-layout-route="/now?type=${key}"><b>${item.label}</b><span>${item.count}개 슬롯</span></button>`).join('');
  const pager=`<div class="politician-directory-pager">${offset>0?`<button class="ghost-btn" type="button" data-layout-route="/now?type=${type}&offset=${Math.max(0,offset-limit)}">이전 30명</button>`:''}<span>${total?`${offset+1}–${shownEnd} / ${total}`:'0명'}</span>${result.hasMore?`<button class="primary-btn" type="button" data-layout-route="/now?type=${type}&offset=${offset+limit}">다음 30명</button>`:''}</div>`;
  return `<main class="subpage now-directory-page"><section class="page-hero"><span class="eyebrow">NOW RANK · CATEGORY LEAGUE</span><h1>NOW Rank · 분야별 순위</h1><p>메인 TOP10은 전체 정치인 통합 순위입니다. 전체보기에서는 국회의원·광역단체장·기초단체장별로 같은 NOW 점수를 다시 정렬해 각 분야의 독립 순위를 보여줍니다</p><div class="capacity-line"><span>국회의원 300개 슬롯 · 광역단체장 16명 · 기초단체장 227명</span><b>현재 ${total}개 슬롯</b></div></section><nav class="now-category-tabs" aria-label="정치인 분류">${tabs}</nav><section class="content-card directory-section"><div class="section-title"><h2>${esc(meta.label)}</h2><span>${rows.length} / ${total}개 표시</span></div>${rows.length?`<div class="person-grid now-category-card-grid">${rows.map(card).join('')}</div>`:'<div class="empty-state"><h2>등록된 정치인 프로필이 없습니다</h2></div>'}${pager}</section></main>`;
}
function basicInfo(item){return `<dl class="info-list"><div><dt>이름</dt><dd>${value(item.name)}</dd></div><div><dt>현재 직책</dt><dd>${value(item.office||item.roleLabel)}</dd></div><div><dt>정당</dt><dd>${value(item.party)}</dd></div><div><dt>${esc(item.jurisdictionLabel||'지역')}</dt><dd>${value(item.jurisdiction)}</dd></div><div><dt>구분</dt><dd>${value(item.terms)}</dd></div><div><dt>사진</dt><dd>${item.photo?.localPath?'프로필 사진 연결':'등록된 사진 없음'}</dd></div></dl>`;}
function electionInfo(item){const term=item.termStart||item.termEnd?`${item.termStart||'—'} ~ ${item.termEnd||'—'}`:'';return `<dl class="info-list"><div><dt>현 임기</dt><dd>${value(term)}</dd></div><div><dt>${item.type==='assembly'?'선수':'민선'}</dt><dd>${value(item.terms)}</dd></div><div><dt>최근 선거</dt><dd>${value(item.electionLabel)}</dd></div><div><dt>정당</dt><dd>${value(item.party)}</dd></div><div><dt>${item.type==='assembly'?'소속 위원회':'관할 지역'}</dt><dd>${value(item.type==='assembly'?item.committee:item.jurisdiction)}</dd></div></dl>`;}
function timeline(item){const rows=[];if(item.electionLabel)rows.push([item.type==='assembly'?'2024':'2026',item.electionLabel,item.jurisdiction]);if(item.type==='assembly'&&item.terms)rows.push(['현재',item.terms,'국회의원 당선 횟수 기준']);if(item.type==='assembly'&&item.committee)rows.push(['현재',item.committee,'국회 공개정보 기반']);if(item.type!=='assembly')rows.push(['2026.07.01','민선 9기 임기 시작',item.office||item.roleLabel]);return rows.map(([year,title,sub])=>`<div class="timeline-row live"><span class="timeline-year">${esc(year)}</span><div class="timeline-copy"><b>${esc(title)}</b><span>${esc(sub)}</span></div></div>`).join('')||'<div class="timeline-row"><span class="timeline-year"></span><div class="timeline-copy"><i></i><i></i></div></div>';}
export async function renderPoliticianDetail(id,service){
  const result=await service.get(id);if(!result?.ok)return `<main class="subpage"><section class="content-card empty-state tall"><div class="empty-icon">?</div><h2>존재하지 않는 정치인입니다</h2><button class="primary-btn" type="button" data-layout-route="/now">전체 정치인</button></section></main>`;
  const item=result.item,activityTitle=item.type==='assembly'?'의정활동':'행정활동',photo=item.photo?.localPath?`<div class="person-detail-photo has-photo" style="--photo-position:${esc(item.photo.focus||'50% 28%')}"><img data-politician-photo src="${esc(item.photo.localPath)}" alt="" width="384" height="384" loading="eager" decoding="async"></div>`:'<div class="person-detail-photo"></div>',photoSource=item.photo?.sourcePage?` · 사진 출처: ${esc(item.photo.sourcePage)}`:'';
  return `<main class="subpage person-live-detail-page"><section class="person-detail-hero person-live-hero content-card">${photo}<div class="person-detail-title"><span class="eyebrow">${esc(item.roleLabel)} · LIVE PROFILE</span><h1>${esc(item.name)}</h1><p class="person-current-role">${esc(item.office||item.roleLabel)}</p><p>${esc([item.party,item.jurisdiction].filter(Boolean).join(' · '))}</p><div class="person-detail-badges"><span>${esc(item.roleLabel)}</span><span>${esc(item.terms||'기본정보')}</span><span>${esc(item.type==='assembly'?(item.committee||'국회의원'):item.jurisdiction)}</span></div></div><div class="detail-action-bar"><button class="ghost-btn" type="button" data-layout-route="/now?type=${esc(item.type)}">목록으로</button></div></section><section class="person-profile-divider"><span>PROFILE & RECORD</span><b>공식 프로필과 정치 기록</b></section><div class="detail-grid"><section class="content-card"><div class="section-title"><h2>기본정보</h2><span>공개 프로필</span></div>${basicInfo(item)}</section><section class="content-card"><div class="section-title"><h2>선거·임기</h2><span>공식 기록</span></div>${electionInfo(item)}</section></div><section class="content-card"><div class="section-title"><h2>정치 기록</h2><span>기존 공식 프로필 기록</span></div><div class="timeline-shell">${timeline(item)}</div></section><section class="content-card"><div class="section-title"><h2>${activityTitle}</h2><span>공식 데이터 순차 확장</span></div><dl class="info-list"><div><dt>${item.type==='assembly'?'소속 위원회':'관할 지역'}</dt><dd>${value(item.type==='assembly'?item.committee:item.jurisdiction)}</dd></div><div><dt>주요 활동</dt><dd>${empty()}</dd></div><div><dt>주요 성과</dt><dd>${empty()}</dd></div></dl></section><section class="content-card"><div class="notice-box">기본 텍스트 출처: ${esc(item.source||'기존 정참시 공식 프로필')}${photoSource}</div></section></main>`;
}
