const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>/^\/assets\/[a-zA-Z0-9_./-]+$/.test(v||'')||/^https:\/\//.test(v||'')?esc(v):'';
const link=(path,label,cls='')=>`<a class="${cls}" href="${path}" data-layout-route="${path}">${label}</a>`;
const issue=p=>String(p.number||1).padStart(2,'0');
const image=p=>`<img src="${safe(p.coverImage||p.image)}" alt="${esc(p.title)} · 네 장면의 웹툰" loading="lazy" decoding="async" width="1536" height="1024">`;
const brand='<span class="comic-wordmark">정치<span>4</span>컷<i>JCS TOON</i></span>';
export function renderComicHome(result={}){
 const p=result.items?.[0];
 return `<section class="political-comic-home" id="political-comic"><header>${brand}${link('/political-comic','전체 회차 보기 ↗')}</header>${p?link(`/political-comic/${encodeURIComponent(p.id)}`,`<div class="comic-home-art">${image(p)}<span class="comic-issue">EP. ${issue(p)}</span></div><div class="comic-home-copy"><span class="comic-kicker">${esc(p.category)} · ${esc(p.date)}</span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p><strong>4컷으로 읽기 <span>→</span></strong></div>`,'comic-feature'):`<p class="comic-empty">${result.ok===false?'웹툰을 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.':'다음 이슈를 준비하고 있습니다.'}</p>`}<footer>오늘의 이슈, 네 장면으로 이해하다.</footer></section>`;
}
export function renderComicPage(result={},id=''){
 const list=result.items||[],p=list.find(p=>p.id===id);
 if(id&&!p)return '<section class="comic-page"><h1>회차를 찾을 수 없습니다.</h1>'+link('/political-comic','목록으로 돌아가기')+'</section>';
 if(!id)return '<section class="comic-page comic-library"><nav>'+link('/','← 정참시 메인')+'</nav><header class="comic-page-heading">'+brand+'<h1>오늘의 이슈를, 한 편의 만화로.</h1></header><div class="comic-archive">'+list.map(p=>link('/political-comic/'+encodeURIComponent(p.id),'<div class="comic-cover">'+image(p)+'</div><div><span class="comic-kicker">EP. '+issue(p)+' · '+esc(p.date)+'</span><h2>'+esc(p.title)+'</h2><b>읽기 →</b></div>','comic-archive-card')).join('')+'</div></section>';
 const panels=p.panels.map((panel,i)=>'<figure><div class="comic-panel-art comic-panel-'+i+'" role="img" aria-label="'+esc(panel.title+'. '+panel.text)+'"><img src="'+safe(p.image)+'" alt="" loading="lazy" decoding="async"></div></figure>').join('');
 return '<article class="comic-page comic-reader"><nav>'+link('/political-comic','← 전체 회차')+'<span>EP. '+issue(p)+'</span></nav><header class="comic-page-heading">'+brand+'<h1>'+esc(p.title)+'</h1><span class="comic-kicker">'+esc(p.date)+' 기준 · '+esc(p.category)+'</span></header><div class="comic-panels comic-manuscript '+(p.format==='comic'?'comic-square':'')+'">'+panels+'</div><p class="comic-editor-note">공개 보도를 바탕으로 재구성한 AI 만화입니다. 등장인물과 대사는 설명을 위한 창작이며 실제 인물의 발언이 아닙니다.</p><details class="comic-sources"><summary>출처와 내용 확인</summary><p>'+esc(p.date)+' 공개 자료 기준</p><ul>'+p.sources.map(s=>'<li><a href="'+safe(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.label)+' ↗</a></li>').join('')+'</ul><details><summary>텍스트로 읽기</summary>'+(p.transcript?'<p class="comic-transcript">'+esc(p.transcript)+'</p>':p.panels.map(q=>'<p><b>'+esc(q.title)+'</b><br>'+esc(q.text)+'</p>').join(''))+'</details></details><footer>'+link('/political-comic','다른 회차 보기 →','comic-button')+'</footer></article>';
}
export function renderComicAdmin(result={},id=''){
 if(result.ok===false)return '<p role="alert">회차를 불러오지 못했습니다. 새로고침해 주세요.</p>';
 const p=result.items?.find(p=>p.id===id)||{};
 const field=(name,label,value='',required=true)=>'<label>'+label+'<input name="'+name+'" value="'+esc(value)+'" '+(required?'required':'')+'></label>';
 const upload=(key,label,value='')=>'<fieldset class="comic-upload-block"><legend>'+label+'</legend><label class="comic-upload-pick">이미지 선택<input type="file" data-comic-upload="'+key+'" accept="image/jpeg,image/png,image/webp"></label><input type="hidden" name="'+key+'" value="'+esc(value)+'"><img data-comic-preview="'+key+'" src="'+safe(value)+'" alt="'+label+' 미리보기" '+(value?'':'hidden')+'><p>'+(key==='image'?'말풍선·내레이션이 포함된 2×2 완성 만화 한 장. 정사각형 원고를 사용하세요. 권장 1536×1536px.':'선택 항목입니다. 등록하지 않으면 원고를 표지로 사용합니다.')+' JPG·PNG·WebP, 1MB 이하.</p></fieldset>';
 const transcript=p.transcript||(p.panels||[]).map(q=>q.title+'\n'+q.text).join('\n\n');
 return '<div class="comic-admin"><section class="comic-admin-list"><h2>회차 관리</h2>'+link('/admin/political-comic','＋ 새 회차','comic-button')+(result.items||[]).map(row=>link('/admin/political-comic?id='+encodeURIComponent(row.id),'<b>EP. '+issue(row)+' '+esc(row.title)+'</b><span>'+(row.published?'게시 중':'비공개')+'</span>')).join('')+'</section><form data-comic-editor><header><h2>'+(p.id?'회차 수정':'새 정치4컷')+'</h2><p>완성된 만화 원고를 올리고 게시 정보를 입력하세요.</p></header><input type="hidden" name="format" value="comic"><input type="hidden" name="id" value="'+esc(p.id)+'"><input type="hidden" name="updatedAt" value="'+esc(p.updatedAt)+'"><fieldset><legend>01 · 게시 정보</legend>'+field('title','회차 제목',p.title)+field('category','주제',p.category||'정치 이슈')+'<label>내용 기준일<input type="date" name="date" required value="'+esc(p.date||new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}))+'"></label></fieldset>'+upload('image','02 · 완성 만화 원고',p.image)+upload('coverImage','03 · 목록 표지 (선택)',p.coverImage)+'<details class="comic-optional"><summary>텍스트 대본 · 접근성 (선택)</summary><p>만화 속 글을 읽기 어려운 독자를 위한 대본입니다. 공개 화면에서는 펼쳐서 읽습니다.</p><label>전체 대본<textarea name="transcript" maxlength="5000" rows="8">'+esc(transcript)+'</textarea></label></details><fieldset><legend>04 · 출처와 공개</legend><label>출처 (한 줄에 자료 이름 | https://주소)<textarea name="sources" required rows="4">'+esc((p.sources||[]).map(q=>q.label+' | '+q.url).join('\n'))+'</textarea></label><label class="comic-publish"><input name="published" type="checkbox" '+(p.published?'checked':'')+'> 메인과 회차 목록에 공개</label></fieldset><button class="comic-button" type="submit">저장하기</button><p data-comic-status role="status" aria-live="polite"></p><a data-comic-public-link '+(p.id?'href="/political-comic/'+encodeURIComponent(p.id)+'"':'hidden')+' target="_blank" rel="noopener">공개 회차 보기 ↗</a></form></div>';
}
