import {POLIMARBLE_BOARD as BOARD,POLIMARBLE_CARDS as CARDS,POLIMARBLE_BOARD_POSITIONS as POSITIONS} from '../core/polimable-data.js?v=0.0.31.202';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>Number(v||0).toLocaleString('ko-KR');
const diceFaces=['⚀','⚁','⚂','⚃','⚄','⚅'];
const miniAvatar=(size=46,variant='brown')=>{
  const hair=variant==='dark'?['#2b2846','#151226']:variant==='gold'?['#8b5d14','#57380e']:['#8a552b','#5b371c'];
  const jacket=variant==='dark'?'#ff6d79':variant==='gold'?'#f9cf62':'#6d57e4';
  return `<svg width="${size}" height="${size}" viewBox="0 0 64 64" aria-label="JCS 미니미" role="img"><defs><linearGradient id="hair-${variant}-${size}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${hair[0]}"/><stop offset="1" stop-color="${hair[1]}"/></linearGradient></defs><circle cx="32" cy="23" r="15" fill="#ffd9bd" stroke="#3b245f" stroke-width="2"/><path d="M18 23c0-13 8-18 15-18 10 0 16 7 16 18-4-5-8-7-12-8-5 0-9 3-11 7-2-2-5-2-8 1z" fill="url(#hair-${variant}-${size})" stroke="#3b245f" stroke-width="2"/><circle cx="27" cy="24" r="1.8" fill="#2a163d"/><circle cx="38" cy="24" r="1.8" fill="#2a163d"/><path d="M29 30c2 2 5 2 7 0" fill="none" stroke="#b34d64" stroke-width="1.8" stroke-linecap="round"/><path d="M21 39c4-4 18-4 22 0l5 17H16z" fill="#f8f7ff" stroke="#3b245f" stroke-width="2"/><path d="M27 38l5 8 5-8" fill="${jacket}" stroke="#3b245f" stroke-width="1.5"/><path d="M23 42l-7 12M41 42l7 12" stroke="#ffd9bd" stroke-width="5" stroke-linecap="round"/><path d="M25 56v5M39 56v5" stroke="#334155" stroke-width="5" stroke-linecap="round"/></svg>`;
};

function sceneSigns(){
  return `<div class="pm-scene-sign pm-scene-left">작은 한 걸음이<br><b>큰 변화를 만드는 Jeongchamsi!</b></div>
  <div class="pm-scene-sign pm-scene-top">국민의<br>목소리가<br>세상을 바꿉니다</div>
  <div class="pm-scene-sign pm-scene-right">함께하는 정책,<br>행복한 정참시</div>
  <div class="pm-scene-speech pm-scene-bottom-left">오늘도<br>더 나은 정참시를 위해! 💗</div>
  <div class="pm-scene-speech pm-scene-bottom-right">함께 만드는 내일 💛</div>`;
}

function board(state){
  return `<div class="pm-board-scene">${sceneSigns()}<div class="pm-board" aria-label="JCS 폴리마블 보드">${BOARD.map((tile,i)=>{const [row,col]=POSITIONS[i],active=state?.position===i,moving=!!state?._moving;return `<div class="pm-tile pm-kind-${tile.kind}${active?' is-active':''}${moving&&active?' is-moving':''}" style="--pm-row:${row};--pm-col:${col}"><span class="pm-tile-icon">${tile.icon}</span><b>${esc(tile.title)}</b>${tile.value?`<small>${tile.kind==='loss'||tile.kind==='percent_loss'?'-':'+'}${number(tile.value)}${tile.kind==='percent_loss'?'%':''}</small>`:''}${active?`<span class="pm-avatar">${miniAvatar(44,'brown')}</span>`:''}</div>`;}).join('')}<div class="pm-center"><div class="pm-center-park"></div><div class="pm-center-building"><span class="pm-dome"></span><span class="pm-body"></span></div><div class="pm-center-garden"></div><strong>정참시</strong><p>작은 한 걸음이<br>큰 변화를 만듭니다.</p><div class="pm-score-big">${number(state?.score??1000)}</div><small>민심 SCORE</small></div><div class="pm-board-char pm-char-top">${miniAvatar(58,'brown')}</div><div class="pm-board-char pm-char-bottom">${miniAvatar(58,'dark')}</div></div><div class="pm-board-footer"><span>💗 JCS 폴리마블</span><small>시민의 생각이 모여, 더 나은 정참시를 만듭니다.</small></div></div>`;
}
function effects(state){if(!state)return '';const rows=[state.effects?.shieldCharges?`🛡 방어 ${state.effects.shieldCharges}`:'',state.effects?.favorPassTurns?`⭐ 우대 ${state.effects.favorPassTurns}턴`:'',state.effects?.doubleGainTurns?`✨ 2배 ${state.effects.doubleGainTurns}`:'',state.effects?.halfLossTurns?`🧯 반감 ${state.effects.halfLossTurns}`:'',state.effects?.bonusDice?`🎲 추가 ${state.effects.bonusDice}`:'',state.effects?.recordInsuranceRatio?`📜 보험 ${Math.round(state.effects.recordInsuranceRatio*100)}%`:'',state.effects?.doubleOrNothingTurns?`⚡ 승부수 ${state.effects.doubleOrNothingTurns}`:''].filter(Boolean);return rows.length?`<div class="pm-effects">${rows.map(x=>`<span>${x}</span>`).join('')}</div>`:'';}
function cards(state,busy){const held=state?.cards||[];return `<div class="pm-card-section"><div class="pm-section-title"><div><b>⚡ 전략카드</b><small>똑똑한 선택이 더 큰 기회를 만듭니다!</small></div><span>보유 ${held.length}/3</span></div><div class="pm-card-grid">${held.map((id,idx)=>{const c=CARDS[id];return `<button type="button" class="pm-strategy-card rarity-${c.rarity}" data-pm-card="${esc(id)}" ${busy||state?.status!=='playing'||state?.pendingChoice||state?._moving?'disabled':''}><span class="pm-card-icon">${c.icon}</span><b>${esc(c.shortLabel)}</b><small>${esc(c.description)}</small><i>${idx+1}</i></button>`;}).join('')}${Array.from({length:Math.max(0,3-held.length)},(_,i)=>`<div class="pm-card-empty"><span>✦</span><small>전략카드</small><i>${held.length+i+1}</i></div>`).join('')}</div></div>`;}
function ranking(leaderboard,scope){const entries=leaderboard?.entries||[],king=entries[0],me=leaderboard?.me;return `<div class="pm-ranking"><div class="pm-section-title"><div><b>🏆 TODAY RANKING</b><small>오늘도 멋진 시민이에요!</small></div>${king?`<span class="pm-king-mini">👑 ${esc(king.initials)} ${number(king.score)}</span>`:''}</div><div class="pm-tabs">${['today','week','all'].map(s=>`<button type="button" data-pm-scope="${s}" class="${scope===s?'active':''}">${s==='today'?'TODAY':s==='week'?'WEEK':'ALL'}</button>`).join('')}</div><ol>${entries.slice(0,5).map((e,idx)=>`<li class="${e.isMe?'me':''}"><span><i>${e.rank===1?'👑':e.rank}</i>${idx===0?miniAvatar(30,'brown'):miniAvatar(28,idx===3?'dark':'gold')}<strong>${esc(e.initials||'JCS')}</strong></span><b>${number(e.score)}</b>${e.isMe?'<em>나의 순위!</em>':''}</li>`).join('')||'<li class="pm-rank-empty">아직 기록이 없습니다. 첫 왕좌에 도전해보세요!</li>'}</ol>${me&&!entries.some(e=>e.userId===me.userId)?`<div class="pm-my-rank">내 순위 <b>#${me.rank}</b> · ${number(me.score)}</div>`:''}</div>`;}
function choice(state,busy){if(!state?.pendingChoice)return '';const c=state.pendingChoice;return `<div class="pm-choice"><b>⚖️ 운명의 선택</b><p>${esc(c.description)}</p><div><button type="button" data-pm-choice="safe" ${busy?'disabled':''}>🫶 ${esc(c.safeLabel)}</button><button type="button" data-pm-choice="risk" ${busy?'disabled':''}>⚡ ${esc(c.riskLabel)}</button></div></div>`;}
function modal(state,recordMode,busy){if(!state||(state.status!=='game_over'&&!recordMode))return '';const gameOver=state.status==='game_over',recordable=gameOver?Number(state.insuredScore||0):Number(state.score||0);return `<div class="pm-modal" role="dialog" aria-modal="true" aria-label="점수 기록"><div class="pm-modal-card"><div class="pm-modal-avatar">${miniAvatar(72,'brown')}</div><b>${gameOver?'GAME OVER':'SCORE REGISTER'}</b><p>${gameOver?'오늘의 도전은 여기까지!':'지금 점수를 안전하게 기록할까요?'}</p><div class="pm-final-score">${number(recordable)}</div>${gameOver&&!recordable?'<p class="pm-modal-note">기록 보험이 없어 이번 점수는 랭킹에 남지 않습니다.</p>':''}${(!gameOver||recordable>0)?`<label>이니셜<input data-pm-initials maxlength="3" value="${esc(state.initials||'JCS')}" autocomplete="off"></label><button type="button" class="pm-primary" data-pm-record ${busy?'disabled':''}>🏆 기록하기</button>`:''}${!gameOver?`<button type="button" class="pm-secondary" data-pm-record-cancel ${busy?'disabled':''}>계속 도전</button>`:`<button type="button" class="pm-secondary" data-pm-start ${busy?'disabled':''}>다시 시작</button>`}</div></div>`;}

export function renderPoliMarblePage({session,state=null,leaderboard=null,scope='today',message='주사위를 굴려 정참시의 오늘을 만들어봐요! 💜',recordMode=false,busy=false}={}){const authenticated=!!session?.authenticated,current=state?BOARD[state.position]:BOARD[0],dice=state?.lastDice?.length?state.lastDice.map(n=>diceFaces[n-1]||'⚄').join(' '):'⚄ ⚂',moving=state?._moving;return `<section class="pm-page"><div class="pm-page-clouds" aria-hidden="true"><i></i><i></i><i></i></div><div class="pm-game-root" data-pm-root data-authenticated="${authenticated?'true':'false'}"><header class="pm-hero"><div class="pm-logo-wrap"><span class="pm-logo-jcs">JCS</span><strong>폴리마블</strong><small>시민과 함께, 더 나은 내일로!</small></div><div class="pm-hero-bubble">${miniAvatar(60,'brown')}<span>주사위를 굴려<br><b>정참시의 오늘</b>을 만들어봐요! ♡</span></div><div class="pm-hero-icons"><button type="button" disabled aria-hidden="true">🔊</button><button type="button" disabled aria-hidden="true">❔</button><button type="button" disabled aria-hidden="true">⚙️</button></div></header><div class="pm-shell"><div class="pm-board-wrap">${board(state)}</div><aside class="pm-panel"><div class="pm-top-row"><div class="pm-dice-box"><div class="pm-console-title"><b>🎲 주사위 굴리기</b><small>${state?`${state.turn+1}번째 걸음의 용기가 더 나은 정참시를 만듭니다!`:'첫 걸음을 시작해보세요!'}</small></div><div class="pm-dice">${dice}</div><div class="pm-current-tile">${current.icon} ${esc(current.title)}</div>${!state?(authenticated?`<button type="button" class="pm-primary" data-pm-start ${busy?'disabled':''}>🎲 GAME START</button>`:`<button type="button" class="pm-primary" data-pm-login>🔐 로그인하고 시작</button>`):state.status==='playing'&&!state.pendingChoice?`<button type="button" class="pm-primary" data-pm-roll ${busy||moving?'disabled':''}>🎲 주사위 굴리기</button><button type="button" class="pm-secondary" data-pm-record-open ${busy||moving?'disabled':''}>🏁 기록하고 종료</button>`:state.status==='cashed_out'?`<button type="button" class="pm-primary" data-pm-start ${busy?'disabled':''}>다시 도전하기</button>`:''}</div><div class="pm-score-card"><span>💗 민심 SCORE</span><strong>${number(state?.score??1000)}</strong><small>👑 최고 기록 ${number(state?.peakScore??1000)}</small><em>STAGE ${state?.stage??1}</em></div></div>${choice(state,busy)}<div class="pm-status" aria-live="polite"><span>${busy&&!moving?'✨ 처리 중...':esc(message)}</span></div>${effects(state)}${cards(state,busy)}${ranking(leaderboard,scope)}</aside></div>${modal(state,recordMode,busy)}</div></section>`;}

export function renderPoliMarbleSidebarCard(data={},session={}){const board=data?.leaderboard||data||{},king=board?.entries?.[0],me=board?.me;return `<section class="side-card side-polimable"><div class="pm-side-sky"><span class="pm-side-star">★</span><div class="pm-side-brand"><small>JCS</small><b>폴리마블</b></div><div class="pm-side-mini">${miniAvatar(48,'brown')}</div></div><div class="pm-side-copy"><div class="pm-side-heading"><b>🎲 오늘도 한 판!</b><span>TODAY</span></div><p>귀여운 미니미와 함께 민심 점수를 쌓아보세요.</p><div class="pm-side-king"><span>👑 TODAY KING</span><b>${king?`${esc(king.initials)} · ${number(king.score)}`:'첫 왕좌를 기다리는 중'}</b></div>${session?.authenticated?`<div class="pm-side-me"><span>내 오늘 기록</span><b>${me?`${number(me.score)} · ${me.rank}위`:'아직 기록 없음'}</b></div>`:''}<button type="button" class="pm-side-start" data-layout-route="/polimable">${session?.authenticated?'GAME START':'게임 구경하기'} <span>→</span></button></div></section>`;}
