import { GOVERNMENT_SEED } from '../data/government-seed.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const matches=(item,term)=>`${item?.title||''} ${item?.summary||''} ${item?.body||''} ${item?.author||''} ${item?.question||''}`.toLocaleLowerCase('ko-KR').includes(term.toLocaleLowerCase('ko-KR'));
const routeFor=(domain,id)=>domain==='columns'?`/column/${id}`:domain==='community'?`/community/${id}`:`/${domain}/${id}`;
export async function renderSearchPage({query='',politicians,content}={}){
  const term=String(query||'').trim();
  if(!term)return `<main class="subpage search-page"><section class="page-hero"><span class="eyebrow">SEARCH · INTEGRATED</span><h1>통합검색</h1><p>정치인 이름·정당·지역·정책·게시글을 한 번에 검색합니다.</p></section><section class="content-card"><div class="schedule-empty">검색어를 입력해 주세요</div></section></main>`;
  const [peopleResult,columns,community,itsme,polls,generation,national]=await Promise.all([
    politicians.search(term,12).catch(()=>({items:[],total:0})),content.list('columns').catch(()=>[]),content.list('community').catch(()=>[]),content.list('itsme').catch(()=>[]),content.readDomain('polls').catch(()=>({items:[]})),content.readDomain('generation').catch(()=>({})),content.readDomain('nationalEvaluation').catch(()=>({}))
  ]);
  const people=peopleResult?.items||[],governmentText=[GOVERNMENT_SEED.profile.name,GOVERNMENT_SEED.profile.office,GOVERNMENT_SEED.vision,...GOVERNMENT_SEED.policies,...GOVERNMENT_SEED.leadership.flatMap(item=>[item.name,item.role])].join(' '),presidentMatch=governmentText.includes(term);
  const peopleSection=`<section class="content-card search-group"><div class="section-title"><h2>정치인</h2><span>${Number(peopleResult?.total??people.length)}명</span></div><div class="search-person-grid">${people.map(person=>`<button type="button" data-layout-route="/person/${esc(person.id)}"><span class="search-person-avatar">${esc(person.name?.slice(0,1)||'?')}</span><span><b>${esc(person.name)}</b><small>${esc([person.party,person.jurisdiction,person.office].filter(Boolean).join(' · '))}</small></span></button>`).join('')||'<div class="schedule-empty">일치하는 정치인이 없습니다</div>'}</div></section>`;
  const presidentSection=presidentMatch?`<section class="content-card search-group search-president-result"><div class="section-title"><h2>대통령 · 정부</h2><span>1건</span></div><button type="button" data-layout-route="/president"><span class="search-president-mark">P</span><span><b>${esc(GOVERNMENT_SEED.profile.name)} 대통령</b><small>${esc(GOVERNMENT_SEED.profile.office)} · 정부 구성과 국정 정보</small></span><em>대통령 페이지 →</em></button></section>`:'';
  const groups=[['COLUMN','columns',columns],['IT’S ME','itsme',itsme],['정뮤니티','community',community]].map(([label,domain,items])=>{const found=(items||[]).filter(item=>item.published!==false&&matches(item,term));return `<section class="content-card search-group"><div class="section-title"><h2>${label}</h2><span>${found.length}건</span></div><div class="search-content-list">${found.slice(0,5).map(item=>`<button type="button" data-layout-route="${esc(routeFor(domain,item.id))}"><b>${esc(item.title)}</b><p>${esc(item.summary||item.body||'')}</p></button>`).join('')||'<div class="schedule-empty">관련 결과가 없습니다</div>'}</div></section>`;}).join('');
  const pollItems=(polls?.items||[]).filter(item=>item.published!==false&&matches(item,term)),generationMatch=(generation?.candidates||[]).some(id=>people.some(person=>person.id===id))||matches(generation,term),evaluationIds=Object.values(national?.slots||{}).map(slot=>slot?.subjectId),evaluationMatch=people.some(person=>evaluationIds.includes(person.id));
  const participation=`<section class="content-card search-group"><div class="section-title"><h2>시민 참여 데이터</h2><span>${pollItems.length+Number(generationMatch)+Number(evaluationMatch)}건</span></div><div class="search-participation-grid">${pollItems.map(item=>`<button data-layout-route="/poll?pollId=${esc(item.id)}"><b>시민 설문</b><span>${esc(item.question||item.title)}</span></button>`).join('')}${generationMatch?'<button data-layout-route="/generation-president"><b>세대의 선택</b><span>대통령 모의투표 결과</span></button>':''}${evaluationMatch?'<button data-layout-route="/national-evaluation"><b>전국 평가제</b><span>정참시민 평가 결과</span></button>':''}</div></section>`;
  return `<main class="subpage search-page"><section class="page-hero"><span class="eyebrow">SEARCH · INTEGRATED</span><h1>통합검색</h1><p>검색어: <b>${esc(term)}</b></p></section>${peopleSection}${presidentSection}${groups}${participation}</main>`;
}
