import { BADGE_CATALOG, badgeCrestSvg } from '../data/badge-catalog.js';

const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{const date=new Date(v);if(Number.isNaN(date.getTime()))return '';return `${date.getFullYear()}. ${String(date.getMonth()+1).padStart(2,'0')}. ${String(date.getDate()).padStart(2,'0')}.`;};
const page=(eyebrow,title,body)=>`<section class="module"><div class="module-header"><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div></div>${body}</section>`;
const subpage=(eyebrow,title,description,body)=>`<div class="subpage"><section class="page-hero"><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></section>${body}</div>`;
const field=(name,label,type='text',value='')=>`<label class="form-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}"></label>`;
const textarea=(name,label,value='')=>`<label class="form-field"><span>${esc(label)}</span><textarea name="${esc(name)}" rows="8">${esc(value)}</textarea></label>`;
const imageUrl=value=>{const url=String(value||'').trim();return /^(https:\/\/|\/)/i.test(url)?url:'';};
const readableBody=value=>String(value||'').replace(/\r\n?/g,'\n').split(/\n\s*\n+/).map(block=>block.trim()).filter(Boolean).map(block=>`<p>${esc(block).replace(/\n/g,'<br>')}</p>`).join('')||'<p>본문이 없습니다.</p>';
const authorIdentity=item=>{const name=esc(item?.author||'정참시'),admin=['admin','parkmovie'].includes(String(item?.ownerId||''))||['관리자','박감독'].includes(String(item?.author||''));return `<span class="author-identity"><span class="author-nickname">${name}</span>${admin?'<span class="author-role author-role-admin">ADMIN</span>':''}</span>`;};
const summaryOf=item=>String(item?.summary||'').trim();
const listSummary=item=>summaryOf(item)||String(item?.body||'').replace(/\s+/g,' ').trim().slice(0,160);

export function renderAbout(){return page('ABOUT JEONGCHAMSI','왜 정참시인가',`<article class="brand-support-story"><h2>세계적으로 유명한 배우들도 끊임없이 훈련합니다.</h2><p>작품을 쉬는 기간에도 호흡과 발성, 효율적인 감정 전달 기법등을 트레이닝 합니다.</p><p>물론 작품 중에도 필요한 순간마다 조언을 구하며 자신을 정비하죠.</p><p>정치도 다르지 않다고 생각합니다.</p><p>정참시는 정치를 하려는 곳도, 정치인이 되려는 곳도 아닙니다.</p><p>다만 현장에서 더 나은 방법이 필요할 때, 현장의 시각과는 다른 방향에서 해답을 찾고자 할 때, <br>의도와는 다르게 난처한 상황을 겪게 될 때, 정참시는 분명한 데이터를 기반으로 더 선명한 방법을 제공합니다.</p><p>정참시는 정참시가 가장 잘하는 일을 하겠습니다.</p><p>막대한 양의 데이터를 빠짐없이 수집하고, JCS만의 독자적인 시스템을 통해 분석하고, <br>시장이 요구하는 신호를 읽어 가장 필요한 순간에 전달하겠습니다.</p><strong>대한민국 No.1 정치 네비게이션 정.참.시</strong></article>`);}
export function renderSupport(){return page('SUPPORT','정참시 후원하기',`<div class="legal-copy"><p>정치에 참여할 수 있는 더 나은 공간을 함께 만들어 주세요.</p><p>후원은 서비스 운영, 데이터 정비, 콘텐츠 제작, 시민 참여 기능 개선에 사용됩니다.</p></div>`);}
export function renderLegal(type){const map={guide:['이용안내','정참시의 메뉴와 참여 기능을 이용하는 방법을 안내합니다.'],privacy:['개인정보처리방침','회원 정보는 서비스 제공과 계정 관리 목적에 필요한 범위에서 처리합니다.'],policy:['운영정책','정참시는 건전한 참여와 정보 공유를 위한 운영 원칙을 적용합니다.']};const [t,b]=map[type]||map.guide;return page('JEONGCHAMSI',t,`<div class="legal-copy"><p>${esc(b)}</p></div>`);}

export async function renderBoard(domain,content,session={}){
  const config=domain==='columns'
    ? {eyebrow:'COLUMN',title:'COLUMN',description:'정치를 조금 더 깊게 읽는 정참시의 칼럼 공간입니다',guide:'관리자가 등록한 게시물을 확인할 수 있습니다',route:'column',type:'COLUMN'}
    : {eyebrow:'COMMUNITY',title:'정뮤니티',description:'시민들이 정치 이야기를 직접 작성하고 나누는 정참시 커뮤니티입니다',guide:'회원이 직접 글을 작성하고 댓글·좋아요로 참여할 수 있습니다',route:'community',type:'정뮤니티'};
  const items=(await content.list(domain)).filter(x=>x.published!==false);
  const canWrite=domain==='community'?session.authenticated:['admin','partner'].includes(session.user?.role);
  const writeButton=canWrite?`<button class="primary-btn" type="button" data-layout-route="/${config.route}/write">글쓰기</button>`:domain==='community'?'<button class="primary-btn" type="button" data-layout-route="/login">로그인 후 글쓰기</button>':'';
  const rows=items.map(item=>{const cover=imageUrl(item.coverImage),summary=listSummary(item);return `<article class="${cover?'':'no-thumb'}">${cover?`<a class="board-thumb" href="#/${config.route}/${esc(item.id)}" data-layout-route="/${config.route}/${esc(item.id)}" style="background-image:url('${esc(cover)}')" aria-label="${esc(item.title)}"></a>`:''}<a href="#/${config.route}/${esc(item.id)}" data-layout-route="/${config.route}/${esc(item.id)}"><span class="type">${esc(item.category||config.type)}</span><h2>${esc(item.title||'제목 없는 게시물')}</h2>${summary?`<p>${esc(summary)}</p>`:''}</a><small>${authorIdentity(item)} · ${fmt(item.createdAt)} · 좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')}</small></article>`;}).join('')||'<div class="schedule-empty">등록된 게시물이 없습니다</div>';
  return subpage(config.eyebrow,config.title,config.description,`<section class="content-card"><div class="board-toolbar"><p>${config.guide}</p><div class="inline-actions"><span class="status-pill"><b>POSTS</b>${items.length.toLocaleString('ko-KR')}개</span>${writeButton}</div></div><div class="board-list">${rows}</div></section>`);
}

async function commentsBlock(domain,id,content,session){const comments=await content.commentsFor(domain,id);return `<section class="content-card comment-section"><div class="section-title"><h2>댓글</h2><span>${comments.length.toLocaleString('ko-KR')}개</span></div>${session?.authenticated?`<form class="stage-form" data-stage-form="comment" data-domain="${esc(domain)}" data-post-id="${esc(id)}">${textarea('text','댓글')}<button class="primary-btn">댓글 등록</button><span data-form-state></span></form>`:'<div class="member-login-prompt"><span>댓글과 좋아요는 로그인 후 사용할 수 있습니다</span><button class="primary-btn" type="button" data-layout-route="/login">로그인</button></div>'}<div class="community-list legacy-comment-list">${comments.map((c,i)=>`<article class="community-row"><span class="community-order">${String(i+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(c.author||'회원')}</b><em>${fmt(c.createdAt)}</em><p>${esc(c.text||'')}</p></span></article>`).join('')||'<div class="empty-inline">아직 작성한 댓글이 없습니다</div>'}</div></section>`;}

async function detailView(domain,item,content,session,label,listLabel,route){const comments=await commentsBlock(domain,item.id,content,session),cover=imageUrl(item.coverImage),summary=summaryOf(item);return `<div class="subpage"><article class="content-card article-detail legacy-board-detail article-${esc(domain)}"><span class="eyebrow">${esc(label)}</span><h1>${esc(item.title)}</h1><div class="article-meta"><span>${authorIdentity(item)}</span><span>${fmt(item.createdAt)}</span><span>조회 ${Number(item.views||0).toLocaleString('ko-KR')}</span><span>좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')}</span></div>${cover?`<div class="article-cover" style="background-image:url('${esc(cover)}')" role="img" aria-label="${esc(item.title)}"></div>`:''}${summary?`<div class="article-lead">${esc(summary)}</div>`:''}<div class="article-body">${readableBody(item.body)}</div><div class="article-actions"><button type="button" class="ghost-btn" data-post-like data-domain="${esc(domain)}" data-post-id="${esc(item.id)}">♡ 좋아요</button><button type="button" class="primary-btn" data-layout-route="/${route}">${esc(listLabel)} 목록으로</button></div></article>${comments}</div>`;}
export async function renderBoardDetail(domain,id,content,session={}){const item=await content.get(domain,id);if(!item)return page('CONTENT','글을 찾을 수 없습니다','<button class="ghost-btn" data-layout-route="/">메인으로</button>');return detailView(domain,item,content,session,domain==='columns'?'COLUMN':'COMMUNITY',domain==='columns'?'COLUMN':'정뮤니티',domain==='columns'?'column':'community');}
export function renderBoardWrite(domain){const label=domain==='columns'?'COLUMN':'COMMUNITY',title=domain==='columns'?'COLUMN 글쓰기':'정뮤니티 글쓰기';return subpage(label,title,'제목과 내용을 입력해 게시물을 등록합니다',`<section class="content-card"><form class="stage-form" data-stage-form="board" data-domain="${domain}">${field('title','제목')}${textarea('body','내용')}<button class="primary-btn" type="submit">저장</button><span class="save-state" data-form-state></span></form></section>`);}

export async function renderItsme(content,route=''){const data=await content.readDomain('itsme'),all=Array.isArray(data?.items)?data.items.filter(x=>x.published!==false):[],categories=Array.isArray(data?.categories)?data.categories:[],selected=new URLSearchParams(String(route).split('?')[1]||'').get('category')||'',items=selected?all.filter(x=>x.category===selected):all;const tabs=['',...categories].map(category=>`<button type="button" class="${category===selected?'active':''}" data-layout-route="/itsme${category?`?category=${encodeURIComponent(category)}`:''}">${esc(category||'전체')}</button>`).join('');const rows=items.map(item=>`<article class="no-thumb"><a href="#/itsme/${esc(item.id)}" data-layout-route="/itsme/${esc(item.id)}"><span class="type">${esc(item.category||'IT’S ME')}</span><h2>${esc(item.title)}</h2>${listSummary(item)?`<p>${esc(listSummary(item))}</p>`:''}</a><small>${authorIdentity(item)} · ${fmt(item.createdAt)} · 좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')}</small></article>`).join('')||'<div class="schedule-empty">등록된 제안이 없습니다</div>';return subpage('IT’S ME · POLICY PROPOSAL','IT’S ME','“내가 대통령이라면, 내가 국회의원이라면, 내가 시장이라면, 내가 장관이라면”을 말머리로 정책과 아이디어를 직접 제안하는 참여 게시판입니다',`<section class="content-card"><div class="board-toolbar"><div class="itsme-category-tabs">${tabs}</div><button class="primary-btn" type="button" data-layout-route="/itsme/write">정책 제안하기</button></div><div class="board-list itsme-board-list">${rows}</div></section>`);}
export function renderItsmeWrite(){return subpage("IT’S ME · POLICY PROPOSAL",'정책 제안하기','정책과 아이디어를 직접 제안합니다',`<section class="content-card"><form class="stage-form" data-stage-form="itsme">${field('title','제안 제목')}${field('category','카테고리')}${textarea('body','제안 내용')}<button class="primary-btn">등록</button><span data-form-state></span></form></section>`);}
export async function renderItsmeDetail(id,content,session={}){const item=await content.get('itsme',id);if(!item)return page("IT’S ME",'제안을 찾을 수 없습니다','');return detailView('itsme',item,content,session,`IT’S ME${item.category?` · ${item.category}`:''}`,"IT’S ME",'itsme');}

export async function renderPoll(content,session={}){const data=await content.readDomain('polls'),poll=(data?.items||[]).find(x=>x.published!==false);if(!poll)return page("CITIZENS’ CHOICE",'시민들의 선택','<div class="schedule-empty">진행 중인 설문이 없습니다</div>');const opts=Array.isArray(poll.options)?poll.options:[],total=opts.reduce((a,o)=>a+Number(o.votes||0),0);return page("CITIZENS’ CHOICE",'귀담아 들어야 합니다',`<div class="poll-main"><div class="poll-question"><span class="poll-status">진행중</span><h3>${esc(poll.question||'시민 설문')}</h3><p>${esc(poll.description||'')}</p></div><div class="poll-options">${opts.map(o=>{const n=Number(o.votes||0),p=total?Math.round(n*100/total):0;return `<button type="button" data-stage-vote="poll:${esc(poll.id)}" data-option="${esc(o.id)}"><span>${esc(o.label)}</span><i><em style="width:${p}%"></em></i><b>${p}%</b></button>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">투표는 로그인 후 참여할 수 있습니다.</p>'}</div>`);}

export async function renderGeneration(content,session={}){const data=await content.readDomain('generation'),ages=['10대','20대','30대','40대','50대','60대+'],candidates=Array.isArray(data?.candidates)?data.candidates:[];if(!candidates.length)return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령','<div class="schedule-empty">후보 데이터는 정치인 DB 이식 단계에서 연결됩니다.</div>');return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령',`<div class="generation-grid">${ages.map(age=>{const results=data?.results?.[age]||{},total=Object.values(results).reduce((a,b)=>a+Number(b||0),0);return `<article class="generation-card"><span class="generation-age">${age}</span><b>세대별 선택</b><p class="module-desc">${total.toLocaleString('ko-KR')}명 참여</p><div class="generation-actions">${candidates.slice(0,8).map(cid=>`<button class="ghost-btn" data-stage-vote="generation:${esc(age)}" data-option="${esc(cid)}">${esc(cid)} · ${Number(results[cid]||0).toLocaleString('ko-KR')}</button>`).join('')}</div></article>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">투표는 로그인 후 참여할 수 있습니다.</p>'}`);}

export async function renderNationalEvaluation(content,session={}){const data=await content.readDomain('nationalEvaluation'),slots=Object.values(data?.slots||{}).filter(x=>x?.subjectId);if(!slots.length)return page('NATIONAL EVALUATION','정참시민 전국 평가제','<div class="schedule-empty">진행 중인 평가가 없습니다</div>');return page('NATIONAL EVALUATION','정참시민 전국 평가제',`<div class="national-eval-layout">${slots.map(slot=>{const r=data?.results?.[slot.evaluationId]||{positive:0,neutral:0,negative:0};return `<div class="eval-person"><span class="eval-avatar"></span><div><small>${esc(slot.slot||'평가')}</small><b>${esc(slot.subjectId)}</b><p>좋음 ${Number(r.positive||0)} · 보통 ${Number(r.neutral||0)} · 아쉬움 ${Number(r.negative||0)}</p><div><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="positive">좋음</button><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="neutral">보통</button><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="negative">아쉬움</button></div></div></div>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">평가는 로그인 후 참여할 수 있습니다.</p>'}`);}

export async function renderAcademy(content,session={}){const data=await content.readDomain('academy'),items=(Array.isArray(data?.slots)?data.slots:[]).filter(x=>x.published!==false).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')));const rows=items.map(item=>`<article data-slot-id="${esc(item.id||'')}"><div><b>${esc(item.date||'일정 준비중')}</b><span>${esc(item.title||'정참시 아카데미')}${item.description?` · ${esc(item.description)}`:''}</span></div><button type="button" data-stage-action="academy-apply">${session.authenticated?'수강 신청':'로그인 후 신청'}</button></article>`).join('')||'<div class="schedule-empty">등록된 일정이 없습니다</div>';return subpage('JEONGCHAMSI ACADEMY','정참시 아카데미','정치를 꿈꾸는 사람이 실제 수강 가능한 일정을 확인하고 신청하는 곳',`<section class="content-card academy-detail-intro"><h2>정치의 꿈을 실제 준비로</h2><p>정치를 꿈꾸는 사람이 실제 수강 가능한 일정을 확인하고 신청하는 곳</p></section><section class="content-card"><div class="section-title"><h2>수강 가능 일정</h2><span>${items.length.toLocaleString('ko-KR')}개</span></div><div class="academy-slot-list">${rows}</div></section>`);}

export function renderPoliticianRequest(){return page('POLITICIAN REQUEST','찾는 정치인이 없나요?',`<form class="stage-form" data-stage-form="politician-request">${field('name','정치인 이름')}<button class="primary-btn">등록 요청</button><span data-form-state></span></form>`);}
export function renderPartners(){return page('JEONGCHAMSI PARTNERS','정참시 파트너스 신청',`<form class="stage-form" data-stage-form="partner">${field('name','이름 / 단체명')}${field('contact','연락처')}${textarea('message','소개')}<button class="primary-btn">신청</button><span data-form-state></span></form>`);}

export function renderLogin(){return page('MEMBER','로그인',`<form class="stage-form" data-stage-form="login">${field('id','아이디')}${field('password','비밀번호','password')}<button class="primary-btn">로그인</button><button class="ghost-btn" type="button" data-layout-route="/join">회원가입</button><span data-form-state></span></form>`);}
export function renderJoin(){return page('MEMBER','회원가입',`<form class="stage-form" data-stage-form="join">${field('id','아이디')}${field('password','비밀번호','password')}${field('name','이름')}${field('nickname','닉네임')}${field('email','이메일','email')}${field('birthYear','출생연도')}${field('regionProvince','시/도')}${field('regionCity','시/군/구')}<button class="primary-btn">가입</button><span data-form-state></span></form>`);}
const BADGE_TIERS=['BRONZE','SILVER','GOLD','PLATINUM','BLACK'];
const BADGE_TIER_LABEL={BRONZE:'브론즈',SILVER:'실버',GOLD:'골드',PLATINUM:'플래티넘',BLACK:'블랙'};

export function renderBadgeCollection(status={},user={}){
  const earned=new Set(status.earnedBadges||[]),eligible=new Set(status.eligibleBadges||[]),showcase=new Set(status.showcaseBadges||[]),representative=status.representativeBadge||'';
  return `<div class="badge-collection">${BADGE_TIERS.map(tier=>{const items=BADGE_CATALOG.filter(item=>item.tier===tier);return `<section class="badge-tier-section badge-tier-${tier.toLowerCase()}" data-badge-tier="${tier}"><header><div><span>${BADGE_TIER_LABEL[tier]}</span><h2>${tier}</h2></div><b>${items.filter(item=>earned.has(item.key)).length} / ${items.length}</b></header><div class="badge-card-grid">${items.map(item=>{const owned=earned.has(item.key),isEligible=eligible.has(item.key),isRepresentative=representative===item.key,isShowcase=showcase.has(item.key),progress=status.progress?.[item.key];const state=owned?(isRepresentative?'대표 배지':isShowcase?'전시 중':'획득 완료'):isEligible?'승인 후보':['GOLD','PLATINUM','BLACK'].includes(tier)?'관리자 승인 필요':'미획득';return `<article class="badge-collection-card ${owned?'is-owned':'is-locked'} ${isEligible?'is-eligible':''}" data-badge-card="${esc(item.key)}">${badgeCrestSvg(item.key)}<div class="badge-card-copy"><span>${esc(item.kind)}</span><h3>${esc(item.name)}</h3><p>${esc(item.mission)}</p>${progress?`<small>${esc(progress.label)} · ${Number(progress.current||0).toLocaleString('ko-KR')} / ${Number(progress.target||0).toLocaleString('ko-KR')}</small>`:''}</div><div class="badge-card-state"><b>${state}</b>${owned?`<button type="button" data-badge-representative="${esc(item.key)}">${isRepresentative?'대표 배지':'대표로 설정'}</button>${isRepresentative?'':`<button type="button" data-badge-showcase="${esc(item.key)}">${isShowcase?'전시 해제':'전시하기'}</button>`}`:''}</div></article>`;}).join('')}</div></section>`;}).join('')}</div>`;
}

export function renderMyActivity(session,status={},search=''){
  if(!session.authenticated)return renderLogin();
  const count=(status.earnedBadges||[]).length;
  return subpage('MY JEONGCHAMSI · BADGES','내 배지 컬렉션','활동으로 획득하고 운영진 승인을 통해 완성하는 정참시의 시민 컬렉션',`<section class="content-card badge-collection-intro"><div><span>COLLECTION STATUS</span><h2>${count}개 획득 · 총 ${BADGE_CATALOG.length}종</h2><p>대표 1개 · 전시 3개를 선택하면 메인 오른쪽 사이드바에 표시됩니다.</p></div><button class="ghost-btn" type="button" data-layout-route="/mypage">마이페이지</button></section>${renderBadgeCollection(status,session.user)}`);
}

export function renderMyPage(session,status={}){if(!session.authenticated)return renderLogin();const count=(status.earnedBadges||[]).length;return page('MY JEONGCHAMSI','마이페이지',`<div class="profile-card"><h3>${esc(session.user.nickname)}님</h3><p>${esc(session.user.id)} · ${esc(session.user.role)}</p><div class="mypage-badge-summary"><span>${status.representativeBadge?badgeCrestSvg(status.representativeBadge):'<i>◇</i>'}</span><div><b>내 배지 컬렉션</b><p>${count}개 획득 · 대표 1개와 전시 3개 설정</p></div><button class="primary-btn" data-layout-route="/mypage/activity">배지 보기</button></div>${session.user.role==='admin'?'<button class="primary-btn" data-layout-route="/admin">관리자 페이지</button>':''}<button class="ghost-btn" data-stage-action="logout">로그아웃</button></div>`);}

export function renderMemberBadgeManager(user={}){
  const grants=new Set(user.grantedBadges||[]),earned=new Set(user.earnedBadges||[]),eligible=new Set(user.eligibleBadges||[]);
  return `<div class="admin-member-badges" data-member-badge-manager="${esc(user.id)}"><div class="admin-member-badge-summary"><b>${earned.size}개 사용 가능</b><span>수동 해금 ${(user.grantedBadges||[]).length}개 · 대표 ${user.representativeBadge?'설정':'미설정'}</span></div>${BADGE_TIERS.map(tier=>`<fieldset data-admin-badge-tier="${tier}"><legend>${BADGE_TIER_LABEL[tier]} <small>${tier}</small></legend><div>${BADGE_CATALOG.filter(item=>item.tier===tier).map(item=>`<label class="admin-badge-check ${earned.has(item.key)?'is-earned':''} ${eligible.has(item.key)?'is-eligible':''}"><input type="checkbox" data-member-badge="${esc(user.id)}" value="${esc(item.key)}" ${grants.has(item.key)?'checked':''}><span>${badgeCrestSvg(item.key)}<b>${esc(item.name)}</b><small>${eligible.has(item.key)&&!earned.has(item.key)?'승인 후보':earned.has(item.key)?'사용 가능':'잠김'}</small></span></label>`).join('')}</div></fieldset>`).join('')}<button class="primary-btn" type="button" data-member-badge-save="${esc(user.id)}">선택한 배지 해금 저장</button><span class="save-state" data-member-badge-state="${esc(user.id)}"></span></div>`;
}
const renderAdminMemberRow=(user,index)=>{const payload={id:user.id,nickname:user.nickname,role:user.role,grantedBadges:user.grantedBadges||[],earnedBadges:user.earnedBadges||[],eligibleBadges:user.eligibleBadges||[],representativeBadge:user.representativeBadge||''};return `<details class="admin-member-row" data-member-badge-row="${esc(user.id)}" data-member-badge-payload="${esc(JSON.stringify(payload))}"><summary><span class="community-order">${String(index+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(user.nickname||user.id)}</b><em>${esc(user.id)} · ${esc(user.role)} · ${fmt(user.createdAt)}</em></span><strong>${Number(user.earnedBadges?.length||0)}개</strong></summary><div data-member-badge-mount></div></details>`;};

const jobLabel=status=>({RUNNING:'진행 중',COMPLETED:'완료',COMPLETED_WITH_ERRORS:'일부 오류',FAILED:'실패'}[status]||'대기');
const jobPanel=(kind,title,job,disabled=false)=>{const total=Number(job?.total||542),completed=Number(job?.completed||0),percent=total?Math.min(100,Math.round(completed/total*100)):0,running=job?.status==='RUNNING',action=kind==='collect'?'전체 수집':'전체 게시';return `<article class="admin-job-card" data-intelligence-job="${kind}" data-job-status="${esc(job?.status||'IDLE')}" data-job-blocked="${disabled?'true':'false'}"><header><div><span>${kind==='collect'?'COLLECT & ANALYZE':'VALIDATE & PUBLISH'}</span><h3>${esc(title)}</h3></div><b>${jobLabel(job?.status)}</b></header><div class="admin-job-progress"><i style="width:${percent}%"></i></div><p><strong data-job-progress-text>${completed.toLocaleString('ko-KR')} / ${total.toLocaleString('ko-KR')}</strong><span>${percent}% · 25명 이하 분할 처리</span></p><button class="primary-btn" type="button" data-intelligence-action="${kind}" ${disabled?'disabled':''}>${running?'이어서 처리':action}</button><small data-job-message>${Number(job?.failed||0)>0?`오류 ${Number(job.failed).toLocaleString('ko-KR')}건 기록됨`:'중단되어도 현재 위치부터 재개됩니다.'}</small></article>`;};

const INTELLIGENCE_STAGES=['공식정보 확인','뉴스 수집','중복 제거','핵심 사건 추출','과거 이력 연결','정치인 유형 판별','10대 진단 생성','10대 처방 생성','모순 검수','초안 저장 완료'];
const pipelineStages=collection=>{const percent=Number(collection?.total)?Number(collection?.completed||0)/Number(collection.total):0,active=['COMPLETED','COMPLETED_WITH_ERRORS'].includes(collection?.status)?10:collection?.status==='RUNNING'?Math.max(1,Math.min(9,Math.ceil(percent*9))):0;return `<ol class="admin-pipeline-stages">${INTELLIGENCE_STAGES.map((label,index)=>`<li data-intelligence-stage="${index+1}" class="${index<active?'is-done':index===active?'is-active':''}"><b>${String(index+1).padStart(2,'0')}</b><span>${label}</span></li>`).join('')}</ol>`;};
const versionHistory=versions=>`<div class="admin-version-history"><h3>분석 버전 이력</h3>${(versions||[]).map(version=>`<div><b>${esc(version.analysisVersion)}</b><span>${esc(version.status)} · ${esc(version.reviewStatus||'pending')}</span></div>`).join('')||'<p>저장된 분석 버전이 없습니다.</p>'}</div>`;
const reviewPanel=preview=>{const sample=preview?.reviewSample,version=preview?.version;if(!preview?.ok||!sample)return '<section class="admin-review-panel"><h3>관리자 검토</h3><p>수집 완료 후 대표 뉴스, 사건, 유형, 진단과 처방을 검토합니다.</p></section>';const type=sample.politicianType||{},diagnosis=sample.diagnoses?.[0],prescription=sample.prescriptions?.[0];return `<section class="admin-review-panel"><header><div><span>JCS INTELLIGENCE REVIEW</span><h3>게시 전 관리자 검토</h3></div><b>${esc(version?.status||'draft')}</b></header><div class="admin-review-summary"><div><small>검토 정치인</small><strong>${esc(sample.personId)}</strong></div><div><small>주유형</small><strong>${esc(type.primaryType)}</strong></div><div><small>현재 국면</small><strong>${esc(type.currentPhase)}</strong></div><div><small>구성</small><strong>진단 ${Number(sample.diagnoses?.length||0)}개 · 처방 ${Number(sample.prescriptions?.length||0)}개</strong></div></div><div class="admin-review-events"><h4>핵심 사건</h4>${(sample.eventClusters||[]).map(event=>`<p><b>${esc(event.eventType)}</b><span>${esc(event.eventTitle)}</span></p>`).join('')||'<p>공식 역할 기반 구조 분석</p>'}</div><form class="admin-review-edit" data-intelligence-draft-form data-person-id="${esc(sample.personId)}"><label>01 핵심 진단<textarea name="diagnosisHeadline">${esc(diagnosis?.headline||'')}</textarea></label><label>01 전략 판단<textarea name="prescriptionJudgment">${esc(prescription?.strategicJudgment||'')}</textarea></label><button class="ghost-btn" type="submit">수정본 저장</button><span data-intelligence-draft-state></span></form>${version?.status==='draft'?'<button class="primary-btn" type="button" data-intelligence-approve>검수 승인</button>':''}<div class="admin-validation-report"><b>자동 검수 ${preview.validation?.ok?'통과':'미통과'}</b><span>${(preview.validation?.errors||[]).map(esc).join(' · ')||'차단 오류 없음'}</span></div></section>`;};

export async function renderAdminStable(session,auth){
  if(!session.authenticated)return renderLogin();if(session.user?.role!=='admin')return page('ADMIN','접근 권한이 없습니다','<p class="module-desc">관리자 계정만 접근할 수 있습니다.</p>');
  const [summary,users,intelligence,preview]=await Promise.all([auth.adminSummary(),auth.exportMembers(),auth.intelligenceStatus(),auth.intelligencePreview?auth.intelligencePreview():Promise.resolve({ok:false})]);
  if(!summary.ok)return page('ADMIN','관리자 데이터 연결 대기',`<p class="module-desc">${esc(summary.error||'저장소 연결을 확인해 주세요.')}</p>`);
  const entries=Object.entries(summary.contents||{}),collection=intelligence.collection||null,publication=intelligence.publication||null,validation=intelligence.validation||null,naver=intelligence.sources?.naverSearchAds||{},activeVersion=(intelligence.versions||[]).find(version=>version.analysisVersion===intelligence.latestDraft)||preview?.version||null;
  const publishReady=['COMPLETED','COMPLETED_WITH_ERRORS'].includes(collection?.status)&&validation?.ok===true&&activeVersion?.status==='approved';
  const pipeline=`<section class="admin-intelligence-console"><div class="admin-console-head"><div><span>JCS POLITICAL DATA PIPELINE</span><h2>정치인 데이터 수집 · 분석 · 게시</h2><p>542명의 실제 정치인을 25명 이하 단위로 처리합니다. 새 분석은 검수 전 초안으로 저장되고, 승인된 버전만 게시됩니다.</p></div><div class="admin-source-status ${naver.configured?'is-ready':'is-missing'}"><small>NAVER SEARCH ADS</small><strong>${naver.configured?'연결됨':'연결 필요'}</strong><span>${naver.configured?'PC·모바일 검색량 수집 가능':'Vercel 환경변수 3개만 연결하면 활성화'}</span></div></div>${pipelineStages(collection)}<div class="admin-job-grid">${jobPanel('collect','전체 정치인 원자료 수집·JCS 분석',collection,!naver.configured)}${jobPanel('publish','검수 승인본 전체 게시',publication,!publishReady&&publication?.status!=='RUNNING')}</div><div class="admin-snapshot-status"><span>수집 스냅샷 <b>${esc(intelligence.latestDraft||'없음')}</b></span><span>현재 공개 스냅샷 <b>${esc(intelligence.publicSnapshot||'없음')}</b></span><span>검증 <b>${validation?.ok?'통과':validation?'미통과':'대기'}</b></span></div>${reviewPanel(preview)}${versionHistory(intelligence.versions)}</section>`;
  return page('ADMIN · CONTROL CENTER','회원 · 콘텐츠 · 정치 인텔리전스 관리',`${pipeline}<div class="national-eval-layout"><div class="eval-question"><strong>회원</strong><p>전체 ${Number(summary.users?.total||0).toLocaleString('ko-KR')}명 · 관리자 ${Number(summary.users?.admins||0).toLocaleString('ko-KR')}명</p></div>${entries.map(([k,v])=>`<div class="eval-question"><strong>${esc(k)}</strong><p>${Number(v||0).toLocaleString('ko-KR')}건</p></div>`).join('')}</div><section class="admin-member-section"><div class="section-title"><h2>회원별 배지 해금</h2><span>획득하지 못한 배지도 관리자가 즉시 열 수 있습니다</span></div><div class="admin-member-list">${users.map(renderAdminMemberRow).join('')}</div></section>`);
}

export function renderMigration(){return page('JCS_0_0_8 · ONE-TIME MIGRATION','기존 데이터 이식',`<div class="legal-copy"><p>회원·게시판 이식과 정치인 기본 DB 이식을 서로 분리해 실행합니다.</p><p>정치인 DB에는 합의된 프로필·정치 기록·등록 사진만 저장하며 NOW 점수·순위·분석값은 포함하지 않습니다.</p></div><form class="stage-form" data-stage-form="migration">${field('secret','마이그레이션 키','password')}<button class="primary-btn">회원·게시판 이식 실행</button><span data-form-state></span></form><form class="stage-form politician-migration-form" data-stage-form="politician-migration">${field('secret','정치인 DB 이관 키','password')}<button class="primary-btn">정치인 DB 543개 슬롯 이식</button><span data-form-state></span></form>`);}
