import { authorIdentity, postMenu, sharedPost, sharedWrite, communityBoard, cageDetail } from './community-ui.js?v=0.0.31.117';
import { BADGE_CATALOG, badgeByKey, badgeCrestSvg } from '../data/badge-catalog.js';
import { regionProvinceOptions, regionDistrictOptions, regionSubdistrictOptions } from '../data/korean-regions.js?v=0.0.31.56';

const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{const date=new Date(v);if(Number.isNaN(date.getTime()))return '';return `${date.getFullYear()}. ${String(date.getMonth()+1).padStart(2,'0')}. ${String(date.getDate()).padStart(2,'0')}.`;};
const page=(eyebrow,title,body)=>`<section class="module"><div class="module-header"><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div></div>${body}</section>`;
const subpage=(eyebrow,title,description,body)=>`<div class="subpage"><section class="page-hero"><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(description)}</p></section>${body}</div>`;
const field=(name,label,type='text',value='')=>`<label class="form-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}"></label>`;
const requiredField=(name,label,type='text',value='')=>`<label class="form-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" required></label>`;
const textarea=(name,label,value='')=>`<label class="form-field"><span>${esc(label)}</span><textarea name="${esc(name)}" rows="8">${esc(value)}</textarea></label>`;
const imageUrl=value=>{const url=String(value||'').trim();return /^(https:\/\/|\/)/i.test(url)?url:'';};
const readableBody=value=>String(value||'').replace(/\r\n?/g,'\n').split(/\n\s*\n+/).map(block=>block.trim()).filter(Boolean).map(block=>`<p>${esc(block).replace(/\n/g,'<br>')}</p>`).join('')||'<p>본문이 없습니다.</p>';

const summaryOf=item=>String(item?.summary||'').trim();
const listSummary=item=>summaryOf(item)||String(item?.body||'').replace(/\s+/g,' ').trim().slice(0,160);
const boardConfig=domain=>domain==='columns'
  ? {eyebrow:'COLUMN',title:'COLUMN',description:'정치를 조금 더 깊게 읽는 정참시의 칼럼 공간입니다',guide:'관리자가 등록한 게시물을 확인할 수 있습니다',route:'column',type:'COLUMN'}
  : domain==='news'
    ? {eyebrow:'JEONGCHAMSI NEWS',title:'정참시 NEWS',description:'정참시가 직접 확인하고 게시한 정치 뉴스입니다',guide:'관리자와 파트너가 등록한 뉴스를 확인할 수 있습니다',route:'news',type:'NEWS'}
    : {eyebrow:'COMMUNITY',title:'정뮤니티',description:'시민들이 정치 이야기를 직접 작성하고 나누는 정참시 커뮤니티입니다',guide:'회원이 직접 글을 작성하고 댓글·좋아요로 참여할 수 있습니다',route:'community',type:'정뮤니티'};

export function renderAbout(){return page('ABOUT JEONGCHAMSI','왜 정참시인가',`<article class="brand-support-story"><h2>세계적으로 유명한 배우들도 끊임없이 훈련합니다.</h2><p>작품을 쉬는 기간에도 호흡과 발성, 효율적인 감정 전달 기법등을 트레이닝 합니다.</p><p>물론 작품 중에도 필요한 순간마다 조언을 구하며 자신을 정비하죠.</p><p>정치도 다르지 않다고 생각합니다.</p><p>정참시는 정치를 하려는 곳도, 정치인이 되려는 곳도 아닙니다.</p><p>다만 현장에서 더 나은 방법이 필요할 때, 현장의 시각과는 다른 방향에서 해답을 찾고자 할 때, <br>의도와는 다르게 난처한 상황을 겪게 될 때, 정참시는 분명한 데이터를 기반으로 더 선명한 방법을 제공합니다.</p><p>정참시는 정참시가 가장 잘하는 일을 하겠습니다.</p><p>막대한 양의 데이터를 빠짐없이 수집하고, JCS만의 독자적인 시스템을 통해 분석하고, <br>시장이 요구하는 신호를 읽어 가장 필요한 순간에 전달하겠습니다.</p><strong>대한민국 No.1 정치 네비게이션 정.참.시</strong></article>`);}
export function renderSupport(){return page('SUPPORT','정참시 후원하기',`<div class="legal-copy"><p>정치에 참여할 수 있는 더 나은 공간을 함께 만들어 주세요.</p><p>후원은 서비스 운영, 데이터 정비, 콘텐츠 제작, 시민 참여 기능 개선에 사용됩니다.</p></div>`);}
export function renderLegal(type){
  const privacy=`<div class="legal-copy legal-policy"><p>정참시는 회원 계정과 시민 참여 서비스를 운영하는 데 필요한 범위에서 개인정보를 처리합니다.</p><section><h3>1. 수집하는 개인정보</h3><p>필수 항목은 아이디, 닉네임, 이름, 이메일, 휴대전화번호, 출생연도, 주소의 시·도 및 시·군·구입니다. 서비스 이용 과정에서 로그인 기록, 투표·평가·게시글·댓글·즐겨찾기·문의 내역이 생성될 수 있습니다.</p></section><section><h3>2. 이용 목적</h3><p>회원 식별과 계정 관리, 연령·지역 기반 참여 자격 확인, 중복 투표 방지, 게시판과 문의 운영, 부정 이용 예방 및 서비스 개선에 사용합니다.</p></section><section><h3>3. 보유 및 파기</h3><p>회원 탈퇴 또는 처리 목적 달성 시 지체 없이 파기합니다. 관계 법령에 따라 보존이 필요한 기록은 해당 기간 동안 분리 보관한 뒤 파기합니다.</p></section><section><h3>4. 처리 위탁</h3><p>서비스 제공을 위해 Vercel의 호스팅·파일 저장 기능과 Redis 기반 데이터 저장 기능을 사용할 수 있으며, 위탁 범위는 서비스 운영에 필요한 저장·전송 업무로 제한합니다.</p></section><section><h3>5. 이용자 권리</h3><p>이용자는 자신의 개인정보 열람·정정·삭제·처리정지를 요청할 수 있습니다. 계정에서 직접 수정할 수 없는 정보는 1:1 문의를 통해 요청할 수 있습니다.</p></section><section><h3>6. 쿠키와 로그인</h3><p>로그인 상태 유지와 보안을 위해 세션 쿠키를 사용합니다. 브라우저에서 쿠키를 차단하면 로그인과 회원 전용 기능이 제한될 수 있습니다.</p></section><section><h3>7. 안전성 확보</h3><p>비밀번호는 원문으로 보관하거나 관리자에게 공개하지 않으며, 접근 권한 제한·세션 보호·관리자 변경 기록 등 합리적인 보호조치를 적용합니다.</p></section><section><h3>8. 개인정보 문의</h3><p>개인정보 관련 문의와 권리 행사는 1:1 문의하기 또는 풋터에 공개된 개인정보 문의 연락처를 이용해 주세요.</p></section></div>`;
  const policy=`<div class="legal-copy legal-policy"><p>정참시는 사실에 기반한 정치 정보와 책임 있는 시민 참여를 위해 다음 운영 원칙을 적용합니다.</p><section><h3>1. 정치·커뮤니티 콘텐츠</h3><p>정치적 견해의 차이를 존중하되 인신공격, 혐오, 반복 도배, 타인의 개인정보 공개 및 참여 방해 행위는 제한합니다.</p></section><section><h3>2. 허위정보·명예훼손·선거 관련</h3><p>검증되지 않은 사실을 확정적으로 유포하거나 타인의 명예를 침해하는 콘텐츠, 선거 관련 법령을 위반할 소지가 큰 콘텐츠는 확인 후 숨김·수정 요청·삭제될 수 있습니다.</p></section><section><h3>3. 공개·비공개 문의</h3><p>1:1 문의는 작성자가 공개 또는 비공개를 선택합니다. 비공개 문의는 작성자와 관리자만 열람할 수 있습니다.</p></section><section><h3>4. 투표 중복 방지</h3><p>투표와 평가의 신뢰성을 위해 회원 계정별 참여 여부와 필요한 범위의 기록을 확인하며, 조작 또는 우회 참여는 무효 처리될 수 있습니다.</p></section><section><h3>5. 원자료와 JCS 해석</h3><p>공식 이력·기사·검색 반응 등 원자료와 정참시의 분석·점수·진단·처방은 구분해 표시합니다. JCS 해석은 공개된 자료를 바탕으로 한 자체 분석이며 사실 자체나 미래 결과를 보증하지 않습니다.</p></section><section><h3>6. 이용 제한과 이의 제기</h3><p>정책 위반의 정도와 반복성에 따라 게시물 숨김, 기능 제한, 계정 정지 조치를 할 수 있습니다. 조치에 이의가 있는 이용자는 1:1 문의로 재검토를 요청할 수 있습니다.</p></section><section><h3>7. 저작권과 외부 링크</h3><p>이용자는 자신이 작성한 콘텐츠에 필요한 권리를 보유해야 합니다. 외부 기사·영상 링크의 내용과 서비스는 해당 제공자가 책임집니다.</p></section><section><h3>8. 정책 변경 고지</h3><p>운영정책이 변경될 경우 적용일과 주요 변경 내용을 서비스 안에서 사전에 알립니다.</p></section></div>`;
  if(type==='privacy')return page('JEONGCHAMSI','개인정보처리방침',privacy);
  if(type==='policy')return page('JEONGCHAMSI','운영정책',policy);
  return page('JEONGCHAMSI','페이지를 찾을 수 없습니다','');
}

export async function renderBoard(domain,content,session={},url=''){
  if(domain==='community')return communityBoard(content,session,url);
  const config=boardConfig(domain);
  const items=(await content.list(domain)).filter(x=>x.published!==false);
  const canWrite=domain==='community'?session.authenticated:['admin','partner'].includes(session.user?.role);
  const writeButton=canWrite?`<button class="primary-btn" type="button" data-layout-route="/${config.route}/write">글쓰기</button>`:domain==='community'?'<button class="primary-btn" type="button" data-layout-route="/login">로그인 후 글쓰기</button>':'';
  const rows=items.map(item=>{const cover=imageUrl(item.coverImage),summary=listSummary(item);return `<article class="${cover?'':'no-thumb'}">${cover?`<a class="board-thumb" href="#/${config.route}/${esc(item.id)}" data-layout-route="/${config.route}/${esc(item.id)}" style="background-image:url('${esc(cover)}')" aria-label="${esc(item.title)}"></a>`:''}<a href="#/${config.route}/${esc(item.id)}" data-layout-route="/${config.route}/${esc(item.id)}"><span class="type">${esc(item.category||config.type)}</span><h2>${esc(item.title||'제목 없는 게시물')}</h2>${summary?`<p>${esc(summary)}</p>`:''}</a><small>${authorIdentity(item)} · ${fmt(item.createdAt)} · 좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')}</small></article>`;}).join('')||'<div class="schedule-empty">등록된 게시물이 없습니다</div>';
  return subpage(config.eyebrow,config.title,config.description,`<section class="content-card"><div class="board-toolbar"><p>${config.guide}</p><div class="inline-actions"><span class="status-pill"><b>POSTS</b>${items.length.toLocaleString('ko-KR')}개</span>${writeButton}</div></div><div class="board-list">${rows}</div></section>`);
}

const postEditor=postMenu;
async function detailView(domain,item,content,session,label,listLabel,route,dashboard={}){return sharedPost(domain,item,content,session,dashboard);}
export async function renderBoardDetail(domain,id,content,session={},dashboard={},url=''){const item=await content.get(domain,id),config=boardConfig(domain);if(!item)return page('CONTENT','글을 찾을 수 없습니다','<button class="ghost-btn" data-layout-route="/">메인으로</button>');if(domain==='community'&&item.cageEnabled&&!item.cageParentId)return cageDetail(item,content,session,dashboard,url);return detailView(domain,item,content,session,config.eyebrow,config.title,config.route,dashboard);}
export function renderBoardWrite(domain,session={},wallet={}){return sharedWrite(domain,session,wallet);}

export async function renderItsme(content,route=''){const data=await content.readDomain('itsme'),all=Array.isArray(data?.items)?data.items.filter(x=>x.published!==false):[],categories=Array.isArray(data?.categories)?data.categories:[],selected=new URLSearchParams(String(route).split('?')[1]||'').get('category')||'',items=selected?all.filter(x=>x.category===selected):all;const tabs=['',...categories].map(category=>`<button type="button" class="${category===selected?'active':''}" data-layout-route="/itsme${category?`?category=${encodeURIComponent(category)}`:''}">${esc(category||'전체')}</button>`).join('');const rows=items.map(item=>`<article class="no-thumb"><a href="#/itsme/${esc(item.id)}" data-layout-route="/itsme/${esc(item.id)}"><span class="type">${esc(item.category||'IT’S ME')}</span><h2>${esc(item.title)}</h2>${listSummary(item)?`<p>${esc(listSummary(item))}</p>`:''}</a><small>${authorIdentity(item)} · ${fmt(item.createdAt)} · 좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')}</small></article>`).join('')||'<div class="schedule-empty">등록된 제안이 없습니다</div>';return subpage('IT’S ME · POLICY PROPOSAL','IT’S ME','“내가 대통령이라면, 내가 국회의원이라면, 내가 시장이라면, 내가 장관이라면”을 말머리로 정책과 아이디어를 직접 제안하는 참여 게시판입니다',`<section class="content-card"><div class="board-toolbar"><div class="itsme-category-tabs">${tabs}</div><button class="primary-btn" type="button" data-layout-route="/itsme/write">정책 제안하기</button></div><div class="board-list itsme-board-list">${rows}</div></section>`);}
export async function renderItsmeWrite(session={},content){const data=content?await content.readDomain('itsme'):{};return sharedWrite('itsme',session,{},Array.isArray(data.categories)?data.categories:undefined);}
export async function renderItsmeDetail(id,content,session={},dashboard={}){const item=await content.get('itsme',id);if(!item)return page("IT’S ME",'제안을 찾을 수 없습니다','');return detailView('itsme',item,content,session,`IT’S ME${item.category?` · ${item.category}`:''}`,"IT’S ME",'itsme',dashboard);}

export async function renderPoll(content,session={}){const data=await content.readDomain('polls'),poll=(data?.items||[]).find(x=>x.published!==false);if(!poll)return page("CITIZENS’ CHOICE",'시민들의 선택','<div class="schedule-empty">진행 중인 설문이 없습니다</div>');const opts=Array.isArray(poll.options)?poll.options:[],total=opts.reduce((a,o)=>a+Number(o.votes||0),0);return page("CITIZENS’ CHOICE",'귀담아 들어야 합니다',`<div class="poll-main"><div class="poll-question"><span class="poll-status">진행중</span><h3>${esc(poll.question||'시민 설문')}</h3><p>${esc(poll.description||'')}</p></div><div class="poll-options">${opts.map(o=>{const n=Number(o.votes||0),p=total?Math.round(n*100/total):0;return `<button type="button" data-stage-vote="poll:${esc(poll.id)}" data-option="${esc(o.id)}"><span>${esc(o.label)}</span><i><em style="width:${p}%"></em></i><b>${p}%</b></button>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">투표는 로그인 후 참여할 수 있습니다.</p>'}</div>`);}

export async function renderGeneration(content,session={}){const data=await content.readDomain('generation'),ages=['10대','20대','30대','40대','50대','60대+'],candidates=Array.isArray(data?.candidates)?data.candidates:[];if(!candidates.length)return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령','<div class="schedule-empty">후보 데이터는 정치인 DB 이식 단계에서 연결됩니다.</div>');return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령',`<div class="generation-grid">${ages.map(age=>{const results=data?.results?.[age]||{},total=Object.values(results).reduce((a,b)=>a+Number(b||0),0);return `<article class="generation-card"><span class="generation-age">${age}</span><b>세대별 선택</b><p class="module-desc">${total.toLocaleString('ko-KR')}명 참여</p><div class="generation-actions">${candidates.slice(0,8).map(cid=>`<button class="ghost-btn" data-stage-vote="generation:${esc(age)}" data-option="${esc(cid)}">${esc(cid)} · ${Number(results[cid]||0).toLocaleString('ko-KR')}</button>`).join('')}</div></article>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">투표는 로그인 후 참여할 수 있습니다.</p>'}`);}

export async function renderNationalEvaluation(content,session={}){const data=await content.readDomain('nationalEvaluation'),slots=Object.values(data?.slots||{}).filter(x=>x?.subjectId);if(!slots.length)return page('NATIONAL EVALUATION','정참시민 전국 평가제','<div class="schedule-empty">진행 중인 평가가 없습니다</div>');return page('NATIONAL EVALUATION','정참시민 전국 평가제',`<div class="national-eval-layout">${slots.map(slot=>{const r=data?.results?.[slot.evaluationId]||{positive:0,neutral:0,negative:0};return `<div class="eval-person"><span class="eval-avatar"></span><div><small>${esc(slot.slot||'평가')}</small><b>${esc(slot.subjectId)}</b><p>좋음 ${Number(r.positive||0)} · 보통 ${Number(r.neutral||0)} · 아쉬움 ${Number(r.negative||0)}</p><div><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="positive">좋음</button><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="neutral">보통</button><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="negative">아쉬움</button></div></div></div>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">평가는 로그인 후 참여할 수 있습니다.</p>'}`);}

export async function renderAcademy(content,session={}){const data=await content.readDomain('academy'),items=(Array.isArray(data?.slots)?data.slots:[]).filter(x=>x.published!==false).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')));const rows=items.map(item=>`<article data-slot-id="${esc(item.id||'')}"><div><b>${esc(item.date||'일정 준비중')}</b><span>${esc(item.title||'정참시 아카데미')}${item.description?` · ${esc(item.description)}`:''}</span></div><button type="button" data-stage-action="academy-apply">${session.authenticated?'수강 신청':'로그인 후 신청'}</button></article>`).join('')||'<div class="schedule-empty">등록된 일정이 없습니다</div>';return subpage('JEONGCHAMSI ACADEMY','정참시 아카데미','정치를 꿈꾸는 사람이 실제 수강 가능한 일정을 확인하고 신청하는 곳',`<section class="content-card academy-detail-intro"><h2>정치의 꿈을 실제 준비로</h2><p>정치를 꿈꾸는 사람이 실제 수강 가능한 일정을 확인하고 신청하는 곳</p></section><section class="content-card"><div class="section-title"><h2>수강 가능 일정</h2><span>${items.length.toLocaleString('ko-KR')}개</span></div><div class="academy-slot-list">${rows}</div></section>`);}

const requestStatusLabel=status=>({received:'접수',in_progress:'진행중',waiting:'대기중',approved:'승인',rejected:'반려'}[status]||'접수');
export function renderPoliticianRequest({session={},requests=[]}={}){const rows=(requests||[]).map(item=>`<article class="politician-request-row"><div><b>${esc(item.name)}</b><span class="request-status is-${esc(item.status)}">${requestStatusLabel(item.status)}</span><small>${esc(String(item.createdAt||'').slice(0,10))}</small></div>${session.user?.role==='admin'?`<form data-stage-form="politician-request-status" data-request-id="${esc(item.id)}"><select name="status"><option value="received" ${item.status==='received'?'selected':''}>접수</option><option value="in_progress" ${item.status==='in_progress'?'selected':''}>진행중</option><option value="waiting" ${item.status==='waiting'?'selected':''}>대기중</option><option value="approved" ${item.status==='approved'?'selected':''}>승인</option><option value="rejected" ${item.status==='rejected'?'selected':''}>반려</option></select><button class="ghost-btn">상태 저장</button><span data-form-state></span></form>`:''}</article>`).join('');return page('POLITICIAN REQUEST','찾는 정치인이 없나요?',`${session.authenticated?`<form class="stage-form" data-stage-form="politician-request">${field('name','정치인 이름')}<button class="primary-btn">등록 요청</button><span data-form-state></span></form>`:'<section class="content-card"><p>정치인 등록 요청은 로그인 후 이용할 수 있습니다.</p><button class="primary-btn" data-layout-route="/login">로그인</button></section>'}<section class="content-card politician-request-list"><div class="section-title"><h2>등록 요청 현황</h2><span>최신순</span></div>${rows||'<p>접수된 정치인 등록 요청이 없습니다.</p>'}</section>`);}
export function renderPartners({session={},applications=[]}={}){const adminRows=session.user?.role==='admin'?`<section class="content-card partner-application-list"><div class="section-title"><h2>비공개 신청 목록</h2><span>관리자 전용 · 최신순</span></div>${(applications||[]).map(item=>`<article><header><b>${esc(item.name)}</b><span>${esc(item.contact)}</span><small>${esc(item.createdAt)}</small></header><p>${esc(item.message)}</p></article>`).join('')||'<p>접수된 신청이 없습니다.</p>'}</section>`:'';return page('JEONGCHAMSI PARTNERS','정참시 파트너스 신청',`<form class="stage-form" data-stage-form="partner">${field('name','이름 / 단체명')}${field('contact','연락처')}${textarea('message','소개')}<p class="form-private-notice">신청 내용은 공개되지 않으며 관리자만 열람할 수 있습니다.</p><button class="primary-btn">신청</button><span data-form-state></span></form>${adminRows}`);}

export async function renderInquiryBoard(content,session={}){
  const result=await content.listInquiries(),items=Array.isArray(result?.items)?result.items:[],rows=items.map(item=>`<article class="inquiry-row"><a href="#/inquiry/${esc(item.id)}" data-layout-route="/inquiry/${esc(item.id)}"><span class="type">${item.visibility==='private'?'비공개':'공개'}</span><h2>${esc(item.title)}</h2><small>${esc(item.author)} · ${fmt(item.createdAt)} · ${item.answer?'답변 완료':'답변 대기'}</small></a></article>`).join('')||'<div class="schedule-empty">등록된 문의가 없습니다</div>';
  const action=session.authenticated?'<button class="primary-btn" type="button" data-layout-route="/inquiry/write">문의 작성</button>':'<button class="primary-btn" type="button" data-layout-route="/login">로그인 후 문의</button>';
  return subpage('HELP · 1:1 INQUIRY','1:1 문의하기','공개 문의는 누구나 볼 수 있으며, 비공개 문의는 작성자 본인과 관리자만 확인합니다',`<section class="content-card inquiry-board"><div class="board-toolbar"><p>서비스 이용 중 궁금한 점을 남겨주세요.</p>${action}</div><div class="board-list">${rows}</div></section>`);
}
export function renderInquiryWrite(session={}){
  if(!session.authenticated)return renderLogin();
  return subpage('HELP · 1:1 INQUIRY','1:1 문의 작성','관리자가 내용을 확인하고 답변합니다',`<section class="content-card inquiry-write"><div class="inquiry-private-notice">비공개 문의는 작성자 본인과 관리자에게만 공개됩니다.</div><form class="stage-form" data-stage-form="inquiry">${field('title','제목')}<label class="form-field"><span>공개 설정</span><select name="visibility"><option value="public">공개 · 누구나 열람</option><option value="private">비공개 · 작성자와 관리자만 열람</option></select></label>${textarea('body','문의 내용')}<button class="primary-btn" type="submit">문의 등록</button><span data-form-state></span></form></section>`);
}
export async function renderInquiryDetail(id,content,session={}){
  const result=await content.getInquiry(id),item=result?.item;
  if(!item)return page('HELP · 1:1 INQUIRY',result?.error==='INQUIRY_FORBIDDEN'?'열람 권한이 없습니다':'문의를 찾을 수 없습니다','<button class="ghost-btn" type="button" data-layout-route="/inquiry">문의 목록</button>');
  const answer=item.answer?`<section class="content-card inquiry-answer"><span class="eyebrow">ADMIN ANSWER</span><h2>관리자 답변</h2><div class="article-body">${readableBody(item.answer.body)}</div><small>${esc(item.answer.author)} · ${fmt(item.answer.createdAt)}</small></section>`:'<section class="content-card inquiry-answer inquiry-answer-pending"><h2>답변 대기 중입니다</h2><p>관리자가 확인한 뒤 이 페이지에 답변을 남깁니다.</p></section>';
  const reply=session.user?.role==='admin'?`<section class="content-card"><form class="stage-form" data-stage-form="inquiry-reply" data-inquiry-id="${esc(item.id)}">${textarea('body','관리자 답변',item.answer?.body||'')}<button class="primary-btn" type="submit">답변 저장</button><span data-form-state></span></form></section>`:'';
  return `<div class="subpage inquiry-detail jc49"><article class="content-card article-detail"><span class="eyebrow">1:1 INQUIRY · ${item.visibility==='private'?'PRIVATE':'PUBLIC'}</span><h1>${esc(item.title)}</h1><div class="article-meta"><span>${esc(item.author)}</span><span>${fmt(item.createdAt)}</span><span>${item.visibility==='private'?'비공개':'공개'}</span></div><div class="article-body">${readableBody(item.body)}</div>${postEditor('inquiry',item,session)}<div class="article-actions"><button class="ghost-btn" type="button" data-layout-route="/inquiry">문의 목록</button></div></article>${answer}${reply}</div>`;
}

export function renderLogin(){return page('MEMBER','로그인',`<form class="stage-form" data-stage-form="login">${field('id','아이디')}${field('password','비밀번호','password')}<button class="primary-btn">로그인</button><button class="ghost-btn" type="button" data-layout-route="/join">회원가입</button><span data-form-state></span></form>`);}
const addressFields=(user={})=>{const province=user.regionProvince||'',city=user.regionCity||'',district=user.regionDistrict||'',sub=regionSubdistrictOptions(province,city),options=(rows,value,placeholder)=>`<option value="">${placeholder}</option>${rows.map(row=>`<option value="${esc(row)}"${row===value?' selected':''}>${esc(row)}</option>`).join('')}`;return `<label class="form-field"><span>주소 시·도</span><select name="regionProvince" data-region-province required>${options(regionProvinceOptions(),province,'시·도 선택')}</select></label><label class="form-field"><span>주소 시·군·구</span><select name="regionCity" data-region-city required${province?'':' disabled'}>${options(regionDistrictOptions(province),city,'시·군·구 선택')}</select></label><label class="form-field" data-region-district-field${sub.length?'':' hidden'}><span>주소 구</span><select name="regionDistrict" data-region-district${sub.length?' required':' disabled'}>${options(sub,district,'구 선택')}</select></label>`;};
export function renderJoin(){const provinces=regionProvinceOptions().map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');return page('MEMBER','회원가입',`<form class="stage-form join-required-form" data-stage-form="join">${requiredField('id','아이디')}${requiredField('password','비밀번호','password')}${requiredField('nickname','닉네임')}${requiredField('name','이름')}${requiredField('email','이메일','email')}<label class="form-field"><span>전화번호</span><span class="phone-entry"><span data-phone-prefix>010</span><input name="phoneDigits" inputmode="numeric" autocomplete="tel-national" pattern="[0-9]{8}" minlength="8" maxlength="8" placeholder="뒷번호 8자리" required></span></label><label class="form-field"><span>출생년도</span><input name="birthYear" type="number" min="1900" max="${new Date().getFullYear()}" inputmode="numeric" required></label>${addressFields()}${field('referrerCode','추천인코드 (선택)')}<small>추천받은 분의 숫자 코드를 입력해 주세요.</small><p class="form-required-notice">아이디·닉네임·이름·이메일·전화번호·출생년도·주소는 필수정보입니다.</p><button class="primary-btn">가입</button><span data-form-state></span></form>`);}
const BADGE_TIERS=['BRONZE','SILVER','GOLD','PLATINUM','BLACK'];
const BADGE_TIER_LABEL={BRONZE:'브론즈',SILVER:'실버',GOLD:'골드',PLATINUM:'플래티넘',BLACK:'블랙'};

export function renderBadgeCollection(status={},user={}){
  const earned=new Set(status.earnedBadges||[]),eligible=new Set(status.eligibleBadges||[]),showcase=new Set(status.showcaseBadges||[]),representative=status.representativeBadge||'';
  return `<div class="badge-collection">${BADGE_TIERS.map(tier=>{const items=BADGE_CATALOG.filter(item=>item.tier===tier);return `<section class="badge-tier-section badge-tier-${tier.toLowerCase()}" data-badge-tier="${tier}"><header><div><span>${BADGE_TIER_LABEL[tier]}</span><h2>${tier}</h2></div><b>${items.filter(item=>earned.has(item.key)).length} / ${items.length}</b></header><div class="badge-card-grid">${items.map(item=>{const owned=earned.has(item.key),isEligible=eligible.has(item.key),isRepresentative=representative===item.key,isShowcase=showcase.has(item.key),progress=status.progress?.[item.key];const state=owned?(isRepresentative?'대표 배지':isShowcase?'전시 중':'획득 완료'):isEligible?'승인 후보':['GOLD','PLATINUM','BLACK'].includes(tier)?'관리자 승인 필요':'미획득';return `<article class="badge-collection-card ${owned?'is-owned':'is-locked'} ${isEligible?'is-eligible':''}" data-badge-card="${esc(item.key)}">${badgeCrestSvg(item.key)}<div class="badge-card-copy"><span>${esc(item.kind)}</span><h3>${esc(item.name)}</h3><p>${esc(item.mission)}</p>${progress?`<small>${esc(progress.label)} · ${Number(progress.current||0).toLocaleString('ko-KR')} / ${Number(progress.target||0).toLocaleString('ko-KR')}</small>`:''}</div><div class="badge-card-state"><b>${state}</b>${owned?`<button type="button" data-badge-representative="${esc(item.key)}">${isRepresentative?'대표 배지':'대표로 설정'}</button>${isRepresentative?'':`<button type="button" data-badge-showcase="${esc(item.key)}">${isShowcase?'전시 해제':'전시하기'}</button>`}`:''}</div></article>`;}).join('')}</div></section>`;}).join('')}</div>`;
}

export function renderMyActivity(session,status={},search=''){
  if(!session.authenticated)return renderLogin();
  const count=(status.earnedBadges||[]).length;
  return subpage('MY JEONGCHAMSI · BADGES','내 배지 컬렉션','활동으로 획득하고 운영진 승인을 통해 완성하는 정참시의 시민 컬렉션',`<section class="content-card badge-collection-intro"><div><span>COLLECTION STATUS</span><h2>${count}개 획득 · 총 ${BADGE_CATALOG.length}종</h2><p>대표 1개 · 전시 3개를 선택하면 메인 오른쪽 사이드바에 표시됩니다.</p></div><button class="ghost-btn" type="button" data-layout-route="/mypage">마이페이지</button></section>${renderBadgeCollection(status,session.user)}`);
}

const myPostRoute=item=>{const route=item.route||(item.domain==='columns'?'column':item.domain||'community');return `/${esc(route)}/${esc(item.id)}`;};
const myPostRows=items=>(items||[]).map(item=>`<a class="mypage-list-row" href="#${myPostRoute(item)}" data-layout-route="${myPostRoute(item)}"><b>${esc(item.title||'제목 없는 게시글')}</b><small>${esc(({community:'커뮤니티',itsme:'잇츠미',columns:'칼럼',news:'정참시 뉴스',inquiry:'문의'})[item.domain]||'게시글')} · ${fmt(item.createdAt)}</small></a>`).join('')||'<p class="mypage-empty">해당 내역이 없습니다.</p>';
const myBadgeRows=keys=>(keys||[]).map(key=>{const badge=badgeByKey(key);return badge?`<button type="button" class="mypage-badge-row" data-layout-route="/mypage/activity">${badgeCrestSvg(key)}<span><b>${esc(badge.name)}</b><small>${esc(badge.mission)}</small></span></button>`:'';}).join('')||'<p class="mypage-empty">해당 배지가 없습니다.</p>';
const BADGE_TIER_PRIORITY={BLACK:5,PLATINUM:4,GOLD:3,SILVER:2,BRONZE:1};
const highestBadgeKeys=keys=>(keys||[]).map(key=>badgeByKey(key)).filter(Boolean).sort((a,b)=>(BADGE_TIER_PRIORITY[b.tier]||0)-(BADGE_TIER_PRIORITY[a.tier]||0)||BADGE_CATALOG.indexOf(a)-BADGE_CATALOG.indexOf(b)).map(item=>item.key);
const pageNumber=search=>Math.max(1,Number(new URLSearchParams(String(search||'').replace(/^\?/,'')).get('page'))||1);
const paginate=(items,search,size=15)=>{const rows=Array.isArray(items)?items:[],pages=Math.max(1,Math.ceil(rows.length/size)),page=Math.min(pages,pageNumber(search)),start=(page-1)*size;return {rows:rows.slice(start,start+size),page,pages,total:rows.length};};
const pagination=(base,page,pages)=>pages<=1?'':`<nav class="mypage-pagination" aria-label="페이지 이동">${Array.from({length:pages},(_,index)=>{const value=index+1;return `<button type="button" data-page="${value}" ${value===page?'aria-current="page"':''} data-layout-route="${base}?page=${value}">${value}</button>`;}).join('')}</nav>`;
const personAvatar=item=>{const src=imageUrl(item?.photo?.url||item?.photo?.localPath),initial=esc(String(item?.name||'?').slice(0,1));return src?`<span class="mypage-person-avatar has-photo" data-politician-avatar style="--photo-position:${esc(item.photo?.focus||'50% 28%')}"><span>${initial}</span><img data-politician-photo src="${esc(src)}" alt=""></span>`:`<span class="mypage-person-avatar"><span>${initial}</span></span>`;};
const myPeopleRows=(items,full=false)=>(items||[]).map((item,index)=>{const rank=Number(item?.now?.rank||item?.rank||0),klass=full?'mypage-person-rank-row':'mypage-person-row';return `<button type="button" class="${klass}" data-layout-route="/person/${esc(item.id)}">${full?`<strong>${index+1}</strong>`:''}${personAvatar(item)}<div><b>${esc(item.name)}</b><small>${esc([item.party,item.jurisdiction||item.office].filter(Boolean).join(' · '))}</small></div>${rank?`<em>NOW ${rank}위</em>`:''}</button>`;}).join('')||'<p class="mypage-empty">즐겨찾기한 정치인이 없습니다.</p>';

const myCommentRows=items=>(items||[]).map(item=>`<a class="mypage-list-row" href="/${esc(item.route)}/${esc(item.postId)}" data-layout-route="/${esc(item.route)}/${esc(item.postId)}"><b>${esc(item.text||'댓글')}</b><small>${esc(item.postTitle||'게시글')} · ${fmt(item.createdAt)}</small></a>`).join('')||'<p class="mypage-empty">작성한 댓글이 없습니다.</p>';
export function renderMyPoints(result={},full=false,search=''){
 if(!result?.ok)return `<section class="content-card my-points"><h2>내 포인트</h2><p>포인트 내역을 불러오지 못했습니다. 다시 확인해 주세요.</p><button class="ghost-btn" data-layout-route="/points">충전소에서 확인</button></section>`;
 const wallet=result.wallet||{},ledger=[...(wallet.ledger||[])].sort((a,b)=>Number(b.at)-Number(a.at)),charges=ledger.filter(x=>x.type==='charge'),sum=(rows,key)=>rows.reduce((v,x)=>v+Number(x[key]||0),0),n=x=>Number(x||0).toLocaleString('ko-KR'),charged=sum(charges,'points'),spent=-sum(ledger.filter(x=>Number(x.points)<0),'points'),paid=sum(charges,'amount'),paged=paginate(ledger,search,20),items=full?paged.rows:ledger.slice(0,5);
 return `<section class="content-card my-points"><div class="section-title"><h2>내 포인트</h2><button class="ghost-btn" data-layout-route="/points">포인트 충전</button></div><div class="my-point-totals"><div><span>보유 포인트</span><strong>${n(wallet.balance)} P</strong></div><div><span>누적 충전 · 보너스 포함</span><strong>${n(charged)} P</strong><small>충전 금액 ${n(paid)}원</small></div><div><span>누적 사용</span><strong>${n(spent)} P</strong></div></div><div class="my-point-history">${items.map(x=>`<div class="my-point-record"><div><b>${x.type==='charge'?'포인트 충전':'케이지 개설'}</b><small>${fmt(x.at)}${x.type==='charge'?' · '+n(x.amount)+'원 · 보너스 '+n(Number(x.points)-Number(x.amount))+' P':''}</small></div><strong class="${Number(x.points)<0?'is-debit':'is-credit'}">${Number(x.points)>0?'+':''}${n(x.points)} P</strong></div>`).join('')||'<p class="mypage-empty">충전·사용 내역이 없습니다.</p>'}</div>${full?pagination('/mypage/points',paged.page,paged.pages):'<button class="mypage-view-all" data-layout-route="/mypage/points">포인트 내역 전체보기</button>'}<small class="my-point-note">입금 확인 후 지급된 포인트를 기준으로 표시합니다.</small></section>`;
}

function renderMyCollection(session,status,dashboard,options){
  const section=String(options?.section||''),search=options?.search||'';
  if(section==='points')return subpage('MY POINTS','내 포인트','충전과 사용 내역을 확인합니다.',renderMyPoints(dashboard.pointResult,true,search));
  if(section==='comments'){
   const paged=paginate(dashboard.authoredComments,search);
   return subpage('MY JEONGCHAMSI','내가 쓴 댓글',`${paged.total.toLocaleString('ko-KR')}개의 댓글을 최신 순서로 확인합니다.`,`<section class="content-card mypage-collection-page"><div class="section-title"><h2>작성 댓글</h2><button class="ghost-btn" data-layout-route="/mypage">마이페이지</button></div>${myCommentRows(paged.rows)}${pagination('/mypage/comments',paged.page,paged.pages)}</section>`);
  }
  if(section==='authored'||section==='favorite-posts'){
    const authored=section==='authored',items=authored?dashboard.authoredPosts:dashboard.favoritePosts,paged=paginate(items,search),base=authored?'/mypage/posts':'/mypage/favorites/posts';
    return subpage('MY JEONGCHAMSI',authored?'내가 쓴 게시글':'즐겨찾기한 게시글',`${paged.total.toLocaleString('ko-KR')}개의 게시글을 최신 순서로 확인합니다.`,`<section class="content-card mypage-collection-page"><div class="section-title"><h2>${authored?'작성 게시글':'즐겨찾기 게시글'}</h2><button type="button" class="ghost-btn" data-layout-route="/mypage">마이페이지</button></div>${myPostRows(paged.rows)}${pagination(base,paged.page,paged.pages)}</section>`);
  }
  if(section==='favorite-people'){
    const items=dashboard.favoritePeople||[];
    return subpage('MY JEONGCHAMSI','즐겨찾기한 정치인',`${items.length.toLocaleString('ko-KR')}명의 정치인을 즐겨찾기에 보관하고 있습니다.`,`<section class="content-card mypage-collection-page"><div class="section-title"><h2>즐겨찾기한 정치인</h2><button type="button" class="ghost-btn" data-layout-route="/mypage">마이페이지</button></div><div class="mypage-favorite-politician-list">${myPeopleRows(items,true)}</div></section>`);
  }
  return '';
}

export function renderMyPage(session,status={},dashboard={},options={}){
  if(!session.authenticated)return renderLogin();
  if(dashboard.dashboardError)return page('MY JEONGCHAMSI','마이페이지',`<section class="content-card"><h3>활동 내역을 불러오지 못했습니다</h3><p>${esc(dashboard.dashboardError)}</p><button type="button" data-mypage-retry class="ghost-btn">다시 불러오기</button></section>`);
  const collection=renderMyCollection(session,status,dashboard,options);if(collection)return collection;
  const count=(status.earnedBadges||[]).length,required=session.user.mustChangePassword?`<form class="stage-form required-password-form" data-required-password-form><h3>새 비밀번호 설정</h3><p>관리자가 발급한 임시 비밀번호로 로그인했습니다. 계속 사용하려면 새 비밀번호로 변경해 주세요.</p>${field('password','새 비밀번호','password')}<button class="primary-btn">비밀번호 변경</button><span data-form-state></span></form>`:'';
  const authored=dashboard.authoredPosts||[],favoritePosts=dashboard.favoritePosts||[],favoritePeople=dashboard.favoritePeople||[],earned=highestBadgeKeys(status.earnedBadges);
  const sectionHead=(title,countValue,routeValue)=>`<div class="section-title"><h2>${title}</h2><button type="button" class="mypage-view-all" data-layout-route="${routeValue}">전체보기 <span>${countValue.toLocaleString('ko-KR')}</span></button></div>`;
  return page('MY JEONGCHAMSI','마이페이지',`${required}<div class="profile-card mypage-profile"><h3>${esc(session.user.nickname)}님</h3><p>${esc(session.user.id)} · ${esc(session.user.role)}</p><div class="content-card my-referral"><span>내 추천인코드</span><strong>${esc(session.user.referralCode||'발급 확인 중')}</strong>${session.user.referralCode?`<button type="button" class="ghost-btn" data-copy-referral="${esc(session.user.referralCode)}">복사</button>`:''}<small>내 코드로 가입한 회원 ${Number(session.user.referralCount||0).toLocaleString('ko-KR')}명</small></div><details><summary>주소 수정</summary><form class="stage-form" data-stage-form="profile-address">${addressFields(session.user)}<button class="primary-btn">주소 저장</button><span data-form-state></span></form></details><div class="mypage-badge-summary"><span>${status.representativeBadge?badgeCrestSvg(status.representativeBadge):'<i>◇</i>'}</span><div><b>내 배지 컬렉션</b><p>${count}개 획득 · 대표 1개와 전시 3개 설정</p></div><button class="primary-btn" data-layout-route="/mypage/badges">배지 관리</button></div>${session.user.role==='admin'?'<button class="primary-btn" data-layout-route="/admin">관리자 페이지</button>':''}<button class="ghost-btn" data-stage-action="logout">로그아웃</button></div>${renderMyPoints(dashboard.pointResult)}<div class="mypage-dashboard"><section class="content-card" data-mypage-preview="authored">${sectionHead('내가 쓴 게시글',authored.length,'/mypage/posts')}${myPostRows(authored.slice(0,5))}</section><section class="content-card" data-mypage-preview="comments">${sectionHead('내가 쓴 댓글',(dashboard.authoredComments||[]).length,'/mypage/comments')}${myCommentRows((dashboard.authoredComments||[]).slice(0,5))}</section><section class="content-card" data-mypage-preview="badges">${sectionHead('획득한 배지',earned.length,'/mypage/badges')}${myBadgeRows(earned.slice(0,5))}</section><section class="content-card" data-mypage-preview="favorite-posts">${sectionHead('즐겨찾기한 게시글',favoritePosts.length,'/mypage/favorites/posts')}${myPostRows(favoritePosts.slice(0,5))}</section><section class="content-card" data-mypage-preview="favorite-people">${sectionHead('즐겨찾기한 정치인',favoritePeople.length,'/mypage/favorites/politicians')}${myPeopleRows(favoritePeople.slice(0,5))}</section></div>`);
}

export function renderMemberBadgeManager(user={}){
  const grants=new Set(user.grantedBadges||[]),earned=new Set(user.earnedBadges||[]),eligible=new Set(user.eligibleBadges||[]);
  return `<div class="admin-member-badges" data-member-badge-manager="${esc(user.id)}"><section class="admin-member-points" data-member-points-panel="${esc(user.id)}">포인트 정보 확인 중…</section><form class="admin-member-profile-form" data-member-profile-form="${esc(user.id)}"><h3>회원 정보 수정</h3><div class="admin-field-grid">${field('nextId','아이디','text',user.id)}${field('name','이름','text',user.name)}${field('nickname','닉네임','text',user.nickname)}${field('email','이메일','email',user.email)}${field('phone','전화번호','text',user.phone)}${field('birthYear','출생연도','number',user.birthYear)}${field('regionProvince','시·도','text',user.regionProvince)}${field('regionCity','시·군·구','text',user.regionCity)}${field('regionDistrict','세부 지역','text',user.regionDistrict)}${field('preferredParty','선호 정당','text',user.preferredParty)}<label class="form-field"><span>상태</span><select name="status"><option value="active" ${user.status==='suspended'?'':'selected'}>정상</option><option value="suspended" ${user.status==='suspended'?'selected':''}>정지</option></select></label><label class="form-field"><span>권한</span><select name="role"><option value="member" ${user.role==='admin'?'':'selected'}>일반회원</option><option value="admin" ${user.role==='admin'?'selected':''}>관리자</option></select></label></div><button class="primary-btn" type="submit">회원 정보 저장</button><span data-member-profile-state></span></form><form class="admin-password-reset-form" data-member-password-reset="${esc(user.id)}"><label class="form-field"><span>임시 비밀번호</span><input name="temporaryPassword" type="password" minlength="8" autocomplete="new-password" required></label><button class="ghost-btn" type="submit">비밀번호 초기화</button><small>현재 비밀번호는 표시하지 않으며, 모든 기존 로그인은 종료됩니다.</small><span data-member-password-state></span></form><div class="admin-member-badge-summary"><b>${earned.size}개 사용 가능</b><span>수동 해금 ${(user.grantedBadges||[]).length}개 · 대표 ${user.representativeBadge?'설정':'미설정'}</span></div>${BADGE_TIERS.map(tier=>`<fieldset data-admin-badge-tier="${tier}"><legend>${BADGE_TIER_LABEL[tier]} <small>${tier}</small></legend><div>${BADGE_CATALOG.filter(item=>item.tier===tier).map(item=>`<label class="admin-badge-check ${earned.has(item.key)?'is-earned':''} ${eligible.has(item.key)?'is-eligible':''}"><input type="checkbox" data-member-badge="${esc(user.id)}" value="${esc(item.key)}" ${grants.has(item.key)?'checked':''}><span>${badgeCrestSvg(item.key)}<b>${esc(item.name)}</b><small>${eligible.has(item.key)&&!earned.has(item.key)?'승인 후보':earned.has(item.key)?'사용 가능':'잠김'}</small></span></label>`).join('')}</div></fieldset>`).join('')}<button class="primary-btn" type="button" data-member-badge-save="${esc(user.id)}">선택한 배지 해금 저장</button><span class="save-state" data-member-badge-state="${esc(user.id)}"></span></div>`;
}
const renderAdminMemberRow=(user,index)=>{const payload={...user,passwordHash:undefined,password:undefined};return `<details class="admin-member-row" data-member-badge-row="${esc(user.id)}" data-member-badge-payload="${esc(JSON.stringify(payload))}"><summary><span class="community-order">${String(index+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(user.nickname||user.id)}</b><em>${esc(user.id)} · ${esc(user.role)} · ${user.status==='suspended'?'정지':'정상'} · ${fmt(user.createdAt)}</em></span><strong>${Number(user.earnedBadges?.length||0)}개</strong></summary><div data-member-badge-mount></div></details>`;};

const jobLabel=status=>({RUNNING:'진행 중',COMPLETED:'완료',COMPLETED_WITH_ERRORS:'일부 오류',FAILED:'실패'}[status]||'대기');
const jobPanel=(kind,title,job,disabled=false)=>{const total=Number(job?.total||542),completed=Number(job?.completed||0),percent=total?Math.min(100,Math.round(completed/total*100)):0,running=job?.status==='RUNNING',action=kind==='collect'?'전체 수집':'전체 게시',message=job?.lastError?`최종 게시 실패 · ${esc(job.lastError)}`:Number(job?.failed||0)>0?`오류 ${Number(job.failed).toLocaleString('ko-KR')}건 기록됨`:'중단되어도 현재 위치부터 재개됩니다.';return `<article class="admin-job-card" data-intelligence-job="${kind}" data-job-status="${esc(job?.status||'IDLE')}" data-job-blocked="${disabled?'true':'false'}"><header><div><span>${kind==='collect'?'COLLECT & ANALYZE':'VALIDATE & PUBLISH'}</span><h3>${esc(title)}</h3></div><b>${jobLabel(job?.status)}</b></header><div class="admin-job-progress"><i style="width:${percent}%"></i></div><p><strong data-job-progress-text>${completed.toLocaleString('ko-KR')} / ${total.toLocaleString('ko-KR')}</strong><span>${percent}% · 25명 이하 분할 처리</span></p><button class="primary-btn" type="button" data-intelligence-action="${kind}" ${disabled?'disabled':''}>${running?'이어서 처리':action}</button><small data-job-message>${message}</small></article>`;};

const INTELLIGENCE_STAGES=['공식정보 확인','뉴스 수집','중복 제거','핵심 사건 추출','과거 이력 연결','정치인 유형 판별','10대 진단 생성','10대 처방 생성','모순 검수','초안 저장 완료'];
const pipelineStages=collection=>{const percent=Number(collection?.total)?Number(collection?.completed||0)/Number(collection.total):0,active=['COMPLETED','COMPLETED_WITH_ERRORS'].includes(collection?.status)?10:collection?.status==='RUNNING'?Math.max(1,Math.min(9,Math.ceil(percent*9))):0;return `<ol class="admin-pipeline-stages">${INTELLIGENCE_STAGES.map((label,index)=>`<li data-intelligence-stage="${index+1}" class="${index<active?'is-done':index===active?'is-active':''}"><b>${String(index+1).padStart(2,'0')}</b><span>${label}</span></li>`).join('')}</ol>`;};
const collectionErrorPanel=collection=>{const rows=Array.isArray(collection?.failures)?collection.failures:[];if(!rows.length)return '';const groups=new Map();for(const row of rows){const key=`${row.stage||'unknown'} · ${row.code||'SOURCE_ERROR'}`;groups.set(key,(groups.get(key)||0)+1);}return `<section class="admin-collection-errors" data-intelligence-error-report><header><div><span>COLLECTION ERROR REPORT</span><h3>수집 오류 상세</h3></div><div><button class="ghost-btn" type="button" data-intelligence-copy-errors>오류 보고서 복사</button>${rows.some(row=>row.retryable!==false)?'<button class="primary-btn" type="button" data-intelligence-retry-failures>실패 항목만 재시도</button>':''}</div></header><div class="admin-error-groups">${[...groups].map(([label,count])=>`<span><b>${esc(label)}</b><strong>${count}건</strong></span>`).join('')}</div><div class="admin-error-table">${rows.map(row=>`<article data-error-row><b>${esc(row.name||row.personId)}</b><span>${esc(row.personId)}</span><span>${esc(row.stage)} · ${esc(row.code)}</span><p>${esc(row.details||'상세 원인 미기록')}</p><small>${esc(row.at||'')} · ${Number(row.attempts||1)}회 시도 · ${row.retryable===false?'재시도 불가':'재시도 가능'}</small></article>`).join('')}</div></section>`;};
const versionHistory=versions=>`<div class="admin-version-history"><h3>분석 버전 이력</h3>${(versions||[]).map(version=>`<div><b>${esc(version.analysisVersion)}</b><span>${esc(version.status)} · ${esc(version.reviewStatus||'pending')}</span></div>`).join('')||'<p>저장된 분석 버전이 없습니다.</p>'}</div>`;
const releasePanel=intelligence=>{const server=intelligence?.release?.version||APP_RELEASE,mismatch=server!==APP_RELEASE;return `<div class="admin-release-panel ${mismatch?'is-stale':'is-current'}" data-admin-release><span>관리자 화면 버전 <b>${esc(APP_RELEASE)}</b></span><span>서버 버전 <b>${esc(server)}</b></span>${intelligence?.release?.commit?`<span>배포 커밋 <b>${esc(intelligence.release.commit)}</b></span>`:''}${mismatch?'<strong>강력 새로고침 필요</strong>':'<strong>최신 화면 적용됨</strong>'}</div>`;};
const reviewPanel=preview=>{const sample=preview?.reviewSample,version=preview?.version;if(!preview?.ok||!sample)return '<section class="admin-review-panel"><h3>선택 검토·수정</h3><p>수집 완료 후 대표 뉴스, 사건, 유형, 진단과 처방을 필요할 때 수정할 수 있습니다.</p></section>';const type=sample.politicianType||{},diagnosis=sample.diagnoses?.[0],prescription=sample.prescriptions?.[0],pastRisks=(diagnosis?.display?.pastRisks||[]).map(row=>[row.tag,row.title,row.url,row.date].filter(Boolean).join(' | ')).join('\n'),targets=(preview.reviewTargets||[{id:sample.personId,name:sample.personId}]).map(person=>`<option value="${esc(person.id)}"${person.id===sample.personId?' selected':''}>${esc(person.name)} · ${esc(person.id)}</option>`).join('');return `<section class="admin-review-panel"><header><div><span>JCS INTELLIGENCE REVIEW</span><h3>선택 검토·수정</h3></div><b>${esc(version?.status||'draft')}</b></header><div class="admin-review-summary"><div><small>검토 정치인</small><strong>${esc(sample.personId)}</strong></div><div><small>주유형</small><strong>${esc(type.primaryType)}</strong></div><div><small>현재 국면</small><strong>${esc(type.currentPhase)}</strong></div><div><small>구성</small><strong>진단 ${Number(sample.diagnoses?.length||0)}개 · 처방 ${Number(sample.prescriptions?.length||0)}개</strong></div></div><div class="admin-review-events"><h4>핵심 사건</h4>${(sample.eventClusters||[]).map(event=>`<p><b>${esc(event.eventType)}</b><span>${esc(event.eventTitle)}</span></p>`).join('')||'<p>공식 역할 기반 구조 분석</p>'}</div><form class="admin-review-edit" data-intelligence-draft-form data-person-id="${esc(sample.personId)}"><label>01 핵심 진단<textarea name="diagnosisHeadline">${esc(diagnosis?.headline||'')}</textarea></label><label>01 전략 판단<textarea name="prescriptionJudgment">${esc(prescription?.strategicJudgment||'')}</textarea></label><button class="ghost-btn" type="submit">수정본 저장</button><span data-intelligence-draft-state></span></form><form class="admin-review-edit" data-intelligence-past-risk-form><h4>PAST RISK SIGNALS 별도 편집</h4><label>대상 정치인<select name="personId" required>${targets}</select></label><label>근거 신호 <small>한 줄마다 #태그 | 근거 제목 | https://근거링크 | 날짜, 최대 5개</small><textarea name="pastRisks">${esc(pastRisks)}</textarea></label><button class="ghost-btn" type="submit">PAST RISK SIGNALS만 저장</button><span data-intelligence-draft-state></span></form><div class="admin-validation-report"><b>자동 검수 ${preview.validation?.ok?'통과':'미통과'}</b><span>${(preview.validation?.errors||[]).map(esc).join(' · ')||'차단 오류 없음 · 바로 게시 가능'}</span></div></section>`;};

const politicianEditor=(row,selectedPerson='')=>{
  const profile=row.profile||{},record=row.record||{},photo=row.photo||{},photoUrl=photo.url||photo.localPath||'',pastRisks=(record.pastRisks||[]).map(item=>[item.tag,item.title,item.url,item.date].join(' | ')).join('\n'),exclusions=(record.newsExclusions||[]).join('\n');
  return `<details class="admin-politician-row" data-admin-politician="${esc(profile.id)}"${String(selectedPerson)===String(profile.id)?' open':''}><summary><b>${esc(profile.name||profile.id)}</b><span>${esc(profile.party)} · ${esc(profile.jurisdiction||profile.office||'')}</span><small>${esc(profile.id)}</small></summary><div class="admin-politician-editor"><form data-politician-photo-form="${esc(profile.id)}" data-current-photo="${photoUrl?'true':'false'}"><h4>프로필 사진</h4><div class="admin-politician-photo-preview" data-politician-photo-preview>${photoUrl?`<img src="${esc(photoUrl)}" alt="${esc(profile.name)} 현재 프로필 사진">`:'<span>사진을 선택하면 업로드 전 미리보기가 표시됩니다.</span>'}</div><input data-politician-photo-input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required><input name="focus" value="${esc(photo.focus||'50% 22%')}" aria-label="사진 초점"><button class="ghost-btn" type="submit">${photoUrl?'사진 교체':'사진 업로드'}</button><small>JPG·PNG·WEBP, 최대 1MB</small><span data-politician-state></span></form><form data-politician-risk-form="${esc(profile.id)}"><h4>PAST RISK SIGNALS</h4><textarea name="pastRisks" rows="5" placeholder="#해시태그 | 기사 제목 | https://기사주소 | YYYY-MM-DD">${esc(pastRisks)}</textarea><button class="ghost-btn" type="submit">영구 저장</button><span data-politician-state></span></form><form data-politician-exclusion-form="${esc(profile.id)}"><h4>뉴스 오탐 제외</h4><textarea name="newsExclusions" rows="3" placeholder="기사 fingerprint 또는 source:기사제목">${esc(exclusions)}</textarea><button class="ghost-btn" type="submit">제외 목록 저장</button><span data-politician-state></span></form><form data-youtube-channel-form="${esc(profile.id)}"><h4>공식 유튜브</h4><input name="reference" value="${esc(row.youtube?.channelUrl||row.youtube?.channelId||'')}" placeholder="채널 URL, @handle 또는 UC 채널 ID" required><button class="ghost-btn" type="submit">채널 저장</button></form>${row.youtube?.channelId?`<button class="ghost-btn is-danger" type="button" data-youtube-delete="${esc(profile.id)}">유튜브 연결 삭제</button>`:''}<div class="admin-person-refresh"><h4>한 명만 수집·게시</h4><button class="ghost-btn" type="button" data-person-refresh="${esc(profile.id)}">새로 수집</button><button class="primary-btn" type="button" data-person-publish="${esc(profile.id)}">게시</button><small>자동 검증을 통과한 수집본은 별도 승인 없이 게시할 수 있습니다. 전체 순위는 다음 전체 게시까지 기존 값을 유지합니다.</small><span data-person-action-state role="status" aria-live="polite"></span></div></div></details>`;
};
export const renderAdminAuditPanel=value=>`<section class="admin-audit-panel"><div class="section-title"><h2>관리자 작업 기록</h2><span>최근 ${(value?.entries||[]).length}건</span></div><div>${(value?.entries||[]).slice(0,50).map(row=>{const details=Object.entries(row.details||{}).filter(([,item])=>item!==undefined&&item!==null&&item!=='').map(([key,item])=>`${key}: ${Array.isArray(item)?item.join(' · '):item}`).join(' / ');return `<article><b>${esc(row.action)}</b><span>${esc(row.actor)} · ${esc(row.personId||'')}</span><small>${esc(row.at)}</small>${details?`<p>${esc(details)}</p>`:''}</article>`;}).join('')||'<p>아직 관리자 변경 기록이 없습니다.</p>'}</div></section>`;

export async function renderAdminStable(session,auth,state={}){
  if(!session.authenticated)return renderLogin();if(session.user?.role!=='admin')return page('ADMIN','접근 권한이 없습니다','<p class="module-desc">관리자 계정만 접근할 수 있습니다.</p>');
  const routeState=typeof state==='string'?{q:state}:state||{},allowedTabs=new Set(['operations','members','politicians','pipeline','site','keywords','participation']),activeTab=allowedTabs.has(routeState.tab)?routeState.tab:'operations',query=String(routeState.q||''),selectedPerson=String(routeState.person||'');
  if(activeTab==='keywords'){const result=await auth.keywordRules(),rules=result.rules||{},lines=object=>Object.entries(object||{}).map(([from,to])=>`${from} = ${to}`).join('\n');return page('ADMIN · KEYWORDS','정치키워드 관리',`<nav class="admin-tabs"><button data-admin-tab="operations">운영현황</button><button data-admin-tab="members">회원관리</button><button data-admin-tab="politicians">정치인정보</button><button data-admin-tab="pipeline">데이터수집·게시</button><button data-admin-tab="site">풋터정보</button><button class="is-active" data-admin-tab="keywords">정치키워드</button><button data-admin-tab="participation">참여·데모</button></nav><form class="stage-form" data-keyword-rules-form>${textarea('hidden','숨길 키워드 · 한 줄에 하나',(rules.hidden||[]).join('\n'))}${textarea('pinned','상단 고정 키워드 · 실제 집계된 키워드만 노출',(rules.pinned||[]).join('\n'))}${textarea('aliases','유사어 통합 · 기존 키워드 = 대표 키워드',lines(rules.aliases))}${textarea('labels','표현 수정 · 키워드 = 표시할 이름',lines(rules.labels))}<button class="primary-btn">설정 저장</button><span data-form-state></span></form>`);}
  const [summary,users,intelligence,preview,politicians,footerResult]=await Promise.all([
    activeTab==='operations'?auth.adminSummary():{ok:true,contents:{},users:{}},
    activeTab==='members'?auth.exportMembers():[],
    activeTab==='pipeline'?auth.intelligenceStatus():{},
    {ok:false},
    activeTab==='politicians'&&auth.adminPoliticians?auth.adminPoliticians(query):{ok:true,items:[],completeness:{total:0,complete:0,missing:{}}},
    activeTab==='site'&&auth.footerInfo?auth.footerInfo():{ok:true,info:{}}
  ]);

  if(!summary.ok)return page('ADMIN','관리자 데이터 연결 대기',`<p class="module-desc">${esc(summary.error||'저장소 연결을 확인해 주세요.')}</p>`);
  const entries=Object.entries(summary.contents||{}),collection=intelligence.collection||null,publication=intelligence.publication||null,validation=intelligence.validation||null,naver=intelligence.sources?.naverSearchAds||{},activeSnapshot=intelligence.latestDraft||collection?.snapshotId||'',activeVersion=(intelligence.versions||[]).find(version=>version.analysisVersion===activeSnapshot)||preview?.version||null;
  const publishReady=['COMPLETED','COMPLETED_WITH_ERRORS'].includes(collection?.status)&&validation?.ok===true;
  const pipeline=`<section class="admin-intelligence-console">${releasePanel(intelligence)}<div class="admin-console-head"><div><span>JCS POLITICAL DATA PIPELINE</span><h2>정치인 데이터 수집 · 분석 · 게시</h2><p>542명의 실제 정치인을 25명 이하 단위로 처리합니다. 수집 완료 후 자동 검증을 통과한 자료는 별도 승인 없이 게시할 수 있습니다.</p></div><div class="admin-source-status ${naver.configured?'is-ready':'is-missing'}"><small>NAVER SEARCH ADS</small><strong>${naver.configured?'연결됨':'연결 필요'}</strong><span>${naver.configured?'PC·모바일 검색량 수집 가능':'Vercel 환경변수 3개만 연결하면 활성화'}</span></div></div>${pipelineStages(collection)}<div class="admin-job-grid">${jobPanel('collect','전체 정치인 원자료 수집·JCS 분석',collection,!naver.configured)}${jobPanel('publish','자동 검증 통과본 전체 게시',publication,!publishReady&&publication?.status!=='RUNNING')}</div>${collectionErrorPanel(collection)}<div class="admin-snapshot-status"><span>수집 스냅샷 <b>${esc(activeSnapshot||'없음')}</b></span><span>현재 공개 스냅샷 <b>${esc(intelligence.publicSnapshot||'없음')}</b></span><span>검증 <b>${validation?.ok?'통과':validation?'미통과':'대기'}</b></span></div><section class="admin-review-panel" data-admin-review-mount><button class="ghost-btn" type="button" data-load-admin-review>분석 미리보기 불러오기</button></section>${versionHistory(intelligence.versions)}</section>`;
  const completeness=politicians.completeness||{missing:{}},overview=`<div class="national-eval-layout"><div class="eval-question"><strong>회원</strong><p>전체 ${Number(summary.users?.total||0).toLocaleString('ko-KR')}명 · 관리자 ${Number(summary.users?.admins||0).toLocaleString('ko-KR')}명</p></div>${entries.map(([k,v])=>`<div class="eval-question"><strong>${esc(k)}</strong><p>${Number(v||0).toLocaleString('ko-KR')}건</p></div>`).join('')}</div><details class="admin-audit-disclosure" data-admin-audit-disclosure><summary>관리자 작업 기록 펼치기</summary><div data-admin-audit-mount><p>펼치면 최근 작업 기록을 불러옵니다.</p></div></details>`;
  const members=`<section class="admin-member-section"><div class="section-title"><h2>회원 정보·상태·권한·배지 관리</h2><span>비밀번호는 조회하지 않고 임시 비밀번호로만 초기화합니다</span></div><div class="admin-member-list">${users.map(renderAdminMemberRow).join('')}</div></section>`;
  const politicianPanel=`<section class="admin-politician-section"><div class="section-title"><h2>정치인 정보 관리</h2><span>전체 정치인 검색 · 사진 · PAST RISK · 뉴스 제외 · 유튜브 · 한 명 게시</span></div><form class="admin-politician-search" data-admin-politician-search role="search"><input name="q" value="${esc(query)}" placeholder="한 글자부터 이름·정당·지역 검색" autocomplete="off" data-politician-autocomplete data-politician-select-mode="admin"><button class="primary-btn">검색</button></form><div class="admin-politician-list">${(politicians.items||[]).map(row=>politicianEditor(row,selectedPerson)).join('')||'<p>정치인을 검색해 편집하세요.</p>'}</div></section>`;
  const footerInfo=footerResult?.info||{},sitePanel=`<section class="admin-site-settings"><div class="section-title"><h2>풋터 운영·사업자 정보</h2><span>입력하고 저장한 항목만 서비스 풋터에 공개됩니다</span></div><form class="stage-form admin-footer-info-form" data-footer-info-form><div class="admin-field-grid">${field('siteName','사이트명','text',footerInfo.siteName)}${field('businessName','운영·사업자명','text',footerInfo.businessName)}${field('businessRegistrationNumber','사업자등록번호','text',footerInfo.businessRegistrationNumber)}${field('mailOrderRegistrationNumber','통신판매업 신고번호','text',footerInfo.mailOrderRegistrationNumber)}${field('representative','대표자','text',footerInfo.representative)}${field('phone','대표전화','text',footerInfo.phone)}${field('fax','팩스','text',footerInfo.fax)}${field('address','주소','text',footerInfo.address)}${field('privacyOfficer','개인정보 보호책임자','text',footerInfo.privacyOfficer)}${field('privacyEmail','개인정보 문의 이메일','email',footerInfo.privacyEmail)}${field('adEmail','광고 문의 이메일','email',footerInfo.adEmail)}${field('customerEmail','고객센터 이메일','email',footerInfo.customerEmail)}${field('partnerEmail','파트너 문의 이메일','email',footerInfo.partnerEmail)}${field('managementEmail','경영지원 문의 이메일','email',footerInfo.managementEmail)}</div>${textarea('disclaimer','책임 고지',footerInfo.disclaimer)}<button class="primary-btn" type="submit">풋터 정보 저장</button><span data-form-state role="status"></span></form></section>`;
  const tabButton=(key,label)=>`<button${activeTab===key?' class="is-active"':''} data-admin-tab="${key}">${label}</button>`,panel=(key,body)=>activeTab!==key?'':`<div class="admin-tab-panel${activeTab===key?' is-active':''}" data-admin-panel="${key}"${activeTab===key?'':' hidden'}>${body}</div>`;
  const tabs=`<nav class="admin-tabs" aria-label="관리자 메뉴">${tabButton('operations','운영현황')}${tabButton('members','회원관리')}${tabButton('politicians','정치인정보')}${tabButton('pipeline','데이터수집·게시')}${tabButton('site','풋터정보')}${tabButton('keywords','정치키워드')}${tabButton('participation','참여·데모')}</nav>${panel('operations',overview)}${panel('members',members)}${panel('politicians',politicianPanel)}${panel('pipeline',pipeline)}${panel('site',sitePanel)}`;
  return page('ADMIN · CONTROL CENTER','회원 · 정치인 · 데이터 운영 관리',tabs);
}

export function renderMigration(){return page('JCS_0_0_8 · ONE-TIME MIGRATION','기존 데이터 이식',`<div class="legal-copy"><p>회원·게시판 이식과 정치인 기본 DB 이식을 서로 분리해 실행합니다.</p><p>정치인 DB에는 합의된 프로필·정치 기록·등록 사진만 저장하며 NOW 점수·순위·분석값은 포함하지 않습니다.</p></div><form class="stage-form" data-stage-form="migration">${field('secret','마이그레이션 키','password')}<button class="primary-btn">회원·게시판 이식 실행</button><span data-form-state></span></form><form class="stage-form politician-migration-form" data-stage-form="politician-migration">${field('secret','정치인 DB 이관 키','password')}<button class="primary-btn">정치인 DB 543개 슬롯 이식</button><span data-form-state></span></form>`);}
import { APP_RELEASE } from '../core/release.js?v=0.0.31.118';

export function renderAdminLoading(tab='operations'){
 const labels={operations:'운영현황',members:'회원관리',politicians:'정치인정보',pipeline:'데이터수집·게시',site:'풋터정보',keywords:'정치키워드',participation:'참여·데모'};
 return page('ADMIN · CONTROL CENTER','회원 · 정치인 · 데이터 운영 관리',`<nav class="admin-tabs" aria-label="관리자 메뉴">${Object.entries(labels).map(([key,label])=>`<button type="button" data-admin-tab="${key}" class="${key===tab?'is-active':''}">${label}</button>`).join('')}</nav><div role="status" aria-live="polite" class="content-card">${labels[tab]||'운영현황'}을 불러오는 중입니다.</div>`);
}

export const renderAdminReview=reviewPanel;

export function renderAdminMemberPoints(result={},userId=''){
 const n=x=>Number(x||0).toLocaleString('ko-KR'),uid=esc(userId),token=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
 if(!result.ok)return `<p>포인트 정보를 불러오지 못했습니다.</p><button type="button" data-member-points-retry="${uid}">다시 불러오기</button>`;
 const wallet=result.wallet||{},pending=(result.orders||[]).filter(o=>o.status==='pending');
 return `<h3>회원 포인트 관리</h3><p>보유 <strong>${n(wallet.balance)} P</strong> · ${wallet.firstPaid?'일반 충전 보너스 적용':'첫 충전 20% 보너스 적용'}</p><h4>충전 신청 · 입금 확인 대기 ${pending.length}건</h4>${pending.map(o=>`<form data-point-form="review"><input type="hidden" name="id" value="${esc(o.id)}"><p><b>${n(o.amount)}원</b> · 입금자 ${esc(o.depositor)} · ${fmt(o.createdAt)}</p><label><input type="checkbox" name="confirmed">실제 입금을 확인했습니다</label><div><button type="submit" name="decision" value="approve" class="primary-btn">입금 확인 · 포인트 지급</button><button type="submit" name="decision" value="reject" class="ghost-btn">신청 반려</button></div><span data-form-state role="status"></span></form>`).join('')||'<p>대기 중인 충전 신청이 없습니다.</p>'}<details><summary>충전 신청 없이 입금한 회원에게 직접 지급</summary><form data-point-form="grant" data-first-charge="${!wallet.firstPaid}"><input type="hidden" name="userId" value="${uid}"><input type="hidden" name="requestId" value="${token()}"><label>실제 입금액<select name="amount" data-admin-charge-amount>${[10000,30000,50000,100000,500000,1000000].map(x=>`<option value="${x}">${n(x)}원</option>`).join('')}</select></label><p data-admin-charge-preview>지급 예정 ${wallet.firstPaid?'10,000':'12,000'} P</p><label>입금 확인 내역<input name="reason" required maxlength="200" placeholder="입금자명 · 입금 일시 등"></label><label><input type="checkbox" name="confirmed" required>실제 입금을 확인했으며, 위 충전 신청으로 이미 지급한 건이 아닙니다</label><button type="submit" class="primary-btn">포인트 지급</button><span data-form-state role="status"></span></form></details><h4>최근 충전·사용 내역</h4>${(wallet.ledger||[]).slice(-5).reverse().map(x=>`<p>${fmt(x.at)} · ${x.type==='charge'?'충전':'케이지 개설'} <b>${n(x.points)} P</b></p>`).join('')||'<p>내역 없음</p>'}`;
}
