const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{try{return new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium'}).format(new Date(v));}catch{return ''}};
const page=(eyebrow,title,body)=>`<section class="module"><div class="module-header"><div><span class="eyebrow">${esc(eyebrow)}</span><h2>${esc(title)}</h2></div></div>${body}</section>`;
const field=(name,label,type='text',value='')=>`<label class="form-field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}"></label>`;
const textarea=(name,label,value='')=>`<label class="form-field"><span>${esc(label)}</span><textarea name="${esc(name)}" rows="8">${esc(value)}</textarea></label>`;

export function renderAbout(){return page('ABOUT JEONGCHAMSI','왜 정참시인가',`<div class="legal-copy"><p>정참시는 시민이 정치 정보를 더 쉽게 이해하고, 비교하고, 선택하고, 평가할 수 있는 공간을 만듭니다.</p><p>정치를 보는 것에서 움직이는 것으로. 정참시는 데이터와 참여를 연결합니다.</p></div>`);}
export function renderSupport(){return page('SUPPORT','정참시 후원하기',`<div class="legal-copy"><p>정치에 참여할 수 있는 더 나은 공간을 함께 만들어 주세요.</p><p>후원은 서비스 운영, 데이터 정비, 콘텐츠 제작, 시민 참여 기능 개선에 사용됩니다.</p></div>`);}
export function renderLegal(type){const map={guide:['이용안내','정참시의 메뉴와 참여 기능을 이용하는 방법을 안내합니다.'],privacy:['개인정보처리방침','회원 정보는 서비스 제공과 계정 관리 목적에 필요한 범위에서 처리합니다.'],policy:['운영정책','정참시는 건전한 참여와 정보 공유를 위한 운영 원칙을 적용합니다.']};const [t,b]=map[type]||map.guide;return page('JEONGCHAMSI',t,`<div class="legal-copy"><p>${esc(b)}</p></div>`);}

export async function renderBoard(domain,content,session={}){const labels={columns:['COLUMN','정참시 COLUMN'],community:['COMMUNITY','정뮤니티']};const [e,t]=labels[domain]||labels.community;const items=await content.list(domain);const canWrite=domain==='community'?session.authenticated:['admin','partner'].includes(session.user?.role);return page(e,t,`<div class="board-toolbar">${canWrite?`<button class="primary-btn" type="button" data-layout-route="/${domain==='columns'?'column':'community'}/write">글쓰기</button>`:''}</div><div class="community-list">${items.filter(x=>x.published!==false).map((x,i)=>`<article class="community-row" data-layout-route="/${domain==='columns'?'column':'community'}/${esc(x.id)}"><span class="community-order">${String(i+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(x.title)}</b><em>${esc(x.author||'정참시')} · ${fmt(x.createdAt)}</em></span><span class="community-stats">좋아요 ${Number(x.likes||0).toLocaleString('ko-KR')} · 보기 →</span></article>`).join('')||'<div class="schedule-empty">등록된 글이 없습니다</div>'}</div>`);}

async function commentsBlock(domain,id,content,session){const comments=await content.commentsFor(domain,id);return `<div class="community-list">${comments.map((c,i)=>`<article class="community-row"><span class="community-order">${String(i+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(c.author||'회원')}</b><em>${fmt(c.createdAt)}</em><p>${esc(c.text||'')}</p></span></article>`).join('')||'<div class="schedule-empty">등록된 댓글이 없습니다</div>'}</div>${session?.authenticated?`<form class="stage-form" data-stage-form="comment" data-domain="${esc(domain)}" data-post-id="${esc(id)}">${textarea('text','댓글')}<button class="primary-btn">댓글 등록</button><span data-form-state></span></form>`:'<button class="ghost-btn" data-layout-route="/login">로그인 후 댓글쓰기</button>'}`;}

export async function renderBoardDetail(domain,id,content,session={}){const item=await content.get(domain,id);if(!item)return page('CONTENT','글을 찾을 수 없습니다','<button class="ghost-btn" data-layout-route="/">메인으로</button>');const comments=await commentsBlock(domain,id,content,session);return page(domain==='columns'?'COLUMN':'COMMUNITY',item.title,`<div class="legal-copy"><p class="module-desc">${esc(item.author||'정참시')} · ${fmt(item.createdAt)}</p><p>${esc(item.body||'').replace(/\n/g,'<br>')}</p></div><div class="board-toolbar"><button class="ghost-btn" data-post-like data-domain="${esc(domain)}" data-post-id="${esc(id)}">좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')}</button></div>${comments}`);}
export function renderBoardWrite(domain){const label=domain==='columns'?'COLUMN':'COMMUNITY';return page(label,'글쓰기',`<form class="stage-form" data-stage-form="board" data-domain="${domain}">${field('title','제목')}${textarea('body','내용')}<button class="primary-btn" type="submit">저장</button><span class="save-state" data-form-state></span></form>`);}

export async function renderItsme(content){const data=await content.readDomain('itsme'),items=Array.isArray(data?.items)?data.items:[];const categories=Array.isArray(data?.categories)?data.categories:[];return page("IT’S ME",'나는 이렇게 제안합니다',`<div class="board-toolbar"><button class="primary-btn" data-layout-route="/itsme/write">정책 제안하기</button></div>${categories.length?`<p class="module-desc">${categories.map(esc).join(' · ')}</p>`:''}<div class="itsme-grid">${items.filter(x=>x.published!==false).map((x,i)=>`<article class="itsme-card" data-layout-route="/itsme/${esc(x.id)}"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(x.title)}</b><p>${esc(x.author||'정참시')}</p></article>`).join('')||'<div class="schedule-empty">등록된 제안이 없습니다</div>'}</div>`);}
export function renderItsmeWrite(){return page("IT’S ME",'정책 제안하기',`<form class="stage-form" data-stage-form="itsme">${field('title','제안 제목')}${field('category','카테고리')}${textarea('body','제안 내용')}<button class="primary-btn">등록</button><span data-form-state></span></form>`);}
export async function renderItsmeDetail(id,content,session={}){const x=await content.get('itsme',id);if(!x)return page("IT’S ME",'제안을 찾을 수 없습니다','');const comments=await commentsBlock('itsme',id,content,session);return page("IT’S ME",x.title,`<div class="legal-copy"><p class="module-desc">${esc(x.author||'정참시')} · ${fmt(x.createdAt)}</p><p>${esc(x.body||'').replace(/\n/g,'<br>')}</p></div><div class="board-toolbar"><button class="ghost-btn" data-post-like data-domain="itsme" data-post-id="${esc(id)}">좋아요 ${Number(x.likes||0).toLocaleString('ko-KR')}</button></div>${comments}`);}

export async function renderPoll(content,session={}){const data=await content.readDomain('polls'),poll=(data?.items||[]).find(x=>x.published!==false);if(!poll)return page("CITIZENS’ CHOICE",'시민들의 선택','<div class="schedule-empty">진행 중인 설문이 없습니다</div>');const opts=Array.isArray(poll.options)?poll.options:[],total=opts.reduce((a,o)=>a+Number(o.votes||0),0);return page("CITIZENS’ CHOICE",'귀담아 들어야 합니다',`<div class="poll-main"><div class="poll-question"><span class="poll-status">진행중</span><h3>${esc(poll.question||'시민 설문')}</h3><p>${esc(poll.description||'')}</p></div><div class="poll-options">${opts.map(o=>{const n=Number(o.votes||0),p=total?Math.round(n*100/total):0;return `<button type="button" data-stage-vote="poll:${esc(poll.id)}" data-option="${esc(o.id)}"><span>${esc(o.label)}</span><i><em style="width:${p}%"></em></i><b>${p}%</b></button>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">투표는 로그인 후 참여할 수 있습니다.</p>'}</div>`);}

export async function renderGeneration(content,session={}){const data=await content.readDomain('generation'),ages=['10대','20대','30대','40대','50대','60대+'],candidates=Array.isArray(data?.candidates)?data.candidates:[];if(!candidates.length)return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령','<div class="schedule-empty">후보 데이터는 정치인 DB 이식 단계에서 연결됩니다.</div>');return page('GENERATION CHOICE · MOCK VOTE','세대의 선택, 대통령',`<div class="generation-grid">${ages.map(age=>{const results=data?.results?.[age]||{},total=Object.values(results).reduce((a,b)=>a+Number(b||0),0);return `<article class="generation-card"><span class="generation-age">${age}</span><b>세대별 선택</b><p class="module-desc">${total.toLocaleString('ko-KR')}명 참여</p><div class="generation-actions">${candidates.slice(0,8).map(cid=>`<button class="ghost-btn" data-stage-vote="generation:${esc(age)}" data-option="${esc(cid)}">${esc(cid)} · ${Number(results[cid]||0).toLocaleString('ko-KR')}</button>`).join('')}</div></article>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">투표는 로그인 후 참여할 수 있습니다.</p>'}`);}

export async function renderNationalEvaluation(content,session={}){const data=await content.readDomain('nationalEvaluation'),slots=Object.values(data?.slots||{}).filter(x=>x?.subjectId);if(!slots.length)return page('NATIONAL EVALUATION','정참시민 전국 평가제','<div class="schedule-empty">진행 중인 평가가 없습니다</div>');return page('NATIONAL EVALUATION','정참시민 전국 평가제',`<div class="national-eval-layout">${slots.map(slot=>{const r=data?.results?.[slot.evaluationId]||{positive:0,neutral:0,negative:0};return `<div class="eval-person"><span class="eval-avatar"></span><div><small>${esc(slot.slot||'평가')}</small><b>${esc(slot.subjectId)}</b><p>좋음 ${Number(r.positive||0)} · 보통 ${Number(r.neutral||0)} · 아쉬움 ${Number(r.negative||0)}</p><div><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="positive">좋음</button><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="neutral">보통</button><button class="ghost-btn" data-stage-vote="national:${esc(slot.evaluationId)}::${esc(slot.subjectId)}" data-option="negative">아쉬움</button></div></div></div>`}).join('')}</div>${session.authenticated?'':'<p class="module-desc">평가는 로그인 후 참여할 수 있습니다.</p>'}`);}

export async function renderAcademy(content,session={}){const data=await content.readDomain('academy'),items=Array.isArray(data?.slots)?data.slots:[];return page('JEONGCHAMSI ACADEMY','정참시 아카데미',`<div class="academy-layout"><div class="academy-intro"><span class="academy-mark">A</span><h3>정치의 꿈을 실제 준비로</h3><button data-stage-action="academy-apply">수강 신청</button></div><div class="academy-schedule"><div class="schedule-head"><b>예정 교육 일정</b><span>${items.length}개</span></div>${items.filter(x=>x.published!==false).map(x=>`<div class="schedule-item" data-slot-id="${esc(x.id||'')}"><b>${esc(x.title)}</b><span>${esc(x.date||'일정 준비중')}</span></div>`).join('')||'<div class="schedule-empty">등록된 일정이 없습니다</div>'}</div></div>${session.authenticated?'':'<p class="module-desc">신청은 로그인 후 가능합니다.</p>'}`);}

export function renderPoliticianRequest(){return page('POLITICIAN REQUEST','찾는 정치인이 없나요?',`<form class="stage-form" data-stage-form="politician-request">${field('name','정치인 이름')}<button class="primary-btn">등록 요청</button><span data-form-state></span></form>`);}
export function renderPartners(){return page('JEONGCHAMSI PARTNERS','정참시 파트너스 신청',`<form class="stage-form" data-stage-form="partner">${field('name','이름 / 단체명')}${field('contact','연락처')}${textarea('message','소개')}<button class="primary-btn">신청</button><span data-form-state></span></form>`);}

export function renderLogin(){return page('MEMBER','로그인',`<form class="stage-form" data-stage-form="login">${field('id','아이디')}${field('password','비밀번호','password')}<button class="primary-btn">로그인</button><button class="ghost-btn" type="button" data-layout-route="/join">회원가입</button><span data-form-state></span></form>`);}
export function renderJoin(){return page('MEMBER','회원가입',`<form class="stage-form" data-stage-form="join">${field('id','아이디')}${field('password','비밀번호','password')}${field('name','이름')}${field('nickname','닉네임')}${field('email','이메일','email')}${field('birthYear','출생연도')}${field('regionProvince','시/도')}${field('regionCity','시/군/구')}<button class="primary-btn">가입</button><span data-form-state></span></form>`);}
export function renderMyPage(session){if(!session.authenticated)return renderLogin();return page('MY JEONGCHAMSI','마이페이지',`<div class="profile-card"><h3>${esc(session.user.nickname)}님</h3><p>${esc(session.user.id)} · ${esc(session.user.role)}</p>${session.user.role==='admin'?'<button class="primary-btn" data-layout-route="/admin">관리자 페이지</button>':''}<button class="ghost-btn" data-stage-action="logout">로그아웃</button></div>`);}

export async function renderAdminStable(session,auth){if(!session.authenticated)return renderLogin();if(session.user?.role!=='admin')return page('ADMIN','접근 권한이 없습니다','<p class="module-desc">관리자 계정만 접근할 수 있습니다.</p>');const summary=await auth.adminSummary(),users=await auth.exportMembers();if(!summary.ok)return page('ADMIN','관리자 데이터 연결 대기',`<p class="module-desc">${esc(summary.error||'저장소 연결을 확인해 주세요.')}</p>`);const entries=Object.entries(summary.contents||{});return page('ADMIN · STABLE DATA','회원 · 콘텐츠 관리',`<div class="national-eval-layout"><div class="eval-question"><strong>회원</strong><p>전체 ${Number(summary.users?.total||0).toLocaleString('ko-KR')}명 · 관리자 ${Number(summary.users?.admins||0).toLocaleString('ko-KR')}명</p></div>${entries.map(([k,v])=>`<div class="eval-question"><strong>${esc(k)}</strong><p>${Number(v||0).toLocaleString('ko-KR')}건</p></div>`).join('')}</div><div class="community-list">${users.slice(0,200).map((u,i)=>`<article class="community-row"><span class="community-order">${String(i+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(u.nickname||u.id)}</b><em>${esc(u.id)} · ${esc(u.role)} · ${fmt(u.createdAt)}</em></span></article>`).join('')}</div>`);}

export function renderMigration(){return page('JCS_0_0_2 · ONE-TIME MIGRATION','기존 회원 · 게시판 데이터 이식',`<div class="legal-copy"><p>기존 정참시의 회원, 회원 활동, 정뮤니티, IT'S ME, COLUMN, 시민 설문, 세대뽑, 전국평가제, 아카데미, 댓글만 새 저장소로 복사합니다.</p><p>NOW · 정치인 데이터 · 분석 · HISTORY는 복사하지 않습니다.</p></div><form class="stage-form" data-stage-form="migration">${field('secret','마이그레이션 키','password')}<button class="primary-btn">이식 실행</button><span data-form-state></span></form>`);}
