const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const valid=v=>typeof v==='number'&&Number.isFinite(v);
const fmt=v=>valid(v)?v.toLocaleString('ko-KR',{maximumFractionDigits:1}):'—';
const pct=v=>valid(v)?Math.max(0,Math.min(100,v)):0;
const noData=()=>'<span class="dr-mini-empty">집계 자료 없음</span>';
export function dial(value){if(!valid(value))return noData();return `<div class="sc-dial"><svg viewBox="0 0 240 134" role="img" aria-label="이미지 일관성 ${fmt(value)}점"><path d="M28 112 A92 92 0 0 1 212 112" pathLength="100" fill="none" stroke="#e3e9f2" stroke-width="16" stroke-linecap="round"/><path d="M28 112 A92 92 0 0 1 212 112" pathLength="100" fill="none" stroke="#4263c7" stroke-width="16" stroke-linecap="round" stroke-dasharray="${pct(value)} 100"/><g fill="#61728a" font-size="13"><text x="18" y="133">0</text><text x="113" y="10">50</text><text x="206" y="133">100</text></g><text x="120" y="91" text-anchor="middle" class="sc-dial-value">${fmt(value)}</text><text x="120" y="113" text-anchor="middle" font-size="14" fill="#61728a">점</text></svg></div>`;}
export function lollipops(rows){if(!rows.length)return noData();return `<div class="sc-lollipops">${rows.map((r,i)=>`<div><div class="sc-row-label"><span>${esc(r.label)}</span><b>${fmt(r.value)}<small>%</small></b></div><div class="sc-lollipop-track" style="--sc-value:${pct(r.value)}%;--sc-color:${i?'#33a2a0':'#4263c7'}"><i></i><em></em></div></div>`).join('')}<div class="sc-axis"><span>0</span><span>50</span><span>100%</span></div></div>`;}
export function localShare(row){if(!row)return noData();return `<b class="dr-mini-subject">${esc(row.label)}</b><div class="sc-local"><div class="sc-donut" style="--sc-value:${pct(row.share)}%" role="img" aria-label="지역 보도 비중 ${fmt(row.share)}퍼센트"><div><b>${fmt(row.share)}<small>%</small></b></div></div><div><strong>${fmt(row.count)}<small>건</small></strong><span>관련 보도</span></div></div>`;}
export function dumbbell(rows){if(rows.length!==2||rows.some(r=>!valid(r.value)))return noData();const x=rows.map(r=>18+pct(r.value)*2.04);return `<div class="sc-versus"><div class="sc-versus-labels">${rows.map((r,i)=>`<div class="sc-person-${i}"><span>${esc(r.label)}</span><b>${fmt(r.value)}<small>점</small></b></div>`).join('')}</div><svg viewBox="0 0 240 70" role="img" aria-label="${esc(rows.map(r=>r.label+' '+fmt(r.value)+'점').join(', '))}"><path d="M18 26H222" stroke="#e1e7f0" stroke-width="7" stroke-linecap="round"/><path d="M${x[0]} 26H${x[1]}" stroke="#9aabd0" stroke-width="7"/><circle cx="${x[0]}" cy="26" r="10" fill="#fff" stroke="#4263c7" stroke-width="4"/><circle cx="${x[1]}" cy="26" r="5" fill="#258c8b"/><g font-size="13" fill="#64748a"><text x="14" y="61">0</text><text x="113" y="61">50</text><text x="202" y="61">100</text></g></svg></div>`;}
export function columns(rows){if(!rows.length)return noData();return `<div class="sc-columns"><div class="sc-column-axis"><span>100</span><span>50</span><span>0</span></div><div class="sc-column-plot">${rows.map((r,i)=>`<div class="sc-column"><div class="sc-column-bar"><i style="height:${pct(r.value)}%;--sc-color:${i?'#b38a4a':'#4263c7'}"><b>${fmt(r.value)}<small>점</small></b></i></div><span>${esc(r.label)}</span></div>`).join('')}</div></div>`;}
export function activitySplit(first,joined){if(!valid(first)||!valid(joined))return noData();const total=first+joined,share=total>0?first/total*100:0;return `<div class="sc-split"><div class="sc-split-values"><div><span>먼저 다룬 이슈</span><b>${fmt(first)}<small>건</small></b></div><div><span>뒤이어 참여</span><b>${fmt(joined)}<small>건</small></b></div></div><div class="sc-split-track" role="img" aria-label="먼저 다룬 이슈 ${fmt(first)}건, 뒤이어 참여 ${fmt(joined)}건">${total>0?`<i style="width:${share}%"></i><em style="width:${100-share}%"></em>`:''}</div><div class="sc-split-caption">먼저 다룬 비중 <b>${total>0?fmt(Math.round(share))+'%':'—'}</b></div></div>`;}
