import {POLIMARBLE_BOARD as BOARD,POLIMARBLE_CARDS as STRATEGY_CARDS} from '../src/core/polimable-data.js';

const BOARD_SIZE=BOARD.length;
const START_SCORE=1000;
const CARD_POOL=['SHIELD','SHIELD','SHIELD','FAVOR_PASS','FAVOR_PASS','FAVOR_PASS','HALF_LOSS','HALF_LOSS','HALF_LOSS','DOUBLE_GAIN','DOUBLE_GAIN','BONUS_DIE','BONUS_DIE','RECORD_INSURANCE','DOUBLE_OR_NOTHING'];
const PUBLIC_EVENTS=[
 {title:'시민 응원',message:'응원 메시지가 이어졌습니다.',delta:220},
 {title:'공감 확산',message:'공감대가 넓어졌습니다.',delta:170},
 {title:'현장 반응',message:'현장 반응이 예상보다 좋았습니다.',delta:120},
 {title:'관심 분산',message:'관심이 다른 이슈로 이동했습니다.',delta:-140},
 {title:'소통 엇박자',message:'소통 과정에서 엇박자가 생겼습니다.',delta:-180},
 {title:'돌발 변수',message:'예상하지 못한 변수가 발생했습니다.',delta:-230}
];

export {BOARD,STRATEGY_CARDS};
export const stageForScore=score=>score>=15000?4:score>=8000?3:score>=3000?2:1;
export const normalizeInitials=value=>String(value||'').trim().replace(/\s+/g,'').slice(0,3)||'JCS';
const stageMultipliers=stage=>stage===2?{gain:1.08,loss:1.16}:stage===3?{gain:1.12,loss:1.35}:stage===4?{gain:1.18,loss:1.58}:{gain:1,loss:1};
const clone=value=>typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));
const drawCard=rng=>CARD_POOL[rng.int(0,CARD_POOL.length-1)];

export function createGameState({sessionId,userId,initials,nickname,now=new Date()}){
 const stamp=now.toISOString();return {version:1,sessionId:String(sessionId),userId:String(userId),initials:normalizeInitials(initials),nickname:String(nickname||''),score:START_SCORE,peakScore:START_SCORE,position:0,turn:0,stage:1,cards:[],effects:{shieldCharges:0,favorPassTurns:0,doubleGainTurns:0,halfLossTurns:0,bonusDice:0,recordInsuranceRatio:0,doubleOrNothingTurns:0},pendingChoice:null,status:'playing',lastDice:[],lastEvents:[{type:'info',title:'게임 시작',message:'민심 1,000점에서 출발합니다.'}],requestLedger:[],createdAt:stamp,updatedAt:stamp};
}
function applyDelta(state,rawDelta,sourceTitle){let delta=rawDelta,multi=stageMultipliers(state.stage);if(delta>0){delta=Math.round(delta*multi.gain);if(state.effects.favorPassTurns>0)delta=Math.round(delta*1.3);if(state.effects.doubleGainTurns>0){delta*=2;state.effects.doubleGainTurns-=1;}}else if(delta<0){delta=-Math.round(Math.abs(delta)*multi.loss);if(state.effects.shieldCharges>0){state.effects.shieldCharges-=1;delta=0;}else if(state.effects.halfLossTurns>0){state.effects.halfLossTurns-=1;delta=-Math.max(1,Math.round(Math.abs(delta)/2));}}if(state.effects.doubleOrNothingTurns>0&&delta!==0){delta*=2;state.effects.doubleOrNothingTurns-=1;}state.score=Math.max(0,state.score+delta);state.peakScore=Math.max(state.peakScore,state.score);return {type:'score',title:sourceTitle,message:delta===0?'방어 효과로 점수 손실을 막았습니다.':`${delta>0?'+':''}${delta.toLocaleString()}점`,delta};}
function maybeStageUp(state,before,events){state.stage=stageForScore(state.score);if(state.stage>before)events.push({type:'stage',title:`STAGE ${state.stage}`,message:'점수가 높아질수록 보상도 커지지만 감점 위험도 함께 올라갑니다.'});}
function finishIfGameOver(state,events,now){if(state.score>0)return;state.status='game_over';state.endedAt=now.toISOString();state.insuredScore=state.effects.recordInsuranceRatio>0?Math.floor(state.peakScore*state.effects.recordInsuranceRatio):0;events.push({type:'game_over',title:'GAME OVER',message:state.insuredScore?`기록보험 적용 가능: ${state.insuredScore.toLocaleString()}점`:'민심 점수가 0이 되었습니다.'});}
export function rollTurn(input,rng,now=new Date()){const state=clone(input);if(state.status!=='playing')throw new Error('GAME_NOT_ACTIVE');if(state.pendingChoice)throw new Error('CHOICE_REQUIRED');const before=state.stage,diceCount=1+Math.min(1,state.effects.bonusDice);if(state.effects.bonusDice>0)state.effects.bonusDice-=1;const dice=Array.from({length:diceCount},()=>rng.int(1,6)),distance=dice.reduce((s,n)=>s+n,0),next=(state.position+distance)%BOARD_SIZE,tile=BOARD[next],events=[{type:'move',title:`${distance}칸 이동`,message:`${tile.icon} ${tile.title} 칸에 도착했습니다.`}];state.position=next;state.turn+=1;state.lastDice=dice;switch(tile.kind){case'start':events.push(applyDelta(state,100,'한 바퀴 보너스'));break;case'gain':case'bonus':events.push(applyDelta(state,tile.value||0,tile.title));break;case'loss':events.push(applyDelta(state,-(tile.value||0),tile.title));break;case'percent_loss':{const percent=tile.value||10,raw=-Math.max(1,Math.round(state.score*(percent/100)));events.push(applyDelta(state,raw,`${tile.title} -${percent}%`));break;}case'strategy_card':{const cardId=drawCard(rng);if(state.cards.length<3){state.cards.push(cardId);events.push({type:'card',title:STRATEGY_CARDS[cardId].name,message:STRATEGY_CARDS[cardId].description,cardId});}else events.push({type:'card',title:'카드 보관함이 가득 찼습니다',message:`${STRATEGY_CARDS[cardId].name}을(를) 발견했지만 보관함은 3/3입니다.`});break;}case'public_card':{const picked=PUBLIC_EVENTS[rng.int(0,PUBLIC_EVENTS.length-1)];events.push(applyDelta(state,picked.delta,picked.title));events.push({type:'info',title:picked.title,message:picked.message});break;}case'choice':state.pendingChoice={id:`choice-${state.turn}`,title:'운명의 선택',description:'안전하게 점수를 얻거나 큰 점수를 노려보세요.',safeLabel:'안전하게 +220',safeGain:220,riskLabel:'승부수 +850 / -650',riskWin:850,riskLose:-650,riskWinChance:.5};events.push({type:'choice',title:'운명의 선택',message:'안전한 선택과 승부수 중 하나를 골라주세요.'});break;case'safe':events.push({type:'info',title:tile.title,message:'점수 변화 없이 안전하게 한 턴을 넘겼습니다.'});break;}if(state.effects.favorPassTurns>0)state.effects.favorPassTurns-=1;maybeStageUp(state,before,events);finishIfGameOver(state,events,now);state.lastEvents=events;state.updatedAt=now.toISOString();return state;}
export function resolveChoice(input,option,rng,now=new Date()){const state=clone(input);if(state.status!=='playing')throw new Error('GAME_NOT_ACTIVE');const choice=state.pendingChoice;if(!choice)throw new Error('NO_PENDING_CHOICE');const events=[],before=state.stage;if(option==='safe')events.push(applyDelta(state,choice.safeGain,'안전한 선택'));else{const win=rng.float()<choice.riskWinChance;events.push(applyDelta(state,win?choice.riskWin:choice.riskLose,win?'승부 성공':'승부 실패'));}state.pendingChoice=null;maybeStageUp(state,before,events);finishIfGameOver(state,events,now);state.lastEvents=events;state.updatedAt=now.toISOString();return state;}
export function useCard(input,cardId,now=new Date()){const state=clone(input);if(state.status!=='playing')throw new Error('GAME_NOT_ACTIVE');if(state.pendingChoice)throw new Error('CHOICE_REQUIRED');if(!STRATEGY_CARDS[cardId])throw new Error('INVALID_CARD');const index=state.cards.indexOf(cardId);if(index<0)throw new Error('CARD_NOT_OWNED');state.cards.splice(index,1);if(cardId==='SHIELD')state.effects.shieldCharges+=1;if(cardId==='FAVOR_PASS')state.effects.favorPassTurns+=2;if(cardId==='DOUBLE_GAIN')state.effects.doubleGainTurns+=1;if(cardId==='HALF_LOSS')state.effects.halfLossTurns+=1;if(cardId==='BONUS_DIE')state.effects.bonusDice+=1;if(cardId==='RECORD_INSURANCE')state.effects.recordInsuranceRatio=Math.max(state.effects.recordInsuranceRatio,.7);if(cardId==='DOUBLE_OR_NOTHING')state.effects.doubleOrNothingTurns+=3;state.lastEvents=[{type:'card',title:`${STRATEGY_CARDS[cardId].name} 사용`,message:STRATEGY_CARDS[cardId].description,cardId}];state.updatedAt=now.toISOString();return state;}
export function cashOut(input,now=new Date()){const state=clone(input);if(state.status!=='playing')throw new Error('GAME_NOT_ACTIVE');if(state.pendingChoice)throw new Error('CHOICE_REQUIRED');state.status='cashed_out';state.finalScore=state.score;state.endedAt=now.toISOString();state.updatedAt=now.toISOString();state.lastEvents=[{type:'info',title:'기록 확정',message:`${state.finalScore.toLocaleString()}점을 랭킹에 기록합니다.`}];return state;}
export const getRecordableScore=state=>state.status==='cashed_out'?(state.finalScore??state.score):state.status==='game_over'?(state.insuredScore??0):0;
