export const eyeMarkup=()=>`<section class="eye-game"><div class="eye-top"><img src="/assets/mine/eye-324/title.png" alt="깨어있는 눈"><p data-eye-message role="status">스무 장의 카드, 세 개의 보물. 끝까지 놓치지 마라.</p><div class="eye-stats"><span data-eye-round>시도 1 / 3</span><span data-eye-found>보물 ◇ ◇ ◇</span></div></div><div class="eye-board" aria-label="보물 카드 20장"></div><div class="eye-controls"><button data-eye-start>눈을 깨우기</button><p data-eye-help>보물 위치를 기억하고 이동을 따라가세요.<br>시도마다 2장 선택 · 발견한 보물은 누적됩니다.</p></div></section>`;
export function mountEye(host,{request,accept,audio}){
 const q=s=>host.querySelector(s),board=q('.eye-board'),message=q('[data-eye-message]'),start=q('[data-eye-start]');
 let disposed=false,run=null,phase='idle',layout=[],picked=[],cards=[],pending=null,busy=false;const timers=new Set();
 const sleep=ms=>new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve();},ms);timers.add(id);});
 function place(){const cols=window.innerWidth<=600?4:5,rows=20/cols;board.style.setProperty('--rows',rows);cards.forEach((card,id)=>{const pos=layout.indexOf(id);card.style.width=`calc(${100/cols}% - 8px)`;card.style.height=`calc(${100/rows}% - 8px)`;card.style.left=`${(pos%cols)*100/cols}%`;card.style.top=`${Math.floor(pos/cols)*100/rows}%`;card.setAttribute('aria-label',`${pos+1}번 카드`);});}
 function makeCards(){layout=Array.from({length:20},(_,i)=>i);board.innerHTML=layout.map(i=>`<button class="eye-card" data-eye-card="${i}" disabled><span class="eye-back"></span><span class="eye-face"><b>◆</b></span></button>`).join('');cards=[...board.children];place();}
 function stats(){q('[data-eye-round]').textContent=`시도 ${run?.round||1} / 3`;q('[data-eye-found]').textContent=`보물 ${'◆ '.repeat(run?.found||0)}${'◇ '.repeat(3-(run?.found||0))}`;}
 async function reveal(){if(disposed||run?.done||!['idle','result'].includes(phase))return;phase='reveal';picked=[];start.hidden=true;stats();makeCards();cards.forEach((c,id)=>{c.classList.toggle('treasure',run.targets.includes(id));c.classList.add('face-up');});message.textContent='빛나는 보물의 위치를 기억하세요 · 3초';await sleep(3000);if(disposed)return;cards.forEach(c=>c.classList.remove('face-up'));phase='shuffle';message.textContent='눈을 떼지 마세요';await sleep(400);if(disposed)return;
  for(const pairs of run.swaps){for(const [a,b] of pairs){[layout[a],layout[b]]=[layout[b],layout[a]];cards[layout[a]].classList.add('cross-high');cards[layout[b]].classList.add('cross-low');}place();audio.play('swing');await sleep(700);if(disposed)return;cards.forEach(c=>c.classList.remove('cross-high','cross-low'));}
  phase='select';cards.forEach(c=>{c.disabled=false;c.classList.remove('treasure');});message.textContent='보물이라고 생각하는 카드 2장을 고르세요';
 }
 async function send(){if(busy||!pending)return;busy=true;start.hidden=true;try{const d=await request('mine',pending);if(disposed)return;if(!d.ok)throw Error(d.error);accept(d);const next=d.result.eye;const wasStart=pending.action==='eye-start';pending=null;
   if(wasStart){run=next;void reveal();}else{phase=next.done?'finished':'result';for(const item of next.last){const card=cards[layout[item.slot]];card.classList.add('face-up');card.classList.toggle('treasure',item.treasure);}run=next;stats();message.textContent=next.won?'세 보물을 찾았습니다! 일일퀘스트 완료':next.done?'세 번의 기회가 끝났습니다. 보물을 모두 찾지 못했습니다.':`보물 ${next.found} / 3개 확보 · 다음 기회가 남아 있습니다`;audio.play(next.won?'success':next.last.some(x=>x.treasure)?'gain':'loss');q('.eye-game').classList.toggle('eye-victory',next.won);start.textContent=next.done?'월드맵으로':'다음 시도';if(next.done){start.removeAttribute('data-eye-start');start.setAttribute('data-panel','world');q('[data-eye-help]').textContent='이번 도전이 종료되었습니다.';}start.hidden=false;}
  }catch(e){if(disposed)return;message.textContent=/MINE_EYE_RUN/.test(e.message)?'진행 정보가 만료되었습니다. 새로 시작해 주세요.':'저장하지 못했습니다. 다시 시도해 주세요.';if(/MINE_EYE_RUN/.test(e.message)){pending=null;run=null;phase='idle';}start.textContent=pending?'연결 재시도':'다시 시작';start.hidden=false;}finally{busy=false;}}
 function click(e){const card=e.target.closest('[data-eye-card]');if(card&&phase==='select'&&!card.disabled){const id=Number(card.dataset.eyeCard);picked.push(layout.indexOf(id));card.disabled=true;card.classList.add('selected');audio.play('tap');message.textContent=`${picked.length} / 2장 선택`;if(picked.length===2){phase='saving';cards.forEach(c=>c.disabled=true);pending={action:'eye-choose',requestId:crypto.randomUUID(),runId:run.id,round:run.round,picks:[...picked]};void send();}return;}
  if(!e.target.closest('[data-eye-start]')||busy||phase==='finished'||['reveal','shuffle','select','saving'].includes(phase)&&!pending)return;if(pending){void send();return;}if(run&&!run.done){void reveal();return;}q('.eye-game').classList.remove('eye-victory');pending={action:'eye-start',requestId:crypto.randomUUID()};void audio.unlock();void send();}
 makeCards();host.addEventListener('click',click);window.addEventListener('resize',place);
 return ()=>{disposed=true;timers.forEach(clearTimeout);host.removeEventListener('click',click);window.removeEventListener('resize',place);};
}
