const symbols={'태양':'☀','달':'☾','별':'✦','왕관':'♛','눈':'◉','날개':'❧'};
export const ruinsMarkup=()=>`<section class="ruins-game"><div class="ruins-intro"><img class="ruins-title" src="/assets/mine/ruins-337/title.png" alt="오래된 폐허"><small>추리 난이도 ★★★★☆ · 예상 3.8~4.0 / 5</small><div class="game-story"><p>왕의 이름은 지워졌지만, 그를 잠재운 여섯 석관은 남아 있습니다. 벽에 새겨진 기록은 서로 다른 이야기를 속삭입니다. 진실은 어느 한 문장이 아니라, 그 사이에 숨어 있죠.</p><p>네 기록을 연결하고 수호자에게 물으세요. 왕의 잠을 깨울 문은 단 하나. 당신이 발견한 것은 보물의 열쇠일까요, 또 하나의 성급한 확신일까요?</p><p class="game-story-rule">단서 4개 · 수호자 질문 2회 · 최종 개봉 1회<br>시간 제한 없음 · 성공하면 일일퀘스트 완료</p></div><button class="ruins-action" data-ruins-start>폐허 조사하기</button></div><div data-ruins-play hidden></div><p data-ruins-status role="status" aria-live="polite"></p></section>`;
export function mountRuins(host,{request,accept,audio}){
 const q=s=>host.querySelector(s);let run=null,busy=false,disposed=false,pending=null,selected=null;const excluded=new Set();
 function paint(){
  q('.ruins-intro').hidden=true;const play=q('[data-ruins-play]');play.hidden=false;
  play.innerHTML=`<div class="ruins-guide"><b>${run.done?(run.won?'왕묘 발견':'봉인이 닫혔습니다'):'여섯 석관 · 왕묘를 찾아라'}</b><span>조사 ${run.clues.filter(c=>c.text).length}/4 · 질문 ${run.asked.length}/2</span></div><p class="ruins-legend">번호는 왼쪽부터 1→6 순서입니다. 모바일에서는 3번 다음이 4번입니다.<br>이웃은 번호 차이 1이며, 1번과 6번은 이웃하지 않습니다. ‘정확히 하나’는 둘 중 하나만 참이라는 뜻입니다.</p><div class="ruins-tombs">${run.board.map(b=>`<article class="ruins-tomb ${excluded.has(b.id)?'excluded':''} ${selected===b.id?'chosen':''} ${run.done&&run.answer===b.id?'royal':''}"><button data-tomb="${b.id}" ${run.done?'disabled':''} aria-pressed="${selected===b.id}" aria-label="${b.id+1}번 ${b.mark} ${b.gem} ${b.weapon}"><small>석관 ${b.id+1}</small><span class="ruins-symbol" aria-hidden="true">${symbols[b.mark]}</span><strong>${b.mark}</strong><span>${b.gem}</span><span>${b.weapon}</span>${run.done&&run.answer===b.id?'<em>진짜 왕묘</em>':''}</button><button class="ruins-exclude" data-exclude="${b.id}" ${run.done?'disabled':''}>${excluded.has(b.id)?'제외 취소':'후보 제외'}</button></article>`).join('')}</div><div class="ruins-notebook"><section><h3>탐사 수첩</h3>${run.clues.map((c,i)=>`<div class="ruins-clue"><b>${['무너진 벽화','부서진 조각상','왕실의 비문','봉인된 기록'][i]}</b>${c.text?`<p>${c.text}</p>`:`<button class="ruins-action" data-clue="${i}" ${run.done?'disabled':''}>단서 조사</button>`}</div>`).join('')}</section><section><h3>수호자의 응답</h3><p>두 번까지 질문할 수 있습니다. 모든 단서는 질문 없이도 하나의 정답으로 이어집니다.</p>${run.asked.map(a=>`<p class="ruins-answer">${run.questions[a.id].text}<strong>${a.yes?'그렇다.':'아니다.'}</strong></p>`).join('')}${!run.done&&run.asked.length<2?`<label>질문 선택<select data-ruins-question>${run.questions.filter(a=>!run.asked.some(b=>b.id===a.id)).map(a=>`<option value="${a.id}">${a.text}</option>`).join('')}</select></label><button class="ruins-action" data-ask>수호자에게 묻기</button>`:''}<div class="ruins-verdict">${run.done?`<strong>${run.won?'왕의 보물을 찾아냈습니다.':'다음 탐험에서 다시 도전하세요.'}</strong><p>정답은 ${run.answer+1}번 석관입니다.${run.choice!==undefined?` 선택한 석관: ${run.choice+1}번.`:''}</p><details><summary>단서 해설 보기</summary>${run.explanation.map(c=>`<p>${c.text}<br><b>이 기록에 맞는 석관: ${c.possible.join(', ')}번</b></p>`).join('')}<p>네 기록을 모두 만족하는 석관은 ${run.answer+1}번뿐입니다.</p></details><button class="ruins-action" data-ruins-start>새로운 폐허 도전</button><button class="ruins-action" data-panel="world">월드맵으로</button>`:`<p>${selected===null?'왕묘라고 생각하는 석관을 선택하세요.':`${selected+1}번 석관 선택 · 개봉하면 정답이 확정됩니다.`}</p><button class="ruins-action" data-open ${selected===null?'disabled':''}>선택한 석관 개봉</button>`}</div></section></div>`;
 }
 async function send(body){if(busy)return;busy=true;pending=body;q('[data-ruins-status]').textContent='기록을 확인하고 있습니다…';try{const d=await request('mine',body);if(disposed)return;if(!d.ok)throw Error(d.error);accept(d);run=d.result.ruins;pending=null;paint();q('[data-ruins-status]').textContent='';audio?.play(run.done?(run.won?'success':'failure'):'tap');}catch(e){if(disposed)return;q('[data-ruins-status]').innerHTML=/MINE_RUINS_RUN/.test(e.message)?'탐험이 종료되었거나 만료되었습니다. 월드맵에서 다시 입장하세요.':'연결하지 못했습니다. <button class="ruins-action" data-retry>다시 연결</button>';}finally{busy=false;}}
 function click(e){const b=e.target.closest('button');if(!b||busy||b.disabled)return;
  if(b.hasAttribute('data-retry')){if(pending)void send(pending);return;}
  if(b.hasAttribute('data-ruins-start')){selected=null;excluded.clear();void audio?.unlock();void send({action:'ruins-start',requestId:crypto.randomUUID()});return;}
  if(!run||run.done)return;
  if(b.hasAttribute('data-tomb')){selected=Number(b.dataset.tomb);excluded.delete(selected);paint();return;}
  if(b.hasAttribute('data-exclude')){const id=Number(b.dataset.exclude);excluded.has(id)?excluded.delete(id):excluded.add(id);if(selected===id)selected=null;paint();return;}
  const base={runId:run.id,requestId:crypto.randomUUID()};
  if(b.hasAttribute('data-clue'))void send({...base,action:'ruins-clue',clue:Number(b.dataset.clue)});
  if(b.hasAttribute('data-ask'))void send({...base,action:'ruins-ask',question:Number(q('[data-ruins-question]').value)});
  if(b.hasAttribute('data-open')&&selected!==null&&confirm(`${selected+1}번 석관을 개봉할까요? 이번 탐험의 마지막 선택입니다.`))void send({...base,action:'ruins-finish',choice:selected});
 }
 host.addEventListener('click',click);return()=>{disposed=true;host.removeEventListener('click',click);};
}
