import {PICKS,equippedPick} from './pick-catalog.js?v=285';
export const towerMarkup=()=>`<section class="tower-game"><header class="tower-hud"><b data-t-floor>1층</b><span data-t-time>30.0초</span><strong data-t-ore>금맥 대기</strong></header><div class="tower-scene"><div class="tower-door"></div><div class="tower-rig"><div class="tower-chain chain-left"></div><div class="tower-chain chain-right"></div><div class="tower-tool" data-t-pick role="img" aria-label="사슬에 묶인 곡괭이"></div></div><div class="tower-ore"><img src="/assets/mine/tower-326/ore.png" alt="채굴할 금덩어리"></div><div class="tower-impact" aria-hidden="true"></div><div class="tower-damage" data-t-damage></div></div><div class="tower-controls"><p data-t-weapon></p><div class="tower-track"><i data-t-progress></i></div><p data-t-message role="status">마법의 사슬이 당신의 가장 강력한 곡괭이를 움직입니다.</p><button data-t-start>탑에 도전</button><p class="tower-help">30초 안에 금을 전부 채굴하세요 · 자동 타격<br>실패하면 같은 층 재도전 · 광산 골드와 별도</p></div></section>`;
export function mountTower(host,{request,accept,audio,state,tower}){
 const q=s=>host.querySelector(s),button=q('[data-t-start]'),rig=q('.tower-rig'),ore=q('.tower-ore'),impact=q('.tower-impact');let run=null,busy=false,disposed=false,active=false,pending=null,raf=0,origin=0,index=0,mined=0,swingCycle=-1,hitTimer=0;
 q('[data-t-floor]').textContent=`${tower?.floor||1}층`;const owned=new Set(['rust',...(state.ownedPicks||[]),...(state.paidPicks||[]),...(state.adminAllPicks?PICKS.map(p=>p.id):[])]);const preview=[...owned].map(tool=>equippedPick({...state,tool})).sort((a,b)=>b.amount*(b.hits+(b.extraChance||0))-a.amount*(a.hits+(a.extraChance||0)))[0];setTool(preview);q('[data-t-weapon]').textContent=preview.name;
 function setTool(pick){const i=Math.max(0,PICKS.findIndex(p=>p.id===(pick.visual||pick.id)));q('[data-t-pick]').style.backgroundPosition=`${i%5*25}% ${i<5?0:100}%`;q('[data-t-pick]').setAttribute('aria-label',pick.name);}
 function message(t){q('[data-t-message]').textContent=t;}
 function showRun(){q('[data-t-floor]').textContent=`${run.floor}층`;setTool(run.pick);q('[data-t-weapon]').textContent=run.pick.name;q('.tower-game').style.setProperty('--tower-color',run.pick.color||'#edc571');q('[data-t-ore]').textContent=`남은 금 ${run.target} / ${run.target}`;}
 async function send(){if(busy||!pending)return;busy=true;button.hidden=true;try{const d=await request('mine',pending);if(disposed)return;if(!d.ok)throw Error(d.error);accept(d);const start=pending.action==='tower-start';run=d.result.towerRun;pending=null;showRun();if(start){active=true;index=0;mined=0;swingCycle=-1;origin=performance.now();ore.style.transform='scale(1)';ore.style.opacity=1;q('.tower-game').classList.remove('tower-cleared');message('사슬이 깨어났습니다. 금맥을 부수세요.');raf=requestAnimationFrame(frame);}else{active=false;q('.tower-game').classList.toggle('tower-cleared',run.won);message(run.won?`${run.floor}층 돌파! 다음 층의 문이 열렸습니다.`:`시간 종료 · 금 ${Math.max(0,run.target-mined)} 남음. 같은 층에 다시 도전하세요.`);q('[data-t-ore]').textContent=`남은 금 ${Math.max(0,run.target-mined)} / ${run.target}`;audio.play(run.won?'success':'failure');button.textContent=run.won?`${run.floor+1}층 도전`:'같은 층 재도전';button.hidden=false;}}
 catch(e){if(disposed)return;const expired=/MINE_TOWER_(RUN|EXPIRED)/.test(e.message);if(expired)pending=null;message(expired?'도전 정보가 만료되었습니다. 같은 층에서 다시 시작하세요.':'진행 정보를 저장하지 못했습니다. 다시 연결해 주세요.');button.textContent=expired?'다시 도전':'연결 재시도';button.hidden=false;}finally{busy=false;}}
 function frame(now){if(disposed||!active)return;const elapsed=Math.min(30000,now-origin);let hit=false;while(index<run.events.length&&run.events[index].at<=elapsed&&mined<run.target){mined+=run.events[index++].amount;hit=true;}
 const remain=Math.max(0,run.target-mined),ratio=remain/run.target;q('[data-t-time]').textContent=`${Math.max(0,(30000-elapsed)/1000).toFixed(1)}초`;q('[data-t-ore]').textContent=`남은 금 ${remain} / ${run.target}`;q('[data-t-progress]').style.width=`${100*(1-ratio)}%`;ore.style.transform=`scale(${Math.cbrt(ratio)})`;ore.style.opacity=ratio?1:0;
 const cycle=(elapsed%1500)/1500;const rise=cycle<.68?cycle/.68:Math.max(0,1-(cycle-.68)/.12);rig.style.transform=`translateY(${-rise*80}px) rotate(${-rise*28}deg)`;
 if(Math.floor(elapsed/1500)!==swingCycle){swingCycle=Math.floor(elapsed/1500);audio.play(`pick-${run.pick.visual||run.pick.id}-swing`);}if(hit){rig.style.transform='translateY(12px) rotate(12deg)';impact.classList.remove('burst');void impact.offsetWidth;impact.classList.add('burst');audio.play(`pick-${run.pick.visual||run.pick.id}-strike`);q('[data-t-damage]').textContent=`−${run.pick.amount}`;clearTimeout(hitTimer);hitTimer=setTimeout(()=>{q('[data-t-damage]').textContent='';},450);}
 if(!remain||elapsed>=30000){active=false;rig.style.transform='translateY(-65px)';pending={action:'tower-finish',requestId:crypto.randomUUID(),runId:run.id};void send();return;}raf=requestAnimationFrame(frame);}
 function click(e){if(!e.target.closest('[data-t-start]')||busy||active)return;if(!pending)pending={action:'tower-start',requestId:crypto.randomUUID()};void audio.unlock();void send();}
 host.addEventListener('click',click);return ()=>{disposed=true;active=false;cancelAnimationFrame(raf);clearTimeout(hitTimer);host.removeEventListener('click',click);};
}
