import { SERVICE_CATALOG, launcherServices, serviceIconSvg } from '../ui/service-icons.js';
import { badgeByKey, badgeCrestSvg } from '../data/badge-catalog.js';

const partyClass=(party='')=>party.includes('더불어')?'party-democratic':party.includes('국민의힘')?'party-peoplepower':party.includes('개혁신당')?'party-reform':party.includes('조국혁신당')?'party-innovation':party.includes('진보당')?'party-progressive':party.includes('기본소득당')?'party-basicincome':party.includes('사회민주당')?'party-socialdemocratic':party.includes('공석')?'party-vacant':'party-independent';
const partyMark=(party='')=>party.includes('더불어')?'민':party.includes('국민의힘')?'국':party.includes('개혁신당')?'개':party.includes('조국혁신당')?'조':party.includes('진보당')?'진':party.includes('기본소득당')?'기':party.includes('사회민주당')?'사':party.includes('공석')?'공':'무';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const publishedItems=data=>(Array.isArray(data?.items)?data.items:[]).filter(item=>item?.published!==false);
const dateLabel=value=>{if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString('ko-KR');};
const academyDate=value=>{const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!match)return {date:String(value||'일정'),day:''};const [,year,month,day]=match,week=['일','월','화','수','목','금','토'][new Date(Date.UTC(Number(year),Number(month)-1,Number(day))).getUTCDay()];return {date:`${month}.${day}`,day:week};};
const imageUrl=value=>{const url=String(value||'').trim();return /^(https:\/\/|\/)/i.test(url)?url:'';};
const NATIONAL_SUBJECT_FALLBACK=Object.freeze({
  'assembly-182':{name:'전용기',party:'더불어민주당',jurisdiction:'경기 화성시정'},
  'basic-038':{name:'신상진',party:'국민의힘',jurisdiction:'경기도 성남시'}
});

function productHero(hero){
  const headline=hero.headline.replace(hero.accent,`<br><strong>${hero.accent}</strong>`);
  return `<section class="product-hero product-hero-participation product-hero-headline-tone-white product-hero-accent-tone-yellow product-hero-description-tone-mint"><div class="product-hero-copy"><div class="product-hero-kicker"><span>${hero.productKicker}</span><em>${hero.productTagline}</em></div><h1>${headline}</h1><p>${hero.description}</p><div class="product-hero-actions"><a class="hero-action-primary" href="#/about" data-layout-route="/about">정참시 응원하기 <span>→</span></a><a class="hero-action-secondary" href="#/support" data-layout-route="/support">정참시 후원하기 <span>♡</span></a></div></div><div class="product-hero-live hero-participation-hub"><button type="button" class="hero-hub-card hero-hub-request" data-layout-route="/request-politician"><span class="hero-hub-label">POLITICIAN REQUEST</span><strong>찾는 정치인이 없나요?</strong><p>이름만 남겨주세요. 정보를 확인해 등록합니다</p><em>정치인 등록 요청 →</em></button><button type="button" class="hero-hub-card hero-hub-partners" data-layout-route="/partners"><span class="hero-hub-label">JEONGCHAMSI PARTNERS</span><strong>정참시와 함께 콘텐츠를 만들어주세요</strong><p>PARTNER는 COLUMN·NEWS를 직접 작성할 수 있습니다</p><em>파트너스 신청 →</em></button></div></section>`;
}
const launcherCards=items=>items.map(item=>`<button type="button" class="launcher-card launcher-${item.key==='poll'?'choice':item.key}" data-layout-route="${item.href}" aria-label="${esc(item.label)} · ${esc(item.description)}"><span class="launcher-icon">${serviceIconSvg(item.key)}</span><span class="launcher-copy"><b>${esc(item.shortLabel)}</b><small>${esc(item.description)}</small></span><span class="launcher-cue">→</span></button>`).join('');
function productLauncher(){return `<section class="product-launcher product-launcher-compact"><div class="product-launcher-head"><div><span>EXPLORE JEONGCHAMSI</span><h2>정참시는 여러분의 참여로 만들어갑니다</h2></div><button type="button" data-launcher-toggle aria-expanded="false" aria-controls="all-services-panel">전체 서비스 <span aria-hidden="true">＋</span></button></div><div class="product-launcher-grid">${launcherCards(launcherServices())}</div><div class="product-launcher-expanded" id="all-services-panel" data-launcher-panel hidden><div class="product-launcher-expanded-head"><b>ALL SERVICES</b><span>정참시의 모든 서비스를 한곳에서 선택하세요</span></div><div class="product-launcher-grid product-launcher-grid-all">${launcherCards(SERVICE_CATALOG)}</div></div></section>`;}
function itsme(items=[]){const rows=items.filter(item=>item?.published!==false).slice(0,6);return `<section class="module itsme-home-module" id="itsme"><div class="module-header"><div><span class="eyebrow">IT’S ME</span><h2 class="itsme-signature-title">나는 이렇게 제안합니다</h2><p class="module-desc">꼭 필요하고 유용한 정책이 공론화될 수 있도록 정참시가 앞장서겠습니다</p></div><button class="more-btn" type="button" data-layout-route="/itsme">전체보기</button></div><div class="itsme-grid">${rows.map((item,i)=>`<article class="itsme-card" data-layout-route="/itsme/${esc(item.id)}"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(item.title||'제목 없는 제안')}</b></article>`).join('')||'<div class="schedule-empty">등록된 정책 제안이 없습니다</div>'}</div></section>`;}
function poll(data={}){const poll=publishedItems(data)[0];if(!poll)return `<section class="module poll-module" id="poll"><div class="module-header"><div><span class="eyebrow">CITIZENS’ CHOICE</span><h2>귀담아 들어야 합니다</h2></div><button class="more-btn" type="button" data-layout-route="/poll">전체보기</button></div><div class="schedule-empty">진행 중인 설문이 없습니다</div></section>`;const options=(Array.isArray(poll.options)?poll.options:[]).slice(0,3),total=(Array.isArray(poll.options)?poll.options:[]).reduce((sum,item)=>sum+Number(item.votes||0),0);return `<section class="module poll-module" id="poll"><div class="module-header"><div><span class="eyebrow">CITIZENS’ CHOICE</span><h2>귀담아 들어야 합니다</h2></div><button class="more-btn" type="button" data-layout-route="/poll">전체보기</button></div><div class="poll-main"><div class="poll-question"><h3>${esc(poll.question||poll.title||'시민 설문')}</h3></div><div class="poll-vote-panel"><div class="poll-options">${options.map(option=>{const percent=total?Math.round(Number(option.votes||0)*100/total):0;return `<button type="button" data-layout-route="/poll"><span>${esc(option.label||option.title)}</span><i><em style="width:${percent}%"></em></i><b>${percent}%</b></button>`;}).join('')}</div><div class="poll-confirm-row"><span>항목을 누르면 전체 설문으로 이동합니다</span><button class="ghost-btn" type="button" data-layout-route="/poll">전체 선택지 보기</button></div></div></div></section>`;}
function nationalEval(data={}){const order=['assembly','local'],slots=order.map(key=>data?.slots?.[key]).filter(slot=>slot?.enabled===true&&!slot?.closedAt);const cards=slots.map((slot,index)=>{const fallback=NATIONAL_SUBJECT_FALLBACK[String(slot.subjectId||'')]||{},name=slot.subjectName||slot.personName||slot.name||fallback.name||slot.subjectId||'평가 대상',party=slot.party||fallback.party||'',jurisdiction=slot.jurisdiction||fallback.jurisdiction||'',result=data?.results?.[slot.evaluationId]||data?.demoResults?.[slot.evaluationId]||{},total=Number(result.positive||0)+Number(result.neutral||0)+Number(result.negative||0),positive=total?Math.round(Number(result.positive||0)*100/total):0,type=slot.slot==='assembly'?'국회의원':'기초단체장';return `<article class="national-eval-home-card active" data-layout-route="/national-evaluation"><div class="national-eval-home-type"><span>SLOT ${index===0?'A':'B'}</span><b>${type}</b></div><div class="eval-person"><span class="eval-avatar"></span><div><small>이번 평가 대상</small><b>${esc(name)}</b><em>${esc([party,jurisdiction].filter(Boolean).join(' · '))}</em></div></div><div class="eval-score"><small>긍정 평가</small><strong>${positive}%</strong><span>${total.toLocaleString('ko-KR')}명 참여</span></div></article>`;}).join('');return `<section class="module national-eval" id="national-eval"><div class="module-header"><div><span class="eyebrow">NATIONAL EVALUATION</span><h2>정참시민 전국 평가제</h2><p class="module-desc">국회의원 1명과 광역·기초단체장 1명을 정참시민이 각각 평가합니다</p></div><button class="more-btn" type="button" data-layout-route="/national-evaluation">전체보기</button></div>${cards?`<div class="national-eval-dual">${cards}</div>`:'<div class="schedule-empty">현재 진행 중인 전국 평가가 없습니다</div>'}</section>`;}
function generation(data={}){const ages=['10대','20대','30대','40대','50대','60대+'],candidates=Array.isArray(data?.candidates)?data.candidates:[],labels=data?.candidateLabels||{};return `<section class="module generation-president" id="generation-president"><div class="module-header"><div><span class="eyebrow">GENERATION CHOICE · MOCK VOTE</span><h2>세대의 선택, 대통령</h2><p class="module-desc">같은 대통령 후보를 세대별로 바라보면 선택은 어떻게 달라질까? 정참시 모의투표로 비교합니다</p></div><button class="more-btn" type="button" data-layout-route="/generation-president">전체보기</button></div><div class="generation-feature"><div class="generation-intro"><h3>10대부터 60대+까지<br>각 세대의 선택을 한눈에</h3><button class="ghost-btn generation-participation-cta" type="button" data-layout-route="/generation-president">모의투표 참여</button></div><div class="generation-grid">${ages.map((age,i)=>{const results=data?.results?.[age]||{},entries=Object.entries(results).sort((a,b)=>Number(b[1]||0)-Number(a[1]||0)),total=entries.reduce((sum,[,votes])=>sum+Number(votes||0),0),top=entries[0],percent=top&&total?Math.round(Number(top[1]||0)*100/total):0;return `<article class="generation-card ${i===1?'focus':''}" data-layout-route="/generation-president"><span class="generation-age">${age}</span>${candidates.length&&top?`<div class="generation-result"><b>${esc(labels[top[0]]||top[0])}</b><div class="generation-bar"><i style="width:${percent}%"></i></div><small>${percent}% · ${total.toLocaleString('ko-KR')}명 참여</small></div>`:'<div class="generation-result generation-result-empty"><b>아직 투표가 이뤄지지 않았습니다</b><div class="generation-bar"><i style="width:0%"></i></div><small>첫 투표를 기다리는 중</small></div>'}</article>`;}).join('')}</div></div></section>`;}
function compare(){return `<section class="module compare-operating-module" id="compare"><div class="module-header"><div><span class="eyebrow">COMPARE · OPERATING</span><h2>정치인 비교분석</h2><p class="module-desc">실제 공개 스냅샷으로 비교</p></div><button class="more-btn" type="button" data-layout-route="/compare">비교하기</button></div><button type="button" class="compare-operating-entry" data-layout-route="/compare"><div><span>JCS ROLE-TIERED COMPARISON</span><h3>같은 정치인도 권한에 따라 더 깊게 비교합니다</h3><p>비로그인 핵심 비교 · 회원 1:1 해석 · 관리자 2~5인 정치 인텔리전스</p></div><em>정치인 검색하고 비교하기 →</em></button></section>`;}
function nowRank(rows=[]){if(!rows.length)return `<section class="module now-module" id="now"><div class="module-header"><div><span class="eyebrow live-heading-inline">NOW RANK <span class="main-live-pulse" aria-label="LIVE"><i></i></span></span><h2>지금 가장 주목받는 정치인</h2></div><button class="more-btn" type="button" data-layout-route="/now">전체보기</button></div><div class="schedule-empty now-rank-pending"><b>NOW Rank 집계 준비 중</b><span>검증된 운영 순위가 게시되면 표시합니다</span></div></section>`;const pages=[];for(let p=0;p<Math.ceil(rows.length/10);p++){const cards=rows.slice(p*10,p*10+10).map(x=>{const src=String(x.photo?.localPath||''),initial=esc(String(x.name||'?').slice(0,1)),avatar=src?`<div class="rank-top-avatar has-photo" data-politician-avatar style="--photo-position:${esc(x.photo?.focus||'50% 28%')}"><span class="politician-photo-initial" aria-hidden="true">${initial}</span><img data-politician-photo src="${esc(src)}" alt="" width="70" height="70" loading="lazy" decoding="async"></div>`:`<div class="rank-top-avatar is-empty" data-politician-avatar><span class="politician-photo-initial" aria-hidden="true">${initial}</span></div>`;return `<article class="rank-top-card ${partyClass(x.party)}" role="button" tabindex="0" data-layout-route="/person/${esc(x.id||'')}" aria-label="${Number(x.rank||0)}위 ${esc(x.name)} 상세"><span class="rank-party-flag" title="${esc(x.party)}">${partyMark(x.party)}</span><div class="rank-top-no">${Number(x.rank||0)}</div>${avatar}<div class="rank-top-copy"><b>${esc(x.name)}</b><span>${esc(x.party)} · ${esc(x.jurisdiction)}</span><strong>NOW ${Number(x.score||0).toFixed(1)}</strong></div></article>`;}).join('');pages.push(`<div class="rank-top-grid rank-top-grid-10 now-rank-page" data-now-rank-page="${p}" ${p?'hidden':''}>${cards}</div>`);}return `<section class="module now-module" id="now"><div class="module-header"><div><span class="eyebrow live-heading-inline">NOW RANK <span class="main-live-pulse" aria-label="LIVE"><i></i></span></span><h2>지금 가장 주목받는 정치인</h2><p class="module-desc">전체 정치인 NOW 운영 순위 · 좌우 버튼으로 10명씩 보기</p></div><button class="more-btn" type="button" data-layout-route="/now">전체보기</button></div><div class="now-rank-carousel" data-now-rank-carousel data-page-count="${pages.length}" data-page="0"><button class="now-rank-nav now-rank-prev" type="button" data-now-rank-prev aria-label="이전 10명">‹</button><div class="now-rank-pages">${pages.join('')}</div><button class="now-rank-nav now-rank-next" type="button" data-now-rank-next aria-label="다음 10명">›</button><div class="now-rank-status" data-now-rank-status>1 / ${pages.length}</div></div></section>`;}
function column(items=[]){const rows=items.filter(item=>item?.published!==false).slice(0,4);return `<section class="module" id="column"><div class="module-header"><div><span class="eyebrow">COLUMN</span><h2>오늘 정치에서 읽어야 할 것</h2></div><button class="more-btn" type="button" data-layout-route="/column">전체보기</button></div><div class="column-grid">${rows.map(item=>{const cover=imageUrl(item.coverImage);return `<article class="column-card" data-layout-route="/column/${esc(item.id)}"><div class="column-thumb">${cover?`<img src="${esc(cover)}" alt="" loading="lazy">`:''}</div><div class="column-card-copy"><b>${esc(item.title||'제목 없는 칼럼')}</b><small>${esc(item.author||'정참시')}${dateLabel(item.createdAt)?` · ${dateLabel(item.createdAt)}`:''}</small></div></article>`;}).join('')||'<div class="schedule-empty">등록된 칼럼이 없습니다</div>'}</div></section>`;}
function community(items=[]){const rows=items.filter(item=>item?.published!==false).slice(0,5);return `<section class="module" id="community"><div class="module-header"><div><span class="eyebrow">COMMUNITY</span><h2>지금 시민들이 말하는 것</h2></div><button class="more-btn" type="button" data-layout-route="/community">전체보기</button></div><div class="community-list">${rows.map((item,i)=>`<div class="community-row" data-layout-route="/community/${esc(item.id)}"><span class="community-order">${String(i+1).padStart(2,'0')}</span><span class="community-copy"><b>${esc(item.title||'제목 없는 게시물')}</b><em>${esc(item.author||'회원')}${dateLabel(item.createdAt)?` · ${dateLabel(item.createdAt)}`:''}</em></span><span class="community-stats">좋아요 ${Number(item.likes||0).toLocaleString('ko-KR')} · 조회 ${Number(item.views||0).toLocaleString('ko-KR')}</span></div>`).join('')||'<div class="schedule-empty">등록된 정뮤니티 게시물이 없습니다</div>'}</div></section>`;}
function academy(data={}){const rows=(Array.isArray(data?.slots)?data.slots:publishedItems(data)).filter(item=>item?.published!==false).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))).slice(0,4);return `<section class="module academy-module" id="academy"><div class="module-header"><div><span class="eyebrow">JEONGCHAMSI ACADEMY</span><h2>정참시 아카데미</h2></div><button class="more-btn" type="button" data-layout-route="/academy">일정 보기</button></div><div class="academy-layout"><div class="academy-intro"><span class="academy-mark">A</span><h3>정치의 꿈을 실제 준비로</h3><button type="button" data-layout-route="/academy">수강 가능 일정 확인</button></div><div class="academy-schedule"><div class="schedule-head"><b>예정 교육 일정</b><span>${rows.length}개</span></div>${rows.map(item=>{const when=academyDate(item.date);return `<div class="schedule-row" data-slot-id="${esc(item.id||'')}"><span class="schedule-date">${esc(when.date)}${when.day?` <small>${esc(when.day)}</small>`:''}</span><span class="schedule-line"><i></i><em>${esc(item.title||item.name||'정참시 아카데미')}</em></span><button type="button" data-layout-route="/academy">신청가능</button></div>`;}).join('')||'<div class="schedule-empty">등록된 일정이 없습니다</div>'}</div></div></section>`;}

function accountPanel(session={},mobile=false){
  const authenticated=session?.authenticated===true;
  const nickname=esc(session?.user?.nickname||'회원');
  if(mobile)return authenticated
    ? `<div class="mobile-login mobile-login-authenticated"><div><b>${nickname}님</b><span>${session.user?.role==='admin'?'관리자 계정':'정참시 회원'} · 로그인 상태 유지 중</span></div><button type="button" data-layout-route="/mypage">마이페이지</button></div>`
    : `<div class="mobile-login"><div><b>정참시에 로그인하세요</b><span>즐겨찾기 · 참여 · 배지 · 알림</span></div><button type="button" data-layout-route="/login">로그인</button></div>`;
  return authenticated
    ? `<section class="side-card login-card side-login side-login-authenticated"><span class="side-login-status">SIGNED IN</span><b>${nickname}님</b><p>${session.user?.role==='admin'?'관리자 계정':'정참시 회원'}으로 로그인되어 있습니다</p><button type="button" data-layout-route="/mypage">마이페이지</button></section>`
    : `<section class="side-card login-card side-login"><b>정참시에 로그인하세요</b><p>즐겨찾기, 참여 기록, 배지, 알림을 한곳에서 관리합니다</p><button type="button" data-layout-route="/login">로그인</button></section>`;
}

function recentPoliticianCard(item){
  const src=String(item?.photo?.localPath||''),initial=esc(String(item?.name||'?').slice(0,1));
  const avatar=src?`<span class="recent-circle-avatar has-photo" data-politician-avatar style="--photo-position:${esc(item.photo?.focus||'50% 28%')}"><span class="politician-photo-initial" aria-hidden="true">${initial}</span><img data-politician-photo src="${esc(src)}" alt="" width="54" height="54" loading="lazy" decoding="async"></span>`:`<span class="recent-circle-avatar is-empty" data-politician-avatar><span class="politician-photo-initial" aria-hidden="true">${initial}</span></span>`;
  return `<button type="button" class="recent-visual-card" data-layout-route="/person/${esc(item.id)}" aria-label="${esc(item.name)} 상세페이지">${avatar}<b>${esc(item.name)}</b><small>${esc([item.party,item.office].filter(Boolean).join(' · '))}</small></button>`;
}

function recentPoliticians(items=[]){
  const rows=Array.isArray(items)?items.filter(item=>item?.id&&item?.name).slice(0,4):[];
  return `${rows.map(recentPoliticianCard).join('')}${Array.from({length:4-rows.length},()=>`<span class="recent-visual-empty"><span class="recent-circle-empty"></span><b>최근 본 인물</b><small>기록 없음</small></span>`).join('')}`;
}

const emptyBadgeSlot=type=>`<span class="badge-showcase-slot badge-showcase-empty" data-badge-slot="${type}"><i>◇</i><small>${type==='representative'?'대표':'전시'}</small></span>`;
const filledBadgeSlot=(key,type)=>{const badge=badgeByKey(key);return badge?`<span class="badge-showcase-slot badge-showcase-filled ${type==='representative'?'is-representative':''}" data-badge-slot="${type}" title="${esc(badge.name)}">${badgeCrestSvg(key)}<small>${esc(badge.name)}</small></span>`:emptyBadgeSlot(type);};

export function renderBadgeShowcase(status={}){
  status=status||{};
  const representative=badgeByKey(status.representativeBadge)?.key||'';
  const showcases=[...new Set(Array.isArray(status.showcaseBadges)?status.showcaseBadges:[])].filter(key=>key!==representative&&badgeByKey(key)).slice(0,3);
  const slots=[representative?filledBadgeSlot(representative,'representative'):emptyBadgeSlot('representative')];
  for(let index=0;index<3;index++)slots.push(showcases[index]?filledBadgeSlot(showcases[index],'showcase'):emptyBadgeSlot('showcase'));
  return `<div class="side-badge-showcase"><div class="badge-showcase-main">${slots[0]}<div><b>${representative?esc(badgeByKey(representative).name):'대표 배지를 선택해보세요'}</b><p>${representative?'나를 상징하는 대표 컬렉션':'획득한 배지를 대표로 설정할 수 있습니다'}</p></div></div><div class="badge-showcase-trio">${slots.slice(1).join('')}</div></div>`;
}

function participationCard(status={},mobile=false){return `<section class="${mobile?'mobile-participation':'side-card side-participation'} participation-card"><div class="side-head"><b>내 참여 · 배지</b><span class="side-action" data-layout-route="/mypage/activity">MY</span></div><div data-badge-showcase-mount>${renderBadgeShowcase(status)}</div></section>`;}

function sideColumn(data,session){const rankRows=Array.isArray(data.rank)?data.rank:[];return `<aside class="side-column">${accountPanel(session)}${participationCard(data.badgeStatus)}<section class="side-card side-recent"><div class="side-head"><b>최근 본 정치인</b><span class="side-action" data-layout-route="/mypage/recent">전체</span></div><div class="recent-visual-grid">${recentPoliticians(data.recentPoliticians)}</div></section><section class="side-card side-keywords live-signal-card"><div class="side-head"><b class="live-heading-inline">실시간 정치키워드 <span class="main-live-pulse" aria-label="LIVE"><i></i></span></b><span class="side-action" data-layout-route="/keywords">더보기</span></div><div class="keyword-grid live-keyword-grid">${data.keywords.map((x,i)=>`<span class="live-keyword-chip"><b>${i+1}</b>${x}</span>`).join('')}</div><small class="signal-source-note">게시된 NOW 뉴스 데이터 기반</small></section><section class="side-card side-news"><div class="side-head"><b>정참시 NEWS</b><span class="side-action" data-layout-route="/news">전체</span></div>${data.news.map((x,i)=>`<div class="side-row"><span>${i+1}</span><i>${x}</i></div>`).join('')}</section><section class="side-card side-rising live-signal-card"><div class="side-head"><b class="live-heading-inline">실시간 급상승 정치인 <span class="main-live-pulse" aria-label="LIVE"><i></i></span></b><span class="side-action" data-layout-route="/trending">전체</span></div>${rankRows.length?rankRows.slice(0,5).map((x,i)=>`<div class="side-row live politician-rising-row" data-layout-route="/person/${esc(x.id||'')}"><span>${i+1}</span><i><b>${esc(x.name)}</b><small><em class="trend-signal up">▲</em> NOW ${i+1}위 · ${esc(x.party)}</small></i></div>`).join(''):'<div class="schedule-empty">집계 준비 중</div>'}<small class="signal-source-note">직전 게시 순위 + 최근 뉴스 가속도</small></section></aside>`;}

export function renderHomeLayout(data){
  return `${productHero(data.hero)}${productLauncher()}<div class="portal-layout product-content-grid"><section class="mobile-utility" aria-label="모바일 내 정참시">${accountPanel(data.session,true)}${participationCard(data.badgeStatus,true)}</section><main class="main-column">${itsme(data.itsmePosts)}${poll(data.polls)}${nationalEval(data.nationalEvaluation)}${generation(data.generation)}${compare()}${nowRank(data.rank)}${column(data.columns)}${community(data.community)}${academy(data.academy)}</main>${sideColumn(data,data.session)}</div>`;
}
