import { SERVICE_CATALOG, launcherServices, moduleActionIconSvg, serviceIconSvg } from '../ui/service-icons.js?v=0.0.31.39';
import { badgeByKey, badgeCrestSvg } from '../data/badge-catalog.js';

const partyClass=(party='')=>party.includes('더불어')?'party-democratic':party.includes('국민의힘')?'party-peoplepower':party.includes('개혁신당')?'party-reform':party.includes('조국혁신당')?'party-innovation':party.includes('진보당')?'party-progressive':party.includes('기본소득당')?'party-basicincome':party.includes('사회민주당')?'party-socialdemocratic':party.includes('공석')?'party-vacant':'party-independent';
const partyMark=(party='')=>party.includes('더불어')?'민':party.includes('국민의힘')?'국':party.includes('개혁신당')?'개':party.includes('조국혁신당')?'조':party.includes('진보당')?'진':party.includes('기본소득당')?'기':party.includes('사회민주당')?'사':party.includes('공석')?'공':'무';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const authorInline=item=>{const badge=badgeByKey(item?.representativeBadge),admin=['admin','parkmovie'].includes(String(item?.ownerId||''))||['관리자','박감독'].includes(String(item?.author||''));return `<span class="author-identity"><span class="author-nickname">${esc(item?.author||'정참시')}</span>${badge?`<span class="author-representative-badge" title="대표배지 · ${esc(badge.name)}">${badgeCrestSvg(badge.key)}</span>`:''}${admin?'<span class="author-role author-role-admin">ADMIN</span>':''}</span>`;};
const publishedItems=data=>(Array.isArray(data?.items)?data.items:[]).filter(item=>item?.published!==false);
const dateLabel=value=>{if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString('ko-KR');};
const academyDate=value=>{const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!match)return {date:String(value||'일정'),day:''};const [,year,month,day]=match,week=['일','월','화','수','목','금','토'][new Date(Date.UTC(Number(year),Number(month)-1,Number(day))).getUTCDay()];return {date:`${month}.${day}`,day:week};};
const imageUrl=value=>{const url=String(value||'').trim();return /^(https:\/\/|\/)/i.test(url)?url:'';};
const politicianPhoto=(person,klass)=>{const src=String(person?.photo?.url||person?.photo?.localPath||''),initial=esc(String(person?.name||'?').slice(0,1));return src?`<span class="${klass} has-photo" data-politician-avatar style="--photo-position:${esc(person.photo?.focus||'50% 28%')}"><span class="politician-photo-initial">${initial}</span><img data-politician-photo src="${esc(src)}" alt="" loading="lazy"></span>`:`<span class="${klass} is-empty" data-politician-avatar><span class="politician-photo-initial">${initial}</span></span>`;};
const NATIONAL_SUBJECT_FALLBACK=Object.freeze({
  'assembly-182':{name:'전용기',party:'더불어민주당',jurisdiction:'경기 화성시정'},
  'basic-038':{name:'신상진',party:'국민의힘',jurisdiction:'경기도 성남시'}
});

function productHero(hero){
  const headline=hero.headline.replace(hero.accent,`<br><strong>${hero.accent}</strong>`);
  return `<section class="product-hero product-hero-participation product-hero-headline-tone-white product-hero-accent-tone-yellow product-hero-description-tone-mint"><div class="product-hero-copy"><div class="product-hero-kicker"><span>${hero.productKicker}</span><em>${hero.productTagline}</em></div><h1>${headline}</h1><p>${hero.description}</p><div class="product-hero-actions"><a class="hero-action-primary" href="#/about" data-layout-route="/about">정참시 응원하기 <span>→</span></a><a class="hero-action-secondary" href="#/support" data-layout-route="/support">정참시 후원하기 <span>♡</span></a></div></div><div class="product-hero-live hero-participation-hub"><button type="button" class="hero-hub-card hero-hub-request" data-layout-route="/request-politician"><span class="hero-hub-label">POLITICIAN REQUEST</span><strong>찾는 정치인이 없나요?</strong><p>이름만 남겨주세요. 정보를 확인해 등록합니다</p><em>정치인 등록 요청 →</em></button><button type="button" class="hero-hub-card hero-hub-partners" data-layout-route="/partners"><span class="hero-hub-label">JEONGCHAMSI PARTNERS</span><strong>정참시와 함께 콘텐츠를 만들어주세요</strong><p>PARTNER는 COLUMN·NEWS를 직접 작성할 수 있습니다</p><em>파트너스 신청 →</em></button></div></section>`;
}
const serviceDockItems=items=>items.map(item=>{const label=item.key==='generation'?'세대별 대통령':item.shortLabel;return `<button type="button" class="service-dock-item service-dock-${item.key} service-dock-tone-${item.tone}" data-layout-route="${item.href}" aria-label="${esc(item.label)}"><span class="service-dock-icon">${serviceIconSvg(item.key)}</span><span class="service-dock-label">${esc(label)}</span></button>`;}).join('');
function productLauncher(){const primary=launcherServices(),primaryKeys=new Set(primary.map(item=>item.key)),additional=SERVICE_CATALOG.filter(item=>!primaryKeys.has(item.key));return `<section class="service-dock"><nav class="service-dock-row" aria-label="주요 서비스">${serviceDockItems(primary)}<button type="button" class="service-dock-more" data-launcher-toggle aria-expanded="false" aria-controls="all-services-panel" aria-label="전체 서비스 펼치기"><span aria-hidden="true">···</span><small>전체</small></button></nav><div class="service-dock-expanded" id="all-services-panel" data-launcher-panel hidden><nav class="service-dock-row service-dock-row-all" aria-label="전체 서비스">${serviceDockItems(additional)}</nav></div></section>`;}
const moduleAction=(icon,route,label)=>`<button class="module-icon-action" type="button" data-layout-route="${route}" aria-label="${label}" title="${label}">${moduleActionIconSvg(icon)}<span class="sr-only">${label}</span></button>`;
function itsme(items=[]){const rows=items.filter(item=>item?.published!==false).slice(0,6);return `<section class="module itsme-home-module" id="itsme"><div class="module-header"><div><span class="eyebrow">IT’S ME</span><h2 class="itsme-signature-title">나는 이렇게 제안합니다</h2><p class="module-desc">꼭 필요하고 유용한 정책이 공론화될 수 있도록 정참시가 앞장서겠습니다</p></div>${moduleAction('write','/itsme','정책 제안 전체보기')}</div><div class="itsme-grid">${rows.map((item,i)=>`<article class="itsme-card" data-layout-route="/itsme/${esc(item.id)}"><span class="itsme-card-order">${String(i+1).padStart(2,'0')}</span><b class="itsme-card-title">${esc(item.title||'제목 없는 제안')}</b></article>`).join('')||'<div class="schedule-empty">등록된 정책 제안이 없습니다</div>'}</div></section>`;}
function poll(data={}){const rows=publishedItems(data),poll=rows.find(item=>item.featured===true)||rows[0];if(!poll)return `<section class="module poll-module" id="poll"><div class="module-header"><div><span class="eyebrow">CITIZENS’ CHOICE</span><h2>귀담아 들어야 합니다</h2></div>${moduleAction('poll','/poll','시티즌 초이스 투표')}</div><div class="schedule-empty">진행 중인 설문이 없습니다</div></section>`;const options=(Array.isArray(poll.options)?poll.options:[]).slice(0,3),total=(Array.isArray(poll.options)?poll.options:[]).reduce((sum,item)=>sum+Number(item.votes||0),0);return `<section class="module poll-module" id="poll"><div class="module-header"><div><span class="eyebrow">CITIZENS’ CHOICE</span><h2>귀담아 들어야 합니다</h2></div>${moduleAction('poll','/poll','시티즌 초이스 투표')}</div><div class="poll-main"><div class="poll-question"><h3>${esc(poll.question||poll.title||'시민 설문')}</h3></div><div class="poll-vote-panel"><div class="poll-options">${options.map(option=>{const percent=total?Math.round(Number(option.votes||0)*100/total):0;return `<button type="button" data-layout-route="/poll"><span>${esc(option.label||option.title)}</span><b>${percent}%</b></button>`;}).join('')}</div></div></div></section>`;}
function nationalEval(data={}){const order=['assembly','local'],slots=order.map(key=>data?.slots?.[key]).filter(slot=>slot?.enabled===true&&!slot?.closedAt);const cards=slots.map((slot,index)=>{const fallback=NATIONAL_SUBJECT_FALLBACK[String(slot.subjectId||'')]||{},name=slot.subjectName||slot.personName||slot.name||fallback.name||slot.subjectId||'평가 대상',party=slot.party||fallback.party||'',jurisdiction=slot.jurisdiction||fallback.jurisdiction||'',result=data?.results?.[slot.evaluationId]||data?.demoResults?.[slot.evaluationId]||{},total=Number(result.positive||0)+Number(result.neutral||0)+Number(result.negative||0),positive=total?Math.round(Number(result.positive||0)*100/total):0,type=slot.slot==='assembly'?'국회의원':'기초단체장',person={name,photo:slot.photo};return `<article class="national-eval-home-card active" data-layout-route="/national-evaluation"><div class="national-eval-home-type"><span>SLOT ${index===0?'A':'B'}</span><b>${type}</b></div><div class="eval-person">${politicianPhoto(person,'eval-avatar')}<div><small>이번 평가 대상</small><b>${esc(name)}</b><em>${esc([party,jurisdiction].filter(Boolean).join(' · '))}</em></div></div><div class="eval-score"><small>긍정 평가</small><strong>${positive}%</strong><span>${total.toLocaleString('ko-KR')}명 참여</span></div></article>`;}).join('');return `<section class="module national-eval" id="national-eval"><div class="module-header"><div><span class="eyebrow">NATIONAL EVALUATION</span><h2>정참시민 전국 평가제</h2><p class="module-desc">국회의원 1명과 광역·기초단체장 1명을 정참시민이 각각 평가합니다</p></div>${moduleAction('evaluation','/national-evaluation','전국 평가 투표')}</div>${cards?`<div class="national-eval-dual">${cards}</div>`:'<div class="schedule-empty">현재 진행 중인 전국 평가가 없습니다</div>'}</section>`;}
function generation(data={}){const ages=['10대','20대','30대','40대','50대','60대+'],candidates=Array.isArray(data?.candidates)?data.candidates:[],labels=data?.candidateLabels||{};return `<section class="module generation-president" id="generation-president"><div class="module-header"><div><span class="eyebrow">GENERATION CHOICE · MOCK VOTE</span><h2>세대의 선택, 대통령</h2></div>${moduleAction('generation','/generation-president','세대 대통령 투표')}</div><div class="generation-grid">${ages.map((age,i)=>{const results=data?.results?.[age]||{},entries=Object.entries(results).sort((a,b)=>Number(b[1]||0)-Number(a[1]||0)),total=entries.reduce((sum,[,votes])=>sum+Number(votes||0),0),top=entries[0],percent=top&&total?Math.round(Number(top[1]||0)*100/total):0;return `<article class="generation-card ${i===1?'focus':''}" data-layout-route="/generation-president"><span class="generation-age">${age}</span>${candidates.length&&top?`<div class="generation-result"><b>${esc(labels[top[0]]||top[0])}</b><div class="generation-bar"><i style="width:${percent}%"></i></div><small>${percent}% · ${total.toLocaleString('ko-KR')}명 참여</small></div>`:'<div class="generation-result generation-result-empty"><b>아직 투표가 이뤄지지 않았습니다</b><div class="generation-bar"><i style="width:0%"></i></div><small>첫 투표를 기다리는 중</small></div>'}</article>`;}).join('')}</div></section>`;}
function compare(){return `<section class="module compare-operating-module" id="compare"><div class="module-header"><div><span class="eyebrow">COMPARE · OPERATING</span><h2>정치인 비교분석</h2></div>${moduleAction('compare','/compare','정치인 비교하기')}</div><button type="button" class="compare-operating-entry" data-layout-route="/compare"><div><span>JCS ROLE-TIERED COMPARISON</span><h3>같은 정치인도 권한에 따라 더 깊게 비교합니다</h3><p>비로그인, 회원로그인에 따른 차등 정보제공</p></div><em>정치인 검색하고 비교하기 →</em></button></section>`;}
export function renderNowRankCard(x){
      const src=String(x.photo?.url||x.photo?.localPath||''),initial=esc(String(x.name||'?').slice(0,1));
      const avatar=src?`<div class="rank-top-avatar has-photo" data-politician-avatar style="--photo-position:${esc(x.photo?.focus||'50% 28%')}"><span class="politician-photo-initial" aria-hidden="true">${initial}</span><img data-politician-photo src="${esc(src)}" alt="" width="70" height="70" loading="lazy" decoding="async"></div>`:`<div class="rank-top-avatar is-empty" data-politician-avatar><span class="politician-photo-initial" aria-hidden="true">${initial}</span></div>`;
      return `<article class="rank-top-card ${partyClass(x.party)}" role="button" tabindex="0" data-layout-route="/person/${esc(x.id||'')}" aria-label="${Number(x.rank||0)}위 ${esc(x.name)} 상세"><span class="rank-party-flag" title="${esc(x.party)}">${partyMark(x.party)}</span><div class="rank-top-no">${Number(x.risingRank||x.rank||0)}${x.change?` <small class="rising-change">▲${Number(x.change)}</small>`:''}</div>${avatar}<div class="rank-top-copy"><b>${esc(x.name)}</b><span class="rank-top-party">${esc(x.party)}</span><span class="rank-top-region">${esc(x.jurisdiction)}</span></div></article>`;

}
function nowRank(rows=[]){
  if(!rows.length)return `<section class="module now-module" id="now"><div class="module-header"><div><span class="eyebrow live-heading-inline">NOW RANK <span class="main-live-pulse" aria-label="LIVE"><i></i></span></span><h2>지금 가장 주목받는 정치인</h2></div>${moduleAction('now','/now','NOW Rank 전체보기')}</div><div class="schedule-empty now-rank-pending"><b>NOW Rank 집계 준비 중</b><span>검증된 운영 순위가 게시되면 표시합니다</span></div></section>`;
  const top=rows.slice(0,100),card=renderNowRankCard,pages=[];for(let start=0;start<top.length;start+=10){const page=start/10;pages.push(`<div class="rank-top-grid rank-top-grid-10 now-rank-page" data-now-rank-page="${page}" ${page?'hidden':''}>${top.slice(start,start+10).map(card).join('')}</div>`);}
  return `<section class="module now-module" id="now"><div class="module-header"><div><span class="eyebrow live-heading-inline">NOW RANK <span class="main-live-pulse" aria-label="LIVE"><i></i></span></span><h2>지금 가장 주목받는 정치인</h2><p class="module-desc"><span class="now-rank-desc-desktop">전체 정치인 NOW 운영 순위 1–100위 · 좌우 버튼으로 10명씩 보기</span><span class="now-rank-desc-mobile">전체 정치인 NOW 운영 순위 1–100위 · 손가락으로 좌우 이동</span></p></div>${moduleAction('now','/now','NOW Rank 전체보기')}</div><div class="now-rank-carousel" data-now-rank-carousel><div class="now-rank-set" data-now-rank-set data-now-rank-mobile-swipe data-page-size="10" data-total="${top.length}" data-page="0"><button class="now-rank-nav now-rank-prev now-rank-gutter-control" type="button" data-now-rank-prev aria-label="이전 순위">‹</button><div class="now-rank-pages">${pages.join('')}</div><button class="now-rank-nav now-rank-next now-rank-gutter-control" type="button" data-now-rank-next aria-label="다음 순위">›</button><div class="now-rank-status now-rank-status-desktop" data-now-rank-status="desktop">1–${Math.min(10,top.length)} / ${top.length}</div></div></div></section>`;
}
function column(items=[]){const rows=items.filter(item=>item?.published!==false).slice(0,4);return `<section class="module" id="column"><div class="module-header"><div><span class="eyebrow">COLUMN</span><h2>오늘 정치에서 읽어야 할 것</h2></div>${moduleAction('column','/column','칼럼 전체보기')}</div><div class="column-grid">${rows.map(item=>{const cover=imageUrl(item.coverImage);return `<article class="column-card" data-layout-route="/column/${esc(item.id)}"><div class="column-thumb">${cover?`<img src="${esc(cover)}" alt="" loading="lazy">`:''}</div><div class="column-card-copy"><b>${esc(item.title||'제목 없는 칼럼')}</b><small>${authorInline(item)}${dateLabel(item.createdAt)?` · ${dateLabel(item.createdAt)}`:''}</small></div></article>`;}).join('')||'<div class="schedule-empty">등록된 칼럼이 없습니다</div>'}</div></section>`;}
function community(items=[]){const rows=items.filter(item=>item?.published!==false).slice(0,5);return `<section class="module" id="community"><div class="module-header"><div><span class="eyebrow">COMMUNITY</span><h2>지금 시민들이 말하는 것</h2></div>${moduleAction('community','/community','커뮤니티 전체보기')}</div><div class="community-list">${rows.map((item,i)=>`<div class="community-row" data-layout-route="/community/${esc(item.id)}"><span class="community-order">${String(i+1).padStart(2,'0')}</span><span class="community-copy"><span class="community-title">${esc(item.title||'제목 없는 게시물')}</span><em>${authorInline(item)}${dateLabel(item.createdAt)?` · ${dateLabel(item.createdAt)}`:''}</em></span><span class="community-stats">조회 ${Number(item.views||0).toLocaleString('ko-KR')}</span></div>`).join('')||'<div class="schedule-empty">등록된 정뮤니티 게시물이 없습니다</div>'}</div></section>`;}
function academy(data={}){const rows=(Array.isArray(data?.slots)?data.slots:publishedItems(data)).filter(item=>item?.published!==false).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))).slice(0,4);return `<section class="module academy-module" id="academy"><div class="module-header"><div><span class="eyebrow">JEONGCHAMSI ACADEMY</span><h2>정참시 아카데미</h2></div>${moduleAction('academy','/academy','아카데미 일정 보기')}</div><div class="academy-layout"><div class="academy-intro"><span class="academy-mark">A</span><h3>정치의 꿈을 실제 준비로</h3><button type="button" data-layout-route="/academy">수강 가능 일정 확인</button></div><div class="academy-schedule"><div class="schedule-head"><b>예정 교육 일정</b><span>${rows.length}개</span></div>${rows.map(item=>{const when=academyDate(item.date);return `<div class="schedule-row" data-slot-id="${esc(item.id||'')}"><span class="schedule-date">${esc(when.date)}${when.day?` <small>${esc(when.day)}</small>`:''}</span><span class="schedule-line"><i></i><em>${esc(item.title||item.name||'정참시 아카데미')}</em></span><button type="button" data-layout-route="/academy">신청가능</button></div>`;}).join('')||'<div class="schedule-empty">등록된 일정이 없습니다</div>'}</div></div></section>`;}

function accountPanel(session={},mobile=false){
  const authenticated=session?.authenticated===true;
  const nickname=esc(session?.user?.nickname||'회원');
  if(mobile)return authenticated
    ? `<div class="mobile-login mobile-login-authenticated"><div><b>${nickname}님</b><span>${session.user?.role==='admin'?'관리자 계정':'정참시 회원'} · 로그인 상태 유지 중</span></div><button type="button" data-layout-route="/mypage">마이페이지</button></div>`
    : `<div class="mobile-login"><div><b>정참시에 로그인하세요</b><span>즐겨찾기 · 참여 · 배지 · 알림</span></div><button type="button" data-layout-route="/login">로그인</button></div>`;
  return authenticated
    ? `<section class="side-card login-card side-login side-login-authenticated"><span class="side-login-status">SIGNED IN</span><b>${nickname}님</b><p>${session.user?.role==='admin'?'관리자 계정':'정참시 회원'}으로 로그인되어 있습니다</p><button type="button" data-layout-route="/mypage">마이페이지</button></section>`
    : `<section class="side-card login-card side-login"><b>정참시에 로그인하세요</b><p>즐겨찾기, 참여 기록, 배지, 알림을 한곳에서 관리합니다</p><button type="button" data-layout-route="/login">로그인</button></section>`;
}

function recentPoliticianCard(item){
  const src=String(item?.photo?.url||item?.photo?.localPath||''),initial=esc(String(item?.name||'?').slice(0,1));
  const avatar=src?`<span class="recent-circle-avatar has-photo" data-politician-avatar style="--photo-position:${esc(item.photo?.focus||'50% 28%')}"><span class="politician-photo-initial" aria-hidden="true">${initial}</span><img data-politician-photo src="${esc(src)}" alt="" width="54" height="54" loading="lazy" decoding="async"></span>`:`<span class="recent-circle-avatar is-empty" data-politician-avatar><span class="politician-photo-initial" aria-hidden="true">${initial}</span></span>`;
  return `<button type="button" class="recent-visual-card" data-layout-route="/person/${esc(item.id)}" aria-label="${esc(item.name)} 상세페이지">${avatar}<b>${esc(item.name)}</b><small>${esc([item.party,item.office].filter(Boolean).join(' · '))}</small></button>`;
}

function recentPoliticians(items=[]){
  const rows=Array.isArray(items)?items.filter(item=>item?.id&&item?.name).slice(0,4):[];
  return `${rows.map(recentPoliticianCard).join('')}${Array.from({length:4-rows.length},()=>`<span class="recent-visual-empty"><span class="recent-circle-empty"></span><b>최근 본 인물</b><small>기록 없음</small></span>`).join('')}`;
}

const emptyBadgeSlot=type=>`<button type="button" class="badge-slot badge-showcase-slot badge-showcase-empty" data-layout-route="/mypage/activity" data-badge-slot="${type}" aria-label="배지 관리로 이동"><i>◇</i><small>${type==='representative'?'대표':'전시'}</small></button>`;
const filledBadgeSlot=(key,type)=>{const badge=badgeByKey(key);return badge?`<button type="button" class="badge-slot badge-showcase-slot badge-showcase-filled ${type==='representative'?'is-representative':''}" data-layout-route="/mypage/activity" data-badge-slot="${type}" title="${esc(badge.name)}">${badgeCrestSvg(key)}<small>${esc(badge.name)}</small></button>`:emptyBadgeSlot(type);};

export function renderBadgeShowcase(status={}){
  status=status||{};
  const representative=badgeByKey(status.representativeBadge)?.key||'';
  const showcases=[...new Set(Array.isArray(status.showcaseBadges)?status.showcaseBadges:[])].filter(key=>key!==representative&&badgeByKey(key)).slice(0,3);
  const slots=[representative?filledBadgeSlot(representative,'representative'):emptyBadgeSlot('representative')];
  for(let index=0;index<3;index++)slots.push(showcases[index]?filledBadgeSlot(showcases[index],'showcase'):emptyBadgeSlot('showcase'));
  return `<div class="side-badge-showcase"><div class="badge-showcase-main">${slots[0]}<div><b>${representative?esc(badgeByKey(representative).name):'대표 배지를 선택해보세요'}</b><p>${representative?'나를 상징하는 대표 컬렉션':'획득한 배지를 대표로 설정할 수 있습니다'}</p></div></div><div class="badge-showcase-trio">${slots.slice(1).join('')}</div></div>`;
}

function participationCard(status={},mobile=false,session={}){const authenticated=session?.authenticated===true,nickname=esc(session?.user?.nickname||'회원'),account=authenticated?`<div class="participation-account-row"><span><small>SIGNED IN</small><b>${nickname}님 · ${session.user?.role==='admin'?'관리자':'정참시 회원'}</b></span><button type="button" data-layout-route="/mypage">마이페이지</button></div>`:`<div class="participation-account-row"><span><small>MEMBER</small><b>로그인하고 참여 기록을 관리하세요</b></span><button type="button" data-layout-route="/login">로그인</button></div>`;return `<section class="${mobile?'mobile-participation':'side-card side-participation side-participation-account'} participation-card">${account}<div data-badge-showcase-mount>${renderBadgeShowcase(status)}</div></section>`;}

function homeBanner(banner={},session={}){const url=imageUrl(banner?.url),target=imageUrl(banner?.targetUrl),admin=session?.user?.role==='admin';if(url)return `<section class="side-card side-home-banner"><a href="${esc(target||'#')}"${target?' target="_blank" rel="noopener noreferrer"':''}><img src="${esc(url)}" alt="${esc(banner.alt||'정참시 배너')}" loading="lazy"></a>${admin?'<button type="button" data-home-banner-edit>배너 변경</button>':''}</section>`;return admin?`<section class="side-card side-home-banner side-home-banner-empty"><b>메인 배너 추가</b><p>권장 640 × 450px · JPG·PNG·WEBP</p><button type="button" data-home-banner-edit>배너 추가하기</button></section>`:'';}

function sideColumn(data,session){const rankRows=Array.isArray(data.trending)?data.trending:[],newsRows=(Array.isArray(data.newsPosts)?data.newsPosts:[]).filter(item=>item?.published!==false).slice(0,5);return `<aside class="side-column">${homeBanner(data.homeBanner,session)}${participationCard(data.badgeStatus,false,session)}<section class="side-card side-recent"><div class="side-head"><b>최근 본 정치인</b><span class="side-action" data-layout-route="/mypage/recent">전체</span></div><div class="recent-visual-grid">${recentPoliticians(data.recentPoliticians)}</div></section><section class="side-card side-keywords live-signal-card"><div class="side-head"><b class="live-heading-inline">실시간 정치키워드 <span class="main-live-pulse" aria-label="LIVE"><i></i></span></b><span class="side-action" data-layout-route="/keywords">더보기</span></div><div class="keyword-grid live-keyword-grid">${(data.keywords||[]).slice(0,10).map((x,i)=>`<span class="live-keyword-chip" role="link" tabindex="0" data-layout-route="/keywords?q=${encodeURIComponent(x.key)}"><b>${i+1}</b>${esc(x.label)}</span>`).join('')}</div><small class="signal-source-note">게시된 NOW 뉴스 데이터 기반</small></section><section class="side-card side-news"><div class="side-head"><b>정참시 NEWS</b><span class="side-action" data-layout-route="/news">전체</span></div>${newsRows.map((item,i)=>`<div class="side-row" data-layout-route="/news/${esc(item.id)}"><span>${i+1}</span><i>${esc(item.title||'제목 없는 뉴스')}</i></div>`).join('')||'<div class="schedule-empty">게시된 정참시 NEWS가 없습니다</div>'}</section><section class="side-card side-rising live-signal-card"><div class="side-head"><b class="live-heading-inline">실시간 급상승 정치인 <span class="main-live-pulse" aria-label="LIVE"><i></i></span></b><span class="side-action" data-layout-route="/trending">전체</span></div>${rankRows.length?rankRows.slice(0,5).map((x,i)=>`<div class="side-row live politician-rising-row" data-layout-route="/person/${esc(x.id||'')}"><span>${i+1}</span><i><span class="rising-politician-name">${esc(x.name)}</span><small><em class="trend-signal up">▲</em> ${Number(x.change||0)}계단 상승 · ${esc(x.party)}</small></i></div>`).join(''):'<div class="schedule-empty">집계 준비 중</div>'}</section></aside>`;}

export function renderHomeLayout(data){
  return `${productHero(data.hero)}${productLauncher()}<div class="portal-layout product-content-grid"><section class="mobile-utility" aria-label="모바일 내 정참시">${participationCard(data.badgeStatus,true,data.session)}</section><main class="main-column">${itsme(data.itsmePosts)}${poll(data.polls)}${nationalEval(data.nationalEvaluation)}${generation(data.generation)}${compare()}${nowRank(data.rank)}${column(data.columns)}${community(data.community)}${academy(data.academy)}</main>${sideColumn(data,data.session)}</div>`;
}

export function renderTrendingPage(result={}){if(result.ok===false)return '<section class="module"><h2>급상승 정치인</h2><p role="alert">순위를 불러오지 못했습니다. 새로고침 후 다시 시도해 주세요.</p></section>';const rows=result.items||[];return `<section class="module"><div class="module-header"><div><span class="eyebrow">RISING POLITICIANS</span><h2>현재 급상승한 정치인</h2><p class="module-desc">이전 게시 순위 대비 상승폭 · 최대 100명</p></div></div>${rows.length?`<div class="rank-top-grid trending-grid" data-trending-grid>${rows.map(renderNowRankCard).join('')}</div>`:`<div class="schedule-empty">${result.ready?'현재 상승한 정치인이 없습니다.':'순위 비교에 필요한 이전 집계를 준비하고 있습니다.'}</div>`}${rows.length<Number(result.total)?`<button type="button" class="primary-btn" data-trending-more data-offset="${rows.length}" data-snapshot="${esc(result.snapshot)}">30명 더보기</button>`:''}<p data-trending-status role="status">${rows.length} / ${Number(result.total||0)}명</p></section>`;}
export function renderKeywordsPage(result={},query=''){if(result.ok===false)return '<section class="module"><h2>정치키워드</h2><p role="alert">키워드를 불러오지 못했습니다. 새로고침 후 다시 시도해 주세요.</p></section>';const items=result.items||[],selected=items.find(row=>row.key===query);return `<section class="module"><span class="eyebrow">POLITICAL KEYWORDS</span><h2>정치키워드</h2><p class="module-desc">최근 7일과 이전 7일의 수집 보도 비교 · 게시 시 갱신</p><div class="keyword-grid">${items.map((row,index)=>`<button class="ghost-btn" data-layout-route="/keywords?q=${encodeURIComponent(row.key)}">${index+1}. ${esc(row.label)} · ${row.recent}건</button>`).join('')||'<p>게시된 뉴스에서 키워드를 준비하고 있습니다.</p>'}</div>${selected?`<article class="content-card"><h3>${esc(selected.label)}</h3><p>최근 7일 ${selected.recent}건 · 이전 7일 ${selected.previous}건 · ${selected.change>=0?'+':''}${selected.change}건 · ${selected.sourceCount}개 매체</p><h4>관련 정치인</h4><div>${selected.people.map(person=>`<button class="ghost-btn" data-layout-route="/person/${esc(person.id)}">${esc(person.name)}</button>`).join('')}</div><h4>관련 뉴스</h4>${selected.articles.map(row=>`<p><a href="${esc(row.url)}" target="_blank" rel="noopener noreferrer">${esc(row.title)}</a><small> · ${esc(row.source)}</small></p>`).join('')}</article>`:''}</section>`;}
